added toast for adding receipts to expenses
fylein/fyle-mobile-app pull request #1028
Opened 2022-04-12 07:03 UTC by sandy-fyle

added toast for adding receipts to expenses
![before](https://user-images.githubusercontent.com/102028313/162900302-61f78af6-42aa-49ca-96cc-bbfe85f37b5f.png)
![after](https://user-images.githubusercontent.com/102028313/162900312-27e4a4c4-d926-494e-86ec-452cc7f24070.png)

2022-04-12 08:09 UTC, sandy-fyle commented on src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts
> +      if (this.attachments.length > this.previousCount) {
![1](https://user-images.githubusercontent.com/102028313/162912646-ff60b57b-5c29-4a3f-a1ca-dd52ffb2d07f.png)

2022-04-26 06:33 UTC, Dimple16 requested changes
you've made changes to a common component, can you add screenshots of how the change looks on other pages too? are those tested?

2022-05-03 05:24 UTC, Dimple16 commented
can you check if we have a toast on adding receipts from my expenses page? Ideally, we should have a toast there too

2022-05-03 05:25 UTC, Dimple16 requested changes

2022-05-03 05:25 UTC, Dimple16 commented on src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts
> +    console.log(this.attachments.length);
remove logs

2022-05-03 05:33 UTC, sandy-fyle commented
> can you check if we have a toast on adding receipts from my expenses page? Ideally, we should have a toast there too

its not there, looking into it.

2022-05-03 07:56 UTC, sandy-fyle commented
> can you check if we have a toast on adding receipts from my expenses page? Ideally, we should have a toast there too

I have made the changes now its showing on my expenses page too
![image](https://user-images.githubusercontent.com/102028313/166420607-c0294b28-2394-4801-bc61-f4a9054e0e02.png)

2022-05-05 06:25 UTC, Dimple16 requested changes

2022-05-05 06:25 UTC, Dimple16 commented on src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts
> +import { MatSnackBar } from '@angular/material/snack-bar';
remove imports if not used

2022-05-05 06:25 UTC, Dimple16 commented on src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts
> +    private matSnackBar: MatSnackBar,
remove if unused

2022-05-06 06:10 UTC, Dimple16 requested changes

2022-05-06 06:10 UTC, Dimple16 commented on src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts
> -  @Input() hideLabel: boolean;
why are we removing this?

2022-05-06 06:11 UTC, sandy-fyle commented on src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts
> -  @Input() hideLabel: boolean;
it wasn't getting used anywhere

2022-05-06 06:11 UTC, sandy-fyle commented on src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts
> -  @Input() hideLabel: boolean;
Should I add it back?

2022-05-06 06:33 UTC, sandy-fyle commented on src/app/shared/components/receipt-preview-thumbnail/receipt-preview-thumbnail.component.ts
> -  @Input() hideLabel: boolean;
oh sorry! it was a misunderstanding, added it back

2022-05-06 09:29 UTC, Dimple16 approved these changes

2022-05-06 09:38 UTC, merged