Fix sentry error: `TypeError: Cannot read properties of undefined (reading 'rp_purpose')`
fylein/fyle-mobile-app pull request #1043
Opened 2022-04-18 08:56 UTC by yksolanki9

Could not repro the error, but this pr should fix it

2022-04-20 08:50 UTC, Dimple16 requested changes

2022-04-20 08:50 UTC, Dimple16 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +    this.erpt$.pipe(filter((erpt) => !!erpt)).subscribe((erpt) => {
should we add an `if` condition to check if erpt exists? OR use `erpt?.rp_purpose`

2022-04-20 14:01 UTC, yksolanki9 commented on src/app/shared/components/fy-view-report-info/fy-view-report-info.component.ts
> +    this.erpt$.pipe(filter((erpt) => !!erpt)).subscribe((erpt) => {
If erpt is does not exist, the filter condition wont be satisfied and no value will be emitted

2022-04-21 04:58 UTC, Dimple16 approved these changes

2022-04-22 06:23 UTC, merged