Upgrade mobile app to angular 13
fylein/fyle-mobile-app pull request #1051
Opened 2022-04-20 12:55 UTC by yksolanki9

2022-06-07 14:28 UTC, Dimple16 approved these changes
only method placement changes included with angular upgrade, not checking method codes

2022-06-07 14:43 UTC, rvab requested changes
Please mention the return data type wherever the method returns.

2022-06-07 14:43 UTC, rvab commented on src/app/fyle/add-edit-mileage/fy-select-vehicle/fy-select-vehicle.component.ts
> +  get valid() {
return `data type`?

2022-06-07 14:43 UTC, rvab commented on src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
> +  ngOnDestroy(): void {}
Is it needed?

2022-06-07 14:43 UTC, rvab commented on src/app/shared/components/fy-select/fy-select.component.ts
> +  ngOnDestroy(): void {}
is it needed?

2022-06-09 15:22 UTC, rvab approved these changes
There are still `get` methods with no return types. We should start mentioning it. Approving with an exception.

2022-06-09 15:22 UTC, rvab commented on src/app/shared/components/fy-duplicate-detection/fy-duplicate-detection.component.ts
> +  ngOnInit() {
Should it be ngOnInit or ionViewWillEnter?

2022-06-10 08:17 UTC, yksolanki9 commented
Adding return types to methods across the codebase and updating component lifcycle methods will involve a lot of testing and modification which goes beyond the scope of this pr. 
I've added link to the comments and created a separate task, will fix these as a separate pr - https://app.clickup.com/t/2f88cgx

2022-06-10 08:20 UTC, yksolanki9 commented on src/app/shared/components/fy-duplicate-detection/fy-duplicate-detection.component.ts
> +  ngOnInit() {
This file has been deleted in master

2022-06-10 09:59 UTC, Julias0 approved these changes

2022-06-14 12:01 UTC, merged