Added LaunchDarkly
fylein/fyle-mobile-app pull request #1062
Opened 2022-04-29 04:33 UTC by OmkarJ13

2022-04-29 05:40 UTC, OmkarJ13 commented on src/app/core/services/launch-darkly.service.ts
> +        (window as any).ldclient.on('change', () => {});
These are not useful when it comes to the context of this PR, but in the future someone will need to track these events so added them earlier.

2022-05-13 06:08 UTC, yksolanki9 requested changes
Some unit tests are failing, please fix those

2022-05-13 06:08 UTC, yksolanki9 commented on src/app/core/services/launch-darkly.service.ts
> +          const devicePlatform$ = this.deviceService.getDeviceInfo().pipe(map((device) => device.platform));
We're already storing these details in local storage, check offlineService and see if that'll help. You can avoid checking for `isOnline` if you use this

2022-05-14 13:37 UTC, OmkarJ13 commented on src/app/core/services/launch-darkly.service.ts
> +  private onLDInitialized() {
Actually this is not really needed for now, since we can directly pass the this.updateCache method for the `initialized` and `change` events, however I added these methods in case someone needs to add something to these in the future. Please let me know if this is not a good idea, I'll remove them :P

2022-05-14 13:41 UTC, OmkarJ13 commented on src/app/core/services/launch-darkly.service.ts
> +      map((cachedFlags) => (cachedFlags[key] === undefined ? defaultValue : cachedFlags[key]))
Do you mean `cachedFlags[key] || defaultValue` ? I don't think we can use || here, because if the value of `cachedFlags[key]` is `false`, the || operator will return the second value which will be default in our case. We needed something to differentiate between false and undefined values, as we want to return the default value only when cachedFlags[key] is undefined, this will happen when it doesn't exist even in storage. Please let me know if I'm misunderstanding anything.

2022-05-15 14:50 UTC, OmkarJ13 commented on src/app/core/services/launch-darkly.service.spec.ts
> +xdescribe('LaunchDarklyService', () => {
Changed describe to xdescribe to fix the error as app component tests are temporarily disabled (therefore it was causing null injector errors), this will temporarily disable the test and will not execute it. This is done because we're changing stuff in test files pretty recently. Most of the files are changed to xdescribe.

2022-05-16 03:33 UTC, yksolanki9 commented on src/app/core/services/launch-darkly.service.ts
> +      map((cachedFlags) => (cachedFlags[key] === undefined ? defaultValue : cachedFlags[key]))
Yeah, ignore the comment

2022-05-16 03:35 UTC, yksolanki9 commented on src/app/core/services/launch-darkly.service.ts
> +    }
This is not taken care of?

2022-05-16 03:37 UTC, yksolanki9 commented on src/app/core/services/launch-darkly.service.ts
> +  private onLDInitialized() {
If you're sure we'll need them then there's no issue

2022-05-16 04:30 UTC, OmkarJ13 commented on src/app/core/services/launch-darkly.service.ts
> +    }
No sorry, tslint wouldn't allow ternary operators without returning something

2022-05-17 05:22 UTC, yksolanki9 approved these changes

2022-05-17 12:39 UTC, Dimple16 requested changes

2022-05-17 12:39 UTC, Dimple16 commented on hooks/secrets.js
> +                LAUNCH_DARKLY_CLIENT_ID: '` + process.env.LAUNCH_DARKLY_CLIENT_ID + `'
this needs to be updated in App flow environments and mobile-app-secrets repo too, please track these separately cc @abhishek1234321

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.spec.ts
> +xdescribe('LaunchDarklyService', () => {
yes, this should be fine

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +
remove extra lines

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +  // https://launchdarkly.github.io/js-client-sdk/interfaces/_launchdarkly_js_client_sdk_.ldclient.html#off
use multi-line comments

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +  private onLDInitialized() {
you can remove it for now and add it when needed, can add this note in a doc if required for reference

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +  private onLDChange() {
same as above

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +        const currentOrg$ = this.offlineService.getCurrentOrg() as Observable<Org>;
this should work I guess
`const currentOrg$: Observable<Org> = this.offlineService.getCurrentOrg();`
you can replace it this way wherever used

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +        const devicePlatform$ = this.deviceService.getDeviceInfo().pipe(map((device) => device.platform));
`device?.platform`

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +            const eou = res.currentEou$;
`res?.currentEou$`
use fail-safes everywhere

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +            // HACK ALERT - Added (currentOrg as any).created_at because created_at is typed as a date but internally is a string
use multi-line comments

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +              key: eou.ou.user_id,
`eou?.ou.user_id`

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +              key: eou.ou.user_id,
same for the rest of them below

2022-05-17 12:39 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +
remove extra line

2022-05-18 05:32 UTC, Dimple16 approved these changes

2022-05-18 15:55 UTC, abhishek1234321 approved these changes

2022-05-18 15:55 UTC, abhishek1234321 commented on src/app/core/services/launch-darkly.service.ts
> +            const eou = res?.currentEou$;
why is `?` needed here?

2022-05-23 03:16 UTC, OmkarJ13 commented on src/app/core/services/launch-darkly.service.ts
> +            const eou = res?.currentEou$;
If the api call returned incorrect or null data for some reason, this will throw 'Cannot access currentEou$ of undefined or null'. To avoid this, we are using ?.

2022-05-23 03:17 UTC, merged