added summary tile(view team advance request revamp)
fylein/fyle-mobile-app pull request #1073
Opened 2022-05-06 04:27 UTC by sandy-fyle

added a summary tile in view team advance request page

![image](https://user-images.githubusercontent.com/102028313/167066544-879831f8-83c3-437a-a0c9-3695dd298e30.png)
![image](https://user-images.githubusercontent.com/102028313/167067067-6749b558-fd9d-4b0f-b8c9-c0aa5b140be1.png)

2022-05-06 06:07 UTC, Dimple16 commented
the second screenshot looks scary, we need to add ellipsis in such cases,
let the text go up to 2 lines, then add ellipsis

2022-05-06 06:08 UTC, Dimple16 commented
I guess the edit icon of approvers is missing

2022-05-06 06:09 UTC, Dimple16 requested changes

2022-05-06 06:09 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance.page.scss
>      border: 1px solid #e5e5e5;
use color variables

2022-05-06 06:10 UTC, sandy-fyle commented
> 

okay


> I guess the edit icon of approvers is missing

I have created separate task for it, will create PR soon

2022-05-06 06:11 UTC, sandy-fyle commented on src/app/fyle/view-team-advance/view-team-advance.page.scss
>      border: 1px solid #e5e5e5;
okay

2022-05-06 09:31 UTC, Dimple16 requested changes

2022-05-06 09:31 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.scss
> +      text-overflow: ellipsis;
use ellipsis pipe

2022-05-06 14:54 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.html
> +        {{ purpose.length > 25 ? (purpose | slice: 0:25) + '..' : purpose }}
you can directly use `purpose | ellipsis: 25` 
why do we need a slice here? please check the existing ellipsis pipe usage and make similar changes

2022-05-06 16:26 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.html
> +        {{ purpose.length > 25 ? (purpose | slice: 0:25) + '..' : purpose }}
> 

![image](https://user-images.githubusercontent.com/102028313/167173508-e1e915a7-f4bb-4c92-99f6-fab2e3f7e73d.png)

2022-05-06 16:26 UTC, sandy-fyle commented
> added a summary tile in view team advance request page
> 
> ![image](https://user-images.githubusercontent.com/102028313/167066544-879831f8-83c3-437a-a0c9-3695dd298e30.png) ![image](https://user-images.githubusercontent.com/102028313/167067067-6749b558-fd9d-4b0f-b8c9-c0aa5b140be1.png)

![image](https://user-images.githubusercontent.com/102028313/167173582-d16f9c6f-9e81-43d6-a9e4-03301fa279ce.png)

2022-05-09 06:03 UTC, Dimple16 approved these changes

2022-11-05 16:08 UTC, closed without merging