Fyle 29h12ax 1
fylein/fyle-mobile-app pull request #1082
Opened 2022-05-09 18:13 UTC by sandy-fyle

combined PR for Team View Advance Request Page (Revamp)

![image](https://user-images.githubusercontent.com/102028313/167471490-b8c7ab53-8a60-47b4-a7cb-13260da04b36.png)
![image](https://user-images.githubusercontent.com/102028313/167471532-52e24891-4a54-4ccb-b209-f114b50dccc8.png)

2022-05-10 06:30 UTC, Dimple16 commented
Comments from screenshots:
- Check the spacing between the edit and comments icon in the header
- Check the font size and font weight of the text added in the approver's section
- Check CTA font size and font weight + background colour

2022-05-10 06:43 UTC, sandy-fyle commented
> 

looking into it

2022-05-10 06:49 UTC, Dimple16 requested changes

2022-05-10 06:49 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() type: any;
avoid using `any`

2022-05-10 06:49 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() type: any;
check all the other places wherever `any` is used in the pr and make sure we use a `type` / `model`

2022-05-10 06:49 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.scss
> +    width: min-content;
also check how the width is set in reports page

2022-05-10 06:54 UTC, sandy-fyle commented on src/app/fyle/view-team-advance/view-team-advance.page.ts
> +      concatMap((fileObj: any) =>
type for this is not there in existing model, I will create one and commit ASAP.

2022-05-10 07:05 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.scss
> +    width: min-content;
> 

I checked, the above two properties are supported by all browsers

2022-05-10 07:10 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.scss
> +    width: min-content;
> also check how the width is set in reports page

I used same way as report but that's not working in this case so I used these stylings

2022-05-10 08:38 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() type: any;
> **Comments from screenshots:**

> * Check the font size and font weight of the text added in the approver's section

I have used same as view-team-report page
![image](https://user-images.githubusercontent.com/102028313/167586494-e5ad775c-f475-4ce9-8724-0a6949d38686.png)

2022-05-10 08:45 UTC, sandy-fyle commented
> **Comments from screenshots:**
> 
> * Check the spacing between the edit and comments icon in the header

it was slight different, fixed now!

2022-05-10 09:51 UTC, Dimple16 requested changes
add a loom video

2022-05-10 09:51 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance.page.html
> +    <ion-title mode="md" class="page-title" [ngClass]="{'view-advances--title-sm': isDeviceWidthSmall}">
it should be `view-team-advance-request` isn't it?

2022-05-10 09:51 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance.page.html
> +    <ion-title mode="md" class="page-title" [ngClass]="{'view-advances--title-sm': isDeviceWidthSmall}">
we decided to rename the entire component from `view-team-advance` to `view-team-advance-request`

2022-05-10 09:51 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() actions: Object;
can we add a model or type for actions?

2022-05-10 09:51 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Output() notify: EventEmitter<any> = new EventEmitter<any>();
this should be `EventEmitter<boolean>` ?  can you check what is emitted?

2022-05-10 09:51 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  approverList$: Observable<any>;
If approvers model is created, you can use the same list here

2022-05-10 09:53 UTC, sandy-fyle commented
> add a loom video

sure

2022-05-10 10:18 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() actions: Object;
I can't find an existing model for actions, Should I create one?

2022-05-10 10:22 UTC, sandy-fyle commented on src/app/fyle/view-team-advance/view-team-advance.page.html
> +    <ion-title mode="md" class="page-title" [ngClass]="{'view-advances--title-sm': isDeviceWidthSmall}">
yes, it should be. I'll change it

2022-05-11 08:44 UTC, Dimple16 commented
this screenshot is from the loom video, the actions are repeated, can you check this? this is critical
![Screenshot 2022-05-11 at 2 12 48 PM](https://user-images.githubusercontent.com/31147415/167808456-a0e8b24e-ea24-4896-abfd-51abdd745cb6.png)

2022-05-11 08:55 UTC, sandy-fyle commented
> this screenshot is from the loom video, the actions are repeated, can you check this? this is critical ![Screenshot 2022-05-11 at 2 12 48 PM](https://user-images.githubusercontent.com/31147415/167808456-a0e8b24e-ea24-4896-abfd-51abdd745cb6.png)

oh!! looking into it.

2022-05-11 08:59 UTC, Dimple16 requested changes

2022-05-11 08:59 UTC, Dimple16 commented on src/app/core/models/actions.model.ts
> +export interface actionsObj {
actionsObj -> `Actions`

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request-routing.module.ts
> +import { ViewTeamAdvancePage } from './view-team-advance-request.page';
we should be changing the component name too, it should be `ViewTeamAdvanceRequestPage`

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.module.ts
> +import { ViewTeamAdvancePage } from './view-team-advance-request.page';
this should be changed

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.page.html
> +<ion-header mode="md">
the folder name should be renamed too, `fyle/view-team-advance-request/view-team-advance-request.page.html`

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/fyle-routing.module.ts
> +      import('./view-team-advance/view-team-advance-request.module').then((m) => m.ViewTeamAdvancePageModule),
folder name will change too

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.page.html
> +        [purpose]="advanceRequest.areq_purpose || '-'"
`advanceRequest?.areq_purpose` make similar changes below

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.page.html
> +                [value]="advanceRequest.areq_created_at | date: 'MMM dd, yyyy'"
`advanceRequest?.areq_created_at`

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.page.html
> +          [value]="advanceRequest.us_full_name || '-'"
add fail-safes everywhere `?.`

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.page.html
> +        <div *ngIf="advanceRequestCustomFields.length > 0">
`advanceRequestCustomFields?.length > 0`

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.page.spec.ts
> +import { ViewTeamAdvancePage } from './view-team-advance-request.page';
`ViewTeamAdvancePage` this will change

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.page.ts
> +    let ReceiptExtension = null;
use `camelCase`

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.page.ts
> +      const idx = filename.lastIndexOf('.');
idx -> `index`

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.page.ts
> +    const ReceiptExtn = this.getReceiptExtension(file.name);
use `camelCase`

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.page.ts
> +    const ReceiptInfo = {
use `camelCase`

2022-05-11 08:59 UTC, Dimple16 commented on src/app/fyle/view-team-advance/view-team-advance-request.page.ts
> +  async viewAttachments(attachments) {
is the param `attachments` a type of list?

2022-05-11 08:59 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +import { actionsObj } from 'src/app/core/models/actions.model';
this name will change

2022-05-11 09:05 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +import { actionsObj } from 'src/app/core/models/actions.model';
> 

checked again, its showing only three actions 
![image](https://user-images.githubusercontent.com/102028313/167812879-7f0c57e1-555c-4a03-a7b7-0d54442c3528.png)

2022-05-11 10:25 UTC, Dimple16 requested changes

2022-05-11 10:25 UTC, Dimple16 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +        <div *ngIf="advanceRequestCustomFields.length > 0">
this isn't changed yet

2022-05-11 10:25 UTC, Dimple16 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +              *ngIf="advanceRequestCustomField.type === StatisticTypes.DATE.toUpperCase() && advanceRequestCustomField.value"
`StatisticTypes.DATE?.toUpperCase()`

2022-05-11 12:39 UTC, Dimple16 approved these changes

2022-05-11 12:52 UTC, Dimple16 commented
the advance actions ss is resolved

2022-05-12 08:00 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Output() notify: EventEmitter<boolean> = new EventEmitter<boolean>();
where is this used?

2022-05-12 08:01 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() id: string;
what is this? Where is this used?

2022-05-12 08:02 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() id: string;
I dont see this being passed into `app-summary-tile`

2022-05-12 08:02 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() type: string;
can you cross check all of the inputs?

2022-05-12 08:03 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  async openApproverListDialog() {
a presentational component shouldnt do this - this should be done from the parent

2022-05-12 08:05 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  getApproverEmails(activeApprovals) {
where is this used?

2022-05-12 08:06 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  onUpdateApprover(message: boolean) {
where is this used?

2022-05-12 08:07 UTC, Julias0 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +      concatMap((fileObj: File) =>
concatMap((fileObj: File) =>this.fileService.downloadUrl(fileObj?.id)),
 map((downloadUrl) => {
    fileObj.url = downloadUrl;
    const details = this.getReceiptDetails(fileObj);
    fileObj.type = details?.type;
    fileObj.thumbnail = details?.thumbnail;
    return fileObj;
  })

2022-05-12 08:08 UTC, Julias0 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +  getReceiptDetails(file: FileObject) {
extract this out into a service - we use this same logic in a lot of places?

2022-05-12 08:12 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.html
> +          {{ status === 'APPROVAL PENDING' ? 'Pending' : (status | snakeCaseToSpaceCase | titlecase) }}
do the transformation of status inside ngOnChanges

2022-05-12 08:18 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() type: string;
sure! I'll look into it if all inputs are getting used or not.

2022-05-12 08:19 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  async openApproverListDialog() {
looking into it

2022-05-12 08:20 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +  getReceiptDetails(file: FileObject) {
will do that.

2022-05-12 08:20 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.html
> +          {{ status === 'APPROVAL PENDING' ? 'Pending' : (status | snakeCaseToSpaceCase | titlecase) }}
okay

2022-05-13 03:35 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +      concatMap((fileObj: File) =>
I tried this way, its giving me error

2022-05-13 06:54 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  onUpdateApprover(message: boolean) {
not getting used, removed!

2022-05-13 06:55 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() type: string;
removed unused inputs

2022-05-17 12:48 UTC, Dimple16 requested changes

2022-05-17 12:48 UTC, Dimple16 commented on src/app/core/services/advance-request-receipt-extension.service.ts
> +export class AdvanceRequestReceiptExtensionService {
shouldn't this be named as receipt extension service? 
that way we can use it in other places too

2022-05-17 12:48 UTC, Dimple16 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +      concatMap((fileObj: File) =>
what error are you facing exactly? can you share it here?

2022-05-17 12:48 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  getApproverEmails(activeApprovals) {
@sandy-fyle can cross-check if this is being used?

2022-05-17 12:48 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  async openApproverListDialog() {
is this resolved?

2022-05-17 12:55 UTC, sandy-fyle commented on src/app/core/services/advance-request-receipt-extension.service.ts
> +export class AdvanceRequestReceiptExtensionService {
sure, will rename it

2022-05-17 15:31 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  getApproverEmails(activeApprovals) {
getApproverEmails not getting used, removed!

2022-05-17 15:35 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +  getReceiptDetails(file: FileObject) {
done

2022-05-17 15:35 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  onUpdateApprover(message: boolean) {
done

2022-05-17 15:36 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() type: string;
done

2022-05-17 15:44 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  async openApproverListDialog() {
I was trying to do this but was getting complex for me so did in this way (except this I have resolved all the comments)

2022-05-17 15:47 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +      concatMap((fileObj: File) =>
![image](https://user-images.githubusercontent.com/102028313/168853745-5bbee940-b8de-4d40-b422-d920e705aafd.png)

2022-05-17 15:48 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +      concatMap((fileObj: File) =>
it says can't find fileObj

2022-05-17 15:49 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Output() notify: EventEmitter<boolean> = new EventEmitter<boolean>();
removed

2022-05-17 15:49 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() id: string;
removed

2022-05-18 02:46 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  async openApproverListDialog() {
done!

2022-05-18 07:01 UTC, Dimple16 requested changes

2022-05-18 07:01 UTC, Dimple16 commented on src/app/core/services/openApproverListDialog.service.ts
> +  async openApproverListDialog() {
this shouldn't be here, remove this service

2022-05-18 07:01 UTC, Dimple16 commented on src/app/core/services/openApproverListDialog.service.ts
> +  async openApproverListDialog() {
this should be called from the parent component, not from summary-tile,
we shouldn't be adding it inside a service as such

2022-05-18 07:03 UTC, sandy-fyle commented on src/app/core/services/openApproverListDialog.service.ts
> +  async openApproverListDialog() {
okay, looking into it!

2022-05-18 08:45 UTC, sandy-fyle commented on src/app/core/services/openApproverListDialog.service.ts
> +  async openApproverListDialog() {
I did it by using existing component app-fy-approver exactly same as view-team-report and deleted the extra service I created.

2022-05-18 09:44 UTC, Dimple16 approved these changes

2022-05-18 09:44 UTC, Dimple16 commented on src/app/shared/components/fy-approver/fy-approver.component.ts
> +
remove this extra line

2022-05-18 10:36 UTC, rvab requested changes

2022-05-18 10:36 UTC, rvab commented on src/app/core/services/receipt-extension.service.ts
> +    let ReceiptExtension = null;
variable name should be camelCase.
Mention return `data type`

2022-05-18 10:36 UTC, rvab commented on src/app/core/services/receipt-extension.service.ts
> +    if (receiptExtn && ['pdf'].indexOf(receiptExtn) > -1) {
`receiptExtn === 'pdf'` should work. No need of `indexOf` here

2022-05-18 10:36 UTC, rvab commented on src/app/core/services/receipt-extension.service.ts
> +    }
What happens if the file `receiptExtn` is `null` or different than the `image/pdf` ?

2022-05-18 10:36 UTC, rvab commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
> +xdescribe('viewTeamAdvanceRequestPage', () => {
is it `xdescribe` or `describe `?

2022-05-18 10:36 UTC, rvab commented on src/app/shared/components/fy-approver/fy-approver.component.ts
> +  @Output() notify?: EventEmitter<any> = new EventEmitter<any>();
Why should this be made optional? What `data type` is it returning ?

2022-05-18 10:36 UTC, rvab commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +    this.status = this.status === 'APPROVAL PENDING' ? 'Pending' : this.status;
Where is `this.status` used?  If used in a template file, we can use the `this.status === 'APPROVAL PENDING' ? 'Pending' : this.status` in a template file instead of doing it inside ngOnChanges callback.

2022-05-18 10:40 UTC, sandy-fyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +    this.status = this.status === 'APPROVAL PENDING' ? 'Pending' : this.status;
I used it in template file earlier but @dhar suggested me to do it in ngOnChanges

2022-05-18 10:43 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
> +xdescribe('viewTeamAdvanceRequestPage', () => {
I didn't make any changes in spec file, I am not sure about it.

2022-05-18 10:44 UTC, sandy-fyle commented on src/app/core/services/receipt-extension.service.ts
> +    if (receiptExtn && ['pdf'].indexOf(receiptExtn) > -1) {
changed!

2022-05-18 10:46 UTC, sandy-fyle commented on src/app/shared/components/fy-approver/fy-approver.component.ts
> +
added this intentionally

2022-05-18 10:48 UTC, sandy-fyle commented on src/app/shared/components/fy-approver/fy-approver.component.ts
> +  @Output() notify?: EventEmitter<any> = new EventEmitter<any>();
made it optional by mistake while testing ( making it compulsory again)

2022-05-18 10:48 UTC, sandy-fyle commented on src/app/core/services/receipt-extension.service.ts
> +    let ReceiptExtension = null;
done

2022-05-18 11:49 UTC, sandy-fyle commented on src/app/core/services/receipt-extension.service.ts
> +    }
it will return as below, as we initially declared it as    
const receiptInfo = {
      type: 'unknown',
      thumbnail: 'img/fy-receipt.svg',
   };

so we don't need extra else block here
(discussed the same with mobile app team)

2022-05-18 11:50 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.spec.ts
> +xdescribe('viewTeamAdvanceRequestPage', () => {
I changed across various files, its xdescribe in every file

2022-05-18 12:15 UTC, rvab requested changes

2022-05-18 12:15 UTC, rvab commented on src/app/core/models/file_obj.model.ts
>    created_at: Date;
Do we follow `_` or `-` while naming files?

2022-05-18 12:15 UTC, rvab commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +import { List } from 'lodash';
I don't  see usage of `List`

2022-05-18 12:15 UTC, rvab commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +            const details = this.ReceiptExtensionService.getReceiptDetails(fileObj);
`this.ReceiptExtensionService` variable casing is wrong

2022-05-18 12:15 UTC, rvab commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +            fileObj.thumbnail = details?.thumbnail;
Do we need `?`  in `details?.type` or `details?.thumbnail`?. We are sending default object with both `type` and `thumbnail` from `getReceiptDetails` method.

2022-05-18 12:15 UTC, rvab commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +    this.status = this.status === 'APPROVAL PENDING' ? 'Pending' : this.status;
@Dimple16 do you know the reason for doing this in `.ts` file rather than HTML file?

2022-05-18 12:24 UTC, sandy-fyle commented on src/app/core/models/file_obj.model.ts
>    created_at: Date;
both ways  are being used in Mobile app folder(I didn't changed the file name, it was like this only)

2022-05-18 12:24 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +import { List } from 'lodash';
removed

2022-05-18 12:25 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +            fileObj.thumbnail = details?.thumbnail;
we don't need that actually. removed!

2022-05-18 12:29 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +            const details = this.ReceiptExtensionService.getReceiptDetails(fileObj);
its service name. I saw all services name are being used this way only like  {AuthService} ,{OfflineServic }etc.

2022-05-18 12:37 UTC, rvab commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +            const details = this.ReceiptExtensionService.getReceiptDetails(fileObj);
I'm talking about the variable name, not the class name
<img width="613" alt="Screenshot 2022-05-18 at 6 07 27 PM" src="https://user-images.githubusercontent.com/11194384/169040224-237d2a34-7998-4bc0-9bdf-87393c1039aa.png">

2022-05-18 12:40 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +            const details = this.ReceiptExtensionService.getReceiptDetails(fileObj);
oh! got it

2022-05-18 12:42 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +            const details = this.ReceiptExtensionService.getReceiptDetails(fileObj);
done

2022-05-18 13:04 UTC, rvab approved these changes

2022-05-18 15:48 UTC, abhishek1234321 requested changes

2022-05-18 15:48 UTC, abhishek1234321 commented on src/app/core/services/receipt-extension.service.ts
> +export class ReceiptExtensionService {
why is this called `ReceiptExtensionService` ? is it used in expenses as well?

2022-05-18 15:48 UTC, abhishek1234321 commented on src/app/core/services/receipt-extension.service.ts
> +export class ReceiptExtensionService {
shouldn't we just use a `FileService` if not already present?

2022-05-18 15:48 UTC, abhishek1234321 commented on src/app/core/services/receipt-extension.service.ts
> +    if (name) {
should this be check present at all? would TS allow to call this function like `getReceiptExtension()`?

2022-05-18 15:48 UTC, abhishek1234321 commented on src/app/core/services/receipt-extension.service.ts
> +export class ReceiptExtensionService {
did we check `file.service.ts` file and this method `getFileExtension`

2022-05-18 15:48 UTC, abhishek1234321 commented on src/app/core/services/receipt-extension.service.ts
> +  getReceiptDetails(file: FileObject) {
check `file.service.ts`

2022-05-18 15:48 UTC, abhishek1234321 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.module.ts
> +import { viewTeamAdvanceRequestPageRoutingModule } from './view-team-advance-request-routing.module';
why are we change this? what is the standard followed?

2022-05-18 15:48 UTC, abhishek1234321 commented on src/app/shared/components/summary-tile/summary-tile.component.html
> +      <div *ngIf="actions">
how does this `ngIf` help? shouldn't we be checking `*ngIf="actions.can_add_approver"` directly?

2022-05-18 15:48 UTC, abhishek1234321 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +  async viewAttachments(attachments: FileObject) {
do we not add return types?

2022-05-18 15:48 UTC, abhishek1234321 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +  async viewAttachments(attachments: FileObject) {
`attachments` is it an `[]`? if not why is it called `attachments` and not `attachment`

2022-05-18 15:48 UTC, abhishek1234321 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +        this.fileService.downloadUrl(fileObj?.id).pipe(
when would you not have `fileObj` present?

2022-05-18 15:48 UTC, abhishek1234321 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +              <app-fy-statistic
shouldn't we be using `ng-repeat` for this?

2022-05-18 16:01 UTC, sandy-fyle commented on src/app/core/services/receipt-extension.service.ts
> +export class ReceiptExtensionService {
> why is this called `ReceiptExtensionService` ? is it used in expenses as well?

it was getting used in this PR so I created a new service so that we can use it later, as of now its getting used only in this PR

2022-05-18 16:17 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.module.ts
> +import { viewTeamAdvanceRequestPageRoutingModule } from './view-team-advance-request-routing.module';
it was little confusing before because file names were view team advance but those pages were actually view-team-advance-request. so I had a discussion with @dhar and @Dimple16 to change the entire folder and files name from view-team-advance to view-team-advance-request

2022-05-18 16:26 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +  async viewAttachments(attachments: FileObject) {
I tried referring existing code base, wasn't aware about this. I will add return types now.

2022-05-18 18:30 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +  async viewAttachments(attachments: FileObject) {
its of type Observable<File[]>;

2022-05-18 18:38 UTC, sandy-fyle commented on src/app/core/services/receipt-extension.service.ts
> +export class ReceiptExtensionService {
also the method getReceiptExtension in file.service.ts is slightly different from getReceiptExtension in view-team-advance-request/view-advance-request

2022-05-18 18:39 UTC, sandy-fyle commented on src/app/core/services/receipt-extension.service.ts
> +    if (name) {
I am sorry, I didn't get this comment. Can you please elaborate?

2022-05-18 18:39 UTC, sandy-fyle commented on src/app/core/services/receipt-extension.service.ts
> +  getReceiptDetails(file: FileObject) {
done

2022-05-19 05:41 UTC, Dimple16 commented on src/app/core/services/receipt-extension.service.ts
> +export class ReceiptExtensionService {
these are 2 different things, @sandy-fyle can you move the methods in `ReceiptExtensionService` to File service, you can name it differently and use, this way we don't need another service as such

2022-05-19 05:42 UTC, Dimple16 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.module.ts
> +import { viewTeamAdvanceRequestPageRoutingModule } from './view-team-advance-request-routing.module';
this is an intentional change, from day 0, we've been naming advance request as advance and using it in team adv req folder, to avoid further confusions, this has been rectified

2022-05-19 05:43 UTC, sandy-fyle commented on src/app/core/services/receipt-extension.service.ts
> +export class ReceiptExtensionService {
oh okay, will do it.

2022-05-19 06:26 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +  async viewAttachments(attachments: FileObject) {
This function has no return so I am unable to give a return type for this function, can I put return type as Promise<any> because if its not any then it will give error as we are not returning anything

2022-05-19 06:50 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +              <app-fy-statistic
looking into it

2022-05-19 06:57 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
> +        this.fileService.downloadUrl(fileObj?.id).pipe(
'?' not needed. removed!

2022-05-19 10:44 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +              <app-fy-statistic
I checked the whole code base, we are using ngFor for all the loops, using ng-repeat at only one place won't give a non-homogeneous experience to developers?

2022-05-20 03:48 UTC, sandy-fyle commented on src/app/fyle/view-team-advance-request/view-team-advance-request-routing.module.ts
> +import { viewTeamAdvanceRequestPage } from './view-team-advance-request.page';
yes, changing it

2022-05-20 06:04 UTC, merged