fixed payment processing and payment pending pill alignment
fylein/fyle-mobile-app pull request #1085
Opened 2022-05-10 06:02 UTC by sandy-fyle

**fixed payment processing and payment pending pill alignment**
![image](https://user-images.githubusercontent.com/102028313/167558730-b5809b37-733b-41a9-9bc5-d8f03f2ef2f9.png)
![image](https://user-images.githubusercontent.com/102028313/167558748-3ad38b50-bd02-4693-8ad2-a6ab85944308.png)

2022-05-10 06:27 UTC, Dimple16 requested changes

2022-05-10 06:27 UTC, Dimple16 commented on src/app/fyle/team-reports/team-report-card/team-report-card.component.scss
> +    margin-left: -27px;
this will break in different resolutions

2022-05-10 06:27 UTC, Dimple16 commented on src/app/fyle/team-reports/team-report-card/team-report-card.component.scss
> +    margin-left: -27px;
we shouldn't be chaning css, can you check how the grid is handled

2022-05-10 06:42 UTC, sandy-fyle commented on src/app/fyle/team-reports/team-report-card/team-report-card.component.scss
> +    margin-left: -27px;
okay, looking into it.

2022-05-10 08:48 UTC, sandy-fyle commented on src/app/fyle/team-reports/team-report-card/team-report-card.component.scss
> +    margin-left: -27px;
will commit this once , re commit the changes in Team View Advance Revamp

2022-05-11 08:41 UTC, Dimple16 approved these changes

2022-05-11 09:27 UTC, merged