Removed Paid by Company
fylein/fyle-mobile-app pull request #1099
Opened 2022-05-15 05:37 UTC by OmkarJ13

2022-05-17 14:30 UTC, OmkarJ13 reviewed
This has other files that included integration of LaunchDarkly as well, this will go away after merging that PR.

2022-05-17 14:31 UTC, OmkarJ13 reviewed
We can't use LaunchDarklyService directly inside of AccountsService, this results in circular dependency injection and infinite loading, had to inject LaunchDarklyService in add-edit expense pages and there pass the value of hidePaidByCompany. (This is fixed)

2022-05-24 04:42 UTC, OmkarJ13 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                    *ngIf="paymentModes.length > 0"
We're changing the condition, context - https://fylein.slack.com/archives/C039XA79QN6/p1652855024888759

2022-05-24 05:52 UTC, OmkarJ13 commented on src/app/core/services/launch-darkly.service.ts
> +    private authService: AuthService,
This is to remove the hack, replacing RouterAuth and OfflineService, as RouterAuth also caused the same issue because it internally uses OfflineService

2022-05-25 08:25 UTC, yksolanki9 approved these changes

2022-05-25 08:25 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          paidByCompanyAccount &&
Use optional chaining

2022-05-25 08:25 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +
Optional chaining

2022-05-25 09:06 UTC, Dimple16 requested changes

2022-05-25 09:06 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +  constructPaymentModes(accounts, isMultipleAdvanceEnabled, isNotOwner?): Observable<any[]> {
avoid using `any` 
if there is no return type model, please create one

2022-05-25 09:06 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +            let currency = account.currency;
`account?.currency`

2022-05-25 09:06 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +            let currency = account.currency;
same for the below, either there should be a way to check if `account` is present, else, use fail safes

2022-05-25 09:06 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  getPaymentModes(): Observable<any[]> {
use a return type

2022-05-25 09:06 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  getPaymentModes(): Observable<any[]> {
same as above

2022-05-25 09:06 UTC, Dimple16 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +  getPaymentModes(): Observable<any[]> {
same as above

2022-05-25 09:06 UTC, Dimple16 commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +  getAccount(orgSettings: any, accounts: any, orgUserSettings: OrgUserSettings): Observable<any> {
avoid using `any`

2022-05-26 02:19 UTC, OmkarJ13 commented on src/app/core/models/account.model.ts
> +  updated_at: string;
Set these to string because this causes issue later if not converted to date after API call, since we're not doing that anywhere like web app using DateService, just kept it as string for now

2022-05-26 02:27 UTC, OmkarJ13 commented on src/app/core/services/accounts.service.ts
> +        const mappedAccouts = accounts.map((account) => account && accountsMap[account.acc.type](account));
This will fail if account is null || undefined.

2022-05-26 02:31 UTC, OmkarJ13 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +          if (isConnected) {
Had missed this edge case before, fixed now

2022-05-26 02:48 UTC, OmkarJ13 commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +          filter((account) => !!account),
Added this to handle null account cases

2022-05-26 11:44 UTC, Dimple16 requested changes

2022-05-26 11:44 UTC, Dimple16 commented on src/app/core/models/account.model.ts
> +  updated_at: string;
we use Date type everywhere in other models, can you check how it is handled?

2022-05-26 11:44 UTC, Dimple16 commented on src/app/core/models/account.model.ts
> +export interface ExtendedAccount {
use separate model files, don't combine interfaces in single files

2022-05-26 11:44 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +            mappedAccouts.push(personalNonreimbursableAccount);
`mappedAccouts` -> typo

2022-05-26 11:44 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +        return mappedAccouts;
fix this in all places used

2022-05-26 14:14 UTC, OmkarJ13 commented on src/app/core/models/account.model.ts
> +  updated_at: string;
We create dates from them using new Date() or use them in date format filters. Should I change this to date as well to avoid confusion? We will change it everywhere at once if need be.

2022-05-27 05:28 UTC, Dimple16 commented on src/app/core/models/account.model.ts
> +  updated_at: string;
yes, this should work

2022-05-27 05:29 UTC, Dimple16 approved these changes

2022-05-29 03:42 UTC, rvab requested changes

2022-05-29 03:42 UTC, rvab commented on src/app/core/services/accounts.service.ts
> +  constructPaymentModes(accounts, isMultipleAdvanceEnabled, isNotOwner?): Observable<ExtendedAccount[]> {
data type?

2022-05-29 03:42 UTC, rvab commented on src/app/core/services/accounts.service.ts
> +        };
please check indentation

2022-05-29 03:42 UTC, rvab commented on src/app/core/services/accounts.service.ts
> +          const personalAccount = accounts.find((account) => account.acc.type === 'PERSONAL_ACCOUNT');
create an enum for account type and use it here (ex: `AccountType. PERSONAL_ACCOUNT`)

2022-05-29 03:42 UTC, rvab commented on src/app/core/services/launch-darkly.service.ts
>        this.storageService.set('cachedLDFlags', latestFlags);
When do we remove the flags from the cache?

2022-05-29 03:42 UTC, rvab commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +  getAccount(orgSettings: any, accounts: any, orgUserSettings: OrgUserSettings): Observable<ExtendedAccount> {
please avoid `any`

2022-05-29 03:42 UTC, rvab commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +          orgSettings.corporate_credit_card_settings.allowed && orgSettings.corporate_credit_card_settings.enabled;
optional chaining?

2022-05-29 03:42 UTC, rvab commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +            (paymentMode) => paymentMode?.acc.type === 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT'
Use enum wherever acc.type is used

2022-05-29 03:42 UTC, rvab commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
>        orgSettings && orgSettings.advance_account_settings && orgSettings.advance_account_settings.multiple_accounts;
optional chaining

2022-05-29 03:42 UTC, rvab commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
>  type Image = Partial<{
Incorrect use of `Partial`. `Partial`should be used when using it as a type not when declaring it. Please discuss this with mobile app team

2022-05-29 03:42 UTC, rvab commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
>            (orgSettings.advance_requests && orgSettings.advance_requests.enabled);
optional chaining?

2022-05-29 03:42 UTC, rvab commented on src/app/core/models/account_detail.model.ts
> +export interface AccountDetail {
Use `-` instead of `_` while naming a file

2022-05-29 03:42 UTC, rvab commented on src/app/core/models/account_option.model.ts
> +import { ExtendedAccount } from './extended_account.model';
Use `-` instead of `_` while naming a file

2022-05-29 03:42 UTC, rvab commented on src/app/core/models/extended_account.model.ts
> +import { User } from '@sentry/angular';
Use `-` instead of `_` while naming a file

2022-05-29 03:42 UTC, rvab commented on src/app/core/services/accounts.service.ts
> +    const hidePaidByCompany$ = that.launchDarklyService.getVariation('hide_paid_by_company', false);
Should we store all the LD variation keys in one place as a const variable?. Something to think about. Not a blocker

2022-05-29 10:42 UTC, OmkarJ13 commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +  getAccount(orgSettings: any, accounts: any, orgUserSettings: OrgUserSettings): Observable<ExtendedAccount> {
Added type for accounts, model for orgSettings doesn't exist. Should I add it in another PR? Since it is out of this PRs context

2022-05-29 10:42 UTC, OmkarJ13 commented on src/app/core/services/launch-darkly.service.ts
>        this.storageService.set('cachedLDFlags', latestFlags);
on logout

2022-05-29 10:43 UTC, OmkarJ13 commented on src/app/core/services/accounts.service.ts
> +        };
This looks good in VScode, some issue here

2022-05-29 10:45 UTC, OmkarJ13 commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
>  type Image = Partial<{
okay, will check this

2022-05-29 10:46 UTC, OmkarJ13 commented on src/app/core/services/accounts.service.ts
> +    const hidePaidByCompany$ = that.launchDarklyService.getVariation('hide_paid_by_company', false);
as a object containing all flags? will think about this

2022-05-29 11:14 UTC, OmkarJ13 commented on src/app/core/services/accounts.service.ts
> +          const personalAccount = accounts.find((account) => account.acc.type === 'PERSONAL_ACCOUNT');
It is being used in alot of places, should we add this in another PR? we will need to change it across the app

2022-05-30 03:16 UTC, rvab commented on src/app/core/services/accounts.service.ts
> +          const personalAccount = accounts.find((account) => account.acc.type === 'PERSONAL_ACCOUNT');
Sure. Not a blocker for now

2022-05-30 03:16 UTC, rvab commented on src/app/core/models/extended_account.model.ts
> +import { User } from '@sentry/angular';
`User` from @sentry/angular?

2022-05-30 03:16 UTC, rvab commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +  getAccount(orgSettings: any, accounts: any, orgUserSettings: OrgUserSettings): Observable<ExtendedAccount> {
Sure.

2022-05-30 03:24 UTC, rvab requested changes

2022-05-30 03:24 UTC, rvab commented on src/app/core/services/launch-darkly.service.ts
>        this.storageService.set('cachedLDFlags', latestFlags);
What happens if the user doesn't log out?. what is the need for caching? How is the cache being used?. What happens when the user, switches the org? Is there a possibility of having multiple values for a single flag based on the org/user/role? For e.g. `A` user belongs to `Org X` and `Org Y` and the flag is `hide_per_diem`. Can the value `hide_per_diem` be different for `Org X` and `Org Y`?.

2022-05-30 16:16 UTC, OmkarJ13 commented on src/app/core/services/launch-darkly.service.ts
>        this.storageService.set('cachedLDFlags', latestFlags);
This was resolved on a call

2022-05-30 16:19 UTC, OmkarJ13 commented on src/app/core/services/accounts.service.ts
> +    const hidePaidByCompany$ = that.launchDarklyService.getVariation('hide_paid_by_company', false);
will think more about this. need to do this across all platforms, not a blocker will do this later. Discussed on a call with ab

2022-05-30 16:21 UTC, rvab approved these changes

2022-05-30 16:57 UTC, abhishek1234321 approved these changes

2022-05-31 02:48 UTC, merged