changed the font and color of amount placeholder and text
fylein/fyle-mobile-app pull request #1100
Opened 2022-05-15 17:53 UTC by sandy-fyle

![image](https://user-images.githubusercontent.com/102028313/168486885-2fca82b6-2d64-4a36-a0e7-bc44ce3c33a0.png)

![image](https://user-images.githubusercontent.com/102028313/168486871-b401a755-7226-4abb-9c7a-bdb11ddcfa49.png)
-----------------------------------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/102028313/168486844-7cb0decf-1999-4d45-b10a-3ca9f5fd9d35.png)

![image](https://user-images.githubusercontent.com/102028313/168486850-8c42b3af-e2b1-494b-9c46-aab2a5b051fc.png)

2022-05-16 05:47 UTC, Dimple16 requested changes

2022-05-16 05:47 UTC, Dimple16 commented on src/app/shared/components/fy-number/fy-number.component.scss
> +    font-weight: 600;
500?

2022-05-16 05:47 UTC, Dimple16 commented on src/app/shared/components/fy-number/fy-number.component.scss
> +    font-weight: 600;
check what Aditi had mentioned in the doc

2022-05-16 09:02 UTC, sandy-fyle commented on src/app/shared/components/fy-number/fy-number.component.scss
> +    font-weight: 600;
in figma design, 400 is mentioned but with font weight 400 it doesn't look the same as notion doc ss

2022-05-17 12:41 UTC, Dimple16 requested changes

2022-05-17 12:41 UTC, Dimple16 commented on src/app/shared/components/fy-number/fy-number.component.scss
> +    font-weight: 600;
500 should do, as this is font-weight - `medium`

2022-05-17 13:59 UTC, Dimple16 approved these changes

2022-05-17 14:08 UTC, merged