FYLE-2a81g3v: Moved tax group service to platform and added tax group models
fylein/fyle-mobile-app pull request #1107
Opened 2022-05-17 05:44 UTC by Dimple16

2022-05-19 15:45 UTC, rvab requested changes

2022-05-19 15:45 UTC, rvab commented on src/app/core/models/platform/platform-tax-group.model.ts
> +  data: PlatformTaxGroupData[];
Make this a generic interface.
<img width="291" alt="Screenshot 2022-05-19 at 8 55 44 PM" src="https://user-images.githubusercontent.com/11194384/169335616-b796f296-564a-487c-99e9-8cece5de1fbb.png">
<img width="828" alt="Screenshot 2022-05-19 at 8 56 02 PM" src="https://user-images.githubusercontent.com/11194384/169335669-5e759029-e71c-4483-b6f5-c74e438c5e34.png">

2022-05-19 15:45 UTC, rvab commented on src/app/core/services/tax_group.service.ts
> +    oldTaxGroup = platformTaxGroup.map((taxGroup) => ({
use const here. No need of let variable?

2022-05-19 15:45 UTC, rvab commented on src/app/core/services/tax_group.service.ts
> +    }));
Why do we need to transform it into an old Interface?. Can't we use the new Interface?

2022-05-19 15:45 UTC, rvab commented on src/app/core/services/tax_group.service.ts
> +      reduce((acc, curr) => acc.concat(curr), [] as any[])
Can we avoid `any`?

2022-05-19 15:45 UTC, rvab commented on src/app/core/services/tax_group.service.ts
>  import { Injectable } from '@angular/core';
Shouldn't the file name be `tax-group.service.ts`?

2022-05-19 15:45 UTC, rvab commented on src/app/core/services/tax_group.service.ts
>  import { TaxGroup } from '../models/tax_group.model';
Shouldn't the file name be `tax-group.model`?

2022-05-19 15:48 UTC, rvab requested changes
Please take care of the comments

2022-05-23 04:51 UTC, Dimple16 commented on src/app/core/services/tax-group.service.ts
> +import { Injectable } from '@angular/core';
renamed service filed

2022-05-23 04:52 UTC, Dimple16 commented on src/app/core/services/tax_group.service.ts
> +    }));
we decided to move the older APIs to the platform in this way,
we'll be using transform methods in service to transform the data,
this way, we can avoid making changes everywhere used,

2022-05-23 05:36 UTC, rvab approved these changes
Minor comments

2022-05-23 05:36 UTC, rvab commented on src/app/core/services/tax-group.service.ts
> +    const oldTaxGroup = platformTaxGroup.map((taxGroup) => ({
Can we take up the transformation in the next iteration?. We should make this change

2022-05-23 05:36 UTC, rvab commented on src/app/core/services/tax-group.service.ts
> +  post(taxGroup: TaxGroup) {
return type?

2022-05-23 06:13 UTC, Dimple16 commented on src/app/core/services/tax-group.service.ts
> +    const oldTaxGroup = platformTaxGroup.map((taxGroup) => ({
we decided to do the transformation for all APIs the same way

2022-05-23 06:14 UTC, Dimple16 commented on src/app/core/services/tax-group.service.ts
> +  post(taxGroup: TaxGroup) {
haven't made changes here, this is old code, will take care of this in post call changes pr

2022-05-23 06:20 UTC, abhishek1234321 requested changes

2022-05-23 06:20 UTC, abhishek1234321 commented on src/app/core/services/tax-group.service.ts
> +        is_enabled: 'eq.' + true,
is this needed here? I saw you removed it somewhere, doesn't platform give enabled only by default?

2022-05-23 06:20 UTC, abhishek1234321 commented on src/app/core/services/tax-group.service.ts
> +        is_enabled: 'eq.' + true,
same as above

2022-05-23 06:21 UTC, Dimple16 commented on src/app/core/services/tax-group.service.ts
> +        is_enabled: 'eq.' + true,
yes, I removed it from the offline service and added it here like other services

2022-05-23 06:25 UTC, abhishek1234321 approved these changes

2022-05-23 06:59 UTC, merged