FYLE-2cqxfzg: Unlink corporate card expenses which are implicitly merged
fylein/fyle-mobile-app pull request #1109
Opened 2022-05-17 08:55 UTC by Dimple16

<img width="385" alt="Screenshot 2022-05-17 at 2 43 09 PM" src="https://user-images.githubusercontent.com/31147415/168798953-3a1611ed-5ade-47a3-8b31-3940b2045bc5.png">
<img width="390" alt="Screenshot 2022-05-17 at 2 52 57 PM" src="https://user-images.githubusercontent.com/31147415/168798967-0d2cd82b-f3f1-4fb3-8535-4b559b4bcdc9.png">
<img width="452" alt="Screenshot 2022-05-17 at 4 52 03 PM" src="https://user-images.githubusercontent.com/31147415/168799926-d5ca39ea-efd4-458a-bd50-78cec386e9bf.png">

2022-05-17 16:29 UTC, rvab commented on src/app/core/services/transaction.service.ts
> +  getUnlinkDialogBody() {
Are we not mentioning return `type`?

2022-05-17 16:46 UTC, rvab requested changes

2022-05-17 16:46 UTC, rvab commented on src/app/core/services/transaction.service.ts
> +  getUnlinkDialogBody() {
Are we not mentioning return type?

2022-05-17 16:46 UTC, rvab commented on src/app/core/services/transaction.service.ts
> +    return this.apiService.post('/transactions/undo_implicit_merge', data);
API return `data type`?

2022-05-17 16:46 UTC, rvab commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          { id: txnDetails?.tx?.report_id, navigateBack: true },
`?` is not necessary `txnDetails?.tx?.report_id`

2022-05-17 16:46 UTC, rvab commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        etxn?.tx?.is_implicitly_merged && ['APPROVER_PENDING', 'COMPLETE', 'DRAFT'].indexOf(etxn?.tx?.state) > -1;
use `includes` instead of `indexOf`

2022-05-18 08:42 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      this.trackingService.showToastMessage({ ToastContent: toastMessageData.message });
this was to gather data around toasts when it was newly added

2022-05-18 09:42 UTC, rvab approved these changes
Minor comment

2022-05-18 09:42 UTC, rvab commented on src/app/core/models/v1/transaction.model.ts
> +import { List } from 'lodash';
Looks like unused.

2022-05-19 11:32 UTC, merged