FYLE-29pu6en-1: Added platform category models and moved category service to platform
fylein/fyle-mobile-app pull request #1116
Opened 2022-05-19 13:43 UTC by Dimple16

2022-05-19 15:22 UTC, rvab requested changes

2022-05-19 15:22 UTC, rvab commented on src/app/core/services/categories.service.ts
>    getAll() {
return type?

2022-05-19 15:22 UTC, rvab commented on src/app/core/services/categories.service.ts
> +        return range(0, count);
Why are we doing this?

2022-05-19 15:22 UTC, rvab commented on src/app/core/services/categories.service.ts
> +    oldCategory = platformCategory.map((category) => ({
use const here. No need of creating let variable

2022-05-19 15:22 UTC, rvab commented on src/app/core/services/categories.service.ts
> +    return this.spenderPlatformApiService.get('/categories', data).pipe(map((res: PlatformCategory) => res.count));
Should we follow mentioning API response type like `this.spenderPlatformApiService.get<PlatformCategory>('/categories', data).pipe(map((res)` instead of `this.spenderPlatformApiService.get('/categories', data).pipe(map((res: PlatformCategory)`?. IMO, the former is more readable.

2022-05-19 15:22 UTC, rvab commented on src/app/core/services/categories.service.ts
> +      reduce((acc, curr) => acc.concat(curr), [] as any[])
No way of avoiding `any`?

2022-05-19 15:22 UTC, rvab commented on src/app/core/services/categories.service.ts
>    skipCategories = ['activity', 'mileage', 'per diem', 'unspecified'];
Shouldn't this be private?

2022-05-23 05:08 UTC, Dimple16 commented on src/app/core/services/categories.service.ts
> +        return range(0, count);
for API pagination

2022-05-23 05:10 UTC, Dimple16 commented on src/app/core/services/categories.service.ts
>    skipCategories = ['activity', 'mileage', 'per diem', 'unspecified'];
haven't made any changes here, this is legacy code

2022-05-23 05:39 UTC, rvab approved these changes

2022-05-23 06:22 UTC, abhishek1234321 approved these changes

2022-05-23 06:59 UTC, merged