aligned the amount error propely
fylein/fyle-mobile-app pull request #1117
Opened 2022-05-19 14:53 UTC by sandy-fyle

![image](https://user-images.githubusercontent.com/102028313/169326212-a2c74446-daf7-48c8-9774-dec760bdb02c.png)

![image](https://user-images.githubusercontent.com/102028313/169326078-63d1d501-669f-47c4-8a84-9d741a205309.png)

2022-05-19 15:11 UTC, Dimple16 requested changes

2022-05-23 03:22 UTC, sandy-fyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    margin: -8px 0 0 34%;
looking into it

2022-05-23 03:56 UTC, sandy-fyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    margin: -8px 0 0 34%;
changed margin to 33% now its good for all resolutions.

2022-05-23 04:00 UTC, sandy-fyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    margin: -8px 0 0 34%;
component is used in such a way that any other way is expensive

2022-05-23 04:16 UTC, Dimple16 approved these changes

2022-05-23 04:27 UTC, merged