Fyle f1u9et v2
fylein/fyle-mobile-app pull request #1130
Opened 2022-05-24 17:15 UTC by Aditya-shrivastav

- Removed fy-currency component from add-per-diem and add-edit-expense component.
- Moved fy-currency component to shared folder for add-edit-expense.

2022-06-07 12:41 UTC, OmkarJ13 commented on src/app/shared/components/fy-currency/fy-currency.component.ts
> +  selector: 'app-new-fy-currency',
Why is `new` here?

2022-06-07 18:44 UTC, Aditya-shrivastav commented on src/app/shared/components/fy-currency/fy-currency.component.ts
> +  selector: 'app-new-fy-currency',
Since, we have app-fy-currency for advance, we cannot use the same selector name for shared component

2022-06-08 05:14 UTC, OmkarJ13 approved these changes

2022-06-13 03:33 UTC, rvab requested changes
Can you update the description?. Please add why fy-currency component is removed from `add-per-diem` and `add-edit-expense` component.

2022-06-13 03:33 UTC, rvab commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                <app-new-fy-currency
Where is `app-new-fy-currency` component?

2022-06-13 05:22 UTC, rvab approved these changes

2022-06-14 10:01 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                <app-new-fy-currency
Why create a component called new fy component? Why not retain the same name or make changes inside the same component?

2022-06-15 09:15 UTC, Julias0 approved these changes

2022-06-20 06:09 UTC, merged