Implemented approving team reports based on approver rank
fylein/fyle-mobile-app pull request #1131
Opened 2022-05-26 03:33 UTC by saitejasFyle

Sharing screenshots and the loom video of the changes:

Loom video:  https://www.loom.com/share/ad4da11c92144e569b032586f6450daa

<img width="313" alt="Screenshot 2022-05-26 at 8 49 58 AM" src="https://user-images.githubusercontent.com/97864484/170410548-7f60be26-ba2e-4b1f-a838-79cc3e5d9a32.png">

2022-05-27 12:49 UTC, Dimple16 requested changes

2022-05-27 12:49 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.html
> +          class="vire-reports--icon-close"
`vire` - typo

2022-05-27 12:49 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    text-align: center;
use global class - `text-center`

2022-05-27 12:49 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    color: #fff;
use color variable - `$pure-white`

2022-05-27 12:49 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +type Approver = {
we should be adding this inside a model

2022-05-27 12:49 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +        res.orgSettings.approval_settings && res.orgSettings.approval_settings.enable_sequential_approvers;
`this.isSequentialApprovalEnabled = res?.orgSettings.approval_settings?.enable_sequential_approvers;`

2022-05-27 12:49 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  closeApproceDisabledTooltip() {
`closeApproceDisabledTooltip` typo

2022-05-27 12:49 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  checkIsTopInSequentialApproval(eou, approvals) {
can we rename this for better readability?

2022-05-27 12:49 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  openApproveDisabledTooltip() {
openApproveDisabledTooltip - `showTooltip()` works?

2022-05-27 12:49 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  closeApproceDisabledTooltip() {
hideTooltip()? works?

2022-05-27 12:49 UTC, Dimple16 commented on src/theme/colors.scss
> +$info-tooltip-color: #2c304e;
`$info-tooltip-color: #2c304e !default;`

2022-05-28 01:20 UTC, saitejasFyle commented on src/theme/colors.scss
> +$info-tooltip-color: #2c304e;
Done.... And why so? Why it has to be !default

2022-05-28 01:21 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  openApproveDisabledTooltip() {
And what if we have to implement someother tooltips in the future as well? Name specific tooltips will help right?

2022-05-28 01:23 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  checkIsTopInSequentialApproval(eou, approvals) {
This is same as per the web app implementation which happened in parallel. Didn't want to change it just in the mobile app. And I think it's pretty understandable. What say?

2022-05-28 01:23 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  closeApproceDisabledTooltip() {
And what if we have to implement someother tooltips in the future as well? Name specific tooltips will help right?

2022-05-28 01:25 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +        res.orgSettings.approval_settings && res.orgSettings.approval_settings.enable_sequential_approvers;
Done

2022-05-28 01:26 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    color: #fff;
Done

2022-05-28 01:27 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    text-align: center;
Done

2022-05-28 01:27 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.html
> +          class="vire-reports--icon-close"
Done

2022-05-28 01:28 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  checkIsTopInSequentialApproval(eou, approvals) {
If not any suggestions?

2022-05-28 01:36 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +type Approver = {
But there is an interface already with the name Approver but with different structure. And it's pretty much used in some places. Quite confused in naming this Approver model. Any suggestions?


<img width="255" alt="Screenshot 2022-05-28 at 7 04 42 AM" src="https://user-images.githubusercontent.com/97864484/170804697-5e221bdd-af19-4d4b-a939-02f15adb8d64.png">
<img width="842" alt="Screenshot 2022-05-28 at 7 04 16 AM" src="https://user-images.githubusercontent.com/97864484/170804700-b855b4de-ae77-4098-9607-c3185bf00c2a.png">

2022-05-30 06:14 UTC, Dimple16 requested changes

2022-05-30 06:14 UTC, Dimple16 commented on src/theme/colors.scss
> +$info-tooltip-color: #2c304e !default;
this isn't required, you can use the existing color - `$blue-black`
please check the existing colors before adding new ones, most of the colors are already added during design revamps

2022-05-30 06:14 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    this.eou$ = from(this.authService.getEou());
why are we changing this to global here?

2022-05-30 06:14 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      eou: this.eou$.pipe(take(1)),
we can directly use `this.authService.getEou()` here right?

2022-05-30 06:14 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    clip-path: polygon(0 0, 100% 0, 50% 100%);
can you check if there is support for this here - https://caniuse.com/

2022-05-30 06:14 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    clip-path: polygon(0 0, 100% 0, 50% 100%);
if not, we might need to use a different way

2022-05-30 06:14 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      this.orgUserId = etxns.map((etxn) => etxn.ou_id)[0];
why is the `[0]` here?

2022-05-30 06:14 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      this.reportApprovals$.subscribe((approvals) => {
are we doing a subscribe inside a subscribe? please don't do it this way
avoid using nested subscribes
refer - https://angular-checklist.io/default/checklist/rxjs/Z1eFwa9

2022-05-30 06:14 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  isSequentialApprovalEnabled: boolean;
assign default values for these flags

2022-05-30 06:14 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  isTopInSequentialApproval: boolean;
same as above

2022-05-30 06:14 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  showApproveDisabledTooltip: boolean;
same as above

2022-05-30 07:37 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  checkIsTopInSequentialApproval(eou, approvals) {
Done

2022-05-30 07:39 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  openApproveDisabledTooltip() {
Done

2022-05-30 07:40 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      this.orgUserId = etxns.map((etxn) => etxn.ou_id)[0];
map returns the id in an array, but just an ID is what I need, so Just referring to the first index

2022-05-30 07:42 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    clip-path: polygon(0 0, 100% 0, 50% 100%);
<img width="1316" alt="Screenshot 2022-05-30 at 1 11 36 PM" src="https://user-images.githubusercontent.com/97864484/170942425-9149f77f-0094-4e7d-bcfd-8ad1a647531e.png">

Yeah, this is being used across fairly

2022-05-30 07:47 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    this.eou$ = from(this.authService.getEou());
Because, I'm making use of this in the forkJoin instead of calling the authService.getEou() redundantly

2022-05-30 07:47 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      eou: this.eou$.pipe(take(1)),
Using this in the forkJoin instead of calling the authService.getEou() redundantly which is already defined in ngOnInit()

2022-05-30 07:49 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  closeApproceDisabledTooltip() {
Done

2022-05-30 07:50 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    bottom: 72px;
Checked this and shared behaviour of it in the different resolutions in the loom video

2022-05-30 07:51 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    left: calc(50% - 10px);
This is tested in different resolutions and shared that in the loom video

2022-05-30 07:54 UTC, saitejasFyle commented on src/theme/colors.scss
> +$info-tooltip-color: #2c304e !default;
Ok sure

2022-05-30 07:57 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  isSequentialApprovalEnabled: boolean;
Done

2022-05-30 07:57 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  isTopInSequentialApproval: boolean;
Done

2022-05-30 07:57 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  showApproveDisabledTooltip: boolean;
Done

2022-05-30 09:48 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      this.reportApprovals$.subscribe((approvals) => {
Resolved this using forkjoin

2022-06-06 04:44 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      this.isTopInSequentialApproval = this.isSequentialApprovalEnabled
This is in accordance with the web app implementation that happened in parallel. So just adopted it

2022-06-06 04:45 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +type Approver = {
Done

2022-06-06 08:00 UTC, saitejasFyle commented on src/app/core/models/v2/approver.model.ts
> +  id: number;
It's /api/report/approvers

2022-06-06 08:41 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  isTopInSeqApproval(eou, approvals) {
Done

2022-06-06 08:42 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    clip-path: polygon(0 0, 100% 0, 50% 100%);
Implemented using CSS itself

2022-06-06 09:25 UTC, Dimple16 requested changes

2022-06-06 09:25 UTC, Dimple16 commented on src/app/core/models/v2/approver.model.ts
> +  id: number;
then it shouldn't be inside the `v2` folder no?

2022-06-06 09:25 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    this.canShowTooltip = false;
`this.canShowTooltip = !!this.canShowTooltip;`

2022-06-06 09:25 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    this.canShowTooltip = true;
this.canShowTooltip = !this.canShowTooltip;

2022-06-06 10:31 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    this.canShowTooltip = false;
Handled these in just one toggle func - toggleTooltip()

2022-06-06 10:31 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    this.canShowTooltip = true;
Handled these in just one toggle func - toggleTooltip()

2022-06-07 08:26 UTC, Dimple16 approved these changes

2022-06-07 13:22 UTC, rvab requested changes

2022-06-07 13:22 UTC, rvab commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    background: $blue-black;
use `background-color`

2022-06-07 13:22 UTC, rvab commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  approvers: Approver[];
same as above

2022-06-07 13:22 UTC, rvab commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    approvers.forEach(function (approver) {
use arrow functions

2022-06-07 13:22 UTC, rvab commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  isTopInSequentialApproval = true;
Can we rename it to `isHeadOfSequentialApproval`?

2022-06-08 04:46 UTC, saitejasFyle commented on src/app/core/models/v2/approver.model.ts
> +  id: number;
Done

2022-06-08 04:55 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.scss
> +    background: $blue-black;
Done

2022-06-08 04:56 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  isTopInSeqApproval(eou: ExtendedOrgUser, approvers: Approver[]) {
Done

2022-06-08 04:58 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  orgUserId: string;
Removed it

2022-06-08 05:02 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    approvers.forEach(function (approver) {
Done

2022-06-08 05:03 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  isTopInSequentialApproval = true;
Done

2022-06-08 05:03 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  approvers: Approver[];
Done

2022-06-08 05:22 UTC, rvab approved these changes
Minor comment

2022-06-08 05:22 UTC, rvab commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    // });
remove this comment if not required

2022-06-08 05:31 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    // });
Done

2022-06-08 06:38 UTC, Julias0 commented on src/app/fyle/view-team-report/view-team-report.page.html
> +      <ion-button
wait why create two buttons for this?
Use ng class for the class and handle the interaction inside a function by checking isHeadOfSequentialApproval and triggering a corresponding function

2022-06-08 06:39 UTC, Julias0 commented on src/app/fyle/view-team-report/view-team-report.page.ts
>    ngOnInit() {
Shouldnt we use ionViewWillEnter instead of ngOnInit? I think this will end up causing bugs

2022-06-08 06:40 UTC, Julias0 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    this.eou$ = from(this.authService.getEou());
Why do you need to connect eou to this?

2022-06-08 06:40 UTC, Julias0 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      eou: this.eou$.pipe(take(1)),
why is take required here?

2022-06-08 06:41 UTC, Julias0 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      orgSettings: this.offlineService.getOrgSettings().pipe(take(1)),
why is take required here?

2022-06-08 06:46 UTC, Julias0 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    let currentApproverRank = 100;
```ts
let currentApproverRank = approvers.find(approver => approver.approver_id === eou.ou.id)?.rank;

let minRank = approvers
.filter(approver => approver.state === 'APPROVAL_PENDING')
.map(approver => approver.rank)
.reduce(function(prev, curr) {
    return prev < curr ? prev : curr;
});
```

Do this in a more functional style

2022-06-08 06:47 UTC, Julias0 requested changes
Please make changes

2022-06-10 06:26 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.html
> +      <ion-button
Done

2022-06-10 06:28 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
>    ngOnInit() {
I haven't touched anything in ngOnInit. Everything is pre-existing. Should I move it to ionViewWillEnter now?

2022-06-10 06:35 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    this.eou$ = from(this.authService.getEou());
`isTopInSeqApproval(eou: ExtendedOrgUser, approvers: Approver[]): boolean {
    let minRank = 100;
    let currentApproverRank = 100;

    approvers.forEach((approver) => {
      if (approver.approver_id === eou.ou.id) {
        currentApproverRank = approver.rank;
      }
      if (approver.state === 'APPROVAL_PENDING' && approver.rank < minRank) {
        minRank = approver.rank;
      }
    });
    return currentApproverRank === minRank;
  }`
  
  To check the user's rank to approve

2022-06-10 06:36 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      eou: this.eou$.pipe(take(1)),
I'm subscribing to the latest value of the stream

2022-06-10 06:36 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      orgSettings: this.offlineService.getOrgSettings().pipe(take(1)),
Same here

2022-06-10 06:59 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    let currentApproverRank = 100;
Done

2022-06-10 07:33 UTC, Julias0 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      eou: this.eou$.pipe(take(1)),
`this.eou$ = from(this.authService.getEou());`
Since this is created from a promise, the stream will complete after emitting 1 item. Take dosnt do anything here

2022-06-10 07:35 UTC, Julias0 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  isTopInSeqApproval(eou: ExtendedOrgUser, approvers: Approver[]): boolean {
isTopInSeqApproval -> isUserActiveInCurrentSeqApprovalQueue

2022-06-10 07:36 UTC, Julias0 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      this.isHeadOfSequentialApproval = this.isSequentialApprovalEnabled
isHeadOfSequentialApproval -> canApprove

2022-06-10 07:37 UTC, Julias0 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    this.eou$ = from(this.authService.getEou());
I meant you can put it inside a const variable right. You dont need to put it inside this

2022-06-10 07:37 UTC, Julias0 requested changes
Minor comments

2022-06-10 07:43 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      this.isHeadOfSequentialApproval = this.isSequentialApprovalEnabled
Done

2022-06-10 07:58 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      eou: this.eou$.pipe(take(1)),
Got it

2022-06-10 07:58 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      orgSettings: this.offlineService.getOrgSettings().pipe(take(1)),
Done

2022-06-10 08:09 UTC, saitejasFyle commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +    this.eou$ = from(this.authService.getEou());
Resolved it based on the conversation: Let's keep it in the class level

2022-06-10 10:00 UTC, Julias0 approved these changes

2022-06-10 11:17 UTC, merged