Fix modals `swipeToClose` deprecation warnings
fylein/fyle-mobile-app pull request #1145
Opened 2022-05-31 15:46 UTC by yksolanki9

Issue:
- We're getting `swipeToClose has been deprecated in favour of canDismiss` warnings after upgrading to ionic 6
- Ionic has deprecated swipeToClose property and it will be removed in v7. We use full page modals in our app and going forward full page modals cannot be closed by swiping.
- This comment from one of the maintainers summarises the point -  `The current thinking is that modals should only be swipeable when either using the card modal or the sheet modal. The fact that non-card/sheet modals could be swipeable was a mistake on our end. This change is being done to better align with native iOS and Android behavior`
- The docs for modals are not updated and all examples on the ionic website throw the same warning we’re getting

Solution
- I have converted all full page modals to sheet modals, there is no visual change, only the way we create a modal has changed and we still have the swipe to close functionality

2022-06-07 11:17 UTC, Dimple16 approved these changes

2022-06-07 13:05 UTC, rvab requested changes

2022-06-07 13:05 UTC, rvab commented on src/app/core/services/modal-properties.service.ts
> +      handle: false,
Can we not move these options to `ModalPropertiesService`?  May be a create new method

2022-06-07 13:05 UTC, rvab commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
> -      presentingElement: await this.modalController.getTop(),
Why remove it?

2022-06-07 13:05 UTC, rvab commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
> -      presentingElement: await this.modalController.getTop(),
Why remove it?

2022-06-07 13:05 UTC, rvab commented on src/global.scss
> +  --background: $white;
Can we not use `background-color`?

2022-06-09 14:26 UTC, yksolanki9 commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
> -      presentingElement: await this.modalController.getTop(),
It is used when presenting modal on top of modal. Since we're presenting on top of page, it is redundant here

2022-06-09 14:37 UTC, yksolanki9 commented on src/global.scss
> +  --background: $white;
Action sheet is not a native html element, usual css properties do not directly work on it
https://ionicframework.com/docs/api/action-sheet

2022-06-09 14:58 UTC, rvab requested changes

2022-06-09 14:58 UTC, rvab commented on src/app/core/services/modal-properties.service.ts
> +      handle: false,
The same custom properties are being used at 6 different places. Shouldn't we avoid this?. Can't we create a new method that returns the default + these new properties?

2022-06-13 06:12 UTC, rvab approved these changes

2022-06-14 04:44 UTC, Julias0 approved these changes

2022-06-14 12:01 UTC, merged