Fyle 29wgk6a - placeholder fix
fylein/fyle-mobile-app pull request #1152
Opened 2022-06-03 04:36 UTC by Aditya-shrivastav

- Added placeholder field for default fields.
- Show label name if placeholder is missing

2022-06-03 07:58 UTC, OmkarJ13 commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
> +                    [placeholder]="customInput.placeholder || 'Enter ' + customInput.name | ellipsis: 30"
Does the ellipsis get applied to both? Do we need brackets here?

2022-06-03 08:01 UTC, OmkarJ13 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                      [placeholder]="txnFields?.org_category_id?.placeholder"
Don't need optional chaining here, we are checking in the parent div

2022-06-03 08:04 UTC, OmkarJ13 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                      [placeholder]="txnFields.train_travel_class?.placeholder || 'Enter ' + txnFields.train_travel_class?.field_name"
Don't need optional chaining here

2022-06-03 08:05 UTC, OmkarJ13 requested changes
Please check all the places where using optional chaining, if the parent has checked, we don't need to check again

2022-06-03 09:00 UTC, Aditya-shrivastav commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
> +                    [placeholder]="customInput.placeholder || 'Enter ' + customInput.name | ellipsis: 30"
Yes, It will be applied to both, tested it

2022-06-03 11:16 UTC, OmkarJ13 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
> +                              [name]="txnFields?.from_dt.placeholder || txnFields?.from_dt.field_name"
Don't need optional chaining here as well

2022-06-03 11:16 UTC, OmkarJ13 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
> +                              [name]="txnFields?.to_dt.placeholder || txnFields?.to_dt.field_name"
Same

2022-06-03 11:16 UTC, OmkarJ13 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
> +                          [placeholder]="txnFields?.num_days.placeholder || 'Enter ' + txnFields?.num_days.field_name | ellipsis: 30"
Same

2022-06-03 11:16 UTC, OmkarJ13 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
> +                              [placeholder]="txnFields.purpose?.placeholder || 'Enter '+txnFields.purpose?.field_name | ellipsis: 30"
Same

2022-06-03 11:16 UTC, OmkarJ13 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.html
> +                            [placeholder]="txnFields.purpose?.placeholder | ellipsis: 30"
Same

2022-06-05 04:18 UTC, OmkarJ13 approved these changes

2022-06-05 04:54 UTC, abhishek1234321 requested changes

2022-06-05 04:54 UTC, abhishek1234321 commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
> +                    [placeholder]="customInput.placeholder | ellipsis: 30"
what if `placeholder` is null? do we not need to handle it here?

2022-06-05 04:54 UTC, abhishek1234321 commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.html
> +                    [placeholder]="customInput.placeholder | ellipsis: 30"
same comment applies everywhere

2022-06-05 04:54 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                      [placeholder]="'Payment Mode'"
could you put a screenshot of how this would look in the UI?

2022-06-06 05:05 UTC, abhishek1234321 approved these changes

2022-06-06 09:46 UTC, merged