FYLE-29pu6en-2: Platform changes - Category service
fylein/fyle-mobile-app pull request #1154
Opened 2022-06-03 10:54 UTC by Dimple16

### Previously approved PR - https://github.com/fylein/fyle-mobile-app/pull/1116

### New changes

1. Subcategory fix
- As the sub-category is null for parent-only categories, added the fix to work similarly on the public side 
`sub_category: category.sub_category || category.name`

2. Cluster domain fix
- SpenderPlatformApiService - cluster domain set root was missing in router-auth service
`this.spenderPlatformApiService.setRoot(domain);`

2022-06-03 13:30 UTC, rvab requested changes

2022-06-03 13:30 UTC, rvab commented on src/app/core/models/platform/platform-category.model.ts
> +  sub_category: string;
Shouldn't this be optional?

2022-06-03 13:30 UTC, rvab commented on src/app/core/services/categories.service.ts
> +        limit: 1,
only 1?

2022-06-06 08:55 UTC, Dimple16 commented on src/app/core/services/categories.service.ts
> +        limit: 1,
yes, this is just to get the count

2022-06-06 08:56 UTC, Dimple16 commented on src/app/core/models/platform/platform-category.model.ts
> +  sub_category: string;
no, we'll have the key always

2022-06-06 11:46 UTC, rvab approved these changes

2022-06-07 06:01 UTC, Julias0 commented on src/app/core/services/categories.service.ts
> +      map((res) => res),
this map dosnt do anything

2022-06-07 06:26 UTC, Julias0 commented on src/app/core/services/categories.service.ts
> +      map(this.sortCategories),
```
map(res => this.sortCategories(res)),
map(res => this.addDisplayName(res))

```

Passing a function as an argument messes up the reference of this associated with the function. Safer to use inside a lambda

2022-06-07 06:26 UTC, Julias0 approved these changes

2022-06-07 12:50 UTC, merged