FYLE-2a81g3v-1: Platform changes - Tax groups service
fylein/fyle-mobile-app pull request #1162
Opened 2022-06-08 13:09 UTC by Dimple16

Previously approved PR - https://github.com/fylein/fyle-mobile-app/pull/1107

2022-06-15 04:43 UTC, Julias0 commented on src/app/core/services/tax-group.service.spec.ts
> +      updated_at: new Date('2020-06-11T13:14:55.201598+00:00'),
ok the response dosnt return a date object na - this needs to happen inside the transform step, you basically pass the value you get from the response into new Date

2022-06-15 04:44 UTC, Julias0 commented on src/app/core/services/tax-group.service.spec.ts
> +describe('TaxGroupService', () => {
Please add a screenshot of the code coverage report for this file - `tax-group.service.ts`
We should be maintaining 100% code coverage

2022-06-15 04:44 UTC, Julias0 requested changes
Added comments to the unit tests

2022-06-15 13:45 UTC, Dimple16 commented on src/app/core/services/tax-group.service.spec.ts
> +describe('TaxGroupService', () => {
will share the screenshot on thread

2022-06-16 04:56 UTC, Julias0 approved these changes

2022-06-21 16:19 UTC, Dimple16 commented on src/app/core/services/tax-group.service.spec.ts
> +describe('TaxGroupService', () => {
added screenshot

2022-06-21 16:20 UTC, Dimple16 commented on src/app/core/services/tax-group.service.ts
> +        count = count >= this.paginationSize ? count / this.paginationSize : 1;
@Julias0 changed this from `count > this.paginationSize` -> `count >= this.paginationSize` 
without this, covering the test case code `count / this.paginationSize` wouldn't be possible even after the pagination size change

2022-06-22 04:19 UTC, Julias0 approved these changes

2022-06-22 05:33 UTC, merged