Fyle 28mekc8 1
fylein/fyle-mobile-app pull request #1169
Opened 2022-06-11 16:50 UTC by saitejasFyle

2022-06-13 04:51 UTC, Julias0 commented on src/app/core/services/categories.service.ts
> +  filterByOrgCategoryId(orgCategoryId, categoryList) {
Why not just use find? Why have this implementation? Also whenever creating a function please add data types to the inputs and response

2022-06-13 04:52 UTC, Julias0 commented on src/app/core/services/policy.service.ts
> +  checkIfViolationsExist(violations) {
Please define input and output datatypes

2022-06-13 06:45 UTC, Dimple16 commented
**Regarding screenshots:**
- We can use the auto-height for new modals henceforth, it is already implemented, please check if we can reuse the same - https://github.com/fylein/fyle-mobile-app2/pull/484
- The CTAs aren't the same as the new FDL, can you check the letter spacing and CTA fill color
- The box shadow is missing from the footer
- There is an extra border in the last screenshot (I guess this was pre-existing - need to remove this)
- The pill `1 Policy violation` - the padding is off, or the height is off, due to which the alignment is broken

2022-06-13 13:54 UTC, Dimple16 requested changes

2022-06-13 13:54 UTC, Dimple16 commented on src/app/core/services/split-expense.service.ts
> +      scan((acc, curr) => ({ ...curr, ...acc }), {}),
instead of scan and last, we can directly use reduce(), as it will emit last value on completion

2022-06-13 13:54 UTC, Dimple16 commented on src/app/core/services/split-expense.service.ts
> +  runApiCallSerially(etxns) {
can we rename with context? this is generalised

2022-06-13 13:54 UTC, Dimple16 commented on src/app/core/services/split-expense.service.ts
> +      mergeMap((etxn) => this.testPolicyForATxn(etxn)),
use `concatMap` instead as mergeMap would work in parallel

2022-06-13 13:54 UTC, Dimple16 commented on src/app/core/services/split-expense.service.ts
> +    return from(etxns).pipe(
we need to check if `etxns` length > 0,

2022-06-13 13:54 UTC, Dimple16 commented on src/app/core/services/split-expense.service.ts
> +    const that = this;
can remove, this is not being used

2022-06-13 13:54 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +import { FyPolicyViolationComponent } from 'src/app/shared/components/fy-policy-violation/fy-policy-violation.component';
I don't think `Fy` is required here?

2022-06-13 13:54 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +
remove extra line

2022-06-13 13:54 UTC, Dimple16 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
> +      <div *ngIf="policyViolations[transaction].rules.length > 0" class="split-expense-policy-violation--accordion">
`policyViolations[transaction]?.rules?.length`

2022-06-13 13:54 UTC, Dimple16 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
> +          <div class="split-expense-policy-violation--header-slot">
we can add the below inside a component?

2022-06-13 13:54 UTC, Dimple16 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.scss
> +    border-bottom: 1px solid #f0f0f2;
add a color variable

2022-06-13 13:54 UTC, Dimple16 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.scss
> +    font-size: 14px;
this is default text size

2022-06-13 13:54 UTC, Dimple16 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  @Input() policyViolations: any;
avoid `any`

2022-06-13 13:54 UTC, Dimple16 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  transactionIDs = [];
add list type

2022-06-13 13:54 UTC, Dimple16 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +      .pipe(map((res) => res));
are we modifying anything in the map here?

2022-06-14 05:19 UTC, saitejasFyle commented on src/app/core/services/policy.service.ts
> +    for (const key in violations) {
No, violations is an object and not an array. We are actually iterating the keys of an object using For in loop

2022-06-14 05:36 UTC, saitejasFyle commented on src/app/core/services/categories.service.ts
> +  filterByOrgCategoryId(orgCategoryId, categoryList) {
Done

2022-06-14 05:36 UTC, saitejasFyle commented on src/app/core/services/categories.service.ts
> +    categoryList.some((cat) => {
Optimised using filter()

2022-06-14 05:55 UTC, saitejasFyle commented on src/app/core/services/policy.service.ts
> +  checkIfViolationsExist(violations) {
Violations is an object with the transactionID as the key which is completely run-time. How could that be modelled?

2022-06-14 05:58 UTC, saitejasFyle commented on src/theme/colors.scss
> +$butter-milk: #ffefb7 !default;
replaced with $pale-orange

2022-06-14 06:10 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +      if (category) {
Added it as a fool proof condition. Optimised it using `return category?.displayName;`

2022-06-14 06:11 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +        etxns.forEach((etxn) => {
But as per the logic, I have to iterate the data which is an object to map the correct etxn

2022-06-14 06:13 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +    const currencyModal = await this.modalController.create({
Renamed as `splitExpenseViolationsModal`

2022-06-14 06:17 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +        this.getCategories().subscribe();
I have just subscribed to that function to invoke it

2022-06-14 06:20 UTC, saitejasFyle commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
> +<div *ngIf="showHeader" mode="md">
It was pre-existing. I've just changed the HTML and CSS. Should I remove it now?

2022-06-14 06:24 UTC, saitejasFyle commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> +  cancel() {
It's just an operation right?

2022-06-14 06:25 UTC, saitejasFyle commented on src/app/shared/components/fy-policy-violation/policy-violation-action/policy-violation-action.component.html
> +    <div class="policy-violation-action--icon" *ngIf="icon">
No, as per the current design in this context, it's not possible. What if we want to reuse the same component elsewhere where an icon is optional?

2022-06-14 07:07 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.scss
> +    border-bottom: 1px solid #f0f0f2;
Added as $lavender

2022-06-14 07:18 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.scss
> +    font-size: 14px;
Unanted snippet - removed it

2022-06-14 07:19 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.scss
> +  &__content {
Resolved

2022-06-14 07:27 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  transactionIDs = [];
If I initialize this as `transactionIDs : string[]`, I won't be able to do any operations like push, pop etc.., It'll thrown an error `push of undefined`. It has to be initialised right?

2022-06-14 07:28 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +      .pipe(map((res) => res));
Nope, we aren't. Just mapping the response as it is and returning it

2022-06-14 07:31 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +        const allEnabledCategories = this.categoriesService.filterEnabled(categories);
Do you mean to pass `allCategories` here ` this.categoryList = this.categoriesService.filterRequired(allEnabledCategories)` instead of `allEnabledCategories` ?

2022-06-14 07:51 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +  runApiCallSerially(etxns) {
renamed as checkPolicyForTransactions()

2022-06-14 08:03 UTC, saitejasFyle commented on src/assets/svg/profile-outline.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
If the height and width are removed, nothing gets displayed. Sharing the screenshot
<img width="323" alt="Screenshot 2022-06-14 at 1 31 25 PM" src="https://user-images.githubusercontent.com/97864484/173525954-abbc2ecb-4728-422e-bfb0-f990f3f22f45.png">

2022-06-14 08:03 UTC, saitejasFyle commented on src/assets/svg/flag-outline.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
same as above

2022-06-14 08:03 UTC, saitejasFyle commented on src/assets/svg/capped-amount.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
same as above

2022-06-14 08:03 UTC, saitejasFyle commented on src/assets/svg/2-users.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
same as above

2022-06-14 08:11 UTC, saitejasFyle commented on src/app/core/services/policy.service.ts
> +    emails.forEach((email, index) => {
Yup, this'll work

2022-06-14 08:38 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +      scan((acc, curr) => ({ ...curr, ...acc }), {}),
Done using reduce()

2022-06-14 08:39 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +        policyResponse[etxn.tx_id] = response;
Do you want me to add comments on the code explaining what we are doing there?

2022-06-14 08:49 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +        return of(txnIds);
This is an unwanted change. reverted it back

2022-06-14 08:54 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +      mergeMap((etxn) => this.testPolicyForATxn(etxn)),
Done

2022-06-14 08:56 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  @Input() policyViolations: any;
Same doubt as in [here](url). Shall I just remove any? like this: `@Input() policyViolations;`

2022-06-14 08:57 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  @Input() policyViolations: any;
same doubt as in [here](https://github.com/fylein/fyle-mobile-app/pull/1169#discussion_r896401296). Shall I just remove any? like this: `  @Input() policyViolations;`

2022-06-14 11:12 UTC, saitejasFyle commented on src/app/core/services/policy.service.ts
> +        if (rules && rules.length > 0) {
Done

2022-06-14 11:13 UTC, saitejasFyle commented on src/app/core/services/policy.service.ts
> +  getApprovalString(emails) {
Done

2022-06-14 11:13 UTC, saitejasFyle commented on src/assets/svg/profile-outline.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Width has been moved to CSS

2022-06-14 11:14 UTC, saitejasFyle commented on src/assets/svg/flag-outline.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Same as above

2022-06-14 11:14 UTC, saitejasFyle commented on src/assets/svg/capped-amount.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Same as above

2022-06-14 11:14 UTC, saitejasFyle commented on src/app/core/services/policy.service.ts
> +    emails.forEach((email, index) => {
Done

2022-06-14 11:14 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +import { analyzeAndValidateNgModules } from '@angular/compiler';
Done

2022-06-14 11:17 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +        policyResponse[etxn.tx_id] = response;
Added comment in the code. Done

2022-06-14 11:19 UTC, saitejasFyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +import { FyPolicyViolationComponent } from 'src/app/shared/components/fy-policy-violation/fy-policy-violation.component';
We have another component named fy-policy-violation-info component already available. So just followed that. If I want to remove, I have to search only for my changes without overriding the existing ones. Is this mandatory?

2022-06-14 11:21 UTC, saitejasFyle commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation.component.html
> +<div *ngIf="showHeader" mode="md">
Done, removed it

2022-06-14 11:23 UTC, saitejasFyle commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> +
This has to be sequential. For every flag being true, the availableActionsCount has to get incremented. For an instance, if all the 4 flags are true, the count should be 4.

`if (this.isExpenseFlagged) {
        this.availableActionsCount += 1;
      }
      if (this.isPrimaryApproverSkipped) {
        this.availableActionsCount += 1;
      }
      if (this.needAdditionalApproval) {
        this.availableActionsCount += 1;
      }
      if (this.isExpenseCapped) {
        this.availableActionsCount += 1;
      }`

2022-06-14 11:23 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  @Input() policyViolations: any;
Associated this with the Object type

2022-06-14 11:24 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  transactionIDs = [];
Done

2022-06-14 11:31 UTC, saitejasFyle commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation-message/fy-critical-policy-violation-message.component.scss
> +    overflow-wrap: anywhere;
Removed overflow-wrap property. It works fine as expected without this property.

2022-06-14 11:32 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +    return from(etxns).pipe(
Done

2022-06-14 11:32 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +    const that = this;
Done

2022-06-14 11:32 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +  categoryList = [];
Done

2022-06-14 11:33 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +
Done

2022-06-14 11:34 UTC, saitejasFyle commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> +  isExpenseFlagged: boolean;
Done

2022-06-14 11:34 UTC, saitejasFyle commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> +  //Remove this once the policy action description gets returned as an array while integrating platform API
Done

2022-06-14 11:36 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
> +      <div *ngIf="policyViolations[transaction].rules.length > 0" class="split-expense-policy-violation--accordion">
Done

2022-06-14 11:38 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  @Input() policyViolations: any;
Done using Object type

2022-06-14 11:38 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  transactionIDs = [];
Done

2022-06-14 12:33 UTC, Julias0 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +    this.transactionIDs.forEach((transactionID) => {
Move this to a service

2022-06-14 12:34 UTC, Julias0 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  postComment(apiPayload) {
data type is not added

2022-06-14 12:34 UTC, Julias0 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +      .pipe(map((res) => res));
Please remove this - this is not doing anything

2022-06-14 12:37 UTC, Julias0 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +    if (this.policyViolations) {
in which case would this be null?

2022-06-14 12:39 UTC, Julias0 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  @Input() policyViolations: Object;
Use Record generic class

2022-06-14 12:41 UTC, Julias0 commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
> +                    [(ngModel)]="comments[transaction]"
Shouldnt we use FormArray? Why use ngModel?

2022-06-14 12:48 UTC, Julias0 commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> +  @Input() comment = '';
This is not used via input

2022-06-14 12:50 UTC, Julias0 commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> +        this.additionalApprovalString = this.policyService.getApprovalString(emails);
additionalApprovalString -> approverEmailsRequiredMsg

2022-06-14 12:59 UTC, Julias0 commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation-message/fy-critical-policy-violation-message.component.scss
> +.critical-policy-violation-message {
The only difference between critical and normal policy violation component is CSS - why dont you combine both of these?

2022-06-14 12:59 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +      //Remove this section
? Please remove dead code before code reviews

2022-06-14 13:04 UTC, Julias0 requested changes
Please to make changes and get back

2022-06-15 06:06 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +    this.transactionIDs.forEach((transactionID) => {
Done

2022-06-15 06:14 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  postComment(apiPayload) {
Have introduced an interface `PolicyViolationComment` for this

2022-06-15 06:17 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +    this.policyViolations[currentTransactionID].isExpanded = !this.policyViolations[currentTransactionID].isExpanded;
Nope, this can't be always true. Consider a case where we are clicking again on the panel which is already expanded. On clicking on any panels, I'm making sure that all the other panels except the clicked one is collapsed and then toggling the clicked one.

2022-06-15 06:19 UTC, saitejasFyle commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> +        this.additionalApprovalString = this.policyService.getApprovalString(emails);
Done

2022-06-15 06:29 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +      //Remove this section
Done

2022-06-15 06:29 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +      //Remove this section
Sure

2022-06-15 07:20 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +    if (model && this.categoryList) {
There are no such cases. Just adding these conditions to make it fool proof

2022-06-15 07:21 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
> +  <ng-container *ngIf="policyViolations && transactionIDs" class="policy-violation--body">
No, just waiting for them to get initialized before rendering the HTML page.

2022-06-15 07:26 UTC, saitejasFyle commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> +  @Input() comment = '';
Removed it

2022-06-15 07:29 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +      .pipe(map((res) => res));
Done

2022-06-15 09:01 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +  getCategories(): Observable<OrgCategory> {
Done. Made use of existing categories$

2022-06-15 11:43 UTC, saitejasFyle commented on src/app/shared/components/fy-critical-policy-violation/fy-critical-policy-violation-message/fy-critical-policy-violation-message.component.scss
> +.critical-policy-violation-message {
Had combined both of these in a single componenent called `PolicyViolationRuleComponent` by controlling them by ngClass based on ngClass

2022-06-15 12:58 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  @Input() policyViolations: Object;
Done

2022-06-15 14:42 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.html
> +                    [(ngModel)]="comments[transaction]"
Done using formArray

2022-06-16 06:19 UTC, Julias0 commented on src/app/core/models/v1/formatted-policy-violation.model.ts
> +export interface FormattedPolicyViolation {
these models shouldnt be inside the v1 folder since these are internal modals. Please keep them at a parent level

2022-06-16 06:19 UTC, Julias0 commented on src/app/core/models/v1/formatted-policy-violation.model.ts
> +export interface FormattedPolicyViolation {
inside core/models

2022-06-16 06:21 UTC, Julias0 commented on src/app/core/services/categories.service.ts
> +    return categoryList.filter((orgCategory) => orgCategory.id === orgCategoryId)[0];
why not use `.find`?

2022-06-16 06:22 UTC, Julias0 commented on src/app/core/services/policy.service.ts
> +      if (violations.hasOwnProperty(key)) {
Whenever iterating over an objects keys use for..of loop with Object.keys

2022-06-16 06:22 UTC, Julias0 commented on src/app/core/services/policy.service.ts
> +      if (violations.hasOwnProperty(key)) {
And this specific case you can do with `.some` You dont need a for loop for this

2022-06-16 06:24 UTC, Julias0 commented on src/app/core/services/split-expense.service.ts
> +    return from(payloadData).pipe(concatMap((payload) => this.postComment(payload)));
Any subscribe attached to this will be called as many times as there are `transactionIDs` present. Please to add a reduce to the  end of the pipe

2022-06-16 06:24 UTC, Julias0 commented on src/app/core/services/split-expense.service.ts
> +  postCommentsFromUsers(transactionIDs: string[], comments): Observable<any> {
why is the return type `any`?

2022-06-16 06:25 UTC, Julias0 commented on src/app/core/services/split-expense.service.ts
> +      if (violations.hasOwnProperty(key)) {
same as above comment

2022-06-16 06:25 UTC, Julias0 commented on src/app/core/services/split-expense.service.ts
> +        const isCriticalPolicyViolation = criticalPolicyRules && criticalPolicyRules.length > 0;
criticalPolicyRules?.length > 0;

Make sure that you dont get repeated comments. I remember this being present in one of the earlier reviews.

2022-06-16 06:26 UTC, Julias0 commented on src/app/core/services/split-expense.service.ts
> +    //  Runs policy for each etxn and the response violation object is assigned to the etxn id
Please add a better name to the method instead of adding a supporting comment

2022-06-16 06:27 UTC, Julias0 commented on src/app/core/services/split-expense.service.ts
> +        obj[Object.keys(violation)[0]] = violation[Object.keys(violation)[0]];
I dont understand what is happening here - Also, can you add better names than `obj` ? You can rename it to `accumulator` or `acc`

2022-06-16 06:27 UTC, Julias0 commented on src/app/core/services/split-expense.service.ts
> +        obj[Object.keys(violation)[0]] = violation[Object.keys(violation)[0]];
If you want to combine the objects why not just use the spread operator?

2022-06-16 06:28 UTC, Julias0 commented on src/app/core/services/split-expense.service.ts
> +  runPolicyCheck(etxns, fileObjs) {
add data types to arguments and add return type

2022-06-16 06:29 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +        etxns.forEach((etxn) => {
Same comment as above. For..in loops should be avoided by convention

2022-06-16 06:29 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +      mergeMap((txnId) => this.transactionService.getEtxn(txnId)),
why use mergeMap?

2022-06-16 06:29 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +  checkForPolicyViolations(txnIds): Observable<{ [id: string]: PolicyViolation }> {
add datatype to `txnIds`

2022-06-16 06:30 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +  checkForPolicyViolations(txnIds): Observable<{ [id: string]: PolicyViolation }> {
Shouldnt this method be inside a service?

2022-06-16 06:31 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +              observables$.push(this.checkForPolicyViolations(res));
observables$ here is not an observable by an array of observables. Please to remove off the `$` from the anme

2022-06-16 06:32 UTC, Julias0 commented on src/app/fyle/split-expense/split-expense.page.ts
> +  handleSplitExpensePolicyViolations(violations) {
data type missing in the argument

2022-06-16 07:07 UTC, saitejasFyle commented on src/app/core/services/categories.service.ts
> +    return categoryList.filter((orgCategory) => orgCategory.id === orgCategoryId)[0];
Done

2022-06-16 07:09 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +        const isCriticalPolicyViolation = criticalPolicyRules && criticalPolicyRules.length > 0;
Done. Sure

2022-06-16 07:17 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +      if (violations.hasOwnProperty(key)) {
Done

2022-06-16 07:25 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +              observables$.push(this.checkForPolicyViolations(res));
Done

2022-06-16 07:42 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +            tap((violations) => {
Done

2022-06-16 07:58 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +      mergeMap((txnId) => this.transactionService.getEtxn(txnId)),
Changed it to concatMap

2022-06-16 07:58 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +  checkForPolicyViolations(txnIds): Observable<{ [id: string]: PolicyViolation }> {
Done

2022-06-16 08:34 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +  postCommentsFromUsers(transactionIDs: string[], comments): Observable<any> {
Have introduced an interface `TransactionStatus` and added it as the return type here

2022-06-16 11:09 UTC, saitejasFyle commented on src/app/core/services/policy.service.ts
> +      if (violations.hasOwnProperty(key)) {
Done using some()

2022-06-16 11:11 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +    //  Runs policy for each etxn and the response violation object is assigned to the etxn id
Done

2022-06-16 12:01 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +  checkForPolicyViolations(txnIds): Observable<{ [id: string]: PolicyViolation }> {
This is dependent on other two functions and those functions depends on the split expense page's class variables. That's why I thought why not in page.ts itself

2022-06-16 13:29 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +        obj[Object.keys(violation)[0]] = violation[Object.keys(violation)[0]];
Renamed and done using spread operator

2022-06-16 13:29 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +  runPolicyCheck(etxns, fileObjs) {
Done

2022-06-16 13:44 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +  checkForPolicyViolations(txnIds): Observable<{ [id: string]: PolicyViolation }> {
Done

2022-06-16 13:49 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +    return from(payloadData).pipe(concatMap((payload) => this.postComment(payload)));
Done

2022-06-20 04:42 UTC, saitejasFyle commented on src/app/core/services/policy.service.ts
> +  checkIfViolationsExist(violations) {
Resolved using generic record class

2022-06-20 04:45 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +        etxns.forEach((etxn) => {
Done by iterating Object.keys instead iterating the object directly by for..in loop

2022-06-20 04:46 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +        this.getCategories().subscribe();
Reused existing categories$

2022-06-20 04:47 UTC, saitejasFyle commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> +
Optimised this snippet

2022-06-20 04:47 UTC, saitejasFyle commented on src/app/shared/components/split-expense-policy-violation/split-expense-policy-violation.component.ts
> +  @Input() policyViolations: any;
Resolved using generic record class

2022-06-20 05:35 UTC, Julias0 commented on src/app/core/services/split-expense.service.ts
> +      map((response) => {
dont use generic names like `response`. Use a keyword to explain what this is, like policyViolationState or something

2022-06-20 05:35 UTC, Julias0 commented on src/app/core/services/split-expense.service.ts
> +          for (const key of Object.keys(data)) {
extract this out into a separate function

2022-06-20 05:36 UTC, Julias0 approved these changes

2022-06-20 05:58 UTC, saitejasFyle commented on src/app/core/services/split-expense.service.ts
> +      map((response) => {
renamed it as policyViolationResponse

2022-06-20 06:23 UTC, Dimple16 approved these changes
fix lint issues

2022-06-20 06:23 UTC, Dimple16 commented on src/app/core/services/categories.service.ts
> +  filterEnabled(categories: OrgCategory[]): OrgCategory[] {
do we need this? I guess we discussed about removing it

2022-06-20 06:23 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +      this.categoryList = categories.map((cat) => cat.value);
cat -> `category`

2022-06-20 06:23 UTC, Dimple16 commented on src/app/shared/components/fy-policy-violation/policy-violation-action/policy-violation-action.component.scss
> +      border-radius: 4px 4px 4px 4px;
`border-radius: 4px;`

2022-06-20 06:24 UTC, saitejasFyle commented on src/app/core/services/categories.service.ts
> +  filterEnabled(categories: OrgCategory[]): OrgCategory[] {
Removed this

2022-06-20 06:25 UTC, saitejasFyle commented on src/app/fyle/split-expense/split-expense.page.ts
> +      this.categoryList = categories.map((cat) => cat.value);
Done

2022-06-20 06:53 UTC, merged