Live updates poc with app version changes
fylein/fyle-mobile-app pull request #1173
Opened 2022-06-14 07:32 UTC by yksolanki9

2022-06-14 11:58 UTC, yksolanki9 commented on package.json
> +    "jasmine-core": "^4.1.1",
There are some dependency conflicts, so updated the `jasmine-core` to solve it

2022-06-15 06:32 UTC, Dimple16 requested changes

2022-06-15 06:32 UTC, Dimple16 commented on android/app/src/main/res/xml/config.xml
> -  <!-- It doesn't matter what value is added to origin - https://capacitorjs.com/docs/v2/cordova/using-cordova-plugins#:~:text=Capacitor%20does%20not%20support%20Cordova,things%20like%20hooks%20are%2
why are we removing this?

2022-06-15 06:32 UTC, Dimple16 commented on hooks/prebuild.js
> +  var androidStringsPath = path.resolve(process.cwd(),'android/app/src/main/res/values/strings.xml');
androidStringsPath -> `androidPath` ?

2022-06-15 06:32 UTC, Dimple16 commented on hooks/prebuild.js
> +  var androidStringsPath = path.resolve(process.cwd(),'android/app/src/main/res/values/strings.xml');
androidStringsPath -> `androidPath` ?

2022-06-15 06:32 UTC, Dimple16 commented on hooks/prebuild.js
> +  var androidStrings = fs.readFileSync(androidStringsPath).toString();
avoid using `type` inside var names

2022-06-15 06:32 UTC, Dimple16 commented on src/app/core/services/app-version.service.ts
> +    const liveUpdateVersion = environment.LIVEUPDATE_APP_VERSION;
LIVEUPDATE_APP_VERSION -> `LIVE_UPDATE_APP_VERSION`

2022-06-15 06:32 UTC, Dimple16 commented on src/app/core/services/app-version.service.ts
> +    const liveUpdateVersion = environment.LIVEUPDATE_APP_VERSION;
LIVEUPDATE_APP_VERSION -> `LIVE_UPDATE_APP_VERSION`

2022-06-15 06:32 UTC, Dimple16 commented on src/app/core/services/app-version.service.ts
> -  codePushUpdates(data) {
unused

2022-06-15 06:32 UTC, Dimple16 commented on src/app/core/services/app-version.service.ts
> -  codePushUpdates(data) {
unused

2022-06-15 08:29 UTC, yksolanki9 commented on android/app/src/main/res/xml/config.xml
> -  <!-- It doesn't matter what value is added to origin - https://capacitorjs.com/docs/v2/cordova/using-cordova-plugins#:~:text=Capacitor%20does%20not%20support%20Cordova,things%20like%20hooks%20are%2
This is removed by capacitor when building the app. Have added it to `capacitor.config.ts` from where we change this

2022-06-15 08:31 UTC, yksolanki9 commented on hooks/prebuild.js
> +  var androidStrings = fs.readFileSync(androidStringsPath).toString();
strings.xml is a file in native android used to store key value pairs that can be accessed across the app. So added Strings in var name to make it explicit

2022-06-15 08:32 UTC, yksolanki9 commented on src/app/core/services/app-version.service.ts
> -  codePushUpdates(data) {
Didnt understand. I have removed the unused method here

2022-06-16 04:57 UTC, Julias0 commented on android/app/src/main/assets/capacitor.config.json
> +	"loggingBehavior": "debug",
Should we have this in production? I dont want this coming up in the next vapt report

2022-06-16 04:57 UTC, Julias0 commented on android/app/src/main/assets/capacitor.config.json
> +		"accessOrigins": [
what does this mean?

2022-06-16 05:02 UTC, Julias0 commented on hooks/secrets.js
> +      googleCredentialsAndroid: `
can you separate each of these into separate files? This file has become too large.

2022-06-16 05:04 UTC, Julias0 requested changes
minor comments

2022-06-16 05:40 UTC, yksolanki9 commented on android/app/src/main/assets/capacitor.config.json
> +		"accessOrigins": [
This was done for vapt, any value we provide to access origin in config.xml is overwritten to * 
Capacitor 3 gives us option to change values in config.xml from capacitor config

2022-06-16 05:42 UTC, yksolanki9 commented on android/app/src/main/assets/capacitor.config.json
> +	"loggingBehavior": "debug",
This will show logs only in debug mode and not in release apk. We had changed this for vapt
It wont come in the report as we share release builds for vapt

2022-06-21 08:35 UTC, merged