Fyle 2a2a8uv: Changed Naming conventions for routes in Add mileage
fylein/fyle-mobile-app pull request #1185
Opened 2022-06-20 12:26 UTC by Aditya-shrivastav

2022-06-20 15:39 UTC, OmkarJ13 commented on src/app/shared/components/route-selector/route-selector.component.ts
> +    return 'End (' + String.fromCharCode(this.mileageLocations.length + 64) + ')';
Same as above

2022-06-20 15:39 UTC, OmkarJ13 commented on src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts
> +  }
Also, put the stuff inside brackets into a variable. More readable that way

2022-06-23 05:02 UTC, abhishek1234321 approved these changes

2022-06-23 05:02 UTC, abhishek1234321 commented on src/theme/timeline.scss
> +        font-size: 24px !important;
is this absolutely needed?

2022-06-23 07:55 UTC, Aditya-shrivastav commented on src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.html
> +                [label]="getLocationAutocompleteLabel(i)"
It will evaluate only on adding/deleting a location. Otherwise, It will only be called for the `Start` and `End`

2022-06-23 11:14 UTC, abhishek1234321 approved these changes

2022-06-23 11:14 UTC, abhishek1234321 commented on src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts
> +  // It takes the index of the fy-location component in the mileageLocations array and assign the fy-location component a label.
use multi line comments

2022-06-24 03:46 UTC, Julias0 commented on src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts
> +      character = String.fromCharCode(this.mileageLocations.length + 64);
Set 64 to a variable and name that variable. Otherwise this is a magic number. 
And move this method into a service and reference it here.

2022-06-24 03:46 UTC, Julias0 commented on src/app/shared/components/route-selector/route-selector-modal/route-selector-modal.component.ts
> +  getLocationAutoCompleteLabel(index) {
add param data type and return type

2022-06-24 03:46 UTC, Julias0 commented on src/theme/timeline.scss
> +        font-size: 24px !important;
Please dont use important everywhere

2022-06-24 03:46 UTC, Julias0 requested changes
Added comments

2022-06-24 08:51 UTC, Julias0 commented on src/app/core/services/location.service.ts
> +
remove the extra line

2022-06-24 08:51 UTC, Julias0 commented on src/app/core/services/location.service.ts
> +      label = 'Stop ' + character;
Dont you need to add brackets around character here?

2022-06-24 08:53 UTC, Julias0 commented on src/app/shared/components/route-selector/route-selector.component.ts
> +    const character = String.fromCharCode(this.mileageLocations.length + 64);
again - same magic number comment

2022-06-24 08:53 UTC, Julias0 requested changes
Added more comments

2022-06-24 12:56 UTC, Aditya-shrivastav commented on src/app/core/services/location.service.ts
> +      label = 'Stop ' + character;
No

2022-06-24 13:56 UTC, Julias0 approved these changes

2022-07-07 10:57 UTC, merged