Add / edit mileage page
fylein/fyle-mobile-app pull request #1187
Opened 2022-06-21 04:41 UTC by mvaishnavi

2022-07-25 14:12 UTC, mvaishnavi commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      mileageRates: this.offlineService.getMileageRates(),
some clean up around not referencing `this.offlineService.getMileageRates()` everywhere but using the allowed mileage rate everywhere is done here - https://github.com/fylein/fyle-mobile-app/pull/1268/files

2022-07-26 05:21 UTC, Julias0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +          const unit = rate.unit && rate.unit.toLowerCase() === 'miles' ? 'mile' : 'km';
This block of code is repeated -lets extract it to a function and move it to a service

2022-07-26 05:21 UTC, Julias0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  formatMileageRateName(rateName) {
move to service

2022-07-26 05:21 UTC, Julias0 requested changes
minor comments

2022-07-26 10:46 UTC, Dimple16 approved these changes

2022-07-27 06:09 UTC, Julias0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +    const filteredMileageRate = mileageRates.filter((mileageRate) => mileageRate.vehicle_type === vehicle_type);
You can use the `.find` to do this

2022-07-27 06:09 UTC, Julias0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +    const filteredMileageRate = mileageRates.filter((mileageRate) => mileageRate.vehicle_type === vehicle_type);
same as above

2022-07-27 06:23 UTC, Julias0 approved these changes
Minor comment - fix and merge

2022-07-27 07:21 UTC, mvaishnavi commented
will merge to master along with - https://github.com/fylein/fyle-mobile-app/pull/1268

2022-07-27 07:21 UTC, closed without merging