Fyle 2d3jwxh v2: Mobile New Sign In Page Design Changes
fylein/fyle-mobile-app pull request #1201
Opened 2022-06-24 08:29 UTC by Aditya-shrivastav

2022-06-24 16:55 UTC, OmkarJ13 requested changes
1. Rename new-header component html file, we don't use .template.html in angular apps
2. Also, why new-header?

2022-06-24 16:55 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.html
> +            layout-align="center center"
Use ion for alignment instead?

2022-06-24 17:06 UTC, OmkarJ13 requested changes

2022-06-24 17:06 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
>    }
this might not be supported on older browsers. check caniuse.com 😅

2022-06-27 06:54 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.html
> +              <div class="action-wrapper" *ngIf="fg.controls.email.valid">
Had the same naming convention in web app, that's why using it here too.

2022-06-27 08:14 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.scss
> +$signin-divider: rgba(0, 0, 0, 0.1);
Need to have opacity, that's why using rgba

2022-06-27 08:22 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.scss
> +  text-transform: uppercase;
I am using Ion-footer but we can not use its feature, since there are some discrepancy between platforms (ios and android)

2022-06-27 08:25 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.scss
> +    min-height: 100vh;
Yes, Otherwise the content will take only the required space and the not whole mobile space;

2022-06-27 08:39 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.scss
> +  align-items: center;
We can use ion-row, ion-col with size , but it will break for smaller screens. Since the `sign in with google` is a large text.

2022-06-27 09:12 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.scss
> +
We can have it either way, but I moved it inside.

2022-06-27 13:31 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
> +$small-device-width: 610px;
Check if $white and small-width are available in some global file, if not we can define it there for others to use as well

2022-06-27 13:31 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
> +    // margin: 0;
Remove this

2022-06-27 13:31 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
> -    margin: 0;
Can this be done using `.m-0`

2022-06-27 13:31 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.html
> +        <div class="signin-divider ion-text-center" ng-if="!vm.hideGoogleLogin">
why vm? not needed here no?

2022-06-27 13:31 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
> +  font-size: 14px;
Same comment, isn't 14 default?

2022-06-27 13:31 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
> +  padding: 8px 0 0 0;
padding-top if you're not overriding the others

2022-06-27 13:31 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
> +  text-align: center;
Do this using text-center?

2022-06-27 13:35 UTC, OmkarJ13 reviewed
Added some comments

2022-06-27 16:32 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.scss
> +    min-height: 325px;
No, Since we want it to change to fit the content, as content changes with user interaction

2022-06-28 02:17 UTC, OmkarJ13 approved these changes
Minor comments

2022-06-28 02:17 UTC, OmkarJ13 commented on src/global.scss
> +  --ion-small-device-width: 610px;
Can you define this as a scss variable using $ outside root?

2022-06-28 02:17 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
> +    background-color: var(--ion-color-fyle-primary-contrast);
Use $pure-white from colors.scss

2022-06-28 02:17 UTC, OmkarJ13 commented on src/global.scss
> +  --ion-small-device-width: 610px;
also check if your variable is not conflicting with others

2022-06-28 11:48 UTC, abhishek1234321 requested changes

2022-06-28 11:48 UTC, abhishek1234321 commented on src/app/auth/sign-in/sign-in.page.scss
> +$asterisk-red: #ff3366;
is this not available in the app already? Please check for each color code that you have added and reuse?

2022-06-28 11:48 UTC, abhishek1234321 commented on src/app/auth/sign-in/sign-in.page.scss
> +    min-height: 100vh;
do we do this in the mobile app? Is this recommended?

2022-06-28 11:48 UTC, abhishek1234321 commented on src/app/auth/sign-in/sign-in.page.scss
> +    height: 47px;
use 46 or 48?

2022-06-28 18:00 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.scss
> +    min-height: 100vh;
We are using min-height property at multiple places in the application. Also, it is being used to cover the whole screen of the mobile, otherwise it will just take the height required for the container.

2022-06-29 06:33 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.scss
> +    letter-spacing: 1.6px;
We are using the same letter spacing in the web app, that's why I have added it here as well. Default letter-spacing is set to normal

2022-06-29 06:33 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.scss
> +    height: 47px;
done

2022-06-29 06:41 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.scss
> +$asterisk-red: #ff3366;
for small-width-variable, I came up with this value by testing for different screen sizes in browser. But, this will be changed in further PR's since there are more things being added to the component.

2022-06-29 08:31 UTC, OmkarJ13 reviewed
Please to resolve all pending comments and assign back

2022-06-30 04:59 UTC, OmkarJ13 requested changes
Some comments

2022-06-30 04:59 UTC, OmkarJ13 commented on src/app/auth/fyle-logo/fyle-logo.component.html
> +    <a>
Remove this as well?

2022-06-30 04:59 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.html
> +          <a [routerLink]="['/','auth','reset_password', {email:fg.controls.email.value}]">Forgot Password ?</a>
Can extract this out in a function for better readability

2022-06-30 04:59 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
> +$asterisk-red: #ff3366;
These colors are available globally, please use them.

2022-06-30 04:59 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
> +    letter-spacing: 1.6px;
Check if this makes any difference with/without this. If no difference visible can remove

2022-06-30 04:59 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
> +      position: unset;
Put code comment of what this does and why we're using it?

2022-07-06 05:22 UTC, Aditya-shrivastav commented on src/app/auth/fyle-logo/fyle-logo.component.html
> +    <a>
done

2022-07-06 05:22 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.html
> +          <a [routerLink]="['/','auth','reset_password', {email:fg.controls.email.value}]">Forgot Password ?</a>
done

2022-07-06 06:29 UTC, OmkarJ13 commented on src/app/auth/sign-in/sign-in.page.scss
> +$gradient-background: linear-gradient(277.33deg, #e1eeff 26.8%, #ffe4fb 97.18%);
This is there, please to reuse

2022-07-06 08:10 UTC, abhishek1234321 requested changes

2022-07-06 11:17 UTC, Aditya-shrivastav commented on src/app/auth/fyle-logo/fyle-logo.component.scss
> +a .brand-logo {
Already done

2022-07-06 11:20 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.scss
> +    min-height: 100vh;
No, we are using ionic pre built facility for centring the contents

2022-07-07 12:03 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.html
> +        <div class="signin-divider ion-text-center">
Shouldnt we be hiding this with google sign in button?

2022-07-07 12:05 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.scss
> +$container-shadow: #00000026;
Add all colors in `colors.scss` and give generic names. Also confirm if they are used somewhere else

2022-07-07 12:07 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.scss
> +    color: $error;
Use generic names for colors. Refer colors.scss

2022-07-07 12:08 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.scss
> +    margin: 10px 0 6px 0;
margin: 10px 0 6px

2022-07-07 12:09 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.scss
> +    margin-bottom: 10px;
`margin: 16px 0 10px`?

2022-07-07 20:11 UTC, Aditya-shrivastav commented on src/app/auth/sign-in/sign-in.page.html
> +        <div class="signin-divider ion-text-center">
No, not for now

2022-07-08 04:54 UTC, Aditya-shrivastav commented
> Please add snapshot of the password screen in pr description

We are doing this iteratively, Password page changes are not in this PR, they will be appear in the next PR. Since the PR is big

2022-07-08 05:54 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.html
> +        <div class="signin-divider ion-text-center">
Please mention that this is a partial pr in the description

2022-07-08 05:58 UTC, yksolanki9 approved these changes

2022-07-11 04:17 UTC, Julias0 commented on src/app/auth/sign-in/sign-in.module.ts
> +import { FyleLogoComponent } from '../../shared/components/fyle-logo/fyle-logo.component';
why do you need a component for this?

2022-07-11 04:18 UTC, Julias0 commented on src/app/auth/sign-in/sign-in.page.html
> +                required
Hey we shouldnt be adding validators through the template when using reactive forms

2022-07-11 04:20 UTC, Julias0 commented on src/app/auth/sign-in/sign-in.page.html
> +              <div class="valid-check-container" matSuffix *ngIf="fg.controls.email.valid">
valid-check-container - this class dosnt follow convention no?

2022-07-11 04:20 UTC, Julias0 commented on src/app/auth/sign-in/sign-in.page.html
> +              *ngIf="fg.controls.email.touched && !fg.controls.email.valid && !fg.controls.email.value"
Why do you need to check for value? Shouldnt you be checking this via the formcontrol validators?

2022-07-11 04:21 UTC, Julias0 commented on src/app/auth/sign-in/sign-in.page.html
> +              *ngIf="fg.controls.email.touched && !fg.controls.email.valid && fg.controls.email.value"
Same as above - the error message should be based on fg.controls.email.errors , not valid and explicit conditions if you have reactive forms

2022-07-11 04:23 UTC, Julias0 commented on src/app/auth/sign-in/sign-in.page.html
> +                    <a id="sign-in--change" (click)="changeEmail()"> Change </a>
We should have a prevent default on click events in anchor tags. Please to relay the event inside the attached callback method and use `.preventDefault` on it

2022-07-11 04:23 UTC, Julias0 commented on src/app/auth/sign-in/sign-in.page.html
> +                [type]="hide ? 'password': 'text'"
use a more detailed variable name than `hide`

2022-07-11 04:29 UTC, Julias0 commented on src/app/auth/sign-in/sign-in.page.scss
> +    min-height: 100vh;
Just to double check if it works on all resolutions

2022-07-11 04:31 UTC, Julias0 commented on src/app/auth/sign-in/sign-in.page.scss
> +      position: unset;
Why not use inherit? I am not comfortable using unset here since most folks are unfamiliar with this

2022-07-11 04:31 UTC, Julias0 commented on src/app/auth/sign-in/sign-in.page.ts
> +    this.hide = !this.hide;
use a better name than hide

2022-11-05 16:09 UTC, closed without merging