Removed number filter and slice hack
fylein/fyle-mobile-app pull request #1203
Opened 2022-06-27 03:45 UTC by OmkarJ13

2022-06-29 03:51 UTC, abhishek1234321 approved these changes

2022-06-29 04:55 UTC, Julias0 commented on src/app/fyle/add-edit-expense/match-transaction/match-transaction.component.html
> +          <span class="match-transaction--currency">{{ getCurrencySymbol(cccExpense.currency) }}</span
we shouldnt use method calls inside the template

2022-06-29 04:55 UTC, Julias0 requested changes
Comment added

2022-07-07 16:35 UTC, OmkarJ13 commented on src/app/fyle/add-edit-expense/match-transaction/match-transaction.component.html
> +          <span class="match-transaction--currency">{{ cccExpense.currency | currencySymbol }}</span
- Added this new pipe which will return a symbol for a currency.
- This was done to avoid setting currency symbols in component.ts to use inside of template files or calling methods which return symbols directly from template files.

2022-07-08 04:58 UTC, Julias0 commented on src/app/shared/components/fy-currency/fy-currency.component.html
> +      <strong>{{ value.amount | currency: value.currency:'code' }}</strong>
What is the `code` value getting passed here?
In the pipes transform function the only two valid options given are `wide` and `narrow`

2022-07-08 04:58 UTC, Julias0 requested changes
Added questions

2022-07-08 05:06 UTC, OmkarJ13 commented on src/app/shared/components/fy-currency/fy-currency.component.html
> +      <strong>{{ value.amount | currency: value.currency:'code' }}</strong>
- This is done because we want to have the currency code as the symbol itself
- This is valid because in currency pipe we accept these options - `symbol` (same as wide), `symbol-narrow`, `code` 
- The pipe `currencySymbol` that I implemented in this PR is different, it only returns the symbol for the currency. There only two options are there which you have mentioned.
- I had implemented a different pipe for transforming currency code to a symbol because of the issue where we had to get the currency symbol using a method and use it in the template.

2022-07-08 06:11 UTC, Julias0 approved these changes

2022-07-11 15:03 UTC, merged