Handled for single payment mode in add-edit-expense first draft
fylein/fyle-mobile-app pull request #1214
Opened 2022-06-30 08:34 UTC by saitejasFyle

2022-07-05 06:21 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    // const selectedPaymentMode$ = this.etxn$.pipe(
Why is this here? Please remove dead code - you can refer to this in git history if you require to look this up later on

2022-07-05 06:22 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            switchMap((paymentModes) => {
why is switchMap required here?

2022-07-05 06:25 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              } else if (paymentModes.length === 1) {
The `iif` condition states that this portion is executed only if `etxn.tx.source_account_id` is present.
This wont work for creation of a new expense no?

2022-07-05 06:25 UTC, Julias0 requested changes
Added comments

2022-07-06 15:35 UTC, saitejasFyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    // const selectedPaymentMode$ = this.etxn$.pipe(
Done

2022-07-06 15:36 UTC, saitejasFyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              } else if (paymentModes.length === 1) {
I've changed the code

2022-07-07 09:38 UTC, Dimple16 requested changes

2022-07-07 09:38 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                *ngIf="(!(isUnifyCcceExpensesSettingsEnabled && isCccExpense) && availablePaymentModes?.length > 1)"
since we've been using the same condition multiple times, you can add this in a variable as `showPaymentMode` and use it in the HTML directly

2022-07-07 09:38 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                  [ngClass]="{'add-edit-expense--orig-amount-error': fg.controls.currencyObj.value.orig_currency}"
why are we changing this?

2022-07-07 09:38 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                [size]="((availablePaymentModes?.length > 1) && !(isUnifyCcceExpensesSettingsEnabled && isCccExpense)) ? 6 : 0"
size 0?

2022-07-07 09:38 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              if (!paymentModes.some((paymentMode) => paymentMode.acc.id === etxn.tx.source_account_id)) {
sine we are finding the payment based on the condition here, can we not use `.find()` here?

2022-07-07 09:38 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          constructedPaymentModes.pipe(
add comments on what the criteria is in this section

2022-07-07 09:38 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                const accountLinkedWithExpense = accounts.find(
what happens if we don't find it? do we directly push the account linked with the expense?

2022-07-07 09:38 UTC, Dimple16 commented on src/app/post-verification/invited-user/invited-user.page.ts
> +      this.fg.controls.fullName.setValue(eou.us.full_name);
is this a related change?

2022-07-07 09:45 UTC, saitejasFyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                [size]="((availablePaymentModes?.length > 1) && !(isUnifyCcceExpensesSettingsEnabled && isCccExpense)) ? 6 : 0"
Added this explicitly jusyt for fool proof. I've given the size of the date field to 12 base on this condition.

2022-07-07 09:47 UTC, saitejasFyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              if (!paymentModes.some((paymentMode) => paymentMode.acc.id === etxn.tx.source_account_id)) {
some() will automatically break as soon it finds the occurence right?

2022-07-07 10:38 UTC, saitejasFyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                [size]="((availablePaymentModes?.length > 1) && !(isUnifyCcceExpensesSettingsEnabled && isCccExpense)) ? 6 : 0"
Done. Have kept the size as just 6 explicitly

2022-07-07 10:38 UTC, saitejasFyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                const accountLinkedWithExpense = accounts.find(
Yup, exactly

2022-07-07 10:42 UTC, saitejasFyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          constructedPaymentModes.pipe(
Done

2022-07-08 05:01 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> -    orgSettings$.subscribe((orgSettings) => {
why are you moving this block of code?

2022-07-08 05:04 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      this.availablePaymentModes = paymentModes;
why resolve this into a variable? Cant we just use the async pipe in the template and use the resolved value?

2022-07-08 05:04 UTC, Julias0 requested changes
Added a few questions

2022-07-08 06:23 UTC, Dimple16 approved these changes

2022-07-08 06:24 UTC, saitejasFyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> -    orgSettings$.subscribe((orgSettings) => {
I was just keeping the required subscriptions in one place one below the other under ionViewWillEnter() to do some testing stuffs. I didn't change anything

2022-07-08 07:20 UTC, Julias0 approved these changes

2022-07-08 10:06 UTC, Julias0 approved these changes

2022-07-08 10:51 UTC, merged