Add logic for ordering payment modes
fylein/fyle-mobile-app pull request #1263
Opened 2022-07-21 13:24 UTC by yksolanki9

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1p1L2u3SmNEZEjHDWIDsxxhQLHelD5PPbf1btYiYe1Q2u3A4l%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=lQFW1oH)

2022-07-25 14:57 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +  getAllowedAccounts(
Split a large method in add-edit-expense component and moved the logic for getting accounts into this service

2022-07-26 06:18 UTC, shishirams222 commented on src/app/fyle/view-expense/view-expense.page.html
> +      <ng-container *ngIf="!(hidePaymentMode$|async)">
Only this is the new addition right? Rest of the block is same

2022-07-26 06:26 UTC, shishirams222 approved these changes

2022-07-26 06:30 UTC, yksolanki9 commented on src/app/fyle/view-expense/view-expense.page.html
> +      <ng-container *ngIf="!(hidePaymentMode$|async)">
Yes

2022-07-26 11:05 UTC, Dimple16 requested changes

2022-07-26 11:05 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.ts
> +          return paymentModes[0] === etxn.source_account_type;
can you add a comment on why we are reassigning this here?

2022-07-26 11:07 UTC, yksolanki9 commented on src/app/fyle/view-expense/view-expense.page.ts
> +          return paymentModes[0] === etxn.source_account_type;
We're not reassigning, we're return a boolean here. Will add a comment in the code

2022-07-27 07:44 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +            return allowedPaymentModes.indexOf('COMPANY_ACCOUNT') >= 0;
Use .some

2022-07-27 07:44 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +          if (paymentMode.acc.type === 'PERSONAL_ACCOUNT' && !paymentMode.acc.isReimbursable) {
Extract this block into separate function - that way we wont need the comment above

2022-07-27 07:45 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +        let resPaymentModes = filteredPaymentModes.sort(
can be extracted to separate function - the function name can be the comment, `sortBasedOnAllowedPaymentModes`

2022-07-27 07:45 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +        if (
extract to separate function

2022-07-27 07:49 UTC, Julias0 commented on src/app/fyle/view-expense/view-expense.page.ts
> +  hidePaymentMode$: Observable<boolean>;
instead of Observable<boolean> make this a Observable<{ flag: boolean }>;

This way you can avoid `*ngIf="!(hidePaymentMode$|async)` which is an antipattern.
instead you can do `
<ng-container *ngIf="hidePaymentMode$|async as hidePaymentMode">
  <ng-container *ngIf="!hidePaymentMode.flag">
   ...
  <ng-container>
</ng-container>
`

2022-07-27 07:49 UTC, Julias0 commented on src/app/fyle/view-expense/view-expense.page.ts
> +  hidePaymentMode$: Observable<boolean>;
Ref: https://stackoverflow.com/questions/66789429/eslint-async-pipes-should-not-be-negated#:~:text=Why%3F,which%20should%20not%20be%20shown.

2022-07-27 07:51 UTC, Julias0 commented on src/app/fyle/view-expense/view-expense.page.ts
> +      this.hidePaymentMode$ = iif(() => this.view === ExpenseView.team, of(false), this.hidePaymentMode(etxn));
Do with a normal if statement instead of using iif. This is because both functions in iif will get executed but that wont happen in normal if conditions

2022-07-27 07:52 UTC, Julias0 commented on src/app/fyle/view-expense/view-expense.page.ts
> +  hidePaymentMode(etxn: Expense) {
hidePaymentMode -> shouldPaymentModeBeHidden

Since this dosnt cause a mutation, the method name shouldn't be like a verb

2022-07-27 07:52 UTC, Julias0 requested changes
Added comments

2022-07-27 12:32 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +    etxn: any,
Done

2022-07-27 12:35 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +    etxn: any,
Will fix it separately

2022-07-27 12:44 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +            return allowedPaymentModes.indexOf('COMPANY_ACCOUNT') >= 0;
Done

2022-07-27 12:56 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +        if (
Done

2022-07-27 13:01 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +        let resPaymentModes = filteredPaymentModes.sort(
Done

2022-07-27 14:05 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +          if (paymentMode.acc.type === 'PERSONAL_ACCOUNT' && !paymentMode.acc.isReimbursable) {
Done

2022-07-28 14:54 UTC, yksolanki9 commented on src/app/fyle/view-expense/view-expense.page.ts
> +      this.hidePaymentMode$ = iif(() => this.view === ExpenseView.team, of(false), this.hidePaymentMode(etxn));
Done

2022-07-28 14:56 UTC, yksolanki9 commented on src/app/fyle/view-expense/view-expense.page.ts
> +  hidePaymentMode(etxn: Expense) {
Done

2022-07-29 11:34 UTC, yksolanki9 commented on src/app/fyle/view-expense/view-expense.page.ts
> +  hidePaymentMode$: Observable<boolean>;
Changed it to a variable

2022-07-29 13:23 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +  addMissingAccount(etxn: any, allPaymentModes: ExtendedAccount[], paymentModes: ExtendedAccount[]) {
paymentModes -> does this contain the missing payment mode? If yes rename to `paymentModeAssociatedWithExpense`. And why is this an array in that particular case

2022-07-29 13:25 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +  addMissingAccount(etxn: any, allPaymentModes: ExtendedAccount[], paymentModes: ExtendedAccount[]) {
paymentModes -> rename this to something more specific. Like paymentModesAvailableInForm or something. Otherwise I am unable to differentiate how this is different from `allPaymentModes` since its synonymous with `paymentModes` and I have to look at the implementation to understand

2022-07-29 13:27 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +        paymentMode.acc.isReimbursable !== etxn.tx.skip_reimbursement
in case of personal account, wouldnt this always be `paymentMode.acc.isReimbursable === true`

Why is this negation of skip reimbursement? are there other cases?

2022-07-29 13:30 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +  isSameAccount(etxn: any, paymentMode: ExtendedAccount) {
isSameAccount -> checkIfPaymentModeIsAssociatedWithAccount or something. 
The naming of the function makes it difficult to understand what is being checked for here

2022-07-29 13:31 UTC, Julias0 requested changes
minor comments

2022-08-02 10:48 UTC, Dimple16 requested changes

2022-08-02 10:48 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +    etxn: any,
we do have the unflattened expense model named as `Transaction` model, check if that works, or, can create a new one

2022-08-02 10:48 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +        const resPaymentModes = this.addMissingAccount(etxn, constructedPaymentModes, sortedPaymentModes);
rename `resPaymentModes`

2022-08-02 10:48 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +        paymentMode.acc.isReimbursable !== etxn.tx.skip_reimbursement
`paymentMode.acc.isReimbursable !== etxn.tx.skip_reimbursement`
will not work for the company account no? can you verify this?

2022-08-02 10:48 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +  isSameAccount(etxn: any, paymentMode: ExtendedAccount) {
add return type

2022-08-02 10:48 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +  addMissingAccount(etxn: any, allPaymentModes: ExtendedAccount[], paymentModes: ExtendedAccount[]) {
add method return type

2022-08-02 10:48 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +  isCompanyAccount(paymentMode: ExtendedAccount) {
add method return type, same for below

2022-08-02 10:48 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +  isSameAccount(etxn: any, paymentMode: ExtendedAccount) {
`etxn: any` -> Use `Transaction` model

2022-08-02 10:48 UTC, Dimple16 commented on src/app/core/services/accounts.service.ts
> +    if (etxn.source_account_type === 'PERSONAL_ACCOUNT') {
check if this works?
```
if (etxn.source_account_type === 'PERSONAL_ACCOUNT' && etxn.tx_skip_reimbursement) {
    return 'COMPANY_ACCOUNT';
 }
return etxn.source_account_type;
```

2022-08-02 10:48 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          paymentModes.length <= 1 || (this.isUnifyCcceExpensesSettingsEnabled && this.isCccExpense))
should we check for the edge case where there are no payment modes? 
in the above condition, it might break for that case, please verify

2022-08-02 10:48 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.html
> +      <ng-container *ngIf="hidePaymentMode === false">
`hidePaymentMode === false`
why are we checking it this way and not `!hidePaymentMode`?

2022-08-02 10:48 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.ts
> +        if (paymentModes.length === 1) {
should we check for `paymentModes.length <= 1`?

2022-08-02 14:18 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +    etxn: any,
@Dimple16 it is model for transaction, not extended transaction

2022-08-02 15:23 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          paymentModes.length <= 1 || (this.isUnifyCcceExpensesSettingsEnabled && this.isCccExpense))
The `allowed_payment_modes` property will always have at least one element - that check is added in backend
Also, I've added optional chaining just in case

2022-08-02 15:23 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +  isSameAccount(etxn: any, paymentMode: ExtendedAccount) {
Renamed to `checkIfEtxnHasSamePaymentMode()`

2022-08-02 15:23 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +  addMissingAccount(etxn: any, allPaymentModes: ExtendedAccount[], paymentModes: ExtendedAccount[]) {
Renamed to `allowedPaymentModes`

2022-08-03 05:03 UTC, Julias0 commented on src/app/fyle/view-expense/view-expense.page.ts
> +          map((shouldPaymentModeBeHidden) => (this.hidePaymentMode = shouldPaymentModeBeHidden))
assignment to variables should happen inside subscribe

2022-08-03 05:04 UTC, Julias0 approved these changes
minor comments - fix and send to Gokul for review

2022-08-03 05:52 UTC, Dimple16 approved these changes

2022-08-08 13:52 UTC, gokulk16 requested changes

2022-08-08 13:52 UTC, gokulk16 commented on src/app/fyle/view-expense/view-expense.page.ts
> +      this.hidePaymentMode = false;
rename to showPaymentMode

2022-08-08 13:52 UTC, gokulk16 commented on src/app/fyle/view-expense/view-expense.page.ts
> +          switchMap((etxn) => this.shouldPaymentModeBeHidden(etxn)),
reneme `shouldPaymentModeBeHidden` to `shouldPaymentModeBeShown`

2022-08-08 13:52 UTC, gokulk16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  hidePaymentMode = false;
rename to showPaymentMode = true;

2022-08-08 13:52 UTC, gokulk16 commented on src/app/core/services/accounts.service.ts
> +            return allowedPaymentModes.some((allowedpaymentMode) => allowedpaymentMode === 'COMPANY_ACCOUNT');
typo. rename `allowedpaymentMode ` to `allowedPaymentMode`

2022-08-08 13:52 UTC, gokulk16 commented on src/app/core/services/accounts.service.ts
> +      constructedPaymentModes: this.constructPaymentModes(userAccounts, isMultipleAdvanceEnabled),
can try to not use this. 
That way your launchDarkly can be 2 separate logics and cabn be easily debugged

2022-08-08 13:52 UTC, gokulk16 commented on src/app/core/services/accounts.service.ts
> +      const accountLinkedWithExpense = allPaymentModes.find((paymentMode) =>
rename `accountLinkedWithExpense ` to `paymentModeOfExpense`

2022-08-08 13:52 UTC, gokulk16 commented on src/app/core/services/accounts.service.ts
> +      constructedPaymentModes: this.constructPaymentModes(userAccounts, isMultipleAdvanceEnabled),
don't use existing `constructPaymentModes` which is the older logic for finding the payment modes to be allowed.
Using the same will have repeated tech debts from it

2022-08-09 16:46 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  hidePaymentMode = false;
Done

2022-08-09 16:49 UTC, yksolanki9 commented on src/app/fyle/view-expense/view-expense.page.ts
> +          switchMap((etxn) => this.shouldPaymentModeBeHidden(etxn)),
Done

2022-08-09 16:50 UTC, yksolanki9 commented on src/app/fyle/view-expense/view-expense.page.ts
> +      this.hidePaymentMode = false;
Done

2022-08-10 06:39 UTC, gokulk16 approved these changes

2022-08-30 08:36 UTC, merged