pill color changes in mobile-app
fylein/fyle-mobile-app pull request #1265
Opened 2022-07-25 05:08 UTC by SowmyaFyle

2022-07-25 11:46 UTC, yksolanki9 requested changes
- Seems you have missed `app-expense-card` component. Please make the changes there as well
- Also in advances all the letters in state pill are capitalized whereas they are in titlecase elsewhere, please confirm how it should be with design and make them consistent

2022-07-25 11:46 UTC, yksolanki9 commented on src/global.scss
> +  text-transform: uppercase;
From the ss, it is not working for report and expense states probably bc of angular pipe. Please fix this

2022-07-25 12:16 UTC, SowmyaFyle commented on src/theme/colors.scss
> +  //state pill in integration exports
not require. removed

2022-07-25 12:16 UTC, SowmyaFyle commented on src/global.scss
> +  text-transform: uppercase;
changed

2022-07-25 12:29 UTC, SowmyaFyle commented
> * Seems you have missed `app-expense-card` component. Please make the changes there as well
> * Also in advances all the letters in state pill are capitalized whereas they are in titlecase elsewhere, please confirm how it should be with design and make them consistent

done

2022-07-25 15:04 UTC, yksolanki9 approved these changes

2022-07-26 05:22 UTC, Julias0 approved these changes

2022-07-27 05:55 UTC, merged