Removing expense forms support in offline mode via launch darkly
fylein/fyle-mobile-app pull request #1267
Opened 2022-07-25 13:42 UTC by Dimple16

2022-07-26 06:14 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +    if (this.isRemoveOfflineFormsSupportEnabled) {
this should be inside the subscribe

2022-07-27 07:35 UTC, Julias0 commented on src/app/auth/switch-org/switch-org.page.ts
> +        offlineData$ = of([]);
current Org from offline data is used inside the subscribe section. That portion will break - its related to lite orgs so let's just remove that off.

Also remove the destructing from the offline data portion

2022-07-27 13:56 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +  initializeLDUser(eou, deviceInfo) {
Initializing launch darkly user in switch org page

2022-07-27 13:58 UTC, Dimple16 commented on src/app/fyle/dashboard/dashboard.page.html
> +    <ion-buttons slot="end" *ngIf="(isConnected$ | async) || !isRemoveOfflineFormsSupportEnabled">
The expense forms actions sheet will not be shown only in this case -> `Offline && remove_forms_support is disabled`

2022-07-27 13:59 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +    /**
Changes from @OmkarJ13's branch in this file

2022-07-27 13:59 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +  // Checks if the passed in user is the same as the user which is initialized to LaunchDarkly (if any)
Changes from @OmkarJ13's branch in this method

2022-07-27 14:00 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +  getLDClient() {
added this to wait for LD user initialisation and then use the remove_forms_support key in switch org page

2022-07-27 14:01 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +    forkJoin([eou$, deviceInfo$])
1st fork-join -> To initialise LD user

2022-07-27 14:01 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +            console.log('check val after .then()', res);
ignore, will remove

2022-07-27 14:02 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +            if (this.isRemoveOfflineFormsSupportEnabled) {
If remove form support is enabled, `offlineData` will be an empty list observable

2022-07-27 14:03 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +                  forkJoin([offlineData$, pendingDetails$, eou$, roles$, isOnline$, deviceInfo$])
only if `offlineData` is present, adding it to the fork join

2022-07-27 14:03 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> -        const pendingDetails = !(currentOrg.lite === true || currentOrg.lite === false) || isPendingDetails;
removed `currentOrg.lite` as discussed previously since we aren't using it anymore

2022-07-28 10:22 UTC, Julias0 commented on src/app/auth/switch-org/switch-org.page.ts
> +            if (offlineData$) {
```typescript

forkJoin([offlineData$, pendingDetails$, eou$, roles$, isOnline$, deviceInfo$]).pipe(
finalize(() => from(this.loaderService.hideLoader()))
).subscribe(([ 
loadedOfflineData,
isPendingDetails,
eou,
roles,
isOnline,
deviceInfo,
 ]) => {
    this.setSentryUser(eou);
    this.navigateBasedOnUserStatus(isPendingDetails, roles, eou);
 });


```

2022-07-28 10:23 UTC, Julias0 approved these changes

2022-08-10 12:11 UTC, Julias0 commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +      this.isRemoveOfflineFormsSupportEnabled = res;
`isRemoveOfflineFormsSupportEnabled` -> `isOfflineFormsRemoved`

2022-08-10 12:11 UTC, Julias0 commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +    from(this.storageService.get('removeOfflineForms')).subscribe((res) => {
removeOfflineForms -> `isOfflineFormsRemoved `

2022-08-10 12:13 UTC, Julias0 commented on src/app/app.component.ts
> +  async getRemoveOfflineFormsLDKey() {
this block of code is duplicated in switch org and app component ts. Can we move this to a service

2022-08-10 12:14 UTC, Julias0 commented on src/app/auth/switch-org/switch-org.page.ts
> +  isRemoveOfflineFormsSupportEnabled = false;
isRemoveOfflineFormsSupportEnabled -> `isOfflineFormsRemoved`

2022-08-10 12:14 UTC, Julias0 commented on src/app/auth/switch-org/switch-org.page.ts
> +  initializeLDUser(eou, deviceInfo, currentOrg) {
same comments as app.component.ts

2022-08-10 12:14 UTC, Julias0 commented on src/app/auth/switch-org/switch-org.page.ts
> +  async getRemoveOfflineFormsLDKey() {
same comments as app.component.ts

2022-08-10 12:17 UTC, Julias0 commented on src/app/core/services/offline.service.ts
> +  loadInOfflineMode() {
loadInOfflineMode -> loadNew or loadOptimized.
loadInOfflineMode isnt really correct as a name

2022-08-10 12:18 UTC, Julias0 requested changes
mostly minor comments

2022-08-11 06:21 UTC, Dimple16 commented on src/app/app.component.ts
> +  async getRemoveOfflineFormsLDKey() {
I had added to the launch darkly common service previously, but, this cannot be moved there as it creates a circular dependency,

2022-08-11 10:30 UTC, Julias0 approved these changes

2022-08-16 06:18 UTC, merged