Upgrade Android API level to 31
fylein/fyle-mobile-app pull request #1276
Opened 2022-07-27 14:13 UTC by Dimple16

2022-07-29 09:12 UTC, yksolanki9 commented on android/app/src/main/AndroidManifest.xml
> +            android:exported="true"
Why do we need this?

2022-07-29 09:20 UTC, yksolanki9 approved these changes

2022-07-29 12:09 UTC, Julias0 commented on android/app/src/main/AndroidManifest.xml
> +            android:exported="true"
+1

2022-08-02 04:33 UTC, Julias0 requested changes
1 question

2022-08-02 07:10 UTC, Dimple16 commented on android/app/src/main/AndroidManifest.xml
> +            android:exported="true"
@Julias0 
We need to explicitly set this for app targeting android 12 and above. adding references:
https://developer.android.com/guide/topics/manifest/activity-element#exported
https://developer.android.com/about/versions/12/behavior-changes-12
https://stackoverflow.com/questions/68554294/androidexported-needs-to-be-explicitly-specified-for-activity-apps-targeting

2022-08-03 05:16 UTC, Julias0 approved these changes

2022-08-03 05:49 UTC, merged