Fyle 2khjeya-fix for overlapping pills
fylein/fyle-mobile-app pull request #1277
Opened 2022-07-29 03:35 UTC by SowmyaFyle

![image](https://user-images.githubusercontent.com/102025104/181677553-0ba1b2b8-955f-4d69-bb16-ec8f5dd79d1a.png)

![image](https://user-images.githubusercontent.com/102025104/181677536-21db97d4-7afa-414d-89b8-e57e885da52c.png)

![image](https://user-images.githubusercontent.com/102025104/181677508-23617e8f-c4a3-499f-9a57-89200f8f6736.png)

2022-07-29 04:58 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.scss
> +    position: absolute;
Can we not use absolute positioning here?

2022-08-02 04:33 UTC, Julias0 commented on src/app/shared/components/expenses-card/expenses-card.component.scss
> +    position: absolute;
+1

2022-08-02 04:33 UTC, Julias0 requested changes
Comments added

2022-08-02 08:49 UTC, SowmyaFyle commented on src/app/shared/components/expenses-card/expenses-card.component.scss
> +    position: absolute;
removed

2022-08-03 05:00 UTC, Julias0 approved these changes

2022-08-03 05:54 UTC, merged