Changes for add/edit/view mileage and per diem
fylein/fyle-mobile-app pull request #1283
Opened 2022-08-03 15:37 UTC by yksolanki9

2022-08-08 05:12 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +    expenseType: string
You can convert this to expenseType: 'MILEAGE' | 'PER_DIEM' | 'Something else'

If the expense types are well defined

2022-08-08 05:14 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +        const isMileageOrPerDiemExpense = ['MILEAGE', 'PER_DIEM'].includes(expenseType);
You can also do `expenseType: 'EXPENSE' | 'MILEAGE' | 'PER_DIEM'` in the arguments of this method, if this enum isn't used in many places

2022-08-08 05:15 UTC, Julias0 commented on src/app/fyle/view-per-diem/view-per-diem.page.ts
> +          map((shouldPaymentModeBeHidden) => (this.hidePaymentMode = shouldPaymentModeBeHidden))
Assignments should happen inside subscribe

2022-08-08 05:15 UTC, Julias0 commented on src/app/fyle/view-mileage/view-mileage.page.ts
> +          map((shouldPaymentModeBeHidden) => (this.hidePaymentMode = shouldPaymentModeBeHidden))
Same comment as below

2022-08-08 05:16 UTC, Julias0 requested changes
minor changes requested

2022-08-08 06:39 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +        const isMileageOrPerDiemExpense = ['MILEAGE', 'PER_DIEM'].includes(expenseType);
Okay, will fix this in the other pr

2022-08-08 06:42 UTC, yksolanki9 commented on src/app/fyle/view-per-diem/view-per-diem.page.ts
> +          map((shouldPaymentModeBeHidden) => (this.hidePaymentMode = shouldPaymentModeBeHidden))
Done

2022-08-08 06:42 UTC, yksolanki9 commented on src/app/fyle/view-mileage/view-mileage.page.ts
> +          map((shouldPaymentModeBeHidden) => (this.hidePaymentMode = shouldPaymentModeBeHidden))
Done

2022-08-10 10:17 UTC, Julias0 approved these changes

2022-08-12 12:21 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +    const isAdvanceEnabled = orgSettings?.advances?.enabled || orgSettings?.advance_requests?.enabled;
Not removing check for advances now, will need this for LD pr

2022-08-22 16:21 UTC, gokulk16 approved these changes

2022-08-30 08:26 UTC, merged