Show currency code everytime for expense card amount in my expenses page
fylein/fyle-mobile-app pull request #1286
Opened 2022-08-05 11:19 UTC by OmkarJ13

2022-08-05 13:14 UTC, OmkarJ13 commented on src/app/shared/components/expenses-card/expenses-card.component.ts
> -import { getCurrencySymbol } from '@angular/common';
Removed all of this, we can directly use the `currencySymbol` pipe to get symbol

2022-08-08 05:26 UTC, Julias0 commented on src/app/shared/components/expenses-card/expenses-card.component.html
> +                expense.tx_amount | humanizeCurrency: expense.tx_currency || homeCurrency:true
This is difficult to read - use a variable or *ngIfs to control this and make it simpler to read

2022-08-08 05:26 UTC, Julias0 requested changes
comments based on readability

2022-08-10 05:39 UTC, Dimple16 approved these changes

2022-08-10 05:49 UTC, Julias0 approved these changes

2022-08-10 06:25 UTC, merged