Get allowedPaymentModes from offline service
fylein/fyle-mobile-app pull request #1288
Opened 2022-08-08 12:33 UTC by yksolanki9

2022-08-08 12:35 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> -    const accounts$ = this.isConnected$.pipe(
Removing this off as it is handled in offline service

2022-08-08 12:49 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> -        }
Removing this off as it is handled in offline service

2022-08-08 12:49 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> -  }
Moved this method to offline service

2022-08-08 12:49 UTC, yksolanki9 commented on src/app/core/services/offline.service.ts
> -    return from(this.storageService.get('activeCorporateCardExpenseTab'));
Removed all unused methods

2022-08-16 05:15 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +    return of(
Why return this as an observable when we can return it synchronously? Change the return type and remove off the of

2022-08-16 05:15 UTC, Julias0 requested changes
1 important comment

2022-08-22 10:46 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +    return of(
Done

2022-08-22 10:52 UTC, Julias0 approved these changes

2022-08-22 16:27 UTC, gokulk16 approved these changes

2022-08-30 08:26 UTC, merged