Fyle 2k5y2va : Skip setup password flow
fylein/fyle-mobile-app pull request #1289
Opened 2022-08-09 05:42 UTC by Aditya-shrivastav

Changes : Skipping Setup Password Flow for SSO orgs and Non SSO ( Multi org where user is Active in one of the org )
DOC : https://www.notion.so/fyleuniverse/Front-End-Engineering-Design-1b5b39419a9c4d009c620e7d060b14cb
Loom Video of working model :
https://www.loom.com/share/c611064051324d3cb4fc7b1895946205
SS of the warning dialog box :
![Screenshot 2022-08-09 at 11 11 56 AM](https://user-images.githubusercontent.com/56168371/183573139-7247d8e5-759a-4ccb-9c6c-0ff60d9c21bc.png)

2022-08-11 05:56 UTC, hlkavya0213 commented on src/app/auth/switch-org/switch-org.page.ts
> +    const invite_link =
use camelCase for variables

2022-08-11 05:57 UTC, hlkavya0213 commented on src/app/auth/switch-org/switch-org.page.ts
> +        message: 'Your Email is not verified, Please check your Email and accept the invite first.',
get the content from Bhavika & update it here

2022-08-11 05:57 UTC, hlkavya0213 commented on src/app/auth/switch-org/switch-org.page.ts
> +      console.log('yaatta');
remove console logs

2022-08-11 05:58 UTC, hlkavya0213 commented on src/app/auth/switch-org/switch-org.page.ts
> +        console.log(orgs);
remove

2022-08-11 05:59 UTC, hlkavya0213 commented on src/app/auth/switch-org/switch-org.page.ts
> +          for (let i = 0; i < this.userOrgs.length; i++) {
create separate function for this ?

2022-08-11 06:00 UTC, hlkavya0213 commented on src/app/auth/switch-org/switch-org.page.ts
> +          const p = [];
rename

2022-08-12 06:04 UTC, hlkavya0213 approved these changes

2022-08-12 11:23 UTC, rvab requested changes

2022-08-12 11:23 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +  userOrgs;
data type?

2022-08-12 11:23 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
>        that.cdRef.detectChanges();
Why running `detectChanges` here?

2022-08-12 11:23 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +      that.activatedRoute.snapshot.params.invite_link && JSON.parse(that.activatedRoute.snapshot.params.invite_link);
Why JSON.parse is required?

2022-08-12 11:23 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +    if (data && data.action === 'close') {
use optional chaining here? `data?.action === 'close`

2022-08-12 11:23 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +    if (roles.indexOf('OWNER') > -1) {
use includes instead of `indexOf`

2022-08-12 11:23 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +  checkUserStatusInAllOrgs(currentOrgId, roles) {
What are the types of `currentOrg` and `roles`?

2022-08-12 11:23 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +    return new Promise((resolve, reject) => {
Please use rxjs

2022-08-12 11:23 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +  async handlePendingDetails(isInviteLink, orgSettings, roles) {
Please mention types

2022-08-12 11:23 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +      .subscribe(async (aggregatedResults) => {
Why using `async` here?

2022-08-12 11:23 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +  async proceed(isInviteLink) {
Mention type

2022-08-12 11:25 UTC, rvab requested changes

2022-08-12 11:25 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +      this.orgService.switchOrg(primaryOrg.id).subscribe(() => {
Avoid nested subscription. Use `switchMap`.

2022-08-12 12:15 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +      that.activatedRoute.snapshot.params.invite_link && JSON.parse(that.activatedRoute.snapshot.params.invite_link);
Following the same pattern as `choose`. Since it might be possible to get invite_link as string instead as boolean.

2022-08-12 12:19 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +      .subscribe(async (aggregatedResults) => {
removed

2022-08-16 03:44 UTC, rvab requested changes

2022-08-16 03:44 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
>        that.cdRef.detectChanges();
Please talk to one of the members from the mobile app team. I would like to know the reason

2022-08-16 03:44 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +      that.activatedRoute.snapshot.params.invite_link && JSON.parse(that.activatedRoute.snapshot.params.invite_link);
When this will come as a string?

2022-08-16 03:44 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +          this.orgService.switchOrg(currentOrgId).subscribe(() => {
This should be handled inside `pipe` operator itself. You are nesting subscription again.

2022-08-16 03:44 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +          this.orgService.switchOrg(currentOrgId).subscribe(() => {
same as above

2022-08-16 03:44 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +      await this.showEmailNotVerifiedAlert();
Why use `await` here?

2022-08-16 03:44 UTC, rvab commented on src/app/auth/verify/verify.page.ts
> +        this.router.navigate(['/', 'auth', 'switch_org', { invite_link: true }]);
Why is `invite_link` set to true?. In web-app, the user is taken to verify page in 2 different scenarios. One is via email invite and another is when tries to login via `Google sign-in`. Is the flow different here?

2022-08-16 07:48 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +      await this.showEmailNotVerifiedAlert();
Since `showEmailNotVerifiedAlert` is a async function. Can we call it normally ? I am not sure

2022-08-16 07:50 UTC, Aditya-shrivastav commented on src/app/auth/verify/verify.page.ts
> +        this.router.navigate(['/', 'auth', 'switch_org', { invite_link: true }]);
Yes, The user details are fetched and user is redirected to switch org page directly in case of google sign in

2022-08-16 07:50 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
>        that.cdRef.detectChanges();
Dhar said : The detect changes is there because there were certain cases where the the rendering would not be able to detect the changes and we would get an error due to changes after detect changes cycle

2022-08-16 07:52 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +      that.activatedRoute.snapshot.params.invite_link && JSON.parse(that.activatedRoute.snapshot.params.invite_link);
In angular, params are treated as string by default. Therefore this will be treated as string as well and we need to convert it to string.

2022-08-16 08:17 UTC, rvab requested changes

2022-08-16 08:17 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +          return this.orgService.switchOrg(currentOrgId);
Please check sign-in page on using nested switchMap

2022-08-16 08:17 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +      await this.showEmailNotVerifiedAlert();
Check by removing `await`

2022-08-16 11:15 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +            map(() => {
use `tap` instead of `map`

2022-08-16 11:16 UTC, rvab approved these changes
minor comment

2022-08-17 14:05 UTC, abhishek1234321 submitted a review, later dismissed

2022-08-17 14:05 UTC, abhishek1234321 commented on src/app/auth/switch-org/switch-org.page.ts
> +  handlePendingDetails(isInviteLink: boolean, orgSettings, roles: string[]) {
Please add code comments with examples?

2022-08-17 14:05 UTC, abhishek1234321 commented on src/app/auth/switch-org/switch-org.page.ts
> +      if (orgSettings.sso_integration_settings.allowed && orgSettings.sso_integration_settings.enabled) {
how do we know the primary org will have the sso settings?

2022-08-17 14:05 UTC, abhishek1234321 commented on src/app/auth/switch-org/switch-org.page.ts
> +  checkUserStatusInPrimaryOrg(currentOrgId: string, roles: string[]) {
do we show a loader while the calls in this method are being made?

2022-08-17 14:05 UTC, abhishek1234321 commented on src/app/auth/switch-org/switch-org.page.ts
> +  checkUserStatusInPrimaryOrg(currentOrgId: string, roles: string[]) {
put code comments on why we have to do what we are doing?

2022-08-17 14:05 UTC, abhishek1234321 commented on src/app/auth/switch-org/switch-org.page.ts
> +        switchMap((pendingDetails) =>
is switchMap the right operator to use?

2022-08-17 14:05 UTC, abhishek1234321 commented on src/app/auth/switch-org/switch-org.page.ts
> +            tap(() => {
is `tap` the right operator to use?

2022-09-08 11:14 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +        message: 'Your email is not verified. Please check your previous emails and accept the invite.',
Bhavika ghate helped with the content

2022-09-08 11:33 UTC, rvab requested changes

2022-09-08 11:33 UTC, rvab commented on src/app/auth/switch-org/switch-org.page.ts
> +      .subscribe(noop);
This is nested subscription

2022-09-08 14:52 UTC, Dimple16 requested changes

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +import { PopupAlertComponentComponent } from 'src/app/shared/components/popup-alert-component/popup-alert-component.component';
please remove `Component` from the name

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +        title: 'Email Not Verified',
should it be `Email is not verified`?

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +        message: 'Your email is not verified. Please check your previous emails and accept the invite.',
If they check this in a certain span of 1-7 days, the link will get expired in the previous email. We can also ask them to opt for resend link option in the content

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +  userOrgsCount: number;
`orgUsersCount`?

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +       * Case : When user is added to a SSO orgs, but he haven't verified his account through link.
`Case: When a user is added to an SSO org but hasn't verified their account through the link.`

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +       * After showing the alert, he will be redirected to sign in page since there is no other org he is part of.
`After showing the alert, the user will be redirected to the sign-in page since there is no other org they are a part of.`

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +       * If user have more than 1 org, user will stay on switch org page to choose another org.
If the user has more than 1 org, the user will stay on the switch org page to choose another org.

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +       * If user have more than 1 org, user will stay on switch org page to choose another org.
aren't we handling this case? in code? since the logic refers to single org only?

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +   * Mark User active in the selected org and redirect him to the dashboard.
use the single-line comment in this case

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +   * Mark User active in the selected org and redirect him to the dashboard.
`Mark the user active in the selected org and redirect them to the dashboard.`

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +        }
is the `else` logic handled in `signOut()` method?

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +   * If user is coming from invite link, Follow invite link flow.
```
If the user is coming from the invite link, Follow the invite link flow.
Otherwise, show the user a popup to verify their email.
```

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +   * If user is coming from invite link, Follow invite link flow.
you can use the Grammarly extension if required, also, while adding comments, do refer to people as users, and pronouns can be they/their.

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +    return of(null);
is this required here?
in which case will it execute this case? or, should this be added in the else block?

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +  ): Observable<OrgUserService | ExtendedOrgUser | null> {
we don't have `strictNullChecks` enabled in the Mobile app, so you can skip `| null`

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/verify/verify.page.ts
> +        this.router.navigate(['/', 'auth', 'switch_org', { invite_link: true }]);
is the above verified?

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/verify/verify.page.ts
> +        this.router.navigate(['/', 'auth', 'switch_org', { invite_link: true }]);
we have the google login even in the case of the Mobile app no? then behavior should be the same I guess, please check

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +  goToSetupPassword(roles: string[]) {
the method name is `goToSetupPassword`, but the redirections are different, can we name this with context?

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +   * If no, Redirect user to setup password page.
this is either `setup_account` page OR `invited_user` page, are we redirecting to the set password page?

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +  navigateBasedOnUserStatus(
use config for too many params, you can check other pages for reference,
this will avoid `"max-params-no-constructor/max-params-no-constructor": ["error", 4],` eslint error, 
refer for more details - https://eslint.org/docs/latest/rules/max-params
```
(config: {
    isPendingDetails: boolean,
    roles: string[],
    eou: ExtendedOrgUser,
    isFromInviteLink?: boolean
})
```

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +          finalize(() => from(this.loaderService.hideLoader()))
check if this is working as expected,

2022-09-08 14:52 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +        .subscribe();
why do this? I don't think `.subscribe()` is required here
we aren't returning anything in this method no? check if you can remove it/mention the use-case

2022-09-12 06:11 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +import { PopupAlertComponentComponent } from 'src/app/shared/components/popup-alert-component/popup-alert-component.component';
Not a typo, using this same at every place.

2022-09-12 06:13 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +        title: 'Email Not Verified',
No, Using `Email Not Verified` only. Confirmed this bhavika ghate

2022-09-12 06:29 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +       * If user have more than 1 org, user will stay on switch org page to choose another org.
Right now, we ask user to setup password in this case. If he has single org only. But since we don't want this happen from the application. We will send him back to sign in page

2022-09-12 06:30 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +        }
In the else logic, user will stay at the switch org. That's why we are not doing anything.

2022-09-12 06:32 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +    return of(null);
Yes, Since the function is needed to return an observable. We can add it inside else block as well but there will be no difference.

2022-09-12 09:29 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +        .subscribe();
Not working without subscribe.

2022-09-12 09:29 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +          finalize(() => from(this.loaderService.hideLoader()))
Working

2022-09-12 09:30 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +            tap(() => {
Removed function

2022-09-12 09:30 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +        switchMap((pendingDetails) =>
Removed function

2022-09-12 09:31 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +  checkUserStatusInPrimaryOrg(currentOrgId: string, roles: string[]) {
done

2022-09-12 09:31 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +      if (orgSettings.sso_integration_settings.allowed && orgSettings.sso_integration_settings.enabled) {
Using new api to get effective SSO now

2022-09-12 09:31 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +  handlePendingDetails(isInviteLink: boolean, orgSettings, roles: string[]) {
done

2022-09-12 09:32 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +  async proceed(isInviteLink: boolean) {
Changed to isFromInviteLink

2022-09-12 09:32 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +        if (orgs.length === 1) {
Nothing happens, User will stay on the switch org page. So that he can select any other org. Added this in code comments as well

2022-09-12 09:34 UTC, Aditya-shrivastav commented on src/app/auth/verify/verify.page.ts
> +        this.router.navigate(['/', 'auth', 'switch_org', { invite_link: true }]);
User go through the verify page in case of invite link only. In case of google sign in , User will be redirected to switch org page directly.

2022-09-12 09:34 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +      await this.showEmailNotVerifiedAlert();
removed

2022-09-12 09:35 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +          this.orgService.switchOrg(currentOrgId).subscribe(() => {
done

2022-09-12 12:10 UTC, Dimple16 requested changes

2022-09-12 12:50 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +import { distinctUntilChanged, finalize, map, shareReplay, startWith, switchMap, tap, flatMap } from 'rxjs/operators';
removed

2022-09-12 12:50 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +  goToSetupPassword(roles: string[]) {
Done

2022-09-12 12:50 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +  // * Mark the user active in the selected org and redirect them to the dashboard.
Done

2022-09-13 09:03 UTC, Dimple16 requested changes

2022-09-13 09:03 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +  handlePendingDetails(roles: string[], isFromInviteLink?: boolean): Observable<OrgUserService | ExtendedOrgUser> {
`OrgUserService` same as above, please check the usage and remove everywhere

2022-09-13 09:03 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +  handlePendingDetails(roles: string[], isFromInviteLink?: boolean): Observable<OrgUserService | ExtendedOrgUser> {
how is the service name used as a `return type` here?

2022-09-13 09:12 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +  handlePendingDetails(roles: string[], isFromInviteLink?: boolean): Observable<OrgUserService | ExtendedOrgUser> {
Not using it right now, but in the initial changes. I was using user status in primary to decide whether to redirect user to setup password page or mark them active. Removed it from the return type now.

2022-09-13 09:12 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +  handleInviteLinkFlow(roles: string[]): Observable<OrgUserService | ExtendedOrgUser> {
Removed

2022-09-13 09:20 UTC, Dimple16 approved these changes

2022-09-13 09:20 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +  handlePendingDetails(roles: string[], isFromInviteLink?: boolean): Observable<ExtendedOrgUser> {
`handlePendingDetails` is used only in one place and the param - `isFromInviteLink` is present, can remove the optional param indicator `?` if not relevant

2022-09-13 09:20 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +    isFromInviteLink?: boolean;
same comment as above

2022-09-13 09:27 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +    isFromInviteLink?: boolean;
Can't remove isFromInviteLink as an optional field. Since isFromInviteLink is coming from proceed and proceed will only be called with inviteLink in case of user coming from invite link. Otherwise it will be called without any params.

2022-09-14 04:14 UTC, Julias0 commented on src/app/auth/switch-org/switch-org.page.ts
> +      that.activatedRoute.snapshot.params.invite_link && JSON.parse(that.activatedRoute.snapshot.params.invite_link);
So if invite link is a string, you should use `!!` to convert it into a boolean before setting it to a boolean variable

2022-09-14 06:46 UTC, rvab approved these changes
Please Dhar's comment here https://github.com/fylein/fyle-mobile-app/pull/1289/files#r970289228

2022-09-19 06:00 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +      that.activatedRoute.snapshot.params.invite_link && JSON.parse(that.activatedRoute.snapshot.params.invite_link);
!!"false" resolves to true. Since string is always truthy

2022-09-19 06:46 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +      component: PopupAlertComponentComponent,
resolved

2022-09-19 06:47 UTC, merged