#payment_mode_configurations: Add LD support
fylein/fyle-mobile-app pull request #1290
Opened 2022-08-09 13:17 UTC by yksolanki9

2022-08-12 16:37 UTC, yksolanki9 commented on src/app/core/services/accounts.service.ts
> +    isPaymentModeConfigurationsEnabled = false
Using these many vars here to avoid repetition and keep the logic for getting accounts in the service.
The last variable is for tracking the LD flag as that cant be called directly from accounts service - circular dependency

2022-08-25 06:16 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +    expenseType: 'EXPENSE' | 'MILEAGE' | 'PER_DIEM' = 'EXPENSE',
type ExpenseType = 'EXPENSE' | 'MILEAGE' | 'PER_DIEM';

2022-08-25 06:21 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +      const shouldCCCBeHidden =
`shouldCCCBeHidden` -> `isNonCCCExpense`

2022-08-25 06:35 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      map(({ paymentModes, orgUserSettings, isPaymentModeConfigurationsEnabled }) => {
move contents of method inside service

2022-08-25 06:36 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          const hasCCCAccount = paymentModes
Dont need `.map` here

2022-08-25 06:37 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            .map((res) => res?.value)
why is optional chaining required?

2022-08-25 06:49 UTC, Julias0 commented on src/app/fyle/view-expense/view-expense.page.ts
> +    const shouldPaymentModeBeShown$ = forkJoin({
```typescript

forkJoin({
etxn: this.etxn$.pipe(take(1)),
      allowedPaymentModes: this.offlineService.getAllowedPaymentModes(),
      isPaymentModeConfigurationsEnabled: this.launchDarklyService.checkIfPaymentModeConfigurationsIsEnabled()
    }).pipe(
      map(({ etxn, allowedPaymentModes, isPaymentModeConfigurationsEnabled }) => !isPaymentModeConfigurationsEnabled || this.accountsService.shouldPaymentModeBeShown(etxn, allowedPaymentModes))
    );

iif(this.view === ExpenseView.team, of(true), )

```

2022-08-25 07:04 UTC, Julias0 requested changes
minor comments - fix and send back

2022-08-25 15:07 UTC, yksolanki9 commented on src/app/fyle/view-expense/view-expense.page.ts
> +    const shouldPaymentModeBeShown$ = forkJoin({
Created a new service `viewExpenseService` and added the common logic there

2022-08-29 10:24 UTC, Dimple16 requested changes

2022-08-29 10:24 UTC, Dimple16 commented on src/app/core/services/view-expense.service.ts
> +  shouldPaymentModeBeShown(etxn: Expense) {
`showPaymentMode`?

2022-08-29 10:24 UTC, Dimple16 commented on src/app/core/services/view-expense.service.ts
> +  shouldPaymentModeBeShown(etxn: Expense) {
return type?

2022-08-29 10:24 UTC, Dimple16 commented on src/app/core/services/view-expense.service.ts
> +export class ViewExpenseService {
is this service related to payment mode? are we using this on multiple pages? since it is named as `ViewExpenseService`, found the content a bit generic to payments

2022-08-29 10:24 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> -        /**
why remove the comment?

2022-08-29 10:24 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          return this.accountsService.getPaymentModes(
instead of having these many `params`, can we add it to `config` and then pass?
that way, we can build the config params and pass it this way
`this.accountsService.getPaymentModes(config: configType)`

2022-08-29 10:24 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          (!isPaymentModeConfigurationsEnabled || paymentModes?.length > 1) &&
can you add a comment before this? as to what it refers to, the condition seems to be huge

2022-08-29 10:24 UTC, Dimple16 commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +    orgSettings: any,
check if there is an existing model?

2022-08-29 12:55 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          (!isPaymentModeConfigurationsEnabled || paymentModes?.length > 1) &&
Done

2022-08-29 12:55 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          return this.accountsService.getPaymentModes(
Grouped together orgSettings, etxn, expenseType, isPaymentModeConfigurationsEnabled, isPaidByCompanyHidden into a config object

2022-08-29 13:00 UTC, Dimple16 approved these changes
one comment

2022-08-30 08:25 UTC, merged