Added some cleanup around my expenses component to allow for writing …
fylein/fyle-mobile-app pull request #1292
Opened 2022-08-15 16:54 UTC by Julias0

…unit tests

2022-08-17 11:12 UTC, Dimple16 requested changes

2022-08-17 11:12 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.service.ts
> +
we can extract a new method for the below, should avoid a bunch of if condition blocks in the same method

2022-08-17 11:12 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.service.ts
> +  getFilters() {
returning a list

2022-08-17 11:12 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.service.ts
> +  addSortToGeneatedFilters(
addSortToGeneatedFilters -> typo, `addSortToGeneratedFilters`

2022-09-09 07:13 UTC, yksolanki9 requested changes

2022-09-09 07:13 UTC, yksolanki9 commented on src/app/core/services/transaction.service.ts
> +      if (filters.state.includes('POLICY_VIOLATED')) {
Create enum for filter state?

2022-09-09 09:01 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +      const startDate = filters?.customDateStart?.toISOString();
Since we are passing this as query params, afaik only ISO String is supported

2022-09-12 14:23 UTC, Dimple16 approved these changes

2022-09-12 14:52 UTC, yksolanki9 approved these changes

2022-09-13 13:57 UTC, merged