Add ld flag to disable keyboard plugin
fylein/fyle-mobile-app pull request #1299
Opened 2022-08-23 09:52 UTC by yksolanki9

2022-08-23 10:21 UTC, Julias0 commented on src/app/core/services/launch-darkly.service.ts
> +    return this.getVariation('disable_keyboard_plugin', false);
I think it would be better if we have `keyboard_plugin_enabled`.
Disabled flags are always hard to read

2022-08-23 10:42 UTC, yksolanki9 commented on src/app/core/services/launch-darkly.service.ts
> +    return this.getVariation('disable_keyboard_plugin', false);
Fixed

2022-08-24 05:44 UTC, Julias0 commented on src/app/shared/components/fy-number/fy-number.component.html
> +  *ngIf="isIos && isKeyboardPluginEnabled; else inputWithoutPlugin"
Are we sure using the ngIf inside input will not cause a nested input statement? I would be happier if we moved the ngIf into a `ng-container`

2022-08-24 05:44 UTC, Julias0 requested changes
Minor comments

2022-08-24 06:26 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.html
> +  *ngIf="isIos && isKeyboardPluginEnabled; else inputWithoutPlugin"
Done

2022-08-24 08:23 UTC, Julias0 approved these changes

2022-08-24 08:25 UTC, merged