#automate_report_submission: Add LD flag in expense form and tasks page
fylein/fyle-mobile-app pull request #1323
Opened 2022-09-07 09:00 UTC by yksolanki9

2022-09-07 12:29 UTC, Dimple16 requested changes

2022-09-07 12:29 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +  checkIfReportAutoSubmissionIsEnabled() {
lets have the method name same as the key -> `checkIfAutomateReportSubmissionIsEnabled`

2022-09-07 12:29 UTC, Dimple16 commented on src/app/core/services/launch-darkly.service.ts
> +  checkIfReportAutoSubmissionIsEnabled() {
also, why do we have the key with `_enabled`? isn't this incorrect? `automate_report_submission_enabled` this should have been `automate_report_submission`

2022-09-07 12:35 UTC, yksolanki9 commented on src/app/core/services/launch-darkly.service.ts
> +  checkIfReportAutoSubmissionIsEnabled() {
Yes, `enabled` does sound a bit redundant here, but this is being used across all clients and will be removed when we release this feature for all orgs, so shouldnt be an issue

2022-09-07 12:40 UTC, yksolanki9 commented on src/app/core/services/launch-darkly.service.ts
> +  checkIfReportAutoSubmissionIsEnabled() {
Renamed the method
\

2022-09-08 06:35 UTC, Dimple16 approved these changes

2022-09-13 11:42 UTC, merged