View team advance request revamp
fylein/fyle-mobile-app pull request #1325
Opened 2022-09-07 11:15 UTC by Dimple16

![Screenshot 2022-09-07 at 4 39 47 PM](https://user-images.githubusercontent.com/31147415/188865109-b9daa1a4-c294-4d59-b578-bb4fb2c3ff91.png)

![Screenshot 2022-09-07 at 4 35 37 PM](https://user-images.githubusercontent.com/31147415/188865131-e7c7c732-7a86-4e23-9d0b-6636f512c015.png)

![Screenshot 2022-09-07 at 4 38 28 PM](https://user-images.githubusercontent.com/31147415/188865158-582ef22c-d071-479a-af23-7b4e8545b954.png)

![Screenshot 2022-09-07 at 4 38 35 PM](https://user-images.githubusercontent.com/31147415/188865193-e1c21a1e-0c36-4a55-92bc-b653ca52ca3d.png)

![Screenshot 2022-09-07 at 4 38 49 PM](https://user-images.githubusercontent.com/31147415/188865290-6ad2dcb3-4e24-4cca-9c38-7fb2ff9f489e.png)

![Screenshot 2022-09-07 at 4 45 24 PM](https://user-images.githubusercontent.com/31147415/188865310-402ca343-08a6-4821-ae5a-4bdea19f8c06.png)

2022-09-08 08:40 UTC, yksolanki9 requested changes
Since this is an old Pr, please make sure Omkar's currency related changes and Sowmya's state pill changes are also included here

2022-09-08 08:40 UTC, yksolanki9 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +      <div class="view-advance-request--element">
Some css class name start with `view-team-advance-request` while others start with `view-advance-request` Please fix this?

2022-09-08 08:40 UTC, yksolanki9 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +            class="view-advance-request--element"
Class names should be `block__element--modifier` as per BEM
We use it incorrectly at many places across the app, but since this is a new file, we should consider fixing it

2022-09-08 08:40 UTC, yksolanki9 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +                [label]="'Created On'"
We can use `label = "Created On"` for strings

2022-09-08 08:40 UTC, yksolanki9 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +                [icon]="'../../../../assets/svg/calendar.svg'"
Use `icon = "path"`

2022-09-08 08:40 UTC, yksolanki9 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +                [label]="'Approved On'"
Same as above

2022-09-08 08:40 UTC, yksolanki9 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +          [label]="'Employee'"
Same as above

2022-09-08 08:40 UTC, yksolanki9 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.ts
>    async setupActionScheet() {
async is not needed here

2022-09-08 08:40 UTC, yksolanki9 commented on src/app/shared/components/summary-tile/summary-tile.component.html
> +        {{ purpose | ellipsis: 25 }}
We should not add ellipsis after fixed no. of chars, as this depends on the width of the screen. Use `text-ellipsis` global class instead

2022-09-08 13:50 UTC, Dimple16 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +                [label]="'Created On'"
Since interpolation is used in the `label` input inside the component, we will need to keep the binding

2022-09-08 13:51 UTC, Dimple16 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +            class="view-advance-request--element"
I've fixed it here, also, this isn't a new file, just a renamed existing file

2022-09-08 14:13 UTC, Dimple16 commented
### Note - This is a new PR checked out from the latest master, I've manually added the previous changes to this branch

2022-09-09 06:23 UTC, yksolanki9 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +                [label]="'Created On'"
`Created On` is a string not an expression, so we can remove the `[]` passed with the property name

2022-09-09 06:24 UTC, yksolanki9 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +                [label]="'Created On'"
Check this out - https://stackoverflow.com/a/36220057/10144339

2022-09-09 06:25 UTC, Dimple16 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +                [label]="'Created On'"
the way this value is fetched in the component differs, you can check how it used

2022-09-09 06:25 UTC, yksolanki9 approved these changes
Approving with minor comment

2022-09-09 06:27 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.html
> +        {{ purpose | ellipsis: 25 }}
I'm aware of the literal, the point is, it is being used as an expression in different places, also, the component itself doesn't accept the strings directly, we;ll have to make a slight change there to make it work as expected, but, I'm not changing existing component for now.

2022-09-09 06:32 UTC, Julias0 commented on src/app/core/models/actions.model.ts
> +export interface Actions {
rename to `AdvanceRequestActions`
The name `Actions` is too generic

2022-09-09 06:33 UTC, Dimple16 commented on src/app/fyle/view-team-advance-request/view-team-advance-request.page.html
> +                [label]="'Created On'"
I'm aware of the literal, the point is, it is being used as an expression in different places, also, the component itself doesn't accept the strings directly, we'll have to make a slight change there to make it work as expected, but, I'm not changing existing component for now.

2022-09-09 06:34 UTC, Julias0 approved these changes

2022-09-09 10:42 UTC, merged