#automate_report_submission: Changes in mileage/per-diem and expenses page report list view
fylein/fyle-mobile-app pull request #1327
Opened 2022-09-08 07:45 UTC by yksolanki9

2022-09-09 06:53 UTC, Dimple16 requested changes

2022-09-09 06:53 UTC, Dimple16 commented on src/app/fyle/dashboard/tasks/tasks.component.ts
> +    this.tasks$ = combineLatest({
why not use `forkJoin` for this case?

2022-09-09 06:53 UTC, Dimple16 commented on src/app/fyle/dashboard/tasks/tasks.component.ts
> +      this.showReportAutoSubmissionInfoCard =
can you add a comment on what this expression does? it'll help in readability as the expression is quite long

2022-09-12 10:13 UTC, yksolanki9 commented on src/app/fyle/dashboard/tasks/tasks.component.ts
> +    this.tasks$ = combineLatest({
`loadData$` is a BehaviourSubject which emits new values everytime a new filter is applied on tasks page. We never complete it, so `forkJoin` will never emit a value. This is how tasks is designed.

2022-09-12 10:27 UTC, yksolanki9 commented on src/app/fyle/dashboard/tasks/tasks.component.ts
> +      this.showReportAutoSubmissionInfoCard =
Added

2022-09-12 11:51 UTC, Dimple16 approved these changes

2022-09-13 07:02 UTC, merged