FYLE-2tea9p4: Increase chunk size to 200 from 50 for APIs
fylein/fyle-mobile-app pull request #1329
Opened 2022-09-08 13:39 UTC by Dimple16

2022-09-08 15:27 UTC, Julias0 commented on src/app/core/services/cost-centers.service.ts
> +        count = count > 200 ? count / 200 : 1;
cant we use the injected `PAGINATION_SIZE` instead of the hardcoded value everywhere?
Next time if we want to change this, we wont have to change this at every place

2022-09-08 15:27 UTC, Julias0 requested changes
Added comments

2022-09-12 06:51 UTC, OmkarJ13 commented on src/app/core/services/cost-centers.service.ts
> +        count = count > 200 ? count / 200 : 1;
heavy plus 👍

2022-09-14 07:41 UTC, yksolanki9 approved these changes
Minor comments

2022-09-15 06:21 UTC, Julias0 approved these changes

2022-09-15 06:22 UTC, merged