Tracking switch org launch time
fylein/fyle-mobile-app pull request #1338
Opened 2022-09-12 09:18 UTC by Dimple16

![Screenshot 2022-09-12 at 2 47 09 PM](https://user-images.githubusercontent.com/31147415/189617894-128175fc-abc0-4716-86d7-06598284deff.png)

2022-09-12 09:55 UTC, Julias0 commented on src/app/auth/switch-org/switch-org.page.ts
> +        performance.measure('switch org launch time', 'app launch start time', 'switch org launch time');
Shouldnt we start this when user clicks on login?
`app launch start time` happens inside app.component.ts which would execute when user opens the app. For folks who are not logged in, it will also take into account the users interaction time while they are entering email and password

2022-09-13 06:57 UTC, Julias0 requested changes
Added minor comments - fix and merge

2022-09-13 06:57 UTC, Julias0 commented on src/app/auth/switch-org/switch-org.page.ts
> +      if (performance.getEntriesByName('switch org launch time').length < 1) {
put this inside a try..catch just to be safe. And Extract this out into a separate funciton

2022-09-13 11:14 UTC, yksolanki9 requested changes

2022-09-13 11:14 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.ts
> +            performance.mark('login start time', markOptions);
Same comment as above

2022-09-13 11:14 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.ts
> +              performance.mark('login start time', markOptions);
Same as above

2022-09-13 11:14 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.ts
> +      if (performance.getEntriesByName('switch org launch time').length < 1) {
Use not operator or equate with 0?

2022-09-13 11:14 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.ts
> +        performance.measure('switch org launch time', 'login start time', 'switch org launch time');
You can skip the 3rd arg here, it'll anyways consider the current time.

2022-09-13 11:14 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.ts
> +        performance.measure('switch org launch time', 'login start time', 'switch org launch time');
Also, should we should define mark names as enums. Strings are prone to errors

2022-09-13 11:28 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +      if (performance.getEntriesByName('switch org launch time').length < 1) {
it won't make a difference, but, I'll equate to zero if that looks better :P

2022-09-13 11:29 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +        const loginMethod = performance.getEntriesByName('login start time')[0]['detail'];
since it uses a `PerformanceMarkOptions` interface, you cannot access it directly, we are forced to use it this way

2022-09-13 13:49 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +        performance.measure('switch org launch time', 'login start time', 'switch org launch time');
enums are added in the next PR

2022-09-14 07:55 UTC, yksolanki9 requested changes

2022-09-14 07:55 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.ts
> +            performance.mark('login start time', markOptions);
Any reason we add this to the beginning of the `else` block?

2022-09-14 07:55 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.ts
> +      that.trackSwitchOrgLaunchTime();
Should we add this on line 123 when we're setting `isLoading` to false?

2022-09-15 06:04 UTC, yksolanki9 approved these changes

2022-09-15 06:20 UTC, Julias0 approved these changes

2022-09-15 06:21 UTC, merged