Removal of org settings, org user settings & accounts API call dependency from offline service
fylein/fyle-mobile-app pull request #1354
Opened 2022-09-15 17:07 UTC by Dimple16

2022-09-17 08:11 UTC, Julias0 commented on src/app/core/services/accounts.service.ts
> +  getAccount(
This should be getDefaultAccount - also drop a message to Yash about this so that he is aware that he has to make changes here

2022-09-17 08:12 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +          transaction.skip_reimbursement = txnAccount.skip_reimbursement;
This looks a bit hacky - why is this happening here? This should happen in transactionOutbox

2022-09-17 08:14 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +      switchMap(({ orgUserSettings, accounts, orgSettings }) =>
witchMap(({ orgUserSettings, accounts, orgSettings }) =>this.accountsService.getAccount(orgSettings, accounts, orgUserSettings)),
 filter((account) => !!account), // why is this required? If account is null it wont emit anything and the parent forkJoin calling it.wont execute
 map((account) => {
            const accountDetails = {
              source_account_id: account.acc.id,
              skip_reimbursement: !account.acc.isReimbursable || false,
            };
            return accountDetails;
          })

2022-09-17 08:15 UTC, Julias0 requested changes
Added comments

2022-09-20 06:32 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> +          transaction.skip_reimbursement = txnAccount.skip_reimbursement;
@Julias0 Adding it to the transaction outbox creates a race condition where the source account ID is never set,
In this case, we add the account ID exactly while upsert if the account ID isn't present, 
This is the expected behavior for expense creations, none of the online created expenses will have the `source_account_id` as null, also, even if it is null, we want the account ID to be set if not present, it shouldn't be a problem imo,

2022-09-20 12:17 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +          transaction.skip_reimbursement = txnAccount.skip_reimbursement;
ok

2022-09-20 12:18 UTC, Julias0 approved these changes

2022-09-20 15:58 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +      map((isConnected) => {
Use `switchMap` in case the network is unstable

2022-09-20 16:02 UTC, yksolanki9 approved these changes
Minor comment

2022-09-21 05:23 UTC, Julias0 approved these changes

2022-09-21 06:13 UTC, merged