Check for app version only if user is logged in
fylein/fyle-mobile-app pull request #1355
Opened 2022-09-19 06:08 UTC by yksolanki9

2022-09-19 07:52 UTC, yksolanki9 commented on src/app/app.component.ts
> -  checkAppSupportedVersion() {
Moved this method inside `app-version` service and added it inside switch org as well.

2022-09-19 07:52 UTC, yksolanki9 commented on src/app/core/services/offline.service.ts
> +      this.appVersionService.checkAppSupportedVersion(deviceInfo);
Added check for supported version in switch org page as well. This fixes a corner case where user is able to login to an deprecated app and create expense

2022-09-19 07:52 UTC, yksolanki9 commented on src/app/app.component.ts
> -    this.checkAppSupportedVersion();
Moved this method inside `platform.ready()` as capacitor plugins may not be always initialized inside `ngOnInit`

2022-09-19 07:52 UTC, yksolanki9 commented on src/app/app.component.ts
> +          filter((isLoggedIn) => !!isLoggedIn),
`/mobileapp/check` and `version/app/<os>` calls should only be made if the user is logged in. Else these checks will be done  after login in switch org page

2022-09-19 08:33 UTC, rvab requested changes

2022-09-19 08:33 UTC, rvab commented on src/app/app.component.ts
> +          filter((isLoggedIn) => !!isLoggedIn),
Why these calls should be made after the user is logged in? What happens if done before and Why?

2022-09-19 08:57 UTC, yksolanki9 commented on src/app/app.component.ts
> +          filter((isLoggedIn) => !!isLoggedIn),
I have already added the sentry issue link in the description. We'd get `403: Forbidden` as the user does not have a valid access token

2022-09-19 11:44 UTC, Julias0 commented on src/app/core/services/app-version.service.ts
>    isSupported(data) {
isSupported(deviceInfo) {

2022-09-19 11:46 UTC, Julias0 commented on src/app/core/services/app-version.service.ts
> +        this.router.navigate(['/', 'auth', 'app_version', { message: appSupportDetails.message }]);
we shouldnt inject the router

2022-09-19 11:47 UTC, Julias0 commented on src/app/core/services/app-version.service.ts
> +        this.router.navigate(['/', 'auth', 'app_version', { message: appSupportDetails.message }]);
Move subscribe block to page level component

2022-09-19 11:51 UTC, Julias0 commented on src/app/core/services/offline.service.ts
> +    this.deviceService.getDeviceInfo().subscribe((deviceInfo) => {
move the behaviour change to inside switch org page

2022-09-19 11:51 UTC, Julias0 approved these changes

2022-09-20 03:08 UTC, rvab commented on src/app/app.component.ts
> +          filter((isLoggedIn) => !!isLoggedIn),
Why does the user need to be authorized to make this API? This check should be independent no? If the app version is deprecated, it's deprecated. Why depend on login status?

2022-09-20 03:30 UTC, rvab approved these changes
One clarification

2022-09-20 08:11 UTC, yksolanki9 commented on src/app/app.component.ts
> +          filter((isLoggedIn) => !!isLoggedIn),
I dont think we can allow any of our internal apis to be accessible without a token. Anyone can use a DDoS attack against us?

2022-09-20 08:55 UTC, yksolanki9 commented on src/app/core/services/app-version.service.ts
>    isSupported(data) {
Fixed

2022-09-21 13:37 UTC, yksolanki9 commented on src/app/core/services/app-version.service.ts
> +        this.router.navigate(['/', 'auth', 'app_version', { message: appSupportDetails.message }]);
Done

2022-09-21 13:37 UTC, yksolanki9 commented on src/app/core/services/offline.service.ts
> +    this.deviceService.getDeviceInfo().subscribe((deviceInfo) => {
Done

2022-09-21 13:37 UTC, merged