FYLE-2v1r96m: Remove offline service methods -  Org User Settings
fylein/fyle-mobile-app pull request #1375
Opened 2022-09-23 16:20 UTC by Dimple16

2022-09-26 12:40 UTC, Julias0 requested changes
Added comments

2022-09-26 12:40 UTC, Julias0 commented on src/app/core/services/offline.service.ts
>    getOrgUserMileageSettings() {
We should remove off this method from offline service and move it to a different service

2022-09-26 12:40 UTC, Julias0 commented on src/app/core/services/offline.service.ts
>    getAllowedPaymentModes(): Observable<AccountType[]> {
We should remove off this method from offline service and move it to a different service

2022-09-27 08:03 UTC, Dimple16 commented on src/app/core/services/offline.service.ts
> +    return this.orgUserSettingsService
removal of this method is taken care in another PR

2022-09-29 04:40 UTC, Julias0 approved these changes

2023-02-20 11:53 UTC, closed without merging