UI changes for expired verification link
fylein/fyle-mobile-app pull request #1376
Opened 2022-09-26 03:43 UTC by arjunaj5

**[Slack Thread](https://fylein.slack.com/archives/CN40C97P0/p1663047374274479)**

- Navigate the spender to pending verification page if the verification link is expired
- Navigate the spender to disabled page if the unverified spender was disabled by the admin.

2022-09-26 03:59 UTC, abhishek1234321 approved these changes

2022-09-26 06:00 UTC, Dimple16 approved these changes

2022-09-27 06:04 UTC, yksolanki9 approved these changes
Minor comment

2022-09-27 06:04 UTC, yksolanki9 commented on src/app/auth/pending-verification/pending-verification.page.ts
> +    this.hasTokenExpired = this.activatedRoute.snapshot.params.hasTokenExpired || false;
Put this in `ionViewWillEnter()` else it wont get executed if the page is already present in the stack

2022-10-11 03:55 UTC, arjunaj5 commented
Added few Additional commits to send the org_id also to the `/auth/resend_email_verification` to let spenders request a resend of email verification to secondary Orgs also.

The org_id will be present in the verification link:
https://fyle.app.link/branchio_redirect?`redirect_uri=https%3A%2F%2Fapp.fyle.tech%2Fapp%2Faccounts%2F%23%2Fverify&verification_code=eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NjU0NTY5NjIsImlzcyI6IkZ5bGVBcHAiLCJvcmdfdXNlcl9pZCI6Im91Q3VlWlRnT3dHZSIsImV4cCI6MTY2NTU0MzM2Mn0.EMf3h0d2DmOGhMjwnTrCtgVi45IHnYc2vuh78Vvrkuk&org_id=orStYfY0zIOT`
@Dimple16 @yksolanki9

2022-10-11 05:05 UTC, abhishek1234321 approved these changes

2022-10-11 05:19 UTC, arjunaj5 commented on src/app/auth/pending-verification/pending-verification.page.ts
> +    this.hasTokenExpired = this.activatedRoute.snapshot.params.hasTokenExpired || false;
fixed

2022-10-11 05:19 UTC, Dimple16 requested changes

2022-10-11 05:19 UTC, Dimple16 commented on src/app/auth/verify/verify.page.ts
> -        next: () => this.router.navigate(['/', 'auth', 'switch_org', { invite_link: true }]),
this was done intentionally, for a fix by @yksolanki9 afaik 
we shouldn't be removing it, please confirm this with him

2022-10-11 05:35 UTC, yksolanki9 requested changes

2022-10-11 05:35 UTC, yksolanki9 commented on src/app/auth/verify/verify.page.ts
> -        next: () => this.router.navigate(['/', 'auth', 'switch_org', { invite_link: true }]),
@arjunaj5 Please use the new rxjs syntax to catch errors

2022-10-12 15:50 UTC, arjunaj5 commented on src/app/auth/verify/verify.page.ts
> -        next: () => this.router.navigate(['/', 'auth', 'switch_org', { invite_link: true }]),
fixed this and tested, @Dimple16  @yksolanki9

2022-10-13 08:19 UTC, yksolanki9 approved these changes

2022-10-13 09:08 UTC, Dimple16 approved these changes

2022-10-14 09:00 UTC, merged