FYLE-2v1r9cf: Remove offline service methods - Current Org
fylein/fyle-mobile-app pull request #1390
Opened 2022-09-28 14:50 UTC by Dimple16

2022-09-28 16:59 UTC, yksolanki9 approved these changes

2022-09-28 16:59 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.ts
> +    this.activeOrg$ = this.orgService.getCurrentOrg();
Make sure these methods are cached in org service

2022-09-29 04:50 UTC, Julias0 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +                org_created_at: (currentOrg?.created_at).toString(),
`currentOrg?.created_at?.toString()`

We should use optional chaining when using `.toString()`

2022-09-29 04:50 UTC, Julias0 requested changes
1 comment

2022-09-30 04:58 UTC, Julias0 approved these changes

2022-10-06 06:59 UTC, merged