FYLE-2v1r9fv: Remove offline service methods - Current User
fylein/fyle-mobile-app pull request #1394
Opened 2022-09-28 15:21 UTC by Dimple16

2022-09-28 17:28 UTC, yksolanki9 requested changes

2022-09-28 17:28 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +        eou: this.orgUserService.getCurrent(),
We already have a duplicate method `getEou()`  in `auth-service`. As we're anyways cleaning it, we should remove either of the two methods, and keep only one of them.

2022-09-30 04:58 UTC, Julias0 approved these changes

2022-10-06 07:11 UTC, Dimple16 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +        eou: this.orgUserService.getCurrent(),
these are 2 different methods, 
in auth service, the method returns the `eou` from local storage of type promise, the use case here is different

2022-10-07 06:25 UTC, yksolanki9 approved these changes

2022-10-07 17:59 UTC, merged