#mission_nps_mobile_40: For sent back reports, show comments section instead of expenses when…
fylein/fyle-mobile-app pull request #1398
Opened 2022-10-03 07:18 UTC by yksolanki9

… opening the report

2022-10-04 10:35 UTC, Dimple16 requested changes

2022-10-04 10:35 UTC, Dimple16 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      if (erpt.rp_state === 'APPROVER_INQUIRY') {
can you check the `segmentChanged()` once, just to verify if it'll overwrite this value

2022-10-04 10:35 UTC, Dimple16 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      if (erpt.rp_state === 'APPROVER_INQUIRY') {
we should be handling in one way itself, here we have a separate value in HTML, and the we are setting `ionsegment` value here,

2022-10-05 06:16 UTC, Dimple16 approved these changes

2022-10-07 06:38 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      if (erpt.rp_state === 'APPROVER_INQUIRY') {
Discussed on slack

2022-10-07 06:38 UTC, merged