Adding new system categories - Airlines, Courier & Lodging
fylein/fyle-mobile-app pull request #1406
Opened 2022-10-07 17:41 UTC by Dimple16

[https://www.notion.so/fyleuniverse/Mobile-app-mcc_v1_and_category_cleanup-48da37baaa954c0d96cc3793e6fd6289](url)

2022-10-10 06:16 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                      *ngIf="txnFields.location1?.is_mandatory && ['Bus', 'Flight', 'Airlines', 'Hotel', 'Lodging', 'Train'].includes(fg.value.category?.fyle_category)"
`['Bus', 'Flight', 'Airlines', 'Hotel', 'Lodging', 'Train']` 
We should move these out to a variable on the component. 
The data in that variable should come from a service - otherwise this is leading to a awesome amount of duplication.

2022-10-10 06:17 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                      *ngIf="txnFields.location1?.is_mandatory && ['Bus', 'Flight', 'Airlines', 'Hotel', 'Lodging', 'Train'].includes(fg.value.category?.fyle_category)"
`allSystemCategories`
`systemCategoriesForBreakfastField`

2022-10-10 06:17 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                      *ngIf="txnFields.location1?.is_mandatory && ['Bus', 'Flight', 'Airlines', 'Hotel', 'Lodging', 'Train'].includes(fg.value.category?.fyle_category)"
You can name the fields in this fashion

2022-10-10 06:17 UTC, Julias0 requested changes
1 refactoring comment

2022-10-10 13:49 UTC, yksolanki9 approved these changes

2022-10-11 06:04 UTC, Julias0 approved these changes

2022-10-13 06:34 UTC, merged