FYLE-2uw0r29: Fix for cards for different org showing up on dashboard
fylein/fyle-mobile-app pull request #1419
Opened 2022-10-14 08:31 UTC by Dimple16

2022-10-14 08:32 UTC, Dimple16 commented on src/app/fyle/dashboard/stats/stats.component.html
> -      <ng-container *ngIf="!isUnifyCCCExpensesSettings">
this section is not required since there is no more `nonunifyccc`, all the orgs have it enabled by default

2022-10-14 08:35 UTC, Julias0 commented on src/app/fyle/dashboard/stats/stats.component.ts
>          this.isCCCStatsLoading = false;
put this in finalize block

2022-10-14 08:36 UTC, Julias0 commented on src/app/fyle/dashboard/stats/stats.component.html
> +  <div *ngIf="(isConnected$ | async) && cardTransactionsAndDetails?.length > 0" class="stats--ccc-cards-section">
Lets move the isConnected to a parent <ng-container>

2022-10-14 08:51 UTC, Dimple16 commented on src/app/fyle/dashboard/stats/stats.component.html
> -  <ng-container *ngIf="isConnected$ | async; else offlineMessage"></ng-container>
change -> added the below section inside the parent container, no other change

2022-10-14 09:30 UTC, yksolanki9 requested changes
Can you add some notes on what was the issue here and how is it fixed? Its difficult to understand from the changes.
Also, please fix lint errors

2022-10-17 07:15 UTC, Julias0 approved these changes

2022-10-17 12:22 UTC, merged