Fyle 2wuxjb5
fylein/fyle-mobile-app pull request #1426
Opened 2022-10-17 13:35 UTC by Aditya-shrivastav

Resend Invite Button added and change content for warning message

https://user-images.githubusercontent.com/56168371/196190913-4b41cad2-0b91-42c3-a272-47eae876bd68.mov

2022-10-18 15:07 UTC, abhishek1234321 commented on src/app/core/services/auth.service.ts
> +  resendVerification(email: string, org_id?: string): Observable<ResendEmailVerificationResponse> {
`orgId`

2022-10-18 15:07 UTC, abhishek1234321 commented on src/app/core/services/auth.service.ts
> +  resendVerification(email: string, org_id?: string): Observable<ResendEmailVerificationResponse> {
why is this optional here?

2022-10-20 12:06 UTC, hlkavya0213 commented on src/app/auth/switch-org/switch-org.page.ts
> +            this.showToastNotification('Oops! Something went wrong. Please try again.');
change the content get it from Bhavika

2022-10-20 12:06 UTC, hlkavya0213 commented on src/app/auth/switch-org/switch-org.page.ts
> +          this.showToastNotification('Verification Email Sent');
get content from Bhavika

2022-10-20 17:21 UTC, Dimple16 requested changes

2022-10-20 17:21 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +    this.handlePopupDismiss(data.action, email, orgId);
`handleDismissPopup`? or mention the dismiss action name

2022-10-20 17:21 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +    if (action === 'close') {
this block doesn't return/do anything if the `orgs.length` condition fails, is this expected?

2022-10-20 17:21 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +    } else if (action === 'resend') {
will there be a case of hitting an `else` block here? how do we handle if the action is null/undefined? test this and add fail-safe if required

2022-10-20 17:21 UTC, Dimple16 commented on src/app/core/services/auth.service.ts
> +  resendVerification(email: string, orgId?: string): Observable<ResendEmailVerificationResponse> {
`resendEmailVerification`

2022-10-21 06:00 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +    if (action === 'close') {
Yes, this is fine. We just need to check if user have only 1 org. If yes, we will logout him. Otherwise, we will do nothing.

2022-10-21 06:12 UTC, Aditya-shrivastav commented on src/app/auth/switch-org/switch-org.page.ts
> +    } else if (action === 'resend') {
else block is not required, since actions are defined inside popup itself. Although, changed condition to have a fail-safe

2022-10-21 06:58 UTC, Dimple16 requested changes

2022-10-21 06:58 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +        .subscribe((orgs) => {
why add `this.orgs$` inside the `switchMap` here? can directly use it below and subscribe, same as the else block

2022-10-21 08:50 UTC, Dimple16 requested changes

2022-10-21 08:50 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +  logoutIfSingleOrg() {
`logoutForSingleOrg`?

2022-10-21 08:50 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +    this.orgs$.subscribe((orgs) => {
you don't have to subscribe to `this.orgs$` here, 
check `ionViewWillEnter()` in line 97, we subscribe it once, and you can assign `this.orgs` there, use it here directly

2022-10-25 05:31 UTC, Dimple16 approved these changes

2022-12-15 11:21 UTC, merged