#mission_nps_mobile_40: Refactor `capture-receipt` component
fylein/fyle-mobile-app pull request #1432
Opened 2022-10-19 06:07 UTC by yksolanki9

2022-10-25 07:42 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +import { Component, EventEmitter, OnDestroy, OnInit, Input, AfterViewInit, ViewChild } from '@angular/core';
This file will be cleaned in the next PR, so ignore issues in the unchanged code

2022-10-26 07:13 UTC, Julias0 requested changes
Added a few comments

2022-10-26 16:03 UTC, Dimple16 requested changes

2022-10-26 16:03 UTC, Dimple16 commented on src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
> +      this.isCameraPreviewStarted = false;
can assign this value after the `.then` of `CameraPreview.stop()`?

2022-10-27 15:54 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
>    @Input() allowGalleryUploads = true;
Yes, in android when adding receipts from inside expense forms

2022-10-27 15:55 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.html
> +            {{ !isBulkMode ? 'Bulk Mode' : 'Single Mode' }}
`!isBulkMode ? 'Bulk Mode' : 'Single Mode'` is correct
If user is not on bulk mode, show `Bulk mode` on the bottom right icon to prompt him/her to switch to bulk mode

2022-10-28 06:19 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
> +  flashMode: string;
Done

2022-10-28 06:21 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
> +  hasModeChanged = false;
Done

2022-10-28 06:21 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
> +      if (permissions?.camera === 'prompt-with-rationale') {
There's a return statement above so it doesn't matter

2022-10-28 06:25 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
> +        if (flashModes.result && flashModes.result.includes('on') && flashModes.result.includes('off')) {
Done

2022-10-28 06:38 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
> +      this.isCameraPreviewStarted = false;
The idea is to get rid of promises altogether, converting it into an observable

2022-10-28 06:43 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
> +  async stopCamera() {
Done

2022-10-28 13:07 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/capture-receipt.component.ts
> +            return this.cameraPreview.showPermissionDeniedPopover('GALLERY');
Yes, done

2022-10-28 13:11 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
> +      return;
Replaced with `else if`

2022-10-28 14:08 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
> +  isCameraPreviewStarted = false;
Have replaced them with an enum

2022-10-31 08:49 UTC, yksolanki9 commented on src/app/constants.ts
> +export const DEVICE_PLATFORM = new InjectionToken<'android' | 'ios' | 'web'>('Device Platform');
Will create an enum for this and use this injection across the app in a separate pr as it is out of scope for this change

2022-10-31 08:49 UTC, yksolanki9 commented on src/app/shared/components/capture-receipt/camera-preview/camera-preview.component.ts
> +    if (Capacitor.getPlatform() === 'web') {
Used dependency injection as discussed

2022-10-31 12:04 UTC, Dimple16 approved these changes

2022-11-03 05:47 UTC, Julias0 approved these changes

2022-11-14 08:16 UTC, merged