Fyle 2x6fvjq
fylein/fyle-mobile-app pull request #1436
Opened 2022-10-25 09:28 UTC by shreya-fyle1

2022-10-25 12:05 UTC, Dimple16 requested changes
added comments

2022-10-25 12:05 UTC, Dimple16 commented on package.json
> +    "@capacitor/core": "^3.9.0",
you can remove package.json files from the PR

2022-10-25 12:05 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +import { Value } from './../../core/models/v2/stats-response.model';
why is this added here?

2022-10-25 12:05 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  listofreports = [];
remove this as you aren't using it

2022-10-25 12:05 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  displayValue;
which change is this related to?

2022-10-25 12:05 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  autoSubmissionReportEnabled;
add the corresponding model type here

2022-10-25 12:05 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.autoSubmissionReportName$.subscribe((res) => {
res -> `autoSubmissionReportEnabled`

2022-10-26 06:09 UTC, Dimple16 requested changes
remove package files from the PR

2022-10-26 06:55 UTC, Dimple16 approved these changes

2022-10-26 07:01 UTC, yksolanki9 requested changes

2022-10-26 07:01 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      this.autoSubmissionReportEnabled = autoSubmissionReportEnabled;
A new variable is not needed, you can directly use forkJoin as mentioned above

2022-10-26 16:10 UTC, Dimple16 requested changes

2022-10-26 16:10 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      this.autoSubmissionReportEnabled = autoSubmissionReportEnabled;
remove this block as it isn't used anymore

2022-10-27 05:51 UTC, yksolanki9 approved these changes
Minor comment

2022-10-27 05:51 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  autoSubmissionReportEnabled: string;
Remove unused variable

2022-10-27 06:01 UTC, Dimple16 requested changes

2022-10-27 06:01 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          return this.reports$.pipe(
this isn't resolved yet

2022-10-27 07:15 UTC, Dimple16 requested changes

2022-10-27 07:15 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  autoSubmissionReportEnabled: string;
remove this if unused

2022-10-27 07:46 UTC, Dimple16 approved these changes

2022-10-27 09:16 UTC, merged