Functions to accomodate check policies call
fylein/fyle-mobile-app pull request #1438
Opened 2022-10-25 12:05 UTC by KirtiGautam

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1RoxuAL99HyDW4hNrruZ0Ci3Gg9BRX04%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=7484Ucj)

2022-10-25 12:54 UTC, Dimple16 requested changes

2022-10-25 12:54 UTC, Dimple16 commented on src/app/core/models/platform/platform-check-expense-policy.model.ts
> +export interface CheckExpensePolicies {
why name it `checkExpensePolicies`? 
can we name it something like `ExpensePolicy`? since this isn't a list

2022-10-25 12:54 UTC, Dimple16 commented on src/app/core/services/policy.service.ts
> +  getCriticalPolicyRules(result: CheckExpensePolicies): string[] {
`result` rename with context

2022-10-25 12:54 UTC, Dimple16 commented on src/app/core/models/platform/platform-final-expense-policy-state.model.ts
> +  // Expense Id is absent in check policies call
add inline comment itself, same like below, easier to read

2022-10-25 12:54 UTC, Dimple16 commented on src/app/core/models/platform/platform-individual-expense-policy-state.model.ts
> +  // In check policies call, the object key is returned with different name than in expense_policies_states call
so we will have 2 things with the same values, but different names, is this intentional in the backend?

2022-10-25 12:54 UTC, Dimple16 commented on src/app/core/services/policy.service.ts
> +    result.data.individual_desired_states.forEach((desiredState) => {
if we change this here, we can't push this change until all the versions use the new API right? else it'll break

2022-10-25 12:54 UTC, Dimple16 commented on src/app/core/services/policy.service.ts
> +  getPolicyRules(result: CheckExpensePolicies): string[] {
rename `result` with context

2022-10-25 12:54 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> +  checkPolicy(policyExpense: PolicyExpense): Observable<CheckExpensePolicies> {
`CheckExpensePolicies` this model will be renamed

2022-10-25 12:54 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> +        if (policyExpense.spent_at) {
will `policyExpense` always have a proper value? else we'll have to add optional chaining

2022-10-25 12:54 UTC, Dimple16 commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.html
> +          [actionsCount]="policyAction?.run_summary?.length"
will this ever be an empty list with length 0? 
If this is the case, we might need to check the component logic if it handles both cases

2022-10-25 12:54 UTC, Dimple16 commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> +      console.log('here in capping');
remove logs

2022-10-25 13:34 UTC, KirtiGautam commented on src/app/core/models/platform/platform-individual-expense-policy-state.model.ts
> +  // In check policies call, the object key is returned with different name than in expense_policies_states call
Hey, no either of these would be present.
In check_policies, it would be returned as `expense_policy_states` and in previous call it was returned as `rule`

2022-10-25 13:46 UTC, KirtiGautam commented on src/app/core/services/policy.service.ts
> +    result.data.individual_desired_states.forEach((desiredState) => {
Right now, the policy is running on both platform and the public side. This change can go out and people will slowly move from public to platform. After all clients are migrated, then only we will kill the public backend service

2022-10-25 13:47 UTC, KirtiGautam commented on src/app/core/services/transaction.service.ts
> +        if (policyExpense.spent_at) {
`spent_at` is always needed. So, it will always be present

2022-10-25 13:50 UTC, KirtiGautam commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.html
> +          [actionsCount]="policyAction?.run_summary?.length"
Yes, this can be zero. But this variable was initialised with zero previously so I don't think it would break now.

2022-10-26 15:28 UTC, Dimple16 requested changes
some clarifications

2022-10-26 15:28 UTC, Dimple16 commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.html
> +          [actionsCount]="policyAction?.run_summary?.length"
okay, make sure we have a default value set for all the variables OR add fail-safe logic

2022-10-26 15:28 UTC, Dimple16 commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> -      this.availableActionsCount = statuses.reduce((acc, curr) => (curr ? acc + 1 : acc), 0);
let's make sure to remove all the instances of `availableActionsCount` /  `statuses` if they aren't used anymore across

2022-10-26 15:28 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
>    testPolicy(etxn) {
what about this method? since we have the previous one, shouldn't we remove it if unused?

2022-10-26 19:23 UTC, KirtiGautam commented on src/app/shared/components/fy-policy-violation/fy-policy-violation.component.ts
> -      this.availableActionsCount = statuses.reduce((acc, curr) => (curr ? acc + 1 : acc), 0);
Yes, it's not used anywhere so have removed it from the file.

2022-10-27 12:06 UTC, Dimple16 approved these changes

2022-10-28 04:19 UTC, merged