Replace /policy/test with /check_policies in add edit expense page
fylein/fyle-mobile-app pull request #1439
Opened 2022-10-25 12:31 UTC by KirtiGautam

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1TsxhJDYlSbLrWNYePRK60s7RWSkv90k%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=BeHcB8Q)

2022-10-25 13:07 UTC, Dimple16 requested changes

2022-10-25 13:07 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    const policyExpense = this.policyService.transformTo(tx);
please add comments on why the transform, etc

2022-10-25 13:07 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> -        return this.categoriesService.getAll().pipe(
isn't this required anymore?

2022-10-25 13:07 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          // any is needed here because params in switchMap throws error if some type is defined on it
we can add a type if that is required, the type might not be matching the response, we should be checking this

2022-10-25 13:07 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            policyViolations && policyViolations.data && policyViolations.data.final_desired_state,
use optional chaining,
`policyViolations?.data?.final_desired_state` 
this should do

2022-10-25 13:07 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                // any is needed here because params in switchMap throws error if some type is defined on it
same as above

2022-10-25 13:07 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                  policyViolations && policyViolations.data && policyViolations.data.final_desired_state,
same as above

2022-10-25 14:59 UTC, KirtiGautam commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> -        return this.categoriesService.getAll().pipe(
Not required since platform policy needs only category id

2022-10-26 15:37 UTC, Dimple16 requested changes
minor comments

2022-10-26 15:37 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  checkPolicyViolation(etxn): Observable<ExpensePolicy> {
`etxn: Expense` -> add the type of param

2022-10-26 15:37 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    // Expense creation has not moved to platform yet and since policy is moved to platform,
use multi-line comments
```
/* 
-----
---------
*/
```

2022-10-26 15:37 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> -        /* Adding number of attachements and sending in test call as tx_num_files
you can keep this comment block for context

2022-10-27 12:08 UTC, Dimple16 approved these changes

2022-10-28 04:22 UTC, merged