Fix for project<>category mapping issues
fylein/fyle-mobile-app pull request #1440
Opened 2022-10-25 17:11 UTC by Dimple16

2022-10-26 07:34 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                (category) => project.project_org_category_ids.indexOf(category.value.id) > -1
same as above

2022-10-26 07:35 UTC, Julias0 requested changes
Added comments

2022-10-26 07:35 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              this.canAutofillCategory = isAllowedRecentCategories[0];
do you need this to be connected to `this`? You are using this locally inside the function only

2022-10-27 05:42 UTC, yksolanki9 approved these changes

2022-10-27 09:20 UTC, Julias0 approved these changes

2022-10-27 09:21 UTC, merged