Replace /policy/test with /check_policies in add edit mileage page
fylein/fyle-mobile-app pull request #1441
Opened 2022-10-26 03:36 UTC by KirtiGautam

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19uYQe7QF82pVmGRa5xfdjHyYDz4mms%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=2eHRsgm)

2022-10-26 15:41 UTC, Dimple16 requested changes
important comments

2022-10-26 15:44 UTC, Dimple16 requested changes

2022-10-26 15:44 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +          if (etxn.dataUrls && etxn.dataUrls.length > 0) {
we don't require `num_files` logic for mileage expense no? 
we can remove it off entirely, please check if this is required and remove it for both mileage and per diem

2022-10-26 19:56 UTC, KirtiGautam commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +    return from(this.mileageRates$).pipe(
`this.mileageRates$` is observable, that's why I have used the `from()` to subscribe and its result i.e. rates are returned. Do you mean I should directly use the subscribe on `this.mileageRates$`

2022-10-27 12:33 UTC, Dimple16 approved these changes

2022-10-27 12:33 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +    return from(this.mileageRates$).pipe(
no, you were previously setting the observable here which shouldn't be the case, you can use it here,

2022-10-28 04:24 UTC, merged