Add Expense To Draft Report
fylein/fyle-mobile-app pull request #1443
Opened 2022-10-26 06:40 UTC by jayfyle

## CTA update on viewing draft report

On opening a report on <strong>my_view_reports</strong>page, the plus button was not visible beside the submit report button on opening a draft report, that has been fixed. On clicking that button, a CTA opened that allows the user to add unreported expenses to the draft report, but it is empty on if there are no unreported expenses. A zero state and and an option to add new expenses has been added to the CTA
![add-expense-ureported expense](https://user-images.githubusercontent.com/115472256/197953120-f07f27b7-553e-4ba3-a09b-cb3c17b46c82.png)
![add-expense-zero-state](https://user-images.githubusercontent.com/115472256/197953141-4d9dce8e-a3ef-4618-bf25-3c11f5239367.png)

2022-10-26 07:14 UTC, yksolanki9 requested changes
Add a loom video of the new flow

2022-10-26 07:14 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +    console.log(this.activatedRoute.snapshot.params.id);
Remove console logs before raising prs

2022-10-26 07:14 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      cssClass: 'fy-modal',
This is not needed. `modalProperties.getModalDefaultProperties()` by default uses `fy-modal` class

2022-10-26 07:14 UTC, yksolanki9 commented on src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.ts
> +  @Input() rp_id: string;
use camelCase

2022-10-26 07:14 UTC, yksolanki9 commented on src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
> +        *ngIf="selectedElements && selectedElements.length > 0"
Optional chaining

2022-10-26 07:14 UTC, yksolanki9 commented on src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
> +      <ion-button (click)="addExpense()">
`addNewExpense()` would be more apt?

2022-10-26 07:14 UTC, yksolanki9 commented on src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
> +  <ng-container *ngIf="!unReportedEtxns || unReportedEtxns.length === 0">
`*ngIf="unReportedEtxns?.length === 0"` would do

2022-10-26 07:14 UTC, yksolanki9 commented on src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
> +        <div class="view-reports--zero-state-header">Looks like this report is empty.</div>
This is incorrect. It should be something like`Looks like there is no complete/unreported expense`
Please confirm with design team once

2022-10-26 07:14 UTC, yksolanki9 commented on src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
> +        <p>Click on + to add new expenses</p>
`Click on + to add a new expense to this report`
Confirm with design

2022-10-27 05:45 UTC, yksolanki9 commented on src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
> +        *ngIf="selectedElements && selectedElements.length > 0"
Not yet fixed

2022-10-27 05:45 UTC, yksolanki9 requested changes
Few comments are not taken care of, please fix all the comments and resolve the conversation before assigning :)

2022-10-28 05:01 UTC, Julias0 requested changes
Will review after @yksolanki9 gives green

2022-10-31 06:05 UTC, Julias0 approved these changes

2022-10-31 06:15 UTC, yksolanki9 commented on src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
> +        <div class="add-expenses-to-report--zero-state--header text-center">Looks like there are no expenses!</div>
This may be confusing. Shoule we change it to `Looks like there are no unreported expenses!?`

2022-10-31 06:34 UTC, yksolanki9 requested changes
Please confirm if we need to provide the `fill` separately to svg. Providing color to parent container should work ig

2022-10-31 06:34 UTC, yksolanki9 commented on src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.html
> +          Looks like there are no unreported expenses!?
Remove question mark

2022-10-31 06:34 UTC, yksolanki9 commented on src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.scss
> +  &--container {
I dont see this class being used anywhere

2022-10-31 06:34 UTC, yksolanki9 commented on src/app/fyle/my-view-report/add-expenses-to-report/add-expenses-to-report.component.ts
> +  @Input() reportID: string;
Use camelcase - `reportId`

2022-10-31 06:34 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.html
> +            *ngIf="(canResubmitReport$ | async) || (erpt$|async)?.rp_state === 'DRAFT'"
ngIf should be applied to parent div

2022-10-31 06:34 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +        reportID: this.activatedRoute.snapshot.params.id,
reportId

2022-10-31 06:34 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.scss
> +        fill: $brand-primary;
I dont think the `fill` property is needed here. Just changing the color of container should do

2022-10-31 13:57 UTC, merged