Default select of report
fylein/fyle-mobile-app pull request #1450
Opened 2022-10-27 14:57 UTC by shreya-fyle1

2022-10-31 06:02 UTC, yksolanki9 requested changes

2022-10-31 06:02 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              this.addToNewReport(res.id);
Why are we creating a new report here?

2022-10-31 06:02 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          return reportOptions.map((res: any) => {
Why is this map needed?

2022-10-31 06:32 UTC, Dimple16 requested changes

2022-10-31 06:32 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          return reportOptions.map((res: any) => {
this isn't required here anymore, since `reportOptions` is already resolved @shreya-fyle1

2022-10-31 06:32 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              this.addToNewReport(res.id);
this shouldn't be added here, we are just setting a default value, not creating another report

2022-11-02 10:31 UTC, Dimple16 approved these changes

2022-11-02 10:33 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          return reportOptions.map((res) => {
since we return the report value/null in a certain case and an observable by default, this map is required

2022-11-03 04:14 UTC, yksolanki9 requested changes
Discussed on slack

2022-11-03 07:08 UTC, yksolanki9 requested changes

2022-11-03 07:08 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          return of(reportOptions[0].value);
We're returning an observable here, but returning a value in the first two conditions. The first two conditions would break here.
You can return observables there, but the better solution is to use `map` here and return the values directly

2022-11-03 08:06 UTC, yksolanki9 approved these changes
Remove the unnecessary import and test all the cases before merging

2022-11-03 08:06 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +import { Value } from './../../core/models/v2/stats-response.model';
Remove this

2022-11-03 08:35 UTC, merged