Position of error message
fylein/fyle-mobile-app pull request #1453
Opened 2022-10-28 09:06 UTC by shreya-fyle1

2022-10-28 12:44 UTC, yksolanki9 requested changes

2022-10-28 12:44 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    margin: -8px 0 0 81.575px;
Specifying the exact value wont work. This would break for different screen sizes

2022-10-28 12:45 UTC, yksolanki9 requested changes

2022-10-28 12:45 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    margin: -68px 4px 48px 81.575px;
Same as above

2022-10-31 05:58 UTC, yksolanki9 approved these changes
Test it for different screen sizes and with and without foreign currency before merging

2022-10-31 06:16 UTC, Dimple16 requested changes

2022-10-31 06:16 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    margin: -68px 4px 48px 33%;
check on different screen resolutions, this might break in a few devices

2022-10-31 07:29 UTC, shreya-fyle1 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    margin: -68px 4px 48px 33%;
I checked every resolutions and dimensions and each of them is working well and none of them is breaking. So we can go with this PR.

2022-10-31 07:30 UTC, Dimple16 requested changes
please add screenshots of the change

2022-10-31 07:40 UTC, shreya-fyle1 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    margin: -68px 4px 48px 33%;
![Screenshot_2022-10-27-19-03-13-50_cb3351a6e9832df473867ce5e08766b8](https://user-images.githubusercontent.com/116056264/198956462-748118c4-0c39-4fb3-ab9a-94559fe2787c.jpg)
Before fixing

2022-10-31 07:41 UTC, shreya-fyle1 commented
![Screenshot (511)](https://user-images.githubusercontent.com/116056264/198956548-c9a1602d-32fe-4daf-b35d-7071a6c4f1e1.png)
After fixing

2022-10-31 08:44 UTC, shreya-fyle1 commented
![Screenshot (512)](https://user-images.githubusercontent.com/116056264/198967405-6c948f80-978b-452f-b4a4-77558d8c5ff7.png)
Without foreign currency

2022-10-31 08:44 UTC, shreya-fyle1 commented
![Screenshot (513)](https://user-images.githubusercontent.com/116056264/198967550-848f8798-6307-4893-a217-56054be0fc35.png)
With foreign currency

2022-10-31 10:43 UTC, Dimple16 approved these changes

2022-10-31 10:45 UTC, merged