color correction of placeholder
fylein/fyle-mobile-app pull request #1454
Opened 2022-10-28 10:30 UTC by shreya-fyle1

2022-10-28 12:46 UTC, yksolanki9 requested changes

2022-10-28 12:46 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.scss
> +      color: #a9acbc !important;
Check the colors name in `colors.scss` and use name instead of the hex value

2022-10-31 05:59 UTC, yksolanki9 approved these changes
Test all number fields in expense/mileage/per-diem/advances before merging

2022-10-31 06:15 UTC, Dimple16 approved these changes

2022-10-31 07:45 UTC, shreya-fyle1 commented
> Test all number fields in expense/mileage/per-diem/advances before merging

yes done.

2022-10-31 08:49 UTC, shreya-fyle1 commented
![image](https://user-images.githubusercontent.com/116056264/198968497-41506460-512f-40b9-b5af-abe44f528c24.png)

2022-10-31 08:50 UTC, shreya-fyle1 commented
![image](https://user-images.githubusercontent.com/116056264/198968815-1892b38c-e448-470a-959f-804f263145ba.png)

2022-10-31 08:51 UTC, shreya-fyle1 commented
> Test all number fields in expense/mileage/per-diem/advances before merging

Yes Done

2022-10-31 08:51 UTC, merged