Font Size Bug Fix
fylein/fyle-mobile-app pull request #1461
Opened 2022-11-04 11:45 UTC by jayfyle

2022-11-07 11:20 UTC, yksolanki9 requested changes
Please remove changes in gradle and capacitor files

2022-11-07 11:20 UTC, yksolanki9 commented on android/app/build.gradle
> +        versionCode 53300
Revert changes in this file

2022-11-07 11:20 UTC, yksolanki9 commented on android/app/src/main/res/values/strings.xml
> +  <string name="ionic_channel_name">Staging</string>
Revert this change

2022-11-07 11:20 UTC, yksolanki9 commented on ios/App/App.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 5.33.0;
Revert changes in this file

2022-11-07 11:20 UTC, yksolanki9 commented on ios/App/App/Info.plist
> +      <string>en</string>
Revert this file

2022-11-07 11:20 UTC, yksolanki9 commented on src/main.ts
>      }),
Revert this change

2022-11-08 05:35 UTC, Julias0 requested changes
Please send for me to review once @yksolanki9 's comments are taken care of and approved

2022-11-08 08:16 UTC, yksolanki9 requested changes

2022-11-08 08:16 UTC, yksolanki9 commented on src/main.ts
>      }),
This file is not reverted yet

2022-11-08 14:13 UTC, yksolanki9 approved these changes
Left minor comments

2022-11-08 14:13 UTC, yksolanki9 commented on android/app/build.gradle
> +       versionCode 51000
Remove the extra space

2022-11-08 14:13 UTC, yksolanki9 commented on ios/App/App.xcodeproj/project.pbxproj
> +				MARKETING_VERSION = 5.33.0;
Revert this file. These are placeholder texts, neednt be updated

2022-11-09 10:01 UTC, Julias0 approved these changes

2022-11-09 12:48 UTC, merged