#mission_nps_mobile_40: Fix hardware back button redirections in android app
fylein/fyle-mobile-app pull request #1468
Opened 2022-11-07 08:40 UTC by yksolanki9

Notion Doc - https://www.notion.so/fyleuniverse/Fix-Android-Hardware-Back-button-97f533f2a020485db9239bcbf1eda7cc

2022-11-08 05:37 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.hardwareBackButtonAction = this.platform.backButton.subscribeWithPriority(20, () => {
The priority can you convert into a injected value? That will make debugging easier and make sure we assign the proper priority every place

2022-11-08 05:37 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.hardwareBackButtonAction = this.platform.backButton.subscribeWithPriority(20, () => {
The priority can have different levels - base, medium, high, absolute

2022-11-08 05:37 UTC, Julias0 requested changes
Added comments

2022-11-09 07:54 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.hardwareBackButtonAction = this.platform.backButton.subscribeWithPriority(20, () => {
Added enum as discussed

2022-11-09 09:45 UTC, Dimple16 approved these changes

2022-11-09 09:59 UTC, Julias0 approved these changes

2022-11-09 10:00 UTC, merged