#mission_nps_mobile_40: Fix redirection when expense is added to a report or a reported expense is edited
fylein/fyle-mobile-app pull request #1471
Opened 2022-11-08 10:54 UTC by yksolanki9

2022-11-09 13:13 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> -  ngOnInit() {
Report details were not getting updated when the place was already in stack. So moved the variable initialization to `ionViewWillEnter()`

2022-11-10 05:52 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> -        this.saveExpenseLoader = false;
why remove this?
What happens if the addEntryAndSync call fails?

2022-11-10 05:52 UTC, Julias0 requested changes
Added minor comments

2022-11-10 07:52 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> -        this.saveExpenseLoader = false;
@Julias0 have not removed it, moved to line 3068 so that the loader stops only after we have the promise is resolved and we have the txn object

2022-11-10 09:58 UTC, Julias0 approved these changes

2022-11-23 14:14 UTC, merged