#mission_nps_mobile_40: Fix hardware back button redirections on tasks page
fylein/fyle-mobile-app pull request #1482
Opened 2022-11-10 14:40 UTC by yksolanki9

Changes:
- When navigating to the tasks page from dashboard, you'd be redirected back to the dashboard
- When navigating to tasks page from any other page, you'd be redirected to that page
- Fixed a bug where clicking on hw back button on expenses page did not do anything

2022-11-11 05:28 UTC, Julias0 commented on src/app/fyle/dashboard/dashboard.page.ts
> +    this.registerBackButtonAction();
Not super clear what is happening here - might want to add a comment

2022-11-11 05:28 UTC, Julias0 requested changes
minor comments

2022-11-14 07:12 UTC, yksolanki9 commented on src/app/fyle/dashboard/dashboard.page.ts
> +    this.registerBackButtonAction();
Moved all logic related to `my_dasboard` route in dashboard page and added comments.

2022-11-14 07:53 UTC, Julias0 approved these changes
Minor comment. - fix and merge

2022-11-14 07:53 UTC, Julias0 commented on src/app/core/services/shared.service.ts
> +export class SharedService {
In our application we have a module named Shared, people might confuse it with something related. Can we rename it to BackButtonService or something similar?

2022-11-14 08:16 UTC, yksolanki9 commented on src/app/core/services/shared.service.ts
> +export class SharedService {
Renamed to BackButtonService

2022-11-14 08:58 UTC, merged