Code coverage: Org settings service unit tests-1
fylein/fyle-mobile-app pull request #1484
Opened 2022-11-10 17:57 UTC by Dimple16

2022-11-11 05:43 UTC, Julias0 commented on src/app/core/services/org-settings.service.ts
> +  get(): Observable<Partial<OrgSettings>> {
Why is this partial? All keys in the response of OrgSettings are not optional right?

2022-11-11 05:46 UTC, Julias0 commented on src/app/core/services/org-settings.service.spec.ts
> +const apiResponse: Partial<OrgSettings> = {
move this to a different file in the same folder

2022-11-11 05:48 UTC, Julias0 requested changes
Added comments

2022-11-11 05:48 UTC, Julias0 commented on src/app/core/services/org-settings.service.spec.ts
> +    orgSettingsService.get().subscribe((res) => {
If what we get from the api response is the same as what we get from the get method, what do we have the `processIncoming` method?

2022-11-16 16:05 UTC, Dimple16 commented on src/app/core/services/org-settings.service.spec.ts
> +    orgSettingsService.get().subscribe((res) => {
I have handled this in the models and test data responses

2022-11-22 04:25 UTC, Julias0 requested changes
Added important comments

2022-11-22 04:25 UTC, Julias0 commented on src/app/core/services/org-settings.service.spec.ts
> +      expect(res).toBeTruthy(postApiData);
you have used `.toBeTruthy` in a number of places. This doesn't compare by equality but just checks if the response is a truth value or not.

We should add assertions based on what we want to test rather than just for code coverage - same for the rest of the tests

2022-11-29 19:26 UTC, Dimple16 commented on src/app/core/services/org-settings.service.spec.ts
> +      expect(res).toBeTruthy(postApiData);
this is done and resolved in all places

2022-11-30 05:30 UTC, Julias0 approved these changes

2022-11-30 06:37 UTC, merged