Code Coverage: Filters-Helper Service
fylein/fyle-mobile-app pull request #1485
Opened 2022-11-11 06:35 UTC by jayfyle

![code-coverage](https://user-images.githubusercontent.com/115472256/201278150-df2c0631-6ecf-4f14-8814-e0a15296d02d.png)

2022-11-15 06:11 UTC, Julias0 commented on src/app/core/models/filters.model.ts
> +export type Filters = Partial<{
The Partial should added where this is used, not in the definition. 
And when declaring models, use interface instead of type

2022-11-15 06:12 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +    expect(result).toBeTruthy();
The check for truthiness is not really required anywhere. Just check if the function behaves as expected and the output of the function is as expected

2022-11-15 06:14 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +    expect(result).toBeTruthy();
The `some project` argument that is passed is an optional argument. If its not relevant for this test case, lets not add it

2022-11-15 06:15 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +  it('should generate pill using only Sorting Params - Approved At New To Old', () => {
should generate pill using only Sorting Params - Approved At New To Old
to 
should generate filter pills based on filters selected for sorting on approved at param and no sort direction

Make the sentences descriptive to indicate what we are testing for

2022-11-15 06:16 UTC, Julias0 requested changes
Have added a few comments. Make sure these are taken care of in all the test cases

2022-11-15 13:03 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +   */
No need to create sections like this - this would be difficult to maintain later on

2022-11-15 13:04 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +    const result = service.generateFilterPills(testFilters, 'some project');
why is there to expect statement in this test case? Every test case should have a assertion / expect statement.
If you are just testing for existence of the response that too is fine

2022-11-16 05:42 UTC, Dimple16 approved these changes

2022-11-16 05:42 UTC, Dimple16 commented on src/app/core/services/filters-helper.service.spec.ts
> +    const resFilters: Filters = {
rename this with context, since this is used as expected value, can be `expectedFilters`?

2022-11-16 05:59 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +  it('should generated pill using project name', () => {
This description is not correct right? You are generating a pill based on the approval date.

2022-11-16 06:00 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
>    let service: FiltersHelperService;
rename to filterHelperService

2022-11-16 06:01 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +  let controller: jasmine.SpyObj<ModalController>;
rename to modalController

2022-11-16 06:02 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +        value: 1,
convert SortingDirection.descending to a number to get the value here. Otherwise this case will become flaky

2022-11-16 06:02 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +        value: 1,
Same as above

2022-11-16 06:04 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +      new Promise((resolve) => {
```typescript

const filterPopoverResponse = new Promise((resInt) => {
            resInt({
              data: selectedFilters,
            });
          });
const modalControllerResponse =  new Promise((resolve) => {
const filterPopoverSpy = jasmine.createSpyObj('filterPopover', ['onWillDismiss', 'present']) as any;
        filterPopoverSpy.onWillDismiss.and.returnValue(
          filterPopoverResponse
        );
        resolve(filterPopoverSpy);
      })

```

2022-11-16 06:05 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +      new Promise((resolve) => {
`controller.create.and.returnValue(modalControllerResponse);

2022-11-16 06:06 UTC, Julias0 requested changes
Added more comments

2022-11-16 07:22 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +        value: ', ',
Wait - this seems to be a bug?

2022-11-16 07:22 UTC, Julias0 requested changes
Added important comments

2022-11-16 07:22 UTC, Julias0 commented on src/app/core/services/filters-helper.service.spec.ts
> +    expect(filterHelperService.generateFilterPills(testFilters, 'some project')).toEqual(filterResponse);
Again, we havent passed a filter for project right? If yes, we are not truly testing for the `'some project'` value which is passed in

2022-11-18 05:30 UTC, Julias0 approved these changes

2022-11-21 08:51 UTC, Dimple16 approved these changes

2022-11-21 09:08 UTC, merged