Task view page
fylein/fyle-mobile-app pull request #1497
Opened 2022-11-16 09:13 UTC by jayfyle

## ClickUp Link : https://app.clickup.com/t/2x6fxe0

<strong>The following changes have been made:</strong>
<ul>
<li>The entire task card is clickable instead of the CTA</li>
<li>Styling updates for the task card, including a chevron icon at the end of the card</li>
<li>Add to existing and Create new Report CTA now replaced by Add to Report CTA</li>
<li>Add to existing CTA modal linked to new Add to Report CTA with the necessary changes</li>
<li>The Create New Report CTA now replaced by an add button on the Add to Report modal header</li>
</ul>

### Screenshots for further reference:
![new-task-page](https://user-images.githubusercontent.com/115472256/202138394-fc5d4d86-ea36-4873-8d13-22ab5c1f41e1.png)
<br />
![Add-to-report-task](https://user-images.githubusercontent.com/115472256/202138438-8a4dd1a0-723b-4322-a103-f7e51d3b310b.png)

2022-11-16 10:40 UTC, Dimple16 requested changes

2022-11-16 10:40 UTC, Dimple16 commented on src/assets/svg/arrow-right-nav.svg
> +<svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
don't use height, width and fill for SVG files, you can add custom CSS wherever used

2022-11-16 10:40 UTC, Dimple16 commented on src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.ts
> +  ctaEvent: any;
I guess there is `TASKEVENT` enum, avoid using `any`

2022-11-16 10:40 UTC, Dimple16 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
> +            (click)="createReportTaskClick()"
`onCreateReportTaskClick()`?

2022-11-16 10:40 UTC, Dimple16 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.scss
> +      font-size: 20px !important;
I guess you can remove this, the header font-size is 20px already

2022-11-17 05:14 UTC, yksolanki9 requested changes
- We have a right arrow icon in `assets/svg`, you can use that
- Fix the advance sent back icon size

2022-11-17 05:14 UTC, yksolanki9 commented on src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.ts
> +    this.ctaEvent = this.task.ctas[0];
Pass the event directly in the taskCtaClicked method, this is not the ideal way to deal with event data

2022-11-17 05:14 UTC, yksolanki9 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
> +<ion-header>
You had created a similar component in reports section, can't we used that shared component directly?

2022-11-21 19:19 UTC, Dimple16 requested changes

2022-11-21 19:19 UTC, Dimple16 commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
> +<ion-header>
@jayfyle any reason why we aren't using the shared component? or is it different?

2022-11-21 19:19 UTC, Dimple16 commented on src/assets/svg/right-arrow.svg
> +<svg width="9" height="13" viewBox="0 0 9 13" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
same as above

2022-11-22 04:31 UTC, Julias0 requested changes
Will review after Dimple and Yash

2022-11-22 05:25 UTC, jayfyle commented on src/app/fyle/my-expenses/add-txn-to-report-dialog/add-txn-to-report-dialog.component.html
> +<ion-header>
It is a different component we are using here, the other one I created was a modal while over here we are using a Mat Bottom Sheet, also the component here is already there. The only changes here are in the header section adding a close button and create report buttoin

2022-11-23 06:25 UTC, yksolanki9 approved these changes
Since you're updating the advances and right-arrow icon make sure things dont break in other places where it is used.
Minor comments

2022-11-23 06:25 UTC, yksolanki9 commented on src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
> +        (click)="taskCtaClicked(task.ctas[0])"
Can pass the task here and get the cta in ts

2022-11-23 06:25 UTC, yksolanki9 commented on src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
> +            <ion-col size="11" *ngFor="let cta of task.ctas" class="task--cta">
Should make it an object instead of an array since every task has only one cta?

2022-11-23 08:35 UTC, jayfyle commented on src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
> +            <ion-col size="11" *ngFor="let cta of task.ctas" class="task--cta">
I can, but all ctas are returned in a similar fashion from tasks.service, in the form of an array

2022-11-23 10:43 UTC, Dimple16 approved these changes

2022-11-23 10:43 UTC, Dimple16 commented on src/assets/svg/advances.svg
> +<svg viewBox="0 0 22 22"  fill="none" xmlns="http://www.w3.org/2000/svg">
remove extra spacing

2022-11-23 13:27 UTC, yksolanki9 commented on src/app/fyle/dashboard/tasks/tasks-card/tasks-card.component.html
> +            <ion-col size="11" *ngFor="let cta of task.ctas" class="task--cta">
Yes ik, but they were returned as an array since some tasks had more than one cta. Now since we have only one cta for all tasks, we can pass the object directly

2022-11-23 13:29 UTC, yksolanki9 approved these changes

2022-11-24 07:09 UTC, Julias0 approved these changes

2022-11-24 07:10 UTC, merged