Code Coverage: Status Service
fylein/fyle-mobile-app pull request #1498
Opened 2022-11-17 06:34 UTC by jayfyle

## Status Service Code Coverage Report:

![code-coverage-service](https://user-images.githubusercontent.com/115472256/202373304-50897c70-1e3f-4e6e-8327-9591a859665e.png)

Edit 1: Unit test for status map and find all comments function added

Edit 2: Unit test for post and find latest comment function added, covering all functions in the service

2022-11-18 05:35 UTC, Julias0 commented on src/app/core/test-data/status.service.spec.data.ts
> +    st: {
wait, I dont think we send the category and icon from the API response right? This is not a right sample of the API response

2022-11-21 19:29 UTC, Dimple16 requested changes
add the updated code coverage report screenshot, the current one doesn't have 100% coverage, else, you can add the test cases and raise PR again

2022-11-21 19:29 UTC, Dimple16 commented on src/app/core/test-data/status.service.spec.data.ts
> +export const updateResponseWithSt: ExtendedStatus[] = [
`updateReponseWithFlattenedEStatus`

2022-11-21 19:29 UTC, Dimple16 commented on src/app/core/test-data/status.service.spec.data.ts
> +export const apiResponse: ExtendedStatus[] = [
rename this to `getEStatusApiResponse`

2022-11-21 19:29 UTC, Dimple16 commented on src/app/core/test-data/status.service.spec.data.ts
> +    st: {
we can remove the `st:` from here since this is not passed by the client, we just use it in the client for our grouping, this isn't stored in the backend

2022-11-22 04:34 UTC, Julias0 requested changes
1 minor comment

2022-12-09 13:25 UTC, Dimple16 approved these changes

2023-04-28 07:41 UTC, closed without merging