Remove LD flag for payment_mode_config
fylein/fyle-mobile-app pull request #1502
Opened 2022-11-18 05:30 UTC by arjunaj5

2022-11-21 06:03 UTC, gokulk16 approved these changes

2022-11-21 06:15 UTC, yksolanki9 requested changes

2022-11-21 06:15 UTC, yksolanki9 commented on src/app/core/services/payment-modes.service.ts
>      return forkJoin({
forkJoin is not needed here

2022-11-21 06:15 UTC, yksolanki9 commented on src/app/core/services/launch-darkly.service.ts
> -  checkIfPaymentModeConfigurationsIsEnabled(): Observable<boolean> {
This method is being used in many places, you need to remove it from everywhere

2022-11-21 06:21 UTC, arjunaj5 commented on src/app/core/services/launch-darkly.service.ts
> -  checkIfPaymentModeConfigurationsIsEnabled(): Observable<boolean> {
There is one more method in `PaymentModesService` with the same name, It is being used in other places. 
This method was used only by `PaymentModesService.checkIfPaymentModeConfigurationsIsEnabled()` which is removed in this PR

2022-11-29 06:04 UTC, arjunaj5 commented on src/app/core/services/payment-modes.service.ts
>      return forkJoin({
fixed it

2022-11-30 05:31 UTC, yksolanki9 approved these changes
Please test this with and without the PMS setting enabled before merging

2022-12-03 06:53 UTC, merged