Org And Name Area Clickable
fylein/fyle-mobile-app pull request #1505
Opened 2022-11-21 06:13 UTC by jayfyle

## Menu Click To Profile Fix
![App_menu](https://user-images.githubusercontent.com/115472256/202977896-714805c9-d03e-4ea4-a31a-abf802a1f2e4.png)

Now clicking on the name of the user on top of the menu will take the user to the profile page.

2022-11-21 06:19 UTC, yksolanki9 requested changes
Add ripple effect for the click so that the user understands that some action is happening on the click and attach a recording of the same

2022-11-21 06:20 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.ts
> +  onClickProfile() {
Redirection should happen from the parent component, emit an event on click and Output it to the parent component

2022-11-21 06:21 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.ts
> +  onClickProfile() {
This is a presentational component - https://blog.angular-university.io/angular-2-smart-components-vs-presentation-components-whats-the-difference-when-to-use-each-and-why/

2022-11-21 08:48 UTC, yksolanki9 requested changes
Add ripple effect as discussed

2022-11-21 19:10 UTC, Dimple16 requested changes

2022-11-21 19:10 UTC, Dimple16 commented on src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.html
> +    <div matRipple [matRippleColor]="'rgba(255, 255, 255, 0.3)'" (click)="onClickProfile($event)">
why do we need the matRippleColor here? is this by design?

2022-11-21 19:10 UTC, Dimple16 commented on src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.ts
> +  @Output() profileClick = new EventEmitter();
`profileClicked`?

2022-11-21 19:10 UTC, Dimple16 commented on src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.ts
> +  onClickProfile(event: Event) {
`onProfileClick`?

2022-11-21 19:10 UTC, Dimple16 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +  goToProfile(event) {
event type?

2022-11-23 10:41 UTC, Dimple16 approved these changes

2022-11-23 13:30 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu-header/sidemenu-header.component.html
> +    <div matRipple [matRippleColor]="'rgba(255, 255, 255, 0.3)'" (click)="onProfileClicked($event)">
`matRippleColor="rgba(255, 255, 255, 0.3)"`

2022-11-23 13:32 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +    if (event.isTrusted) {
Can skip this check

2022-11-23 13:34 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +  goToProfile(event: Event) {
`goToProfilePage` - to make it more evident that we're navigating to another page

2022-11-23 13:35 UTC, yksolanki9 approved these changes
Left some minor comments

2022-11-23 13:49 UTC, merged