#mission_nps_mobile_40: Fix view report page not updating after adding expenses to report
fylein/fyle-mobile-app pull request #1511
Opened 2022-11-23 14:38 UTC by yksolanki9

Fixes:
- When adding expense to report, the expenses inside report were not updated
- After adding expense to report, the unreported expenses modal is not updated which results in 400 errors
- Removed unnecessary logic and did some refactoring

UI Preview:
https://user-images.githubusercontent.com/39493102/203567708-372e1ad6-f3ff-4849-8300-936c6092eeab.mov

2022-11-29 06:46 UTC, Dimple16 approved these changes

2022-11-29 12:03 UTC, Julias0 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      switchMap(() => this.loaderService.showLoader()),
why use a switchMap here?

2022-11-29 12:03 UTC, Julias0 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      tap(() => from(this.loaderService.hideLoader())),
This should be done in finalize. Otherwise this will not get executed if the API call fails

2022-11-29 12:04 UTC, Julias0 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +        setTimeout(() => (this.ionSegment.value = 'comments'), 0);
Why is this change required?

2022-11-29 12:05 UTC, Julias0 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      tap(() => from(this.loaderService.hideLoader())),
This should be inside finalize.

2022-11-29 12:05 UTC, Julias0 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      tap(() => (this.isExpensesLoading = false))
This should be inside finalize.

2022-11-29 12:07 UTC, Julias0 requested changes
minor comments

2022-11-30 05:44 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +        setTimeout(() => (this.ionSegment.value = 'comments'), 0);
If I remove this, there's an error - `Reading value of undefined`. There's only one ngIf in the parent element where we use the async pipe for `erpt$`.
So, this is probably bc the value was emitted but the child elements have not been added to the DOM yet. Adding setTimeout fixes it.

2022-11-30 05:45 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +        setTimeout(() => (this.ionSegment.value = 'comments'), 0);
Let me know if you have something else in mind

2022-11-30 05:46 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      tap(() => from(this.loaderService.hideLoader())),
`finalize` is called only when the source observable completes, but here, `loadReportDetails$` is a BehaviourSubject which'll emit a new value everytime there's an update

2022-11-30 05:47 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      tap(() => (this.isExpensesLoading = false))
`finalize` is called only when the source observable completes, but here, `loadReportTxns$` is a BehaviourSubject which'll emit a new value everytime there's an update

2022-11-30 05:51 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      switchMap(() => this.loaderService.showLoader()),
Fixed

2022-12-02 12:50 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      tap(() => (this.isExpensesLoading = false))
Fixed as discussed

2022-12-02 12:50 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +      tap(() => from(this.loaderService.hideLoader())),
Fixed as discussed

2022-12-05 06:20 UTC, Julias0 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +        setTimeout(() => (this.ionSegment.value = 'comments'), 0);
cant we just set value as a input type property and set it via a variable? Why do we need to do this viewChild stuff?

<ion-segment [value]="selectedSegment" >

2022-12-05 06:20 UTC, Julias0 requested changes
1 comment

2022-12-07 07:07 UTC, Julias0 approved these changes

2022-12-14 06:57 UTC, closed without merging