Code Coverage: Custom-Inputs Service
fylein/fyle-mobile-app pull request #1512
Opened 2022-11-29 14:46 UTC by jayfyle

## Code coverage for Custom Inputs Service
![custom-inputs-service-coverage-1](https://user-images.githubusercontent.com/115472256/204559960-c6ca1689-deff-4ee4-8545-d552e1d4631a.png)

### Edit 1: Code coverage is almost complete except branch, which stands at 90.9%

2022-11-30 12:01 UTC, Dimple16 requested changes
add param and return types for all methods in the service, will check the rest in next review

2022-12-07 06:29 UTC, Julias0 requested changes
Have added a few comments

2022-12-07 06:29 UTC, Julias0 commented on src/app/core/models/v1/expense-field.model.ts
> +  created_at: Date | string;
We should have date as Date object only inside the application. The string format is a bug

2022-12-07 06:29 UTC, Julias0 commented on src/app/core/models/v1/user-details.model.ts
> +  cluster_domain: string[] | string;
In what case will cluster domain be an array? What are we receiving from the API call? We shouldn't have mixed datatypes in the model

2022-12-07 06:29 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +    const result = customInputsService.filterByCategory(apiResponse, orgId);
the second argument is a category id, why are we passing a org id there?

2022-12-09 09:28 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      switchMap((categoryId: string | number) =>
@jayfyle why does this have a mixed datatype?

2022-12-09 09:30 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.ts
> +    from(this.authService.getEou())
Is this testing code? If yes, lets remove this @jayfyle

2022-12-09 09:32 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.ts
> +  fillCustomProperties(orgCategoryId: number, customProperties, active: boolean): Observable<CustomField[]> {
Cant we add a datatype to `customProperties`

2022-12-09 09:33 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +      options: ['asdf', 'asdfa'],
lets add some realistic values here instead of random strings @jayfyle

2022-12-09 09:33 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +      options: ['asdf', 'asdfa'],
Same comment as above for all the option cases

2022-12-09 09:35 UTC, Julias0 requested changes
Minor comments

2022-12-09 09:35 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +  it('should get custom property to be displayed | TEXT', () => {
should get proper empty value custom property of type TEXT to be displayed when value is not present

Use same structure for the rest of case where you are checking for the empty case

2022-12-09 11:33 UTC, jayfyle commented on src/app/core/services/custom-inputs.service.spec.ts
> +      options: ['asdf', 'asdfa'],
![some_values_from_backend](https://user-images.githubusercontent.com/115472256/206691613-94780d3b-a063-40fb-b272-0f327bf1b819.png)

These values are from the backend, I have checked multiple orgs as well.

2022-12-09 11:37 UTC, jayfyle commented on src/app/core/services/custom-inputs.service.spec.ts
> +  it('should get custom property to be displayed | TEXT', () => {
Actually components where the function is being called, they expect a string value, so should I change it to a customProperty model object with proper empty case or send a string indicating an empty response like "no value added" etc?

2022-12-09 13:32 UTC, Dimple16 commented on src/app/core/services/custom-inputs.service.spec.ts
> +      options: ['asdf', 'asdfa'],
@jayfyle use another org, staging loaded org has such data, 
you can use Fyle staging org with my email,

2022-12-09 13:33 UTC, Dimple16 commented on src/app/core/services/custom-inputs.service.spec.ts
> +      options: ['asdf', 'asdfa'],
@jayfyle you can also create new custom fields from the web app and add proper values if that's easier for you

2022-12-09 13:37 UTC, Dimple16 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      switchMap((categoryId: any) =>
can you check this again?
if you check the codebase it shows 
`(parameter) categoryId: string | {}`, verify once

2022-12-09 15:32 UTC, jayfyle commented on src/app/core/services/custom-inputs.service.spec.ts
> +      options: ['asdf', 'asdfa'],
![SOME_MORE_DATA_FROM_BACKEND](https://user-images.githubusercontent.com/115472256/206736278-24cc760e-0e09-4e8c-8a5c-e284e2ad707b.png)
I am still getting such data using Fyle Staging, although I have changed a few test case params. Also, I am seeing most value properties to have empty string or null values, but functions in the service rely on value property to be present in order to perform any actions. Else they return default values.

2022-12-13 06:03 UTC, Julias0 commented on src/app/core/models/custom-properties.model.ts
> +  value: any;
We shouldnt use `any` inside a model definition

2022-12-13 06:05 UTC, Julias0 requested changes
Added comment

2022-12-14 06:02 UTC, Julias0 commented on src/app/core/models/custom-properties.model.ts
> +export interface CustomProperty {
```typescript
export interface CustomProperty<T> {
name: string;
value: T;
}

```

2022-12-14 06:03 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
>        startWith({}),
startWith(null),

2022-12-14 06:05 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
>        startWith({}),
startWith(null),

2022-12-14 06:05 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      switchMap((categoryId: string | {}) =>
switchMap((categoryId: string) =>

2022-12-14 06:06 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.ts
> +        displayValue = customProperty.value.display ? customProperty.value.display : '-';
customProperty.value.display || '_';

Reduce to this expression

2022-12-14 06:15 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +    const result = customInputsService.filterByCategory(filterTestData, orgId);
- Trim the data inside filterTestData and responseAfterAppliedFilter
 - orgId to be replaced with a orgCategoryId

2022-12-14 06:17 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +      value: 'record',
value should be something from options in case of select type field for this test case

2022-12-14 06:17 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +      options: ['value1', 'value2'],
option property should probably be `null` in case of text type fields

2022-12-14 06:18 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +      options: ['record1', 'record2'],
option property should probably be `null` in case of text type fields

2022-12-14 06:18 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +      options: ['record1', 'record2'],
option property should probably be `null` in case of text type fields

2022-12-14 06:20 UTC, Julias0 requested changes
Added comments

2022-12-16 05:40 UTC, Julias0 requested changes
Some comments are not taken care of here

2022-12-19 06:29 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +      options: [],
add a few random emails

2022-12-19 06:30 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +      value: ['record1', 'record2'],
value needs to be a subset containing elements from options

2022-12-19 06:31 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.spec.ts
> +      value: 'value',
something to check

2022-12-19 06:31 UTC, Julias0 requested changes
Added some comments

2022-12-19 10:23 UTC, Julias0 approved these changes

2022-12-19 17:13 UTC, Dimple16 approved these changes

2022-12-19 17:15 UTC, merged