Auto Select Currency Bug
fylein/fyle-mobile-app pull request #1528
Opened 2022-12-05 14:36 UTC by jayfyle

# Most recent currency to be selected by default
## Clickup Link: https://app.clickup.com/t/2y36tpk
The most recent currency should be selected by default when filing an expense. The flow works correctly when filing manually, but does not work when capturing the receipt and then filling the expense form.

2022-12-09 09:20 UTC, yksolanki9 requested changes

2022-12-09 13:47 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                currency: recentCurrencies[0].shortCode,
We need to check for many cases here before setting the recent currency,
@jayfyle can you check this block of code?
```} else if (
            orgSettings.org_expense_form_autofills &&
            orgSettings.org_expense_form_autofills.allowed &&
            orgSettings.org_expense_form_autofills.enabled &&
            orgUserSettings.expense_form_autofills.allowed &&
            orgUserSettings.expense_form_autofills.enabled &&
            recentValue &&
            recentValue.recent_currencies &&
            recentValue.recent_currencies.length > 0
          ) {
            etxn.tx.currency = recentValue.recent_currencies[0];
            this.presetCurrency = recentValue.recent_currencies[0];
          } 
```

2022-12-09 13:51 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                currency: recentCurrencies[0].shortCode,
the above code will break for
- the edit expense case, 
- data extraction case, 
- for orgs with auto-fills disabled, 
- for orgs with recently_used.recent_currencies is null

@jayfyle make sure you handle and test all the above

2022-12-12 16:51 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          const isAutofillsEnabled =
Use optional chaining

2022-12-13 07:31 UTC, jayfyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            if (isAutofillsEnabled && recentCurrencies) {
I tried using else if but then the fix doesn't work, since the code to change currency is under the if condition checking for `etxn.tx.amount && etxn.tx.currency`, the currency does not change and stays the same as extracted or home currency

2022-12-13 07:32 UTC, jayfyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>            } else if (etxn.tx.user_amount && isNumber(etxn.tx.policy_amount) && etxn.tx.policy_amount < 0.0001) {
I have tested it for creating new expenses and editing existing ones, although I haven't seen any unexpected behaviour, will check again thoroughly before merging

2022-12-13 08:34 UTC, Julias0 requested changes
1 important comment

2022-12-14 15:18 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>            } else if (etxn.tx.user_amount && isNumber(etxn.tx.policy_amount) && etxn.tx.policy_amount < 0.0001) {
Okay, but any reason for moving it here?

2022-12-14 15:20 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            if (isAutofillsEnabled && recentCurrencies) {
> I tried using else if but then the fix doesn't work,
If it doesnt work, it means that you're patching some value and then overwriting it, so there is some problem in the condition. We can check this on a call tmrw if needed

2022-12-15 05:45 UTC, jayfyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>            } else if (etxn.tx.user_amount && isNumber(etxn.tx.policy_amount) && etxn.tx.policy_amount < 0.0001) {
Actually it is moved there as an else case if `recentCurrencies` is not present or is null. If it is not present it goes to the else block where it will fall back to `homeCurrency`, hence the flow will move as it was previously.

2022-12-15 08:02 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            if (isAutofillsEnabled && recentCurrencies) {
This comment is not resolved^

2022-12-15 12:01 UTC, yksolanki9 requested changes
All comments not resolved

2022-12-20 07:15 UTC, closed without merging