Code Coverage: Projects Service
fylein/fyle-mobile-app pull request #1532
Opened 2022-12-08 10:54 UTC by jayfyle

## Edit 1: Code coverage now 100 across all measures.
![Code-Coverage-100-Service-Project](https://user-images.githubusercontent.com/115472256/206428856-725f02b7-1a87-42ab-9c5f-dd6700cc4286.png)

2022-12-13 06:57 UTC, Julias0 commented on src/app/core/services/projects.service.spec.ts
> +    const testProjectParams = {
can we extract this to a different file?

2022-12-13 06:57 UTC, Julias0 commented on src/app/core/services/projects.service.spec.ts
> +    const testProject = {
can we extract this to a different file?

2022-12-13 06:57 UTC, Julias0 commented on src/app/core/services/projects.service.spec.ts
> +    const testParams = [
can we extract this to a different file?

2022-12-13 06:58 UTC, Julias0 commented on src/app/core/services/projects.service.ts
> +  addActiveFilter(active: boolean, params: any) {
We should replace `any` with a proper data type

2022-12-13 06:58 UTC, Julias0 commented on src/app/core/services/projects.service.ts
> +  addOrgCategoryIdsFilter(orgCategoryIds: number[], params: any) {
We should replace `any` with a proper data type

2022-12-13 06:58 UTC, Julias0 commented on src/app/core/services/projects.service.ts
> +  addProjectIdsFilter(projectIds: number[], params: any) {
We should replace `any` with a proper data type

2022-12-13 06:58 UTC, Julias0 commented on src/app/core/services/projects.service.ts
> +  addNameSearchFilter(searchNameText: string, params: any) {
We should replace `any` with a proper data type

2022-12-13 07:04 UTC, Julias0 commented on src/app/core/services/projects.service.spec.ts
> +    result.subscribe((res) => {
we should check if the query params being generated inside this method is being done properly or not. Otherwise this test doesn't really do anything

2022-12-13 07:04 UTC, Julias0 requested changes
Added comments

2022-12-14 06:23 UTC, Julias0 requested changes
Added comment

2022-12-19 06:18 UTC, Julias0 commented on src/app/core/services/projects.service.spec.ts
> +    const result = projectService.getAllowedOrgCategoryIds(testProject, testActiveCategoryList);
data to be trimmed - unable to review the test case

2022-12-19 06:19 UTC, Julias0 commented on src/app/core/services/projects.service.spec.ts
> +  it('should get allowed organisation category IDs | Without project', () => {
should return whole category list if project passed is not present

2022-12-19 06:22 UTC, Julias0 commented on src/app/core/services/projects.service.spec.ts
> +  it('should get project count | with categoryID', (done) => {
should get project count restricted by a set of category ids

2022-12-19 06:23 UTC, Julias0 commented on src/app/core/services/projects.service.spec.ts
> +  it('should get project count | without category IDs', (done) => {
same as above

2022-12-19 06:23 UTC, Julias0 commented on src/app/core/services/projects.service.spec.ts
> +  it('should get project count | without category IDs', (done) => {
combine with the above one

2022-12-19 06:24 UTC, Julias0 requested changes
Added comments

2022-12-21 11:15 UTC, Julias0 approved these changes

2022-12-21 12:10 UTC, Dimple16 requested changes

2022-12-21 12:10 UTC, Dimple16 commented on src/app/core/models/v1/extended-project.model.ts
> +export interface ExtendedProjectV1 {
this is not extended no? should be projectv1, since this is API v1 resposne

2022-12-21 12:10 UTC, Dimple16 commented on src/app/core/services/projects.service.spec.ts
> +    const resWoParam = projectService.getProjectCount();
resWoParam - rename this with context, same for below, not readable friendly

2022-12-21 12:10 UTC, Dimple16 commented on src/app/core/services/projects.service.ts
> +  getAllActive(): Observable<ExtendedProjectV1[]> {
this will change

2022-12-21 12:10 UTC, Dimple16 commented on src/app/core/test-data/projects.spec.data.ts
> +export const testProject = {
`testProjectV2` else this is confusing

2022-12-21 12:10 UTC, Dimple16 commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.ts
> +  projects$: Observable<ExtendedProjectV1[]>;
this will change too

2022-12-22 09:28 UTC, Dimple16 approved these changes

2022-12-22 09:29 UTC, merged