Code Coverage : Per-Diem Service
fylein/fyle-mobile-app pull request #1568
Opened 2022-12-21 14:09 UTC by jayfyle

# Code Coverage For Per Diem Service
## Edit 1 : Code coverage at 100 across the board except for branch coverage

![per-diem-service_code_coverage](https://user-images.githubusercontent.com/115472256/208924734-7cae10bf-e101-45ec-b6e5-ae605b9aac12.png)

2022-12-28 08:34 UTC, Dimple16 requested changes

2022-12-29 14:58 UTC, jayfyle commented on src/app/core/services/per-diem.service.spec.ts
> +    orgUserSettingsService.get.and.returnValue(of(apiOrgUserSettings));
I don't think as the function returns the allowed per diems using the allowed per diems inside the org user settings

2022-12-29 14:58 UTC, jayfyle commented on src/app/core/services/per-diem.service.spec.ts
> +  it('should get all allowed per diems', (done) => {
Yes, we are checking for both the cases

2023-01-02 12:06 UTC, Dimple16 approved these changes

2023-01-05 07:06 UTC, Julias0 commented on src/app/core/services/per-diem.service.spec.ts
> +    result.subscribe((res) => {
we should also add assertions to check if 
`this.spenderPlatformApiService
      .get` is being called the proper number of times and with proper assertions

2023-01-05 07:07 UTC, Julias0 commented on src/app/core/services/per-diem.service.spec.ts
> +    spenderPlatformApiService.get.and.returnValue(of(apiCountResponse));
The count response is `count: 57` and the `spenderPlatformApiService.get` is mocked to return 2 counts of data. The data for this test case is incorrect na

2023-01-05 07:10 UTC, Julias0 commented on src/app/core/services/per-diem.service.spec.ts
> +    spenderPlatformApiService.get.and.returnValue(of(apiPerDiemRates));
You have mocked the same thing twice - the second one is overriding the first one. This doesn't test for a case where you have multiple pages of data.

Add a apiCount of 4 and the page side of 2, so that we can check if pulling all of the data is working properly. Also we need to check if `this.spenderPlatformApiService
      .get` is being called with the right arguments otherwise what are we even testing in this test case

2023-01-05 07:11 UTC, Julias0 commented on src/app/core/test-data/per-diem.service.spec.data.ts
> +export const allPerDiemRatesParam = [
why is this named param? This is response data right?

2023-01-05 07:13 UTC, Julias0 commented on src/app/core/services/per-diem.service.spec.ts
> +    orgUserSettingsService.get.and.returnValue(of(null));
I dont think there will be a case where org_user_settings will even be null. The type safety is probably wrongly added for this

2023-01-05 07:22 UTC, Julias0 requested changes
Important comments

2023-01-10 05:43 UTC, Julias0 commented on src/app/core/services/per-diem.service.spec.ts
> +    spenderPlatformApiService.get.and.returnValue(of(apiPerDiem));
dont we need to mock the responses by call? Otherwise this is returning the same value in each call. 
Example - 
apiPerDiem in the count call gives 3 in count.
But in the  expectedPerDiemRates you are having 6 values which would never be the case

2023-01-11 07:40 UTC, Dimple16 commented on src/app/core/test-data/per-diem.service.spec.data.ts
> +export const allPerDiemRatesParam = [
this is used as param for the method `getAllowedPerDiemRates()`, 
we pass the list of per diem rates and filter the allowed ones

2023-01-11 07:55 UTC, Dimple16 approved these changes

2023-01-13 15:22 UTC, Julias0 approved these changes

2023-01-16 05:39 UTC, merged