fixes for the sentry issues
fylein/fyle-mobile-app pull request #1575
Opened 2023-01-02 12:52 UTC by yashfalke77

Clickup Task: https://app.clickup.com/t/85zrh6cgx
Sentry issues thats been fixed:
1) https://sentry.io/organizations/fyle-technologies-private-limi/issues/3840499445/?project=5622998&referrer=release-issue-stream
2) https://sentry.io/organizations/fyle-technologies-private-limi/issues/3836338631/?project=5622998&referrer=release-issue-stream

2023-01-02 13:00 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.ts
> +    if (this.orgs?.length === 1) {
Why do we still need this?

2023-01-02 13:01 UTC, yksolanki9 requested changes

2023-01-02 13:01 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.ts
> +    forkJoin([eou$, this.orgs$]).subscribe(async (result) => {
Use object instead of array

2023-01-02 13:02 UTC, yksolanki9 reviewed
https://sentry.io/organizations/fyle-technologies-private-limi/issues/3840499445/?project=5622998&referrer=release-issue-stream

How is this issue fixed?

2023-01-02 13:10 UTC, Dimple16 requested changes

2023-01-02 13:10 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +      this.handleDismissPopup(data?.action, email, orgId);
shouldn't the method `handleDismissPopup` be called if `data` is present? 
or, are you handling the null case separately?

2023-01-02 13:10 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +      this.orgs = result[1];
why are we resetting `this.orgs` here?

2023-01-02 14:09 UTC, yashfalke77 commented on src/app/auth/switch-org/switch-org.page.ts
> +    if (this.orgs?.length === 1) {
now we are refetching the orgs info when the pop up of org not verified is displayed to user. But there can be a case that due to user network connection this can also fails, for the safety point of added this

2023-01-02 14:09 UTC, yashfalke77 commented on src/app/auth/switch-org/switch-org.page.ts
> +    forkJoin([eou$, this.orgs$]).subscribe(async (result) => {
ok

2023-01-02 14:10 UTC, yashfalke77 commented on src/app/auth/switch-org/switch-org.page.ts
> +      this.handleDismissPopup(data?.action, email, orgId);
handling it in handleDismissPopup function if the data is undefined or null, it will have the default parameter

2023-01-02 14:18 UTC, yashfalke77 commented on src/app/auth/switch-org/switch-org.page.ts
> +      this.orgs = result[1];
Yes, the problem was due to users network issue  the orgs were not setted up,due to which value of this.orgs was undefined, so to solve this when the user not verified for particular org  popup is displayed we will again fetch it and reset the `this.orgs`

2023-01-02 14:21 UTC, yashfalke77 commented
> https://sentry.io/organizations/fyle-technologies-private-limi/issues/3840499445/?project=5622998&referrer=release-issue-stream
> 
> How is this issue fixed?

Due to network issue , we were not able get the this.orgs from api call, to solve this whenever the dialogue is displayed we will refetch the org through the api call, even if this fails we are applying safety `?` in `this.orgs?.length`

2023-01-03 05:41 UTC, yksolanki9 requested changes

2023-01-03 05:41 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.ts
> +    if (this.orgs?.length === 1) {
Rephrasing: Why do we need a class member var? We're already getting orgs from the forkjoin, pass it inside the method and we're gtg

2023-01-03 05:41 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.ts
> +      this.orgs = orgs;
Not needed

2023-01-03 08:45 UTC, yashfalke77 commented on src/app/auth/switch-org/switch-org.page.ts
> +      this.orgs = orgs;
ok

2023-01-03 12:49 UTC, yksolanki9 approved these changes

2023-01-03 12:50 UTC, yksolanki9 reviewed
Minor: Remove the unused `orgs` member variable

2023-01-04 05:43 UTC, Dimple16 approved these changes

2023-01-04 05:53 UTC, merged