Code coverage:  Org user service - changes 3&4
fylein/fyle-mobile-app pull request #1584
Opened 2023-01-05 11:57 UTC by Dimple16

<img width="739" alt="Screenshot 2023-01-05 at 4 50 01 PM" src="https://user-images.githubusercontent.com/31147415/210775064-54da25de-e0d9-4e3d-b07e-a2154d34b70a.png">

2023-01-06 10:21 UTC, Julias0 commented on src/app/core/services/org-user.service.spec.ts
> +      'eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzI5MTcyMDAsImlzcyI6IkZ5bGVBcHAiLCJ1c2VyX2lkIjoidXNNakxpYm15ZTdzIiwib3JnX3VzZXJfaWQiOiJvdXJ3N0hpNG1tcE8iLCJvcmdfaWQiOiJvck5WdGhUbzJaeW8iLCJyb2xlcyI6IltcIkZZTEV
add a comment on what this token contains

2023-01-06 10:21 UTC, Julias0 commented on src/app/core/services/org-user.service.spec.ts
> +      'eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NzI5MTcxNTgsImlzcyI6IkZ5bGVBcHAiLCJ1c2VyX2lkIjoidXNCa0pEMVVtMTc0Iiwib3JnX3VzZXJfaWQiOiJvdTVxclBKYkdmV00iLCJvcmdfaWQiOiJvck5WdGhUbzJaeW8iLCJyb2xlcyI6IltcIkZZTEV
add a comment on what this token contains

2023-01-06 10:22 UTC, Julias0 commented on src/app/core/services/org-user.service.spec.ts
> +    orgUserService.isSwitchedToDelegator().then(async (res) => {
Why are the same tests done twice?

2023-01-06 10:23 UTC, Julias0 commented on src/app/core/services/org-user.service.spec.ts
> +    expect(apiV2Service.get).toHaveBeenCalledWith('/spender_employees', { params });
Move this inside the subscribe otherwise you may hit a race condition

2023-01-06 10:24 UTC, Julias0 commented on src/app/core/services/org-user.service.spec.ts
> +    orgUserService.getEmployeesBySearch(params).subscribe((res) => {
Move this to a different test.

2023-01-06 10:24 UTC, Julias0 commented on src/app/core/services/org-user.service.spec.ts
> +    expect(apiV2Service.get).toHaveBeenCalledWith('/spender_employees', { params });
Move this inside the subscribe otherwise this may lead to a race condition

2023-01-06 10:24 UTC, Julias0 requested changes
Added comments

2023-01-09 07:36 UTC, Dimple16 commented on src/app/core/services/org-user.service.spec.ts
> +    orgUserService.getEmployeesBySearch(params).subscribe((res) => {
we already have a different test for `getEmployeesByParams`, in the service `getEmployeesBySearch` method, calls the `getEmployeesByParams` to return the value, we need the extra method call for `getEmployeesBySearch`

2023-01-10 06:03 UTC, Julias0 commented on src/app/core/services/org-user.service.spec.ts
> +    orgUserService.getEmployeesBySearch(params).subscribe((res) => {
The reason I am asking this is that this can cause a race condition - If this subscribe finishes first, the done method will be called and the test will be passed even though the other subscribe block may execute later and fail.

2023-01-10 07:46 UTC, Dimple16 commented on src/app/core/services/org-user.service.spec.ts
> +    orgUserService.getEmployeesBySearch(params).subscribe((res) => {
I've removed the extra subscribe block,

2023-01-10 07:55 UTC, Julias0 approved these changes

2023-01-10 08:05 UTC, merged