task 20d8kmq Create Expense: Mileage expense: Select location pop up.~ There should be some top spacing
fylein/fyle-mobile-app pull request #1587
Opened 2023-01-10 10:41 UTC by CODEX108

@Dimple16 
### Tried solving the bug:
#### I have increased the margin-top and given it as 12px which was 0 at first, here's the modified version.
<img src = "https://user-images.githubusercontent.com/82377810/211529506-dc735e1b-b013-4a61-8f00-3cf8a229cb1e.png" width=300 height=300>

2023-01-10 10:46 UTC, Dimple16 requested changes

2023-01-10 10:46 UTC, Dimple16 commented on src/global.scss
> +    padding-top: 12px;
this is a global change, this will impact all files using this class, you will have to change it specific to the location pop up

2023-01-10 10:50 UTC, CODEX108 commented on src/global.scss
> +    padding-top: 12px;
ok

2023-01-12 12:16 UTC, Dimple16 approved these changes

2023-01-12 12:23 UTC, merged