Added unit tests for select project
fylein/fyle-mobile-app pull request #1591
Opened 2023-01-11 11:56 UTC by Julias0

2023-01-12 08:51 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                        [touchedInParent]="fg.controls.project.touched"
This is required to avoid using injected NgControl inside the component. That was a pre-existing hack

2023-01-16 06:56 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                        [touchedInParent]="fg.controls.project.touched"
It is mandatory for the child to know the touched state of the parent form control because the markAllAsTouched we do when users click on save, doesn't propage through controls

2023-01-16 06:56 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                        [touchedInParent]="fg.controls.project.touched"
Same for valid

2023-01-30 08:49 UTC, rvab requested changes

2023-01-30 08:49 UTC, rvab commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +    await fixture.whenStable();
* Why use `fixture.whenStable()`? Is there any promise/setTimeout involved?
* Can we use `fakeAsync` instead of `async` and use `flushMicroTasks`?

2023-01-30 08:49 UTC, rvab commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +  let el: DebugElement;
`el` -> `element`

2023-01-30 08:49 UTC, rvab commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +        schemas: [CUSTOM_ELEMENTS_SCHEMA],
why is this required?

2023-01-30 08:49 UTC, rvab commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +    const callBackTestObject = jasmine.createSpyObj('touchedTested', ['touchedTested']);
is `touchedTested` a dummy callback function?

2023-01-30 08:49 UTC, rvab commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +    const project = {
Create a model and test data file for this and import it here.

2023-01-30 08:49 UTC, rvab commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                        [touchedInParent]="fg.controls.project.touched"
> This is required to avoid using injected NgControl inside the component. That was a pre-existing hack and that hack would cause getting code coverage in certain places impossible

Didn't understand the comment. Angular Material is using `ngControl`. https://github.com/angular/components/blob/main/src/material/input/input.ts. Why can't we use it?

2023-01-30 14:04 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                        [touchedInParent]="fg.controls.project.touched"
ngControl is not directly injected into this component. If you looked at the material component, the ngControl is directly injected. 
We cant directly inject NgControl into this component since it causes a circular dependency error, hence I added a hack to do it using injector. But dependency injection using injector makes this almost impossible to unit test.

Just removing this and replacing it with inputs makes it much much more easier to write the tests, circumventing the whole problem.

2023-01-30 14:07 UTC, Julias0 commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +        schemas: [CUSTOM_ELEMENTS_SCHEMA],
This is required to prevent ionic components which are being used in the template from throwing errors.

Ref: https://stackoverflow.com/questions/39428132/custom-elements-schema-added-to-ngmodule-schemas-still-showing-error

2023-01-30 14:15 UTC, Julias0 commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +    await fixture.whenStable();
Without fixture.whenStable(), the changes were not reflecting inside the DOM component value property which would cause the assertion to fail. My assumption is, the change detection needs some time for the ngModel value change to take effect.

The only async task here is waiting for the fixture to get stable. Since the async operation is not really inside the component, I feel fakeAsync/flushMicroTasks is overkill

2023-01-30 14:15 UTC, Julias0 commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +    const callBackTestObject = jasmine.createSpyObj('touchedTested', ['touchedTested']);
Yes. Basically I will check if this method has been called if the blur event gets triggered in the input field. This gives me a clean way to do this

2023-01-30 14:17 UTC, Julias0 commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +    const project = {
I find this easier to read rather than jumping between multiple files. This was meant to serve as an example to work off rather than be an actual PR I will merge in.

2023-01-31 07:15 UTC, rvab approved these changes

2024-04-19 05:17 UTC, closed without merging