Code Coverage: Dashboard Service #2
fylein/fyle-mobile-app pull request #1595
Opened 2023-01-12 12:58 UTC by jayfyle

# Subtask #3 to #5
![Dashboard_Service_code_coverage_94](https://user-images.githubusercontent.com/115472256/212056931-61018a73-05c7-408d-ab15-73130f9e693a.png)

2023-01-13 06:05 UTC, Dimple16 requested changes

2023-01-13 06:05 UTC, Dimple16 commented on src/app/core/test-data/dashboard.service.spec.data.ts
> +export const apiTransactionUnreportedStatsRes = [
please follow the new convention of adding mock data? 
you can add a new folder /mock-data inside the core and add files based on models

2023-01-13 06:05 UTC, Dimple16 commented on src/app/core/test-data/dashboard.service.spec.data.ts
> +export const apiTransactionUnreportedStatsRes = [
this whole file will change that way, I'll review once it is fixed

2023-01-13 09:48 UTC, Dimple16 requested changes
added comments

2023-01-13 09:48 UTC, Dimple16 commented on src/app/core/mock-data/dashboard-stats.data.ts
> +export const expectedUnreportedExpStats = {
don't we have a model for `DashboardStats`?
if not, please create one,
ideally, it should be:
```
export const expectedUnreportedExpStats: DashboardStats = {
  count: 6,
  sum: 16748.73,
};
```

2023-01-13 09:48 UTC, Dimple16 commented on src/app/core/mock-data/dashboard-stats.data.ts
> +export const expectedReportStats = {
this will be in another file then, since this object model type is different

2023-01-13 09:48 UTC, Dimple16 commented on src/app/core/mock-data/dashboard-stats.data.ts
> +export const expectedReportStats = {
let us define models for every type of mock data we use if they are missing

2023-01-13 09:48 UTC, Dimple16 commented on src/app/core/mock-data/stats-one-dimension.data.ts
> +export const apiTransactionUnreportedStatsRes = [
same comments for this file too

2023-01-13 09:48 UTC, Dimple16 commented on src/app/core/mock-data/stats-one-dimension.data.ts
> +export const apiTransactionUnreportedStatsRes = [
apiTransactionUnreportedStatsRes -> `apiTxnUnreportedStatsRes`

2023-01-13 09:48 UTC, Dimple16 commented on src/app/core/mock-data/stats-one-dimension.data.ts
> +export const apiTransactionIncompleteStatsRes = [
same comment for the this

2023-01-13 09:48 UTC, Dimple16 commented on src/app/core/mock-data/stats-response.data.ts
> +export const apiReportStatsRes = {
let us add model `ReportStats`

2023-01-13 09:48 UTC, Dimple16 commented on src/app/core/models/dashboard-stats.model.ts
> +export interface ReportDashboardStats {
keep this in a separate file

2023-01-13 09:48 UTC, Dimple16 commented on src/app/core/models/dashboard-stats.model.ts
> +export interface DashboardStats {
this can be just `Stats`?

2023-01-13 09:48 UTC, Dimple16 commented on src/app/core/models/dashboard-stats.model.ts
> +export interface ReportDashboardStats {
`ReportStats`?

2023-01-13 09:48 UTC, Dimple16 commented on src/app/fyle/dashboard/dashboard.service.spec.ts
> +  it('should get UNREPORTED expense stats', (done) => {
let us follow the new convention of naming this, 
```
it('getUnreportedExpensesStats(): should get UNREPORTED expense stats',
```

2023-01-13 09:48 UTC, Dimple16 commented on src/app/fyle/dashboard/dashboard.service.spec.ts
> +    const apiParams = {
this is repeated, can we define a model for the params and move it accordingly?

2023-01-13 09:48 UTC, Dimple16 commented on src/app/fyle/dashboard/dashboard.service.spec.ts
> +    reportService.getReportStats.and.returnValue(of(new StatsResponse(apiReportStatsRes)));
`new StatsResponse()` this won't be necessary here if we add the explicit type in the mock data file itself

2023-01-13 09:48 UTC, Dimple16 commented on src/app/fyle/dashboard/dashboard.service.spec.ts
> +      scalar: false,
add off these keys to the model too, we can use `Partial` and reuse the same model

2023-01-16 07:50 UTC, jayfyle commented on src/app/fyle/dashboard/dashboard.service.spec.ts
> +    reportService.getReportStats.and.returnValue(of(new StatsResponse(apiReportStatsRes)));
It is giving an error when I try to use an explicitly casted response data. I guess it is due to this type being declared as a class. Trying to figure it out.

2023-01-16 09:27 UTC, Dimple16 requested changes
added comments and few questions

2023-01-16 09:27 UTC, Dimple16 commented on src/app/core/mock-data/stats-dimension-response.data.ts
> +import { StatsDResponse } from '../models/stats-dimension-response.model';
In this, the dimension is always an empty list no? why is the `dimension` in naming then?

2023-01-16 09:27 UTC, Dimple16 commented on src/app/core/models/stats-dimension-response.model.ts
> +  dimensions: any;
this can be empty list or list of strings no?

2023-01-16 09:27 UTC, Dimple16 commented on src/app/core/models/v2/stats-response.model.ts
> +  getDatum?(index: number) {
why is this required?

2023-01-16 09:27 UTC, Dimple16 commented on src/app/core/models/v2/stats-response.model.ts
> +
remove extra lines

2023-01-16 09:27 UTC, Dimple16 commented on src/app/fyle/dashboard/dashboard.service.spec.ts
> +    reportService.getReportStats.and.returnValue(of(new StatsResponse(apiReportStatsRes)));
let's check this once? what's the error?

2023-01-16 10:29 UTC, Dimple16 requested changes

2023-01-16 10:29 UTC, Dimple16 commented on src/app/core/mock-data/dashboard-stats.data.ts
> +import { Stats } from '../models/dashboard-stats.model';
rename the file name

2023-01-16 10:29 UTC, Dimple16 commented on src/app/core/mock-data/stats-dimension-response.data.ts
> +import { StatsDResponse } from '../models/stats-dimension-response.model';
let's name it `statsDimensionResponse`?

2023-01-16 10:29 UTC, Dimple16 commented on src/app/core/models/stats-dimension-response.model.ts
> +  dimensions: any;
`[] || string[]`?

2023-01-16 11:11 UTC, Dimple16 approved these changes

2023-01-17 06:21 UTC, Julias0 approved these changes

2023-01-17 06:36 UTC, merged