Dependent fields poc with FormArray in parent expense form
fylein/fyle-mobile-app pull request #1602
Opened 2023-01-16 09:42 UTC by yksolanki9

2023-01-16 10:21 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  addDependentField(id: number) {
id will always be formArray.length -1 right. Do we need this as a parameter?

2023-01-16 10:22 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      fieldIndex: [formArray.length || 0],
Why do you need this inside the form?

2023-01-16 10:22 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    const formArray = this.fg.get('dependent_fields') as FormArray;
this.fg.controls. dependent_fields
This gives better intellisense support

2023-01-16 10:23 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    const updatedDependentField = (this.fg.get('dependent_fields') as FormArray).controls[data.fieldIndex] as FormGroup;
You should define getters and methods for these

2023-01-16 11:28 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  addDependentField(id: number) {
Nai, id is the dependent field field based on the value the user selects. Have renamed it

2023-01-16 11:30 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    const formArray = this.fg.get('dependent_fields') as FormArray;
Fixed

2023-01-24 04:44 UTC, Julias0 requested changes
Sending back because POC

2023-02-17 12:40 UTC, closed without merging