Code Coverage: Dashboard Service #3
fylein/fyle-mobile-app pull request #1607
Opened 2023-01-17 08:45 UTC by jayfyle

# Subtask #6
Almost 100% code coverage across the board, only a few branches left
![Almost_100_code_coverage_dashboard](https://user-images.githubusercontent.com/115472256/212850330-f693c91d-de7e-4ebf-9f23-8e707944ef6d.png)

2023-01-18 06:37 UTC, Dimple16 requested changes
added comments

2023-01-18 06:37 UTC, Dimple16 commented on src/app/core/mock-data/card-aggregate-stat.data.ts
> +  {
let's reduce this list to have 3 items?

2023-01-18 06:37 UTC, Dimple16 commented on src/app/core/mock-data/ccc-expense.details.data.ts
> +      aggregates: [
for any list, let's keep 2/3 items max

2023-01-18 06:37 UTC, Dimple16 commented on src/app/core/mock-data/extended-org-user.data.ts
> +    custom_field_values: [
keep 1/2 custom values to compare

2023-01-18 06:37 UTC, Dimple16 commented on src/app/core/mock-data/stats-response.data.ts
> +export const apiAssignedCardDetailsRes: StatsResponse = {
this data is huge too, you can reduce it

2023-01-18 06:37 UTC, Dimple16 commented on src/app/core/mock-data/stats.data.ts
> +  count: undefined,
is this to cover any branch? this will never be the result no? or should it be null?

2023-01-18 06:37 UTC, Dimple16 commented on src/app/core/mock-data/unique-cards-stats.data.ts
> +export const expectedUniqueCardStats: UniqueCardStats[] = [
reduce

2023-01-18 06:37 UTC, Dimple16 commented on src/app/core/mock-data/unique-cards.data.ts
> +  {
reduce

2023-01-18 06:37 UTC, Dimple16 commented on src/app/fyle/dashboard/dashboard.service.spec.ts
> +  it('getUnreportedExpensesStats():  should return null INCOMPLETE expense stats as api sends empty values as response', (done) => {
`should return empty`?

2023-01-18 07:28 UTC, jayfyle commented on src/app/core/mock-data/stats.data.ts
> +  count: undefined,
When there is no relevant data, the function sends undefined as values

2023-01-18 07:31 UTC, jayfyle commented on src/app/core/mock-data/stats.data.ts
> +  count: undefined,
It is used in branch coverage, for edge cases when the API does not send any data or the aggregate value be an empty list. In all such cases, the object returned has sum and count as undefined.

2023-01-19 10:05 UTC, Dimple16 approved these changes

2023-01-19 10:40 UTC, rvab requested changes

2023-01-19 10:40 UTC, rvab commented on src/app/fyle/dashboard/dashboard.service.spec.ts
> +      expect(transactionService.getTransactionStats).toHaveBeenCalledWith(
don't we have `toHaveBeenCalledTImes(number)` in jasmine?

2023-01-19 10:40 UTC, rvab commented on src/app/fyle/dashboard/dashboard.service.spec.ts
> +  it('getUnreportedExpensesStats(): should return empty or undefined UNREPORTED expense stats as api sends empty list for aggregates', (done) => {
Is the test description correct? is it `should return empty or undefined for UNREPORTED expense` or `should return empty or undefined UNREPORTED expense`?

2023-01-19 10:40 UTC, rvab commented on src/app/core/mock-data/stats-response.data.ts
>  type StatsResponse = {
Do we need a new `type`? Can this be done with `interface`?  Is this being used anywhere else?

2023-01-19 10:40 UTC, rvab commented on src/app/core/models/stats-dimension-response.model.ts
> +  aggregates?: {
Why make it optional?

2023-01-19 11:59 UTC, jayfyle commented on src/app/core/models/stats-dimension-response.model.ts
> +  aggregates?: {
I was trying to increase branch coverage, and certain branches required aggregates not being present. Hence I made it optional. Here's a screenshots for reference:

![branches_to_be_covered](https://user-images.githubusercontent.com/115472256/213433917-4ca9f835-e959-4ffc-ae58-bf206ba4d190.png)

![Still_remaining_branches](https://user-images.githubusercontent.com/115472256/213433358-ecde46a3-1cd3-4aa2-bf46-dd544bd6cca5.png)

2023-01-19 11:59 UTC, jayfyle commented on src/app/core/mock-data/stats-response.data.ts
>  type StatsResponse = {
The original type has been written as a class, so it was throwing errors while trying to explicitly cast it due to the member functions. To avoid initialising it the conventional way, I created an additional type of the same name and structure, only to cast the responses in the expected type. A similar implementation can be found in task service as well.

2023-01-19 11:59 UTC, jayfyle commented on src/app/fyle/dashboard/dashboard.service.spec.ts
> +  it('getUnreportedExpensesStats(): should return empty or undefined UNREPORTED expense stats as api sends empty list for aggregates', (done) => {
Sorry, my bad. It is a typo, meant to write the first one. I have fixed it for all such cases

2023-01-19 12:50 UTC, jayfyle commented on src/app/fyle/dashboard/dashboard.service.spec.ts
> +      expect(transactionService.getTransactionStats).toHaveBeenCalledWith(
Added it for all cases

2023-01-20 04:05 UTC, rvab approved these changes

2023-01-20 05:30 UTC, merged