Code Coverage: Report Service #2
fylein/fyle-mobile-app pull request #1612
Opened 2023-01-18 14:18 UTC by jayfyle

![Report_Service_1st_PR](https://user-images.githubusercontent.com/115472256/213194952-83642f3a-c896-4e61-b54b-f7142d6243ef.png)

2023-01-20 09:50 UTC, Dimple16 requested changes
added comments

2023-01-20 09:50 UTC, Dimple16 commented on src/app/core/mock-data/api-reports.data.ts
> +export const apiReportRes = {
what is the type of this response? can you add it accordingly?

2023-01-20 09:50 UTC, Dimple16 commented on src/app/core/mock-data/extended-org-user.data.ts
> +    joining_dt: '2017-07-25T00:00:00.000+0000',
any reason this is being removed? or, are we receiving a string here?

2023-01-20 09:50 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +  it('actions(): should get related actions for a report', (done) => {
`should get report actions`?

2023-01-23 10:21 UTC, Dimple16 requested changes

2023-01-23 10:21 UTC, Dimple16 commented on src/app/core/models/report.model.ts
>    approved_by?: any;
is `approved_by` of `User` type? check and fix

2023-01-23 10:21 UTC, Dimple16 commented on src/app/core/models/report.model.ts
>    ou_business_unit?: any;
this should be a string

2023-01-23 10:21 UTC, Dimple16 commented on src/app/core/models/report.model.ts
>    ou_business_unit?: any;
please fix the others too

2023-01-23 10:21 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +    const params = {
you can define this as `ReportParams` model

2023-01-23 12:25 UTC, Dimple16 requested changes

2023-01-23 12:25 UTC, Dimple16 commented on src/app/core/models/report.model.ts
>    ou_employee_id?: any;
shouldn't we change all keys with type `any`?

2023-01-24 17:40 UTC, rvab requested changes

2023-01-24 17:40 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +  function fixDates(res) {
* any reason for creating a new function?
* is this recommended?

2023-01-24 17:40 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +    getExtendedOrgUser();
Could you rename it to a different name? `mockExtendedOrgUser`?. When using `get`, ideally the function should return something

2023-01-24 17:40 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +    reportService.getMyReports(reportParams).subscribe((res) => {
`toHaveBeenCalledWith` and `toHaveBeenCalledTimes` for apiv2Service.get is missing

2023-01-24 17:40 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +    reportService.getMyReportsCount({}).subscribe((res) => {
* should mock the `getMyReports()` method instead of mocking `getExtendedOrgUser` and `getReports`
* `toHaveBeenCalledWith` and `toHaveBeenCalledTimes`?

2023-01-24 17:40 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(apiService.get).toHaveBeenCalledWith(`/reports/${reportID}/actions`);
`toHaveBeenCalledTimes`?

2023-01-24 17:40 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +    reportService.getExports(reportID).subscribe(() => {
* Does this API return an empty array?
* `toHaveBeenCalledTimes()`?

2023-01-24 17:40 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +    reportService.getReportETxnc(reportID, orgUserID).subscribe((res) => {
* `toHaveBeenCalledTimes`?
* Should be checking for a result, no?

2023-01-25 13:15 UTC, jayfyle commented on src/app/core/services/report.service.spec.ts
> +    reportService.getExports(reportID).subscribe(() => {
Yes, as of now the API is returning an empty array. I guess I might find some data, or would have to generate some. Most probably it returns the IDs that the report has been shared with. I have tried to find some data from multiple orgs but haven't got anything yet. I will try to get something and update the specs in the following PRs.

2023-01-25 13:15 UTC, jayfyle commented on src/app/core/services/report.service.spec.ts
> +  function fixDates(res) {
Had added this to convert the dates, but I was already doing it in the data file. So I guess this was not required, removing it. Thanks.

2023-01-25 13:27 UTC, jayfyle commented on src/app/core/models/api-reports.model.ts
> +export interface ApiReports {
This is from v2. Have added it in the name as well. I was trying to create a model for the API response, as `getMyReports` returns the API response as it is after modifying dates. So, in order to add a return type to the method, I had to write a new.

2023-01-27 12:01 UTC, rvab requested changes
Sending this back for now

2023-01-30 03:57 UTC, rvab approved these changes

2023-01-30 07:10 UTC, merged