Dependent Fields: Create new component for dependent field
fylein/fyle-mobile-app pull request #1618
Opened 2023-01-23 05:38 UTC by yksolanki9

2023-01-23 05:40 UTC, yksolanki9 commented on src/app/shared/components/dependent-field/dependent-field.component.ts
> +  get valid() {
Will remove this ngControl, getter and setter after creating the modal component and will use formControl for setting the value of this field instead of ngModel

2023-01-23 10:48 UTC, Julias0 commented on src/app/shared/components/dependent-field/dependent-field.component.html
> +      [placeholder]="!disabled ? placeholder || 'Select ' + label : ''"
why is placeholder linked to disabled

2023-01-23 10:50 UTC, Julias0 commented on src/app/shared/components/dependent-field/dependent-field.component.ts
> +  get valid() {
From the parent you can pass in the valid state and touched state as inputs which can be in turn used for this

2023-01-23 10:50 UTC, Julias0 commented on src/app/shared/components/dependent-field/dependent-field.component.html
> +  </div>
What about validation messages? Shouldnt we add them inside this? Or will they be added outside

2023-01-23 10:52 UTC, Julias0 requested changes
minor comments and questions

2023-01-23 11:08 UTC, yksolanki9 commented on src/app/shared/components/dependent-field/dependent-field.component.ts
> +  get valid() {
Okay, will handle it in the next PR as discussed

2023-01-23 11:18 UTC, yksolanki9 commented on src/app/shared/components/dependent-field/dependent-field.component.html
> +  </div>
Inititally, I thought of showing it from expense form, but since we're anyways passing the validation state to child, we can show this in the child.

2023-01-23 11:29 UTC, yksolanki9 commented on src/app/shared/components/dependent-field/dependent-field.component.html
> +  </div>
This is done

2023-01-24 04:45 UTC, Julias0 approved these changes

2023-02-17 12:00 UTC, merged