Dependent Fields: Create component for dependent field modal
fylein/fyle-mobile-app pull request #1620
Opened 2023-01-23 06:30 UTC by yksolanki9

2023-02-02 12:23 UTC, Julias0 commented on src/app/core/services/dependent-fields.service.ts
> +        expense_field_value: `=ilike.%${searchQuery}%`,
Do we need to add `=` in the value here? I think just ilike will be enough

2023-02-02 12:23 UTC, Julias0 commented on src/app/core/services/dependent-fields.service.ts
> +        parent_expense_field_value: parentFieldValue,
Dont you need to add `eq.` for the above ones

2023-02-02 12:24 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  onPageExit$ = new Subject();
This should be initialized in ionViewWillEnter and in ionViewWillLeave, we should emit the complete to this to also remove this from memory.

2023-02-02 12:25 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      .pipe(
Dont you need a distinctUnitChanged?

2023-02-02 12:26 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          this.dependentFieldControls.clear();
Does this remove the whole array?

2023-02-02 12:33 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  onDependentFieldChanged(data: {
Declare this method above the above method - this is because this method is used inside the above method

2023-02-02 12:34 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      value: [null, dependentField.mandatory && Validators.required],
if dependentField.mandatory is false, false will be passed as the 2nd value here. Lets use a ternary operator to make sure we pass null

2023-02-02 12:36 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      //Remove all dependent field controls after the changed one
extract into a utility method

2023-02-02 12:37 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.dependentFields.push({
why is this even needed - we have everything already inside the formgroup right

2023-02-02 12:40 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    return this.customInputs$.pipe(
Why do we need to get from customInput$? Saying this because customInputs$ is dependant on category and we don't want this field varying by category.

Also we should filter out `DEPENDENT_SELECT` from customInput$ since that isn't a normal custom input

2023-02-02 12:41 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              delay(1000),
Is this intentional or for testing? If for testing please to add a TODO

2023-02-02 12:53 UTC, Julias0 requested changes
Added comments

2023-02-03 06:33 UTC, yksolanki9 commented on src/app/core/services/dependent-fields.service.ts
> +        expense_field_value: `=ilike.%${searchQuery}%`,
My bad

2023-02-03 06:49 UTC, yksolanki9 commented on src/app/core/services/dependent-fields.service.ts
> +        parent_expense_field_value: parentFieldValue,
Done

2023-02-03 06:53 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  onPageExit$ = new Subject();
Done

2023-02-03 06:55 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          this.dependentFieldControls.clear();
Yes, when the project changes, we remove all the controls from UI and formArray. A new dependent field will be created only if the selected project has valid values for the dependent field.

2023-02-03 06:58 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              delay(1000),
This is for testing shimmers, have added a TODO

2023-02-03 07:01 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      value: [null, dependentField.mandatory && Validators.required],
Done

2023-02-03 07:03 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  onDependentFieldChanged(data: {
Done

2023-02-03 09:20 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    return this.customInputs$.pipe(
Done

2023-02-03 09:20 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.dependentFields.push({
Discussed in call

2023-02-03 09:22 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      .pipe(
Added

2023-02-03 09:31 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      //Remove all dependent field controls after the changed one
Done

2023-02-03 09:33 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          this.dependentFieldControls.clear();
Discussed in call

2023-02-03 10:35 UTC, Julias0 approved these changes

2023-02-17 11:58 UTC, merged