FYLE-85zrjffnh: Transaction service - subtask-4
fylein/fyle-mobile-app pull request #1623
Opened 2023-01-23 15:56 UTC by Dimple16

### Code coverage - 20.62%
![Screenshot 2023-01-23 at 9 25 09 PM](https://user-images.githubusercontent.com/31147415/214086110-b15bb6e6-87af-484e-b737-325688b0eb47.png)

2023-01-24 05:03 UTC, rvab commented on src/app/core/mock-data/expense.data.ts
> +  tx_currency: 'INR',
use `USD` currency

2023-01-24 05:04 UTC, rvab commented on src/app/core/mock-data/expense.data.ts
> +  ou_location: 'INdia',
is it correct?

2023-01-24 07:23 UTC, rvab requested changes
Didn't understand why you're using `Partial` everywhere.

2023-01-24 07:23 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +      expect(transactionService.getIsDraft(expenseData1)).toBeTrue();
`toBeTrue()` is nice. Jest doesn't have it. :(

2023-01-24 12:41 UTC, Dimple16 commented on src/app/core/models/expense.model.ts
> +  tx_duplicates?: string[];
These are optional transaction keys

2023-01-24 12:41 UTC, Dimple16 commented on src/app/core/models/v1/transaction.model.ts
> +  corporate_credit_card_expense_group_id?: string;
optional transaction keys

2023-01-24 12:44 UTC, Dimple16 commented on src/app/core/mock-data/expense.data.ts
> +  ou_location: 'INdia',
this is fixed, staging has bad data

2023-01-24 12:44 UTC, Dimple16 commented on src/app/core/mock-data/expense.data.ts
> +  tx_currency: 'INR',
fixed currency to be `USD` everywhere

2023-01-24 12:45 UTC, Dimple16 commented on src/app/core/mock-data/expense.data.ts
> +        "'-102717':57 '1':42 '111':9 '20210809':56 '5':53 '899':1 '899.00':2 'a':15,21,27,33 'abcdfeiapcalp':43,44,45,46,47 'abhishek':39 'ajain@fyle.in':41 'ana':12 'approver':4 'aus':55 'board':50
yes, since this is a part of response, added the same here

2023-01-24 12:45 UTC, Dimple16 commented on src/app/core/models/undo-merge.model.ts
> +  auto_created_expense: Partial<Transaction>;
this is fixed

2023-01-24 12:45 UTC, Dimple16 commented on src/app/core/services/transaction.service.spec.ts
> +      expect(res).toBeFalsy();
this is fixed

2023-01-25 05:54 UTC, Julias0 commented on src/app/core/services/transaction.service.spec.ts
> +    transactionService.clearCache().subscribe((res) => {
```typescript
const spyObj = jasmine.createSpyObj('mockObj', ['callback']);

transactionsCacheBuster$.subscribe(spyObj.callback);

transactionService.clearCache().subscribe((res) => {
  expect(spyObj.callback).toHaveBeenCalled();
  expect(res).toBeNull();
  done();
});
```
The above test case is not testing for the behaviour of notifying the cachebuster subject. We need to check if that observable is being triggered or not.

The above code is written of the top of my head, so you might need to fix the syntax. This is also done in another place - I will paste a link in a while

2023-01-25 06:02 UTC, Julias0 commented on src/app/core/services/transaction.service.spec.ts
> +      expect(apiV2Service.get).toHaveBeenCalledWith('/expenses', {
expect(apiV2Service.get).toHaveBeenCalledWith('/expenses', params);

The spread into the empty object will be the same as the object

2023-01-25 06:03 UTC, Julias0 commented on src/app/core/services/transaction.service.spec.ts
> +    storageService.get.and.returnValue(new Promise((resolve) => resolve(defaultVehicleType)));
You can use Promise.resolve directly

2023-01-25 06:11 UTC, abhishek1234321 requested changes

2023-01-25 09:57 UTC, Dimple16 commented on src/app/core/services/transaction.service.spec.ts
> +    storageService.get.and.returnValue(new Promise((resolve) => resolve(defaultVehicleType)));
this is fixed

2023-01-25 09:58 UTC, Dimple16 commented on src/app/core/services/transaction.service.spec.ts
> +      expect(apiV2Service.get).toHaveBeenCalledWith('/expenses', {
this is fixed

2023-01-25 09:58 UTC, Dimple16 commented on src/app/core/models/expense.model.ts
> +  tx_activity_policy_pending?: boolean;
discussed offline

2023-01-25 11:23 UTC, Dimple16 commented on src/app/core/services/transaction.service.spec.ts
> +    transactionService.clearCache().subscribe((res) => {
added for this method

2023-01-25 11:23 UTC, Dimple16 commented on src/app/core/services/transaction.service.spec.ts
> +  it('manualFlag(): should manually flag a transaction', (done) => {
discussed offline

2023-01-25 11:24 UTC, abhishek1234321 approved these changes

2023-01-25 11:26 UTC, merged