FYLE-85zrjffp2: Code coverage - Transaction service - subtask5 - 50%
fylein/fyle-mobile-app pull request #1629
Opened 2023-01-24 15:09 UTC by Dimple16

2023-01-30 11:36 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> +  getMyExpensesCount(queryParams: EtxnParams): Observable<number> {
removed default empty object since this case never occurs

2023-01-30 11:38 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> +      newQueryParamsCopy = this.generateCustomDateParams(newQueryParamsCopy, filters);
there was a bug in production where the date filter didn't get applied properly which I noticed while adding the unit test case, fixed the issue here

2023-01-30 13:21 UTC, rvab requested changes

2023-01-30 13:21 UTC, rvab commented on src/app/core/mock-data/extended-org-user.data.ts
> +    currency: 'INR',
`USD`

2023-01-30 13:21 UTC, rvab commented on src/app/core/mock-data/expense-v2.data.ts
> +      tx_currency: 'INR',
`USD`

2023-01-30 13:21 UTC, rvab commented on src/app/core/mock-data/expense.data.ts
> +  tx_categoryDisplayName: 'Groceries',
iirc, this is not part of the API response. Could you check if there's a different way to do it?

2023-01-30 13:21 UTC, rvab commented on src/app/core/mock-data/expense.data.ts
> +export const expenseDataWithDateString = {
Please add type

2023-01-30 13:21 UTC, rvab commented on src/app/core/mock-data/expense.data.ts
> +  tx_duplicates: [
Are we still using this? I thought this was removed.

2023-01-30 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +      done();
`done` may not be required. Please check the examples here. https://www.piotrl.net/angular-testing-avoid-done/.

2023-01-30 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +      transactionService.getEtxn(transactionID).subscribe((res) => {
`toHaveBeenCalledWith` / `toHaveBeenCalledTimes` ?

2023-01-30 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +      transactionService.getEtxn(transactionID).subscribe((res) => {
same as above

2023-01-30 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +      expect(apiV2Service.get).toHaveBeenCalledWith('/expenses', {
`toHaveBeenCalledWith`/`toHaveBeenCalledTimes` for `dateService`?

2023-01-30 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +      expect(apiV2Service.get).toHaveBeenCalledTimes(1);
same as above

2023-01-30 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +    transactionService.getMyExpensesCount(params).subscribe((res) => {
`toHaveBeenCalledWith`/`toHaveBeenCalledTimes` for `getMyExpenses`?

2023-01-30 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +      expect(apiService.post).toHaveBeenCalledWith('/transactions/unmatch', {
`toHaveBeenCalledTimes(1)`?

2023-01-30 13:21 UTC, rvab commented on src/app/core/services/transaction.service.ts
> +  getTransactionStats(aggregates: string, queryParams: EtxnParams): Observable<any> {
is it possible to avoid `any`? If not, then please add a TODO

2023-01-30 13:21 UTC, rvab commented on src/app/core/services/transaction.service.ts
> +  unmatchCCCExpense(txnId: string, corporateCreditCardExpenseId: string): Observable<void> {
this method returns the response of the API, why use `void` here?

2023-01-30 13:21 UTC, rvab commented on src/app/core/services/transaction.service.ts
> +      newQueryParamsCopy = this.generateCustomDateParams(newQueryParamsCopy, filters);
* is it a P0? 
* What is the impact? 
* When are we fixing it on prod?

2023-01-30 13:23 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> +  unmatchCCCExpense(txnId: string, corporateCreditCardExpenseId: string): Observable<void> {
API returns null

2023-01-30 13:23 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> +  getTransactionStats(aggregates: string, queryParams: EtxnParams): Observable<any> {
already added a TODO

2023-01-30 13:24 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> +      newQueryParamsCopy = this.generateCustomDateParams(newQueryParamsCopy, filters);
I have already fixed it, slight mismatch in the variable used

2023-01-30 13:28 UTC, Dimple16 commented on src/app/core/mock-data/expense.data.ts
> +export const expenseDataWithDateString = {
I haven't added type for this variable intentionally as this is the variable used before date transformation, the date keys in this variable are of type string, they will be transformed to type Date

2023-01-30 13:40 UTC, Dimple16 commented on src/app/core/mock-data/expense.data.ts
> +  tx_duplicates: [
it is present in the API response, it is not removed in the backend, and we are not using it on the client side, but since API is sending it, I've kept it

2023-01-30 13:51 UTC, Dimple16 commented on src/app/core/services/transaction.service.spec.ts
> +      done();
since the response is dealing with an observable, shouldn't we use `done()`?

2023-01-31 13:21 UTC, rvab approved these changes
One minor doubt

2023-01-31 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +      expect(lodash.cloneDeep).toHaveBeenCalledWith(params);
Why do it inside `afterEach`?

2023-01-31 13:47 UTC, Dimple16 commented on src/app/core/services/transaction.service.spec.ts
> +      expect(lodash.cloneDeep).toHaveBeenCalledWith(params);
had to mock the `cloneDeep` implementation for both the tests, instead of repeating, I added it here

2023-01-31 13:48 UTC, merged