FYLE-85zrja2zx Code Coverage : Cost Center Services subtask 2 : 85zrk1m8b Add params and return types with models
fylein/fyle-mobile-app pull request #1632
Opened 2023-01-27 11:15 UTC by CODEX108

Since there were no unused methods to be removed, subtask 2 was directly done.

2023-01-27 11:46 UTC, jayfyle commented on src/app/core/test-data/cost-centers.service.spec.data.ts
> +export const getCostCenterData = [
Trim the data, try and keep the number of objects less around 3 or 4. Also typecast it as per the return type or parameter and keep it in a file named similar to the model. You can add the file in core/mock-data

2023-01-27 11:47 UTC, jayfyle approved these changes
Update the data array, rest looks good.

2023-01-29 11:01 UTC, CODEX108 commented
### Statements covered 100% | Branches covered 50%

<img src="https://user-images.githubusercontent.com/82377810/215321673-0292aee0-737d-46ad-8107-4789092874b7.png" width=100% height=300>
<img src="https://user-images.githubusercontent.com/82377810/215321678-7ab86e32-b40a-40f3-9061-35acac8dd2ce.png" width=100% height=200>

2023-01-30 07:32 UTC, jayfyle commented on src/app/core/services/cost-centers.service.spec.ts
> +      expect(spenderPlatformApiService.get).toHaveBeenCalledWith('/cost_centers', testParams3);
Add a check for number of times API has been called, using `toHaveBeenCalledTimes`

2023-01-30 07:32 UTC, jayfyle commented on src/app/core/services/cost-centers.service.spec.ts
> +      done();
Same as above

2023-01-30 07:32 UTC, jayfyle commented on src/app/core/services/cost-centers.service.spec.ts
> +      expect(spenderPlatformApiService.get).toHaveBeenCalledWith('/cost_centers', data);
Same

2023-01-30 07:35 UTC, jayfyle approved these changes
Just add check for number of times api called, rest looks good.

2023-01-30 08:10 UTC, jayfyle commented on src/app/core/mock-data/cost-centers.data.ts
> +export const apiCostCenterSingleResponse = {
Use `api-response` model on latest master

2023-01-31 14:42 UTC, Dimple16 requested changes
we need to add test cases for all other private methods too

2023-01-31 14:42 UTC, Dimple16 commented on src/app/core/mock-data/cost-centers.data.ts
> +export const apiCostCenterSingleResponse = {
model is not added for data in this file

2023-01-31 14:42 UTC, Dimple16 commented on src/app/core/mock-data/cost-centers.data.ts
> +export const apiCostCenterSingleResponse = {
you can use `ApiV2Response<PlatformCostCenter>`

2023-01-31 14:42 UTC, Dimple16 commented on src/app/core/mock-data/cost-centers.data.ts
> +export const transformedCostCenterData = [
this should be of type `CostCenter[]`

2023-01-31 14:42 UTC, Dimple16 commented on src/app/core/mock-data/cost-centers.data.ts
> +      created_at: '2018-02-01T07:23:14.321866+00:00',
shouldn't this be `new Date()`?

2023-01-31 14:42 UTC, Dimple16 commented on src/app/core/mock-data/cost-centers.data.ts
> +      updated_at: '2019-01-08T10:51:37.721398+00:00',
same for `updated_at`

2023-01-31 14:42 UTC, Dimple16 commented on src/app/core/services/cost-centers.service.spec.ts
> +    spenderPlatformApiService.get.and.returnValue(of(apiCostCenterSingleResponse));
you should also mock `getActiveCostCentersCount()` and `getCostCenters()` since these are called inside `getAllActive` method

2023-02-01 14:45 UTC, CODEX108 commented
<img src="https://user-images.githubusercontent.com/82377810/216074253-c6cdcd77-54e1-4d60-8350-f49c90dc7607.png" width=100% height=300>

2023-02-02 11:01 UTC, jayfyle commented on src/app/core/services/cost-centers.service.spec.ts
> +      expect(spenderPlatformApiService.get).toHaveBeenCalledWith('/cost_centers', data);
Add `toHaveBeenCallledTimes()`

2023-02-02 11:02 UTC, jayfyle commented on src/app/core/services/cost-centers.service.spec.ts
> +      //  expect(res).toEqual(transformedCostCenterData);
Is the test not working?

2023-02-02 11:03 UTC, jayfyle commented on src/app/core/services/cost-centers.service.ts
> +        console.log(res);
Same

2023-02-02 11:04 UTC, jayfyle commented on src/app/core/services/cost-centers.service.spec.ts
> +      expect(spenderPlatformApiService.get).toHaveBeenCalledWith('/cost_centers', params);
toHaveBeenCalledTime()

2023-02-02 11:05 UTC, jayfyle requested changes
Minor comments

2023-02-08 10:48 UTC, jayfyle approved these changes

2023-02-09 07:01 UTC, jayfyle approved these changes

2023-02-13 15:08 UTC, Dimple16 requested changes
added comments

2023-02-13 15:08 UTC, Dimple16 commented on src/app/core/mock-data/platformCostCenter.data.ts
> +//api single and multiple response
since we'll be reusing mock data in other places, the comment specifies it to be related to only cost center service which shouldn't be the case, our idea is to reuse the mock data in multiple places as much as possible

2023-02-13 15:08 UTC, Dimple16 commented on src/app/core/mock-data/platformCostCenter.data.ts
> +export const apiCostCenterSingleResponse: PlatformApiResponse<PlatformCostCenter> = {
`platformCostCenterSingleRes`

2023-02-13 15:08 UTC, Dimple16 commented on src/app/core/mock-data/platformCostCenter.data.ts
> +export const apiCostCenterSingleResponse: PlatformApiResponse<PlatformCostCenter> = {
why is the `count: 4` for a single response?
if the count is correct then the limit is missing I guess

2023-02-13 15:08 UTC, Dimple16 commented on src/app/core/mock-data/platformCostCenter.data.ts
> +export const apiCostCenterMultipleResponse: PlatformApiResponse<PlatformCostCenter> = {
platformCostCenterMultipleRes

2023-02-13 15:08 UTC, Dimple16 commented on src/app/core/services/cost-centers.service.spec.ts
> +      expect(spenderPlatformV1BetaApiService.get).toHaveBeenCalledWith('/cost_centers', params);
`expect(spenderPlatformV1BetaApiService.get).toHaveBeenCalledOnceWith('/cost_centers', params);`

2023-02-13 15:08 UTC, Dimple16 commented on src/app/core/services/cost-centers.service.spec.ts
> +      expect(res).toEqual(4);
don't use the count directly, this might throw errors if anything changes, 
you can use `apiCostCenterSingleResponse.count`

2023-02-13 15:08 UTC, Dimple16 commented on src/app/core/services/cost-centers.service.spec.ts
> +  it('getCostCenters() :should get cost centers as per config', (done) => {
'getCostCenters(): should get cost centers as per config'

2023-02-13 15:08 UTC, Dimple16 commented on src/app/core/services/cost-centers.service.spec.ts
> +
you aren't mocking the `transformFrom` method here, even that should be added

2023-02-13 15:08 UTC, Dimple16 commented on src/app/core/services/cost-centers.service.spec.ts
> +      expect(spenderPlatformV1BetaApiService.get).toHaveBeenCalledWith('/cost_centers', data);
how many times is the API getting called here? add that check too

2023-02-13 15:08 UTC, Dimple16 commented on src/app/core/services/cost-centers.service.spec.ts
> +      expect(costCentersService.getActiveCostCentersCount).toHaveBeenCalled();
remove this line^
the below line makes sure to check if it is called or not, we don't have to check again, to doesn't add any value to the test case
`expect(costCentersService.getActiveCostCentersCount).toHaveBeenCalledTimes(1);`

2023-02-15 05:42 UTC, jayfyle requested changes
Minor comments

2023-02-15 05:42 UTC, jayfyle commented on src/app/core/services/cost-centers.service.spec.ts
> +      expect(costCentersService.getActiveCostCentersCount).toHaveBeenCalledTimes(1);
Remove the duplicated check

2023-02-15 05:42 UTC, jayfyle commented on src/app/core/services/cost-centers.service.spec.ts
> +      expect(costCentersService.getCostCenters).toHaveBeenCalledTimes(2);
Add a check for params as well with `tohaveBeenCalledWith`

2023-02-15 07:27 UTC, jayfyle approved these changes

2023-02-15 11:31 UTC, jayfyle approved these changes

2023-02-16 06:16 UTC, merged