Code Coverage: Report Service #4
fylein/fyle-mobile-app pull request #1633
Opened 2023-01-27 14:25 UTC by jayfyle

# Subtask #4: Will edit it further
![Report_Service_79](https://user-images.githubusercontent.com/115472256/215109806-0ab2e54d-8ddf-4d97-b786-36fb02650ca6.png)

2023-02-06 05:43 UTC, Dimple16 requested changes
added comments

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/mock-data/api-reports.data.ts
> +      rp_currency: 'INR',
replace `INR` with `USD` everywhere

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/mock-data/approver.data.ts
> +export const apiAllApproverRes2 = [
add type?

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/mock-data/approver.data.ts
> +export const expectedApprovers = [
add type for all variables used

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/mock-data/report-response.data.ts
> +export const apiErptcReportsRes = [
add report type?

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/mock-data/report-response.data.ts
> +  created_at: '2023-01-19T16:25:46.804Z',
is the date of the type string? or is this used to add as a param for `fixDates` method?

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/models/org-settings.model.ts
> +  date_to_sync_from?: string | null;
remove `null`

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/models/org-user.model.ts
>    approver2_id?: any;
replace all the `any` type in this file too

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +  it('getERpt(): should get an extended report', (done) => {
we should also mock the below:
```
- this.dataTransformService.unflatten(data)
- this.dateService.fixDates(erpt.rp)
- this.dateService.getLocalDate(erpt.rp.created_at)
```

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +    spyOn(reportService, 'getReportAutoSubmissionDetails').and.returnValue(of(apiReportAutoSubmissionDetails));
we should also mock:
`this.datePipe.transform(nextReportAutoSubmissionDate, 'MMM d')`

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +      expect(reportService.getReportAutoSubmissionDetails).toHaveBeenCalledTimes(1);
`expect(reportService.getReportAutoSubmissionDetails).toHaveBeenCalled();`

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +  it('getAutoSubmissionReportName(): should report null', (done) => {
`should return null if auto submission is not scheduled`

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +  it('getAutoSubmissionReportName(): should report null', (done) => {
since you are adding another test case for the same method, add both these `it` blocks inside a `describe` block

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +      expect(res).toEqual(null);
`expect(res).toBeNull();`

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +  it('getReportAutoSubmissionDetails(): should get submission details when no data is passed', (done) => {
add both these test cases inside one describe block

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +  it('addApprovers(): should add approver to a report', (done) => {
`addApprover()`

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +      expect(reportService.clearTransactionCache).toHaveBeenCalledTimes(1);
`expect(reportService.clearTransactionCache).toHaveBeenCalled();`

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +
also mock `this.dataTransformService.unflatten(erpt);`

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +      expect(reportService.clearTransactionCache).toHaveBeenCalledTimes(1);
```
expect(reportService.clearTransactionCache).toHaveBeenCalled();
expect(dataTransformService.unflatten).toHaveBeenCalledWith(erpt);
expect(dataTransformService.unflatten).toHaveBeenCalledTimes(1);
```

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +      expect(reportService.getMyReports).toHaveBeenCalledWith(getMyReportsParam);
also add this:
`expect(reportService.getMyReportsCount).toHaveBeenCalledWith(params.queryParams);`

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +  xit('getFilteredPendingReports(): should get all pending reports', (done) => {
remove this test case if not used here

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +  it('getApproversInBulk(): should get approvers in bulk for all report IDs speified', (done) => {
speified -> remove this

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +    apiService.get.and.returnValue(of({ count: 4 }));
we should also mock 
`this.storageService.set('erpts-count' + JSON.stringify(params), res);`
based on the condition^

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +  it('addOrderByParams(): return the params since no order is specified', () => {
return the params when no order is specified

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +  it('getUserReportParams(): generate parameters as per state | edit', () => {
add all these inside one `describe block`, 
check this -> https://www.notion.so/fyleuniverse/Unit-Testing-Guide-for-Mobile-app-dd328c458fd34f388b8867ce1fb6b984#6aab624641694ced866da47cb6c85cb8

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +    expect(result).toEqual(expectParam);
shouldn't it be `expectedRes`?

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.ts
> +  getPaginatedERptc(offset: number, limit: number, params: any) {
add type for `params`

2023-02-06 05:43 UTC, Dimple16 commented on src/app/core/services/report.service.ts
> +    params: any,
add a model - `reportParams` and use it if not already present

2023-02-06 10:45 UTC, Dimple16 requested changes

2023-02-06 10:45 UTC, Dimple16 commented on src/app/core/mock-data/data-transform.data.ts
> +  '': {
let's skip this?

2023-02-06 10:45 UTC, Dimple16 commented on src/app/core/mock-data/data-transform.data.ts
> +  '': {
is it mapped to an empty string?

2023-02-06 10:45 UTC, Dimple16 commented on src/app/core/services/report.service.ts
> +    params: {},
you can use `ReportParams` type here

2023-02-06 10:45 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +  it('getERpt(): should get an extended report', (done) => {
what about mocking dateService methods?

2023-02-06 10:45 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +    it('getUserReportParams(): generate parameters as per state | edit', () => {
if you are using a describe block, you can directly add the description in it block,
`it('generate parameters as per state | edit', ..`
adding the method name for every test case is not required

2023-02-06 10:47 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +    spyOn(reportService, 'getReportAutoSubmissionDetails').and.returnValue(of(apiReportAutoSubmissionDetails));
the pipe isn't mocked here

2023-02-06 10:48 UTC, Dimple16 requested changes
added comments

2023-02-06 10:48 UTC, Dimple16 commented on src/app/core/services/report.service.spec.ts
> +      storageService.get.and.returnValue(Promise.resolve({ count: 4 }));
shouldn't this be `storageService.set`?

2023-02-07 08:56 UTC, Dimple16 approved these changes

2023-02-07 09:35 UTC, rvab requested changes

2023-02-07 09:35 UTC, rvab commented on src/app/core/mock-data/data-transform.data.ts
> +export const dataErtpTransformed = {
Shouldn't we have a `type` for this?

2023-02-07 09:35 UTC, rvab commented on src/app/core/mock-data/data-transform.data.ts
> +export const apiErptReporDataParam = {
same as above

2023-02-07 09:35 UTC, rvab commented on src/app/core/models/api-reports.model.ts
> +export interface ApiV2Reports {
Should this be APIV2Response?

2023-02-07 09:35 UTC, rvab commented on src/app/core/models/report-auto-submission-details.model.ts
> +    next_at?: Date;
why make it optional?

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(reportService.clearTransactionCache).toHaveBeenCalled();
same as above

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(reportService.clearTransactionCache).toHaveBeenCalled();
`ToHaveBeenCalledTimes(1)` is already called in the above line. Do you still need this?

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      apiReportRes.data[3]
can't we use `array.slice` here?

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(dataTransformService.unflatten).toHaveBeenCalledTimes(1);
` expect(dataTransformService.unflatten).toHaveBeenCalledWith(apiExtendedReportRes[0]);`. This is sufficient. line 324, 325 aren't required

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(dateService.fixDates).toHaveBeenCalledTimes(1);
`toHaveBeentCalledOnceWith` for `dateService.fixDates` ?

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(dateService.getLocalDate).toHaveBeenCalledTimes(1);
same as above

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +    mockExtendedOrgUser();
why `mockExtendedOrgUser` is needed here?

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(reportService.clearTransactionCache).toHaveBeenCalled();
Why use `toHaveBeenCalledTimes(1)` and `toHaveBeenCalled()`  for `clearTransactionCache`

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +        expect(reportService.getReportAutoSubmissionDetails).toHaveBeenCalled();
why use both `toHaveBeenCalledTimes(1)` && `toHaveBeenCalled`

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +        expect(reportService.getReportAutoSubmissionDetails).toHaveBeenCalled();
same as above

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(reportService.clearTransactionCache).toHaveBeenCalledTimes(1);
same as above

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(reportService.clearTransactionCache).toHaveBeenCalled();
Why use both `toHaveBeenCalled` and `toHaveBeenCalledTimes`? Am I missing something there?

2023-02-07 09:35 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(dataTransformService.unflatten).toHaveBeenCalledWith(reportParam);
`toHaveBeenCalledOnceWith`?

2023-02-07 10:21 UTC, jayfyle commented on src/app/core/models/api-reports.model.ts
> +export interface ApiV2Reports {
Already have a model called `ApiV2Response`, which is being used everywhere, this model was made earlier, forgot to remove the file.

2023-02-07 11:16 UTC, jayfyle commented on src/app/core/mock-data/data-transform.data.ts
> +export const apiErptReporDataParam = {
Same as the above object, this is an unflattened version passed between methods before the final output is derived.

2023-02-07 11:17 UTC, jayfyle commented on src/app/core/models/report-auto-submission-details.model.ts
> +    next_at?: Date;
I was trying to cover an else case, where this property is not present, hence made it optional.

2023-02-07 11:19 UTC, jayfyle commented on src/app/core/services/report.service.spec.ts
> +      expect(reportService.clearTransactionCache).toHaveBeenCalled();
I have been asked to keep both `toHaveBeenCalled` and `toHaveBeenCalledTimes`, in case a method is being called once and with parameters, I can replace both with `toHaveBeenCalledOnce` which I have in other specs, else both should be there.

2023-02-07 12:34 UTC, jayfyle commented on src/app/core/services/report.service.spec.ts
> +      apiReportRes.data[3]
We are passing each array item individually and taking the output, hence I am passing each item separately

2023-02-07 14:06 UTC, rvab requested changes
Sending this back for now

2023-02-09 05:08 UTC, rvab approved these changes

2023-02-09 05:13 UTC, merged