Fyle 85zrja33r Code Coverage : Advance request custom fields service
fylein/fyle-mobile-app pull request #1635
Opened 2023-01-30 08:06 UTC by CODEX108

<img src="https://user-images.githubusercontent.com/82377810/215421220-f36691fa-3311-4505-b01b-8cc3466d1db0.png" height=200 width=500>

2023-01-30 12:32 UTC, Dimple16 requested changes
added comments

2023-01-30 12:32 UTC, Dimple16 commented on src/app/core/mock-data/advance-requests-custom-fields.data.ts
> +export const advanceRequestCustomField = [
what is the type of this data?

2023-01-30 12:32 UTC, Dimple16 commented on src/app/core/mock-data/advance-requests-custom-fields.data.ts
> +export const advanceRequestCustomField = [
reduce the list to 3 items

2023-01-30 12:32 UTC, Dimple16 commented on src/app/core/services/advance-requests-custom-fields.service.spec.ts
> +  it('should return all advance requests custom fields', () => {
add the description in this format `methodName(): method description`

2023-01-30 12:32 UTC, Dimple16 commented on src/app/core/services/advance-requests-custom-fields.service.spec.ts
> +    apiServiceSpy.get.and.returnValue(of(advanceRequestCustomField));
`advanceRequestCustomField` -> this should be plural since it's a list of multiple items

2023-01-30 12:32 UTC, Dimple16 commented on src/app/core/services/advance-requests-custom-fields.service.spec.ts
> +    expect(apiServiceSpy.get).toHaveBeenCalledWith('/advance_request_custom_fields');
this should be inside the subscribe block, 
also, you haven't used `done()`, since we are testing observables make sure we add it

2023-01-30 12:32 UTC, Dimple16 commented on src/app/core/services/advance-requests-custom-fields.service.spec.ts
> +    advanceRequestsCustomFieldsService.getAll().subscribe((res) => {
`getAll()` method return type isn't added, add it in the service file

2023-01-30 15:13 UTC, Dimple16 requested changes

2023-01-30 15:13 UTC, Dimple16 commented on src/app/core/models/advance-requests-custom-fields.model.ts
> +  placeholder?: any;
this should be string

2023-01-30 15:13 UTC, Dimple16 commented on src/app/core/models/advance-requests-custom-fields.model.ts
> +  options: any;
this should be a list of string

2023-01-30 15:13 UTC, Dimple16 commented on src/app/core/models/advance-requests-custom-fields.model.ts
> +  created_at: string;
shouldn't this be `Date` type?

2023-01-30 15:13 UTC, Dimple16 commented on src/app/core/services/advance-requests-custom-fields.service.ts
> +  getAll(): Observable<AdvanceRequestsCustomFields[]> {
we should handle fixing the dates to date type, you can refer `fixDates()` method used in other services, 
API is returning string here, but we need to handle it on the client side

2023-01-30 15:13 UTC, Dimple16 commented on src/app/core/services/advance-requests-custom-fields.service.spec.ts
> +    apiServiceSpy = jasmine.createSpyObj('ApiService', ['get']);
const apiServiceSpy = jasmine.createSpyObj('ApiService', ['get']);

2023-01-30 15:13 UTC, Dimple16 commented on src/app/core/services/advance-requests-custom-fields.service.spec.ts
> +    apiServiceSpy = jasmine.createSpyObj('ApiService', ['get']);
```
TestBed.configureTestingModule({
      providers: [
        AdvanceRequestsCustomFieldsService,
        {
          provide: ApiService,
          useValue: apiServiceSpy,
        },
  });
  
  apiService = TestBed.inject(ApiService) as jasmine.SpyObj<ApiService>;
  ```

2023-01-30 15:14 UTC, Dimple16 requested changes
fix lint issues

2023-01-31 12:59 UTC, jayfyle approved these changes

2023-01-31 13:44 UTC, Dimple16 approved these changes

2023-01-31 13:50 UTC, merged