FYLE-85zrjffpe: Code coverage - Transaction service 80%
fylein/fyle-mobile-app pull request #1636
Opened 2023-01-31 18:59 UTC by Dimple16

2023-02-02 11:21 UTC, Dimple16 commented on src/app/core/models/v1/transaction.model.ts
> +  project_id: number | string;
there are places where it returns as a string and a few it returns as a number

2023-02-02 11:22 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> -  removeTxnsFromRptInBulk(txnIds: string[], comment?: string): Observable<Expense[]> {
unused method

2023-02-02 11:23 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> -  getPaginatedETxncCount(params?: EtxnParams): Observable<ApiV2Response<Expense>> {
there are no params for this method, removed unused code

2023-02-02 11:24 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> -  review(txnId: string): Observable<UnflattenedTransaction> {
doesn't return anything

2023-02-02 11:24 UTC, Dimple16 commented on src/app/core/services/transaction.service.ts
> -    if (expensesToBeDeleted?.length > 0 && cccExpenses > 0) {
this is always present

2023-02-02 13:21 UTC, rvab requested changes
Few doubts.

2023-02-02 13:21 UTC, rvab commented on src/app/core/mock-data/file-object.data.ts
> +import { FileObject } from '../models/file_obj.model';
`file_obj`? Are we following `_` in the mobile app?

2023-02-02 13:21 UTC, rvab commented on src/app/core/models/v1/transaction.model.ts
> +  project_id: number | string;
Do you mean in the API response we're getting it as a string/number?

2023-02-02 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +      transactionService.getETxn(transactionID).subscribe((res) => {
Why there are 2 methods with the same name?. Only letter casing is different `getEtxn`, `getETxn`?

2023-02-02 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +      expect(res).toEqual(null);
toBeNull()

2023-02-02 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +    const expectedResult = [
is it possible to move them to different file?

2023-02-02 13:21 UTC, rvab commented on src/app/core/services/transaction.service.spec.ts
> +        count: 1,
Create a object for USD?

2023-02-06 09:29 UTC, Dimple16 commented on src/app/core/models/v1/transaction.model.ts
> +  project_id: number | string;
yes, it expects to be a string at a few places and a number in a few

2023-02-06 09:30 UTC, Dimple16 commented on src/app/core/mock-data/file-object.data.ts
> +import { FileObject } from '../models/file_obj.model';
no, this is legacy code, I've renamed the file now

2023-02-06 09:33 UTC, Dimple16 commented on src/app/core/services/transaction.service.spec.ts
> +      transactionService.getETxn(transactionID).subscribe((res) => {
yes, this is legacy code, I've renamed the method based on return type

2023-02-06 09:36 UTC, Dimple16 commented on src/app/core/services/transaction.service.spec.ts
> +        count: 1,
will keep this INR since it is a split for foreign currency

2023-02-06 09:37 UTC, Dimple16 commented on src/app/core/services/transaction.service.spec.ts
> +    const expectedResult = [
moved to /mock-data/currency-summary.data.ts

2023-02-06 10:58 UTC, rvab approved these changes

2023-02-06 11:02 UTC, merged