FYLE-85zrk1n2yCode Coverage : Ellipses pipe
fylein/fyle-mobile-app pull request #1643
Opened 2023-02-02 12:24 UTC by CODEX108

<img src="https://user-images.githubusercontent.com/82377810/216323788-1b4d0738-2e03-4776-a03d-1e653c498f51.png" width=60% height=300>

2023-02-02 12:50 UTC, jayfyle commented on src/app/shared/pipes/ellipses.pipe.spec.ts
> +    const input2 = 'Hello';
Try and use a larger string since the case for equal length has been covered

2023-02-02 12:52 UTC, jayfyle approved these changes
Update the spec, rest looks good

2023-02-03 05:43 UTC, Dimple16 requested changes
added comments

2023-02-03 05:43 UTC, Dimple16 commented on src/app/shared/pipes/ellipses.pipe.spec.ts
> +    const input2 = 'Hello';
yes, for ellipsisPipe let's use long strings

2023-02-03 05:43 UTC, Dimple16 commented on src/app/shared/pipes/ellipses.pipe.spec.ts
> +    const input = 'We are testing';
use string inputs related to Fyle app, - `Jan - 1 Report for reimbursement`

2023-02-03 05:43 UTC, Dimple16 commented on src/app/shared/pipes/ellipses.pipe.spec.ts
> +    const input = 'Hello World';
use long category/project names as examples

2023-02-06 05:10 UTC, Dimple16 requested changes
tests lgtm, add param and return types for transform() method

2023-02-06 12:23 UTC, jayfyle approved these changes

2023-02-06 12:48 UTC, Dimple16 approved these changes

2023-02-06 13:10 UTC, merged