FYLE-85zrkx6jk Code coverage: Pending User Service method
fylein/fyle-mobile-app pull request #1646
Opened 2023-02-03 10:23 UTC by CODEX108

<img src="https://user-images.githubusercontent.com/82377810/216575851-1b0a8a60-f2f6-4225-b346-6270b7e646c4.png" width=70% height=300>

2023-02-03 10:28 UTC, CODEX108 commented
@jayfyle @Dimple16, the `method names` aren't mentioned in the spec file for other methods can I include those names too?
`<method name> should do this`

2023-02-06 05:12 UTC, Dimple16 requested changes

2023-02-06 05:12 UTC, Dimple16 commented on src/app/core/services/user.service.spec.ts
> +const userPasswordStatus: UserPasswordStatus = {
add these 2 variables in a separate file -> `/mock-data/user-password-status.data.ts`

2023-02-06 12:55 UTC, Dimple16 requested changes
added comments

2023-02-06 12:55 UTC, Dimple16 commented on src/app/core/mock-data/user.data.ts
> +export const userPasswordStatus: UserPasswordStatus = {
the name of this file should be `user-password-status.data.ts`

2023-02-06 12:55 UTC, Dimple16 commented on src/app/core/services/user.service.spec.ts
> +      expect(apiService.get).toHaveBeenCalledWith('/users/password_required');
use `toHaveBeenCalledOnceWith` and remove the below line

2023-02-06 14:08 UTC, Dimple16 approved these changes

2023-02-08 10:47 UTC, jayfyle approved these changes

2023-02-09 15:41 UTC, merged