Fyle 85zrmb5uq Code Coverage : Highlight Pipe
fylein/fyle-mobile-app pull request #1654
Opened 2023-02-07 08:39 UTC by CODEX108

<img src="https://user-images.githubusercontent.com/82377810/217194001-a43705a5-8509-4509-b313-60cbf0c1ebbb.png" width=60% height=300>

2023-02-07 09:08 UTC, Dimple16 requested changes
added comments

2023-02-07 09:08 UTC, Dimple16 commented on src/app/shared/pipes/highlight.pipe.spec.ts
> +  it('highlightPipe transform() : should highlight the search term in the text', () => {
replace `term` with `query` everywhere

2023-02-07 09:08 UTC, Dimple16 commented on src/app/shared/pipes/highlight.pipe.spec.ts
> +  it('highlightPipe transform() : should handle a search term with special character', () => {
add another test case with different special characters like @#$%^

2023-02-07 11:02 UTC, CODEX108 commented
<img src="https://user-images.githubusercontent.com/82377810/217227163-73ee4cc1-807e-42cd-a279-14fda1220a8b.png" width=200 height=300>

2023-02-07 11:04 UTC, CODEX108 commented
Can I add a single test for the special character?
```
 it('highlightPipe transform() : should handle a search query other with special characters', () => {
    const text = 'This is some text with special characters: @#$%^+-[]{}()/*';
    const search = '@#$%^+-[]{}()/*';
    const expectedResult = 'This is some text with special characters: <span class="highlight">@#$%^+-[]{}()/*</span>';

    const result = highlightPipe.transform(text, search);

    expect(result).toBe(expectedResult);
  });
```

2023-02-07 11:35 UTC, jayfyle commented on src/app/shared/pipes/highlight.pipe.spec.ts
> +  it('highlightPipe transform() : should handle a search query with special character', () => {
Change spec description, should highlight search query special characters. Do ask Dimple once, as this one and below seem quite similar making it difficult to differentiate between the two specs.

2023-02-07 11:37 UTC, jayfyle commented on src/app/shared/pipes/highlight.pipe.spec.ts
> +  it('highlightPipe transform() : should handle a search query other with special characters', () => {
Remove other from the spec description.

2023-02-08 06:03 UTC, Dimple16 approved these changes
minor comments, fix all of them and merge

2023-02-08 06:03 UTC, Dimple16 commented on src/app/shared/pipes/highlight.pipe.spec.ts
> +  it('highlightPipe transform() : should handle a search query other with special characters', () => {
this isn't resolved

2023-02-08 06:03 UTC, Dimple16 commented on src/app/shared/pipes/highlight.pipe.spec.ts
> +  it('highlightPipe transform() : should handle a search query with special character', () => {
rename it to `should handle a search query with single special character`

2023-02-08 06:03 UTC, Dimple16 commented on src/app/shared/pipes/highlight.pipe.spec.ts
> +  it('highlightPipe transform() : should handle a search query other with special characters', () => {
rename it to `should handle a search query with multiple special characters`

2023-02-09 05:32 UTC, merged