Code Coverage: Report Service #5
fylein/fyle-mobile-app pull request #1660
Opened 2023-02-09 08:13 UTC by jayfyle

## Code coverage almost 100%

![Report_Coverage_98](https://user-images.githubusercontent.com/115472256/217754635-4721ce3c-2af4-4c3c-9692-903b299ae931.png)

2023-02-10 06:51 UTC, Julias0 commented on src/app/core/mock-data/api-reports.data.ts
> +  count: 3,
Why is this 3? There are 2 items in data and the offset is 0, limit 2 so this cant happen right?

2023-02-10 06:52 UTC, Julias0 commented on src/app/core/mock-data/api-reports.data.ts
> +  count: 3,
Why is this with count 3 when there is just 1 line item?

2023-02-10 06:55 UTC, Julias0 commented on src/app/core/models/report-unflattened.model.ts
> +    approvals?:
Can we clean up this mixed data type if possible? create another variable called approvalsMap if that makes it easier

2023-02-10 06:57 UTC, Julias0 commented on src/app/core/services/report.service.spec.ts
> +      mockExtendedOrgUser();
why have this inside a function - this is 1 line only so it doesn't really help with reuse or rewriting. Same for mockReports
The code in the line is more obvious than the method call
Ref: https://refactoring.guru/inline-method

2023-02-10 10:25 UTC, Julias0 commented on src/app/core/services/report.service.spec.ts
> +      reportService.getMyReports(params).subscribe((res) => {
can we also check apiv2Service.get toHaveBeenCalledWith. That will test if the params are being properly added or not

2023-02-10 10:27 UTC, Julias0 commented on src/app/core/services/report.service.spec.ts
> +    it('should get reports from API when no order is specified', (done) => {
Same as above - we should test the toHaveBeenCalledWith of apiv2Service.get, to see if the proper params are being sent or not.

2023-02-13 03:43 UTC, rvab requested changes

2023-02-13 03:43 UTC, rvab commented on src/app/core/models/api-reports.model.ts
> +export interface ApiV2Reports {
There's already an `APIV2Response` model. Why do you need a new model for `ApiV2Reports`?

2023-02-13 03:43 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(dataTransformService.unflatten).toHaveBeenCalledTimes(1);
why remove `toHaveBeenCalledOnceWith`? isn't it short hand for `toHaveBeenCalledWith` and `toHaveBeenCalledTimes`?

2023-02-13 03:43 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +        expect(permissionsService.allowedActions).toHaveBeenCalledTimes(1);
`toHaveBeenCalledOnceWith` isn't required?

2023-02-13 03:43 UTC, rvab commented on src/app/core/services/report.service.spec.ts
> +      expect(res).toEqual(expectedAddedApproverERpts);
You should be checking for `toHaveBeenCalledOnceWith` for all the mocked methods(line no 1004 to 1007)

2023-02-13 14:14 UTC, Dimple16 requested changes
added comments

2023-02-13 16:35 UTC, jayfyle commented on src/app/core/services/report.service.spec.ts
> +        expect(res).toEqual(res);
The function returns the data as given as response from the API after date manipulation, I have changed the statement.

2023-02-13 16:36 UTC, jayfyle commented on src/app/core/services/report.service.spec.ts
> +        expect(res).toEqual(res);
Same as above

2023-02-13 16:38 UTC, jayfyle commented on src/app/core/services/report.service.spec.ts
> +      const getMyReportsParam2 = {
There is no model for API parameters, I am creating a common model, that we can use for methods where we pass API params.

2023-02-13 16:41 UTC, jayfyle commented on src/app/core/services/report.service.ts
> +    return Object.assign({}, params, searchParams);
All the instances of the method being called are in the expense forms, where we don't pass `dateRange` property. Everywhere there is only state property being passed. But I will thoroughly test the relevant flows once the PR is merged

2023-02-15 05:49 UTC, Dimple16 approved these changes

2023-02-15 05:49 UTC, Dimple16 commented on src/app/core/models/api-params.model.ts
> +export interface ApiParams {
this looks very specific to report API params, rename this to `ReportApiParams`

2023-02-16 05:51 UTC, rvab requested changes

2023-02-16 05:51 UTC, rvab commented on src/app/core/services/report.service.ts
> +    config: Partial<{ order: string; queryParams: ReportApiParams['queryParams'] }>
same as above

2023-02-16 05:51 UTC, rvab commented on src/app/core/services/report.service.ts
> +      queryParams: ReportApiParams['queryParams'];
is it recommended to use `ReportApiParams['queryParams']`?

2023-02-16 05:51 UTC, rvab commented on src/app/core/services/report.service.ts
>            if (res.data.next_at) {
if you're checking for `res.data.next_at`, then it means `next_at` is optional. Why did you make it mandatory in the `ReportAutoSubmissionDetails` model?

2023-02-16 06:35 UTC, jayfyle commented on src/app/core/services/report.service.ts
>            if (res.data.next_at) {
Was trying out something to get more coverage, forgot to change it back. Have restored it to the previous version.

2023-02-16 06:56 UTC, rvab approved these changes

2023-02-16 06:58 UTC, merged