Fyle 85zrkj8et Code coverage : Sidemenubar Services
fylein/fyle-mobile-app pull request #1662
Opened 2023-02-10 11:27 UTC by CODEX108

<img src="https://user-images.githubusercontent.com/82377810/218081329-873de419-67f6-45c2-a1a3-fe2a17216cb4.png" width=60% height=300>

2023-02-10 11:42 UTC, jayfyle requested changes

2023-02-10 11:42 UTC, jayfyle commented on src/app/core/services/sidemenu.service.spec.ts
> +      });
Add checks for report service and org-setings serve as they are being mocked.

2023-02-10 11:42 UTC, jayfyle commented on src/app/core/services/sidemenu.service.spec.ts
> +      expect(permissionsService.allowedActions).toHaveBeenCalled();
Same here as well

2023-02-10 11:42 UTC, jayfyle commented on src/app/core/services/sidemenu.service.spec.ts
> +  it('getAllActions() : should call allowedActions from permissionsService if both the params are true, and return null if false', () => {
`getAllActions()`, I don't see a method with that name, change the spec description. Also, if there are many tests for a single function, group them in a describe block together.

2023-02-10 12:13 UTC, CODEX108 commented on src/app/core/services/sidemenu.service.spec.ts
> +  it('getAllActions() : should call allowedActions from permissionsService if both the params are true, and return null if false', () => {
Yes it was a typo

2023-02-10 12:54 UTC, jayfyle commented on src/app/core/services/sidemenu.service.spec.ts
> +        expect(reportService.getReportPermissions).toHaveBeenCalledWith(orgSettings);
Same

2023-02-10 12:54 UTC, jayfyle commented on src/app/core/services/sidemenu.service.spec.ts
> +        expect(orgSettingsService.get).toHaveBeenCalled();
Same

2023-02-10 12:55 UTC, jayfyle commented on src/app/core/services/sidemenu.service.spec.ts
> +        expect(reportService.getReportPermissions).toHaveBeenCalledWith(orgSettings2);
Add the same check here as well

2023-02-10 12:55 UTC, jayfyle commented on src/app/core/services/sidemenu.service.spec.ts
> +        expect(reportService.getReportPermissions).toHaveBeenCalledWith(orgSettingsParams);
if the method is being called once with params use `toHaveBeenCalledOnceWith`

2023-02-13 03:53 UTC, rvab requested changes

2023-02-13 03:53 UTC, rvab commented on src/app/core/mock-data/sidemenubar-allowed-actions.data.ts
> +  create: undefined,
why it's `undefined`? is it an optional value? If yes, then we don't have to add the key

2023-02-13 03:53 UTC, rvab commented on src/app/core/services/sidemenu.service.spec.ts
> +        expect(result).toEqual({ allowedReportsActions, allowedAdvancesActions });
`toHaveBeenCalled`?

2023-02-13 03:53 UTC, rvab commented on src/app/core/services/sidemenu.service.spec.ts
> +      const orgSettings = {
I think the model is already there for `OrgSettings`. Use `Partial<OrgSettings>` as type

2023-02-13 07:32 UTC, CODEX108 commented on src/app/core/mock-data/sidemenubar-allowed-actions.data.ts
> +  create: undefined,
The `create` is not optional in the model `allowed-actions.model` is it ok if I create a different model for `advanceAllowedActionsResponse` because the current model is as follows:

![image_720](https://user-images.githubusercontent.com/82377810/218397037-1949fc13-6d98-4259-b36b-12d904ab2fd9.png)

2023-02-13 15:10 UTC, closed without merging