Dependent fields: Add unit tests for new method in merge-expense service
fylein/fyle-mobile-app pull request #1668
Opened 2023-02-14 08:25 UTC by yksolanki9

2023-02-14 09:14 UTC, Dimple16 requested changes
added comments

2023-02-14 09:14 UTC, Dimple16 commented on src/app/core/models/expense.model.ts
> +  tx_activity_details?: any;
we don't use activity keys in client, since the API returns these keys, you can add the type as well,
```
tx_activity_details?: string;
tx_activity_policy_pending?: boolean;
```

2023-02-14 09:14 UTC, Dimple16 commented on src/app/core/services/merge-expenses.service.spec.ts
> +    expect(mergeExpensesService.getProjectDependentFieldsMapping(expensesWithSameProject, dependentFields)).toEqual(
you can move this to different specs, 
basically, add different test cases for different data, else, if one fails, the whole spec will fail 

you can add the other spec as 
`it('should return the correct project mapping with the same project', () => {` etc

2023-02-14 09:14 UTC, Dimple16 commented on src/app/core/services/merge-expenses.service.spec.ts
> +  it('getProjectDependentFieldsMapping(): should return the correct project mapping', () => {
add a describe block for this method, since you'll have 3 test cases for 1 method
```
describe('getProjectDependentFieldsMapping(): ', () => {
....
it('should return .....', () => {
......
it(should return ....', () => {
```

2023-02-14 09:14 UTC, Dimple16 commented on src/app/core/test-data/merge-expense.service.spec.data.ts
> +export const expensesWithDependentFields = [
type of this data? `export const expensesWithDependentFields" Expense[] = [`

2023-02-14 09:14 UTC, Dimple16 commented on src/app/core/test-data/merge-expense.service.spec.data.ts
> +export const expensesWithDependentFields = [
move this file inside the `/mock-data` folder, the convention is different there, 
you can keep the file name corresponding to the model used, 
if data is of type `DependentFields` 
the mock data name would be - `/mock-data/dependent-fields.data.ts`

2023-02-14 09:14 UTC, Dimple16 commented on src/app/core/test-data/merge-expense.service.spec.data.ts
> +    tx_custom_properties: [
use max 3 items if that works, we can avoid huge data that way

2023-02-14 11:09 UTC, yksolanki9 commented on src/app/core/services/merge-expenses.service.spec.ts
> +  it('getProjectDependentFieldsMapping(): should return the correct project mapping', () => {
Done

2023-02-14 11:31 UTC, yksolanki9 commented on src/app/core/test-data/merge-expense.service.spec.data.ts
> +export const expensesWithDependentFields = [
Done

2023-02-14 11:31 UTC, yksolanki9 commented on src/app/core/test-data/merge-expense.service.spec.data.ts
> +    tx_custom_properties: [
Done

2023-02-14 11:33 UTC, yksolanki9 commented on src/app/core/mock-data/dependent-field.data.ts
> +interface CustomInput {
This model is different than the API returned model and is local to the file so keeping it local to this file

2023-02-15 05:29 UTC, Dimple16 approved these changes

2023-02-15 05:29 UTC, Dimple16 commented on src/app/core/mock-data/dependent-field.data.ts
> +interface CustomInput {
you can still name it accordingly and move it to a separate file in `/models` folder

2023-02-15 07:02 UTC, Julias0 commented on src/app/core/mock-data/dependent-field.data.ts
> +export const dependentFields: CustomInput[] = [
add a todo here so that we remember to remove this off. Same for other places where we have kept temporary data

2023-02-15 07:03 UTC, Julias0 commented on src/app/core/mock-data/dependent-field.data.ts
> +interface CustomInput {
@yksolanki9 lets move this model to models - you can name it as custom-input-internal or something. The filename should match the model name

2023-02-15 07:03 UTC, Julias0 commented on src/app/core/mock-data/project-dependent-field-mapping.data.ts
> +export const projectDependentFieldsMapping: ProjectDependentFieldMapping = {
Same for these - lets add a todo

2023-02-15 07:03 UTC, Julias0 approved these changes

2023-02-15 07:39 UTC, Julias0 commented on src/app/core/mock-data/dependent-field.data.ts
> +interface CustomInput {
merge-expene-custom-input

2023-02-17 05:26 UTC, Julias0 approved these changes

2023-02-17 11:54 UTC, yksolanki9 commented on src/app/core/mock-data/dependent-field.data.ts
> +interface CustomInput {
Done

2023-02-17 11:55 UTC, merged