Fyle 85zrn57ak Code Coverage:Mileage rate services
fylein/fyle-mobile-app pull request #1694
Opened 2023-02-20 14:27 UTC by CODEX108

<img src="https://user-images.githubusercontent.com/82377810/220133425-a384e257-422d-4126-a11a-daace0ca324c.png" width=50% height=300>

2023-02-20 15:43 UTC, jayfyle approved these changes

2023-02-20 18:42 UTC, Dimple16 requested changes
add return type for this service method - `formatMileageRateName()`

2023-02-20 18:42 UTC, Dimple16 commented on src/app/core/mock-data/mileage-rate.data.ts
> +export const unfilterdMileageRatesData: PlatformMileageRates[] = [
`unfilteredMileageRatesData`

2023-02-20 18:42 UTC, Dimple16 commented on src/app/core/mock-data/mileage-rate.data.ts
> +export const nullRateIncludedData: PlatformMileageRates[] = [
`nullMileageRateData`

2023-02-20 18:42 UTC, Dimple16 commented on src/app/core/mock-data/mileage-rate.data.ts
> +export const nullRateExcludedData1: PlatformMileageRates[] = [
if it's excluded, then we can name it as `platformMileageRatesData`

2023-02-20 18:42 UTC, Dimple16 commented on src/app/core/services/mileage-rates.service.spec.ts
> +      const input = 'invalid_rate_name';
`three_wheeler`

2023-02-20 18:42 UTC, Dimple16 commented on src/app/core/services/mileage-rates.service.spec.ts
> +    const result = mileageRatesService.filterEnabledMileageRates(unfilterdMileageRatesData);
`unfilterdMileageRatesData` -> typo

2023-02-20 18:42 UTC, Dimple16 commented on src/app/core/services/mileage-rates.service.spec.ts
> +  it('should get mileage rates', (done) => {
`getMileageRates(): should get mileage rates`

2023-02-20 18:42 UTC, Dimple16 commented on src/app/core/services/mileage-rates.service.spec.ts
> +    spyOn(mileageRatesService, 'getAllMileageRatesCount').and.returnValue(of(100));
reduce this count value, use 20,

2023-02-20 18:42 UTC, Dimple16 commented on src/app/core/services/mileage-rates.service.spec.ts
> +    const testParams1 = { offset: 0, limit: 50 };
change this accordingly

2023-02-21 07:29 UTC, Dimple16 approved these changes

2023-02-21 07:31 UTC, merged