Code coverage: AdvanceActions Component - 100%
fylein/fyle-mobile-app pull request #1697
Opened 2023-02-20 16:15 UTC by Dimple16

![Screenshot 2023-02-20 at 9 44 43 PM](https://user-images.githubusercontent.com/31147415/220156552-f633b4e5-8301-4970-b781-4ddf4cc183e6.png)

2023-02-21 04:12 UTC, rvab requested changes

2023-02-21 04:12 UTC, rvab commented on src/app/fyle/view-team-advance-request/advance-actions/advance-actions.component.spec.ts
> +      component.actions = {
* Are these actions exclusive?. If one is true, the other 2 will be false all the time?
* Is there a situation where `can_approve` and `can_inquire` are true and `can_reject` is false?. What is the UI state here?. Shouldn't we cover all cases here?
* what happens if all 3 are false?

2023-02-21 04:12 UTC, rvab commented on src/app/fyle/view-team-advance-request/advance-actions/advance-actions.component.spec.ts
> +      sendBackButton.click();
create a utility function for click https://angular.io/guide/testing-components-scenarios#click-helper

2023-02-21 04:12 UTC, rvab commented on src/app/fyle/view-team-advance-request/advance-actions/advance-actions.component.spec.ts
> +    it('should dismiss popover with the rejectAdvance command when reject advance action button is clicked', () => {
same as above

2023-02-22 16:42 UTC, Dimple16 commented on src/app/fyle/view-team-advance-request/advance-actions/advance-actions.component.spec.ts
> +      component.actions = {
> Are these actions exclusive?. If one is true, the other 2 will be false all the time?
- No, not always, 

> Is there a situation where can_approve and can_inquire are true and can_reject is false?. What is the UI state here?. Shouldn't we cover all cases here?
- I have covered usual cases, 
- Most cases for an approver:
      - all 3 buttons will be visible when the advance request isn't approved yet, 
      - once approved, it can only be sent back, so only 1 button sent back will be present

> what happens if all 3 are false?
- The entire advance action button itself isn't visible, added a test case for that too

2023-02-22 16:49 UTC, Dimple16 commented on src/app/fyle/view-team-advance-request/advance-actions/advance-actions.component.spec.ts
> +    it('should dismiss popover with the rejectAdvance command when reject advance action button is clicked', () => {
added helper method for `click()`

2023-02-23 05:38 UTC, rvab approved these changes

2023-02-23 05:50 UTC, merged