Code coverage: Storage service - 100%
fylein/fyle-mobile-app pull request #1701
Opened 2023-02-20 18:26 UTC by Dimple16

![Screenshot 2023-02-20 at 11 54 37 PM](https://user-images.githubusercontent.com/31147415/220177956-f41af870-41a5-4097-a4f9-0b5840c7fffa.png)

2023-02-21 04:22 UTC, rvab requested changes

2023-02-21 04:22 UTC, rvab commented on src/app/core/services/storage.service.spec.ts
> +      pending();
Why is it `pending`?

2023-02-21 04:22 UTC, rvab commented on src/app/core/services/storage.service.spec.ts
> +      pending();
same as above

2023-02-21 04:22 UTC, rvab commented on src/app/core/services/storage.service.spec.ts
> +      pending();
same as above

2023-02-21 05:35 UTC, Dimple16 commented on src/app/core/services/storage.service.spec.ts
> +      pending();
I've added `pending` to avoid warning that there is no expect() in this test case.
Since Preferences is a capacitor plugin, not able to create a spyObj for it

2023-02-22 03:51 UTC, rvab approved these changes

2023-02-22 16:31 UTC, merged