Code coverage: Disabled page component - 100%
fylein/fyle-mobile-app pull request #1712
Opened 2023-02-23 14:43 UTC by Dimple16

![Screenshot 2023-02-23 at 8 12 01 PM](https://user-images.githubusercontent.com/31147415/220939510-8c3144fa-a194-446e-a803-6a6c23e21c62.png)

2023-02-27 03:59 UTC, rvab requested changes

2023-02-27 03:59 UTC, rvab commented on src/app/auth/disabled/disabled.page.spec.ts
> +  it('should navigate to /auth/sign_in when onGotoSignInClick is called', () => {
both can be combined into a single test case.

2023-02-27 15:27 UTC, Dimple16 commented on src/app/auth/disabled/disabled.page.spec.ts
> +  it('should navigate to /auth/sign_in when onGotoSignInClick is called', () => {
this is fixed

2023-02-28 05:15 UTC, rvab approved these changes

2023-02-28 07:10 UTC, merged