State name changes for Simplified Report Closure
fylein/fyle-mobile-app pull request #1723
Opened 2023-02-27 15:50 UTC by arjunaj5

2023-03-01 07:58 UTC, yksolanki9 requested changes

2023-03-01 07:58 UTC, yksolanki9 commented on src/app/core/services/org-settings.service.ts
> +        allowed: incoming.simplified_report_closure_settings && incoming.simplified_report_closure_settings.allowed,
Use optional chaining

2023-03-01 07:58 UTC, yksolanki9 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +      if (orgSettings?.simplified_report_closure_settings?.enabled) {
Use it as an observable and resolve it in html using async pipe, if orgSettings takes some time to load, the user will see `Reported` then it'll be updated to `Submitted` after a couple of seconds, not a good UX

2023-03-01 07:58 UTC, yksolanki9 commented on src/app/core/services/org-settings.service.ts
> +      simplified_report_closure_settings: {
Also, check with @Dimple16 if this affects the code coverage or any new test case needs to be added for this

2023-03-01 07:58 UTC, yksolanki9 commented on src/app/fyle/my-reports/my-reports.page.ts
> +    this.orgSettingsService.get().subscribe((orgSettings) => {
Use observable

2023-03-01 07:58 UTC, yksolanki9 commented on src/app/fyle/my-reports/my-reports.page.ts
> +    this.orgSettingsService.get().subscribe((orgSettings) => {
`isNewReportsFlowEnabled$`, `isCCCOnlyOrg$` - They are visible to user on the reports page, chances are orgSettings may take time to resolve and user may see old values

2023-03-01 07:58 UTC, yksolanki9 commented on src/app/fyle/my-reports/my-reports.page.ts
> +      (!this.isCCCOnlyOrg && [
Can there be a case where `isNewReportsFlowEnabled` is true and `isCCCOnlyOrg` is true?
If yes, as per the logic, it'll hide both payment pending and processing filters for them, intentional?

Please add comments for future ref

2023-03-01 07:58 UTC, yksolanki9 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +        this.isNewReportsFlowEnabled = true;
Convert to observable since it is shown directly on view report page

2023-03-01 07:58 UTC, yksolanki9 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      this.isNewReportsFlowEnabled = orgSettings?.simplified_report_closure_settings?.enabled || false;
Observable

2023-03-01 12:55 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.ts
> +      (!this.isCCCOnlyOrg && [
Yes, CCC only orgs should not see any payment level filters in the new reports flow

2023-03-01 12:57 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.ts
> +      (!this.isCCCOnlyOrg && [
added a code comment

2023-03-01 13:26 UTC, arjunaj5 commented on src/app/core/services/org-settings.service.ts
> +        allowed: incoming.simplified_report_closure_settings && incoming.simplified_report_closure_settings.allowed,
done

2023-03-01 13:27 UTC, arjunaj5 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +      if (orgSettings?.simplified_report_closure_settings?.enabled) {
:done, used observables and async pipe

2023-03-01 13:38 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.ts
> +    this.orgSettingsService.get().subscribe((orgSettings) => {
Used observables.
However, the resolved value had to be used in another function `async openFilters(activeFilterInitialName?: string)`.
This function is also bound to click event, hence used in the template also, so could not pass in the resolved values to this function in the template.

As a solution, have created a new method `createFilterOptions` which will resolve the above two values and create the filter options based on the values.

2023-03-01 13:38 UTC, arjunaj5 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      this.isNewReportsFlowEnabled = orgSettings?.simplified_report_closure_settings?.enabled || false;
done but
Same comment as [here](https://github.com/fylein/fyle-mobile-app/pull/1723/files#r1121743870)

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            [name]="(isNewReportsFlowEnabled$ | async) ? 'Submitted' : 'Reported'"
simplifyReportsEnabled

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +  isNewReportsFlowEnabled$: Observable<boolean>;
simplifyReportsEnabled

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/my-reports/my-reports-card/my-reports-card.component.ts
> +  @Input() isNewReportsFlowEnabled: Boolean;
simplifyReportsEnabled

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/my-reports/my-reports.page.html
> +          [isNewReportsFlowEnabled]="isNewReportsFlowEnabled$ | async"
simplifyReportsEnabled

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/my-reports/my-reports.page.ts
> +  isNewReportsFlowEnabled$: Observable<boolean>;
simplifyReportsEnabled

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/my-reports/my-reports.page.ts
> +  isCCCOnlyOrg$: Observable<boolean>;
nonReimbursableOrg

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/my-reports/my-reports.page.ts
> +    this.isNewReportsFlowEnabled$ = orgSettings$.pipe(
simplifyReportsEnabled

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/my-reports/my-reports.page.ts
> +      isNewReportsFlowEnabled: this.isNewReportsFlowEnabled$,
simplifyReportsEnabled

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/my-reports/my-reports.page.ts
> +      isCCCOnlyOrg: this.isCCCOnlyOrg$,
nonReimbursableOrg

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/team-reports/team-report-card/team-report-card.component.ts
> +  @Input() isNewReportsFlowEnabled: boolean;
simplifyReportsEnabled

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/team-reports/team-reports.page.html
> +          [isNewReportsFlowEnabled]="isNewReportsFlowEnabled"
simplifyReportsEnabled

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/team-reports/team-reports.page.ts
> +  isNewReportsFlowEnabled$: Observable<boolean>;
simplifyReportsEnabled

2023-03-02 06:33 UTC, gokulk16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +  isNewReportsFlowEnabled = false;
simplifyReportsEnabled

2023-03-02 12:50 UTC, yksolanki9 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            [name]="(isNewReportsFlowEnabled$ | async) ? 'Submitted' : 'Reported'"
This value will be null while the API is being resolved, so, we'll have to show shimmers.
Inside this component, change the condition to `isLoading = isNewReportsFlowEnabled === null  || reportStatsLoading`

2023-03-02 12:54 UTC, yksolanki9 commented on src/app/fyle/my-reports/my-reports.page.html
> +          [isNewReportsFlowEnabled]="isNewReportsFlowEnabled$ | async"
Show loader till this is not resolved, you'll have to move this inside `*ngIf`

2023-03-02 13:04 UTC, yksolanki9 requested changes

2023-03-02 13:04 UTC, yksolanki9 commented on src/app/fyle/my-reports/my-reports.page.ts
> +    return filterOptions;
`filterOptions` will be undefined here, the code inside subscribe is async

2023-03-02 13:04 UTC, yksolanki9 commented on src/app/fyle/team-reports/team-reports.page.ts
> +    return filterOptions;
`filterOptions` will be undefined here

2023-03-02 13:05 UTC, yksolanki9 reviewed
Get green from @Julias0 before merging

2023-03-03 07:42 UTC, arjunaj5 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            [name]="(isNewReportsFlowEnabled$ | async) ? 'Submitted' : 'Reported'"
done, changed to
`[loading]="(simplifyReportsEnabled$ | async) === null || reportStatsLoading"`

2023-03-03 09:14 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.ts
> +          orgSettings.payment_mode_settings?.payment_modes_order[0] === 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT'
Yes, used `AllowedPaymentModes.PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT` enum.

2023-03-03 09:14 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.html
> +          [isNewReportsFlowEnabled]="isNewReportsFlowEnabled$ | async"
done

2023-03-06 04:05 UTC, Julias0 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            [loading]="(simplifyReportsEnabled$ | async) === null || reportStatsLoading"
This is not correct. simplifyReportsEnabled$ when not completed should cause the reportStatsLoading to be true. Once loaded, based on its value will change the value on name.

You ng-container to resolve the observable with ngIf and use else to show the loading state.

2023-03-06 04:06 UTC, Julias0 commented on src/app/fyle/my-reports/my-reports.page.html
> +      *ngIf="isLoading || (simplifyReportsEnabled$ | async) === null"
Again - dont use observables like this - use ng-container to resolve them first.

Read through 
https://ultimatecourses.com/blog/angular-ngif-async-pipe

2023-03-06 04:08 UTC, Julias0 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      const reportState = new ReportState();
shouldnt we dependency inject this instead of directly loading it? Otherwise this component will become very hard to unit test in the future

2023-03-06 04:09 UTC, Julias0 requested changes
Added comments

2023-03-06 12:13 UTC, arjunaj5 commented on src/app/fyle/team-reports/team-reports.page.ts
> +    return filterOptions;
fixing this in another sub PR

2023-03-06 12:13 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.ts
> +    return filterOptions;
fixing this in another sub pr

2023-03-06 12:13 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.ts
> +    const orgSettings$ = this.orgSettingsService.get();
done

2023-03-07 14:53 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.html
> +      *ngIf="isLoading || (simplifyReportsEnabled$ | async) === null"
this is done, 🏋️

2023-03-07 16:03 UTC, arjunaj5 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            [loading]="(simplifyReportsEnabled$ | async) === null || reportStatsLoading"
this is done, using as clause to set a local variable `loaded` and using it to show loading state, not using `else` as it used to refer to template.

2023-03-07 16:41 UTC, arjunaj5 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      const reportState = new ReportState();
this is done.

2023-03-09 07:12 UTC, yksolanki9 requested changes

2023-03-09 07:12 UTC, yksolanki9 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      this.simplifyReportsEnabled = res?.orgSettings?.simplified_report_closure_settings?.enabled;
Check this once with this setting enabled on a slow internet connection. If the report name changes from Reported to Submitted, convert this to an observable

2023-03-09 07:12 UTC, yksolanki9 commented on src/app/shared/pipes/report-state.pipe.ts
> +  transform(val, simplifyReportsEnabled = false) {
[Optional] We can make call to orgSettings and check if simplify report closure is enabled inside the pipe itself, this way, we'll not have to create a new variable in every file.
Discussed here - https://fylein.slack.com/archives/C03JJJP4MSL/p1677076372597599?thread_ts=1676979046.565799&cid=C03JJJP4MSL

2023-03-09 13:54 UTC, arjunaj5 commented on src/app/fyle/dashboard/stats/stats.component.html
> +          <ng-container *ngIf="(simplifyReportsEnabled$ | async) !== null as loaded">
If using the above-given snippet, the stats will be shown only if (simplifyReportsEnabled$ | async) evaluates to true, for accounts where the flow is disabled, the stats won't show up.

2023-03-09 13:58 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.html
> +    <ng-container *ngIf="!isLoading && (simplifyReportsEnabled$ | async) !== null; else loading">
added the reason above 🤕

2023-03-09 14:03 UTC, arjunaj5 commented on src/app/fyle/team-reports/team-reports.page.html
> +    <ng-container *ngIf="!isLoading && (simplifyReportsEnabled$ | async) !== null; else loading">
Added the reason [here](https://github.com/fylein/fyle-mobile-app/pull/1723#discussion_r1131063680)

2023-03-09 14:32 UTC, arjunaj5 commented on src/app/fyle/my-view-report/my-view-report.page.html
> +                {{erpt.rp_state | reportState : (simplifyReportsEnabled$ | async) | snakeCaseToSpaceCase}}
We will need to make two subscriptions to do this, reason mentioned [here](https://github.com/fylein/fyle-mobile-app/pull/1723#discussion_r1131063680).
Also checked this in slow internet connection, there is no flickering of the state pill, most probably because we are taking the org settings from cache.

2023-03-09 14:36 UTC, arjunaj5 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      this.simplifyReportsEnabled = res?.orgSettings?.simplified_report_closure_settings?.enabled;
Checked this, and in most of cases, the pill is coming first with the correct value even before other components are loaded. Mostly because the org settings is taken from cache: 
Loom recording: https://www.loom.com/share/c6ef2e0fef694a3ebc07b48dbc02ba54

2023-03-10 05:01 UTC, yksolanki9 commented on src/app/fyle/dashboard/stats/stats.component.html
> +          <ng-container *ngIf="(simplifyReportsEnabled$ | async) !== null as loaded">
Mentioned approach in slack

2023-03-10 05:14 UTC, Julias0 commented on src/app/fyle/dashboard/stats/stats.component.html
> +          <ng-container *ngIf="(simplifyReportsEnabled$ | async) !== null as loaded">
(simplifyReportsEnabled$ | async) !== null dont resolve observables like this as I already referenced. If you need this transformation, create a new observable from the older one and then use it

2023-03-10 05:15 UTC, Julias0 commented on src/app/fyle/my-reports/my-reports.page.html
> +    <ng-container *ngIf="!isLoading && (simplifyReportsEnabled$ | async) !== null; else loading">
So dont use a boolean observable - use a map operator and put it inside an object no

2023-03-10 05:16 UTC, Julias0 requested changes
Added comments

2023-03-10 05:16 UTC, arjunaj5 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      this.simplifyReportsEnabled = res?.orgSettings?.simplified_report_closure_settings?.enabled;
Update: This worked in all of the cases, in most of the cases, the pill with the correct value comes up first even before other components are loaded.

2023-03-10 08:14 UTC, yksolanki9 approved these changes

2023-03-13 05:49 UTC, Julias0 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            *ngIf="!reportStatsLoading && (simplifyReportsSettings$ | async) as simplifyReportsSettings; else loading"
Can you combine simplifyReportsSettings$ and reportStatsLoading into the same observable?

2023-03-13 05:50 UTC, Julias0 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            *ngIf="!reportStatsLoading && (simplifyReportsSettings$ | async) as simplifyReportsSettings; else loading"
That way, there is no chance of the loading state being different in different cases

2023-03-13 05:50 UTC, Julias0 commented on src/app/fyle/my-reports/my-reports.page.html
> +    <ng-container *ngIf="!isLoading && (simplifyReportsSettings$ | async) as simplifyReportsSettings; else loading">
combine into the same observable

2023-03-13 05:51 UTC, Julias0 requested changes
Added comments

2023-03-14 13:15 UTC, arjunaj5 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            *ngIf="!reportStatsLoading && (simplifyReportsSettings$ | async) as simplifyReportsSettings; else loading"
Fixed this

2023-03-14 13:20 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.html
> +    <ng-container *ngIf="!isLoading && (simplifyReportsSettings$ | async) as simplifyReportsSettings; else loading">
Not sure, how to convert this isLoading into an observable. 

Reason: The `isLoading` is set to `true` on the `ionViewWillEnter` method, after this many observables are created (including `simplifyReportsSettings$`)  and subscribed to, at the end of the method, the isLoading is set to `false` after a timeout.

Please help @Julias0

2023-03-15 05:03 UTC, Julias0 commented on src/app/fyle/my-reports/my-reports.page.html
> +    <ng-container *ngIf="!isLoading && (simplifyReportsSettings$ | async) as simplifyReportsSettings; else loading">
you can just use 2 ng-containers with separate ng-ifs. The other way is to change isLoading into an observable with a behaviourSubject

2023-03-15 05:05 UTC, Julias0 commented on src/app/fyle/my-view-report/my-view-report.page.html
> +                {{erpt.rp_state | reportState : (simplifyReportsEnabled$ | async) | snakeCaseToSpaceCase}}
Even then - async observables are cleaner if they are resolved independently. This multiple pipes statement is difficult to read and you have nested pipes

2023-03-15 05:07 UTC, Julias0 commented on src/app/shared/pipes/report-state.pipe.ts
>  export class ReportState implements PipeTransform {
Are there no unit tests with report-state.pipe? Please to check code coverage and update it if required

2023-03-15 05:07 UTC, Julias0 requested changes
Added comments

2023-03-15 05:15 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.html
> +    <ng-container *ngIf="!isLoading && (simplifyReportsSettings$ | async) as simplifyReportsSettings; else loading">
Thanks, fixed this following:
> you can just use 2 ng-containers with separate ng-ifs

2023-03-15 05:36 UTC, arjunaj5 commented on src/app/shared/pipes/report-state.pipe.ts
>  export class ReportState implements PipeTransform {
Yes, there are unit tests,  updated the tests with new test cases,

2023-03-15 05:42 UTC, arjunaj5 commented
Fixed the comments @Julias0 , please re-review  🙏

2023-03-17 05:19 UTC, Julias0 commented on src/app/fyle/dashboard/stats/stats.component.html
> +              [value]="(reportedStats$ | async)?.sum"
Hey didnt we decide to resolve these before passing it to components?

2023-03-17 05:21 UTC, Julias0 requested changes
PLease resolve all async variables before passing it to components

2023-03-17 06:54 UTC, arjunaj5 commented on src/app/fyle/dashboard/stats/stats.component.html
> +              [value]="(reportedStats$ | async)?.sum"
Sorry, missed this as this was just copy paste and I did not have any changes in these,

2023-03-20 08:59 UTC, Julias0 commented on src/app/fyle/my-reports/my-reports-card/my-reports-card.component.ts
> +  @Input() simplifyReportsEnabled: Boolean;
Boolean -> boolean

2023-03-20 10:12 UTC, Julias0 approved these changes

2023-03-21 06:07 UTC, merged