Code Coverage: Split Expense Service #1
fylein/fyle-mobile-app pull request #1748
Opened 2023-03-03 12:10 UTC by jayfyle

# Edit 1: Coverage at 63

![split_exp_63](https://user-images.githubusercontent.com/115472256/222716780-9ffd6525-02c7-4a1d-beff-660c8e11e692.png)

2023-03-03 12:22 UTC, Dimple16 requested changes

2023-03-03 12:22 UTC, Dimple16 commented on src/app/core/mock-data/file-txn.data.ts
> +      content:
let's use some dummy string here? 
else it'll get very difficult

2023-03-03 12:22 UTC, Dimple16 commented on src/app/core/mock-data/policy-violation.data.ts
> +export const policyViolationData3 = {
what data type is this?

2023-03-03 12:22 UTC, Dimple16 commented on src/app/core/models/file-txn.model.ts
> +export interface File {
we already have an existing interface named `File` no?

2023-03-03 12:22 UTC, Dimple16 commented on src/app/core/services/split-expense.service.ts
> +  createTxns(
add types for all the arguments

2023-03-03 13:02 UTC, jayfyle commented on src/app/core/models/file-txn.model.ts
> +export interface File {
Yes, but that does not have any common properties with this interface, and I created it here for use in this file only.

2023-03-06 12:00 UTC, Dimple16 requested changes
added comments

2023-03-06 12:00 UTC, Dimple16 commented on src/app/core/models/file-txn.model.ts
> +export interface File {
no no, this will get very confusing, use a different name

2023-03-06 12:00 UTC, Dimple16 commented on src/app/core/services/split-expense.service.spec.ts
> +    const postCommentSpy = spyOn<any>(splitExpenseService, 'postComment');
why is this `spyOn<any>`?

2023-03-06 12:00 UTC, Dimple16 commented on src/app/core/services/split-expense.service.spec.ts
> +    expect(
you should also mock `formatDisplayName` here

2023-03-06 12:00 UTC, Dimple16 commented on src/app/core/services/split-expense.service.spec.ts
> +    policyService.getPolicyRules.and.returnValue([
why not move these to a different file?

2023-03-06 13:47 UTC, Dimple16 approved these changes
one minor comment

2023-03-06 13:47 UTC, Dimple16 commented on src/app/core/mock-data/crtical-policy-violations.data.ts
> +export const criticalPolicyViolation1 = [
`criticalPolicyViolation1: string[]`

2023-03-06 13:47 UTC, merged