State name changes for filter options || Simplified Report Closure
fylein/fyle-mobile-app pull request #1753
Opened 2023-03-06 11:39 UTC by arjunaj5

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1GjHeHRRmdRxTnKfnqB0nqBKybK3GvBg%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=CgRfspq)

2023-03-06 13:02 UTC, yksolanki9 commented on src/app/fyle/team-reports/team-reports.page.ts
> +        simplifyReportsEnabled$: this.simplifyReportsEnabled$,
same as above

2023-03-06 13:04 UTC, yksolanki9 requested changes
Passing obvservables to dialog is not a good practive, resolve it in the parent component itself, and pass the result to the dialog

2023-03-08 06:25 UTC, arjunaj5 commented on src/app/fyle/my-reports/my-reports.page.ts
> +        simplifyReportsEnabled$: this.simplifyReportsEnabled$,
If we resolve in the parent component itself, we would not be able to show the skeleton loaders as the modal does not react to changes in the `componentProps`. We will have to disable the filter funnel icon in this case. Is this fine?  @yksolanki9

2023-03-09 06:51 UTC, yksolanki9 approved these changes
Minor comment

2023-03-09 06:51 UTC, yksolanki9 commented on src/app/shared/components/fy-filters/fy-filters.component.ts
> +    const stateFilterIndex = this.filterOptions.findIndex((option) => option.name === 'State');
Move this inside forkJoin since it is not used anywhere else

2023-03-20 14:12 UTC, merged