Sign In Page Design Update
fylein/fyle-mobile-app pull request #1757
Opened 2023-03-07 09:00 UTC by jayfyle

# Design Update for sign in page:

![sign_in_3](https://user-images.githubusercontent.com/115472256/223373578-df16bbcc-f791-40e5-a813-ecf4a402e86c.png)

2023-03-09 13:56 UTC, jayfyle commented on src/app/auth/sign-in/sign-in.page.scss
> +$secondary-cta-border: #a9acbc;
Changed colour as it was in the figma file

2023-03-09 13:56 UTC, jayfyle commented on src/app/auth/sign-in/sign-in.page.scss
> +    border-radius: 8px;
Border-radius in the file was 8px and padding was 40 and 24

2023-03-10 05:52 UTC, Dimple16 requested changes
added comments

2023-03-10 05:52 UTC, Dimple16 commented on src/app/auth/sign-in/sign-in.page.html
> +<ion-content class="background">
follow the bem, add a class inside `.sign-in` something like `--page-container`

2023-03-10 05:52 UTC, Dimple16 commented on src/app/auth/sign-in/sign-in.page.html
> +<ion-content class="background">
and use it here as `class="sign-in--page-container"`

2023-03-10 05:52 UTC, Dimple16 commented on src/app/auth/sign-in/sign-in.page.scss
> +$secondary-cta-border: #a9acbc;
use the colors from the `colors.scss` file, refer the `/themes` folder

2023-03-10 05:52 UTC, Dimple16 commented on src/app/auth/sign-in/sign-in.page.scss
> +$secondary-cta-border: #a9acbc;
`$grey-light` is already defined, you can use the same,

2023-03-10 05:52 UTC, Dimple16 commented on src/app/auth/sign-in/sign-in.page.scss
> +.background {
this will go inside the `.sign-in` block

2023-03-10 05:52 UTC, Dimple16 commented on src/app/auth/sign-in/sign-in.page.scss
> +    padding: 40px 24px;
why `40px`?  is it 40 in design?

2023-03-10 05:52 UTC, Dimple16 commented on src/app/auth/sign-in/sign-in.page.scss
> +      gap: 10px;
check if this is responsive and looks fine in all the resolutions of devices

2023-03-13 10:28 UTC, Dimple16 approved these changes

2023-03-13 17:22 UTC, Dimple16 approved these changes

2023-03-14 07:09 UTC, merged