Show more fix
fylein/fyle-mobile-app pull request #1759
Opened 2023-03-07 09:40 UTC by suyashpatil78

Whenever user clicks on 'Show More' in Add Expense, we persist the data in localStorage so that user doesn't need to click again and again.

2023-03-07 10:30 UTC, Julias0 requested changes

2023-03-07 10:30 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    }
Should you be setting this to isExpandedView since you are again setting this variable again later. What would be a better/more readable way to do this?

2023-03-07 10:31 UTC, Julias0 requested changes

2023-03-07 10:31 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    JSON.stringify(localStorage.removeItem('isExpandedView'));
Is there a way to prevent the repetition of this every time we change `isExpandedView`? What will be a cleaner way to do this?

2023-03-07 10:39 UTC, suyashpatil78 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    console.log(typeof JSON.parse(localStorage.getItem('isExpandedView')));
yes @Julias0 removed that in the next commits

2023-03-07 11:09 UTC, suyashpatil78 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    }
Yes, moving the logic in `ionViewWillEnter` so that it doesn't set the variable again.

2023-03-07 14:08 UTC, suyashpatil78 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    console.log(typeof JSON.parse(localStorage.getItem('isExpandedView')));
@Julias0 I have used the recentLocalStorage service to persist the data and added the commits

2023-03-09 05:52 UTC, yksolanki9 requested changes
Use storageService, recentLocalStorageItemsService is sort of a persistant cache in local storage which we use to store recently used projects, categories, etc.
recentLocalStorageItemsService is built on top of storageService and has additional checks which are not needed here

2023-03-09 07:13 UTC, suyashpatil78 commented
> Use storageService, recentLocalStorageItemsService is sort of a persistant cache in local storage which we use to store recently used projects, categories, etc. recentLocalStorageItemsService is built on top of storageService and has additional checks which are not needed here

I have changed the service

2023-03-09 07:21 UTC, yksolanki9 requested changes

2023-03-09 07:21 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.storageService.delete('isExpandedView');
Why delete it? Set it to false instead?

2023-03-09 07:21 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      if (expandedView === true) {
`this.isExpandedView = this.mode !== 'add' || expandedView`

2023-03-09 07:38 UTC, suyashpatil78 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      if (expandedView === true) {
@yksolanki9 I have done the required changes.

2023-03-09 08:55 UTC, yksolanki9 approved these changes

2023-03-09 09:09 UTC, suyashpatil78 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    JSON.stringify(localStorage.removeItem('isExpandedView'));
I am now setting isExpandedView to false rather than removing it.

2023-03-10 04:54 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.storageService.set('isExpandedView', false);
Is there a better way to keep the value of this.isExpandedView and isExpandedView in sync?

2023-03-10 08:50 UTC, suyashpatil78 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.storageService.set('isExpandedView', false);
@Julias0 I have added the getter and setter methods. Please have a look at it.

2023-03-13 05:38 UTC, Julias0 approved these changes

2023-03-13 08:41 UTC, merged