Code Coverage: Auth Service #1
fylein/fyle-mobile-app pull request #1764
Opened 2023-03-09 11:39 UTC by jayfyle

# Edit 1: Coverage at 86

![auth_86](https://user-images.githubusercontent.com/115472256/224012466-817fad9b-1dba-4021-911c-8360a4980add.png)

2023-03-09 11:49 UTC, jayfyle commented on src/app/core/services/auth.service.spec.ts
> +          expect(storageService.delete).toHaveBeenCalledOnceWith('recentlyUsedProjects');
@Dimple16 , I have a doubt here, I was trying to cover the `finalize` block, and I was able to get the coverage but here there should be many calls to storage service with different parameters but they do not happen. The test fails stating this is the only call that went through

2023-03-10 11:13 UTC, Dimple16 requested changes
added comments

2023-03-10 11:13 UTC, Dimple16 commented on src/app/core/services/auth.service.spec.ts
> +    it('should get roles from access token', (done) => {
mocking the try-catch block is missing, you will have to spyOn JSON, 'parse'

2023-03-10 11:13 UTC, Dimple16 commented on src/app/core/services/auth.service.spec.ts
> +          expect(storageService.delete).toHaveBeenCalledOnceWith('recentlyUsedProjects');
try this method:
```
it('should logout and delete all storage items', fakeAsync(() => {
spyOn(storageService, 'delete').and.returnValue(Promise.resolve());
authService
      .logout(payload).subscribe(() => {
       expect(apiService.post).toHaveBeenCalledWith('/auth/logout', Payload);
       expect(storageService.delete).toHaveBeenCalledWith('recentlyUsedProjects');
       expect(storageService.delete).toHaveBeenCalledWith('recentlyUsedCategories');
       ....and so on...
       tick();
  }));
```

2023-03-13 17:31 UTC, Dimple16 requested changes
added comments

2023-03-13 17:31 UTC, Dimple16 commented on src/app/core/services/auth.service.spec.ts
> +    it('should get roles from access token', (done) => {
this isn't taken care of yet?

2023-03-13 17:31 UTC, Dimple16 commented on src/app/core/services/auth.service.spec.ts
> +        expect(storageService.delete).toHaveBeenCalledOnceWith('ui-grid-pagination-page-size');
we don't use these, you should remove these from here,  `ui-grid-pagination-page-size`, 
`ui-grid-pagination-page-number`, `customExportFields` etc, are never used,
can you individually check what are used and keep them? remove the unused code

2023-03-14 12:53 UTC, Dimple16 approved these changes

2023-03-14 12:53 UTC, Dimple16 commented on src/app/core/services/auth.service.spec.ts
> +          expect(storageService.delete).toHaveBeenCalledWith('recentlyUsedProjects');
add a `Todo` to revisit this section

2023-03-14 13:36 UTC, merged