Code Coverage: Approver Platform API Service
fylein/fyle-mobile-app pull request #1771
Opened 2023-03-10 11:59 UTC by jayfyle

# Coverage at 100%

![approver_platform_api_100](https://user-images.githubusercontent.com/115472256/224310613-053339d5-d489-4918-b399-c419f49742b1.png)

2023-03-10 12:07 UTC, Dimple16 requested changes

2023-03-13 07:09 UTC, rvab requested changes
Sending it back for now. https://fylein.slack.com/archives/C049CK3JPJQ/p1678691268011879?thread_ts=1678690034.186059&cid=C049CK3JPJQ

2023-03-14 06:03 UTC, rvab requested changes

2023-03-14 06:03 UTC, rvab commented on src/app/core/services/approver-platform-api.service.spec.ts
> +        expect(res).toEqual(ApproverExpensePolicyStatesData);
`done` should be here. When you execute `req.flush`, then the mocking of HTTP happens.

2023-03-14 07:24 UTC, jayfyle commented on src/app/core/services/approver-platform-api.service.spec.ts
> +      expect();
Autocomplete typo, I have removed it.

2023-03-14 07:36 UTC, rvab approved these changes

2023-03-14 07:41 UTC, Dimple16 approved these changes

2023-03-14 07:45 UTC, merged