fix:Dashboard stats changes for Simplified report closure
fylein/fyle-mobile-app pull request #1773
Opened 2023-03-10 13:35 UTC by arjunaj5

https://app.clickup.com/t/85zrpcyvg
Slack thread: https://fylein.slack.com/archives/C03JJJP4MSL/p1677559257845899

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19TQh59Vo8IitetzdWbSuUCfXLGdM51cwY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=iTffk3Y)

Changes in this PR:

1. Service function to check for nonreimbursable accounts. (accounts having CCC only or CCC + paid by company payment modes)
2. Dashboard stats changes to remove Approved and Payment spending stats for non-reimbursable only accounts in the new flow
3. Dashboard stats changes to change p`ayment pending` stat to `processing` stat for reimbursable accounts in the new flow.

2023-03-13 04:56 UTC, gokulk16 approved these changes

2023-03-13 05:48 UTC, yksolanki9 requested changes

2023-03-13 05:48 UTC, yksolanki9 commented on src/app/core/models/org_user_settings.model.ts
> +import { AllowedPaymentModes } from './allowed-payment-modes.enum';
Is the import needed?

2023-03-13 05:48 UTC, yksolanki9 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            <ng-container *ngIf="simplifyReportsSettings.enabled">
Put this inside `ng-template`

2023-03-13 05:48 UTC, yksolanki9 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            <ng-container *ngIf="!simplifyReportsSettings.enabled">
Use else if `<ng-container *ngIf="...; else "> `

2023-03-13 05:48 UTC, yksolanki9 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +import { concat, interval, of, Subject } from 'rxjs';
Remove unused imports

2023-03-13 05:48 UTC, yksolanki9 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +      this.isNonReimbursableOrg = this.paymentModeService.isNonReimbursableOrg(orgSettings.payment_mode_settings);
Convert this to observable, else user may see old value

2023-03-13 12:19 UTC, arjunaj5 commented on src/app/core/models/org_user_settings.model.ts
> +import { AllowedPaymentModes } from './allowed-payment-modes.enum';
no, removed it

2023-03-13 12:19 UTC, arjunaj5 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            <ng-container *ngIf="simplifyReportsSettings.enabled">
done

2023-03-13 12:19 UTC, arjunaj5 commented on src/app/fyle/dashboard/stats/stats.component.html
> +            <ng-container *ngIf="!simplifyReportsSettings.enabled">
yes, done 🚀

2023-03-13 12:19 UTC, arjunaj5 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +import { concat, interval, of, Subject } from 'rxjs';
:done

2023-03-13 12:20 UTC, arjunaj5 commented on src/app/fyle/dashboard/stats/stats.component.ts
> +      this.isNonReimbursableOrg = this.paymentModeService.isNonReimbursableOrg(orgSettings.payment_mode_settings);
converted to observable.

2023-03-14 04:36 UTC, yksolanki9 approved these changes

2023-03-20 15:19 UTC, merged