feat: Dependent Fields: Create new component for dependent fields
fylein/fyle-mobile-app pull request #1785
Opened 2023-03-14 12:57 UTC by yksolanki9

2023-03-15 11:45 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            this.dependentFieldsRef.addDependentFieldWithValue(
Calling this method with the ref as there's no easier way to do this. Can discuss this over a call if this doesn't work

2023-03-16 09:39 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +      .subscribe((res) => {
rename res to an appropiate name

2023-03-16 09:40 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +          .subscribe((res) => {
rename from res

2023-03-16 11:07 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +  ngOnDestroy() {
Yes it won't, so calling this method from `ionViewWillLeave()` of the parent page

2023-03-16 11:27 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +      .subscribe((res) => {
Done

2023-03-16 11:27 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +          .subscribe((res) => {
Done

2023-03-16 12:21 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +    this.expenseForm?.controls.project.valueChanges
If we want to reuse this component for cost center, category etc, will that be doable?

2023-03-17 07:41 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +    this.expenseForm?.controls.project.valueChanges
Can ask Neeraj to add some dependent fields for cost center and do a small demo next week

2023-03-20 06:15 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +    this.expenseForm?.controls.project.valueChanges
what if we pass the project value through an input and handle the value inside onChanges

2023-03-20 06:16 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +    this.expenseForm?.controls.project.valueChanges
If remove the dependency of passing the project value and the controls this would become generic

2023-03-20 06:16 UTC, Julias0 requested changes
Added comments

2023-03-20 07:07 UTC, rvab requested changes

2023-03-20 07:07 UTC, rvab commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.dependentFieldsRef.ngOnDestroy();
Why call `ngOnDestroy` programmatically?

2023-03-20 07:07 UTC, rvab commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +    this.expenseForm?.controls.project.valueChanges
I agree with @Julias0 on removing the dependency on the expense form and project value.

2023-03-20 08:25 UTC, yksolanki9 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +    this.dependentFieldsRef?.ngOnInit();
That's how ionic works, when you're redirected from one page to another, the component is not destroyed, but the page is stored in a stack. 
When user visits the page again `ngOnInit()` is not triggered. We use  `ionViewWillEnter()` lifecycle hook in such cases

2023-03-20 08:28 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.dependentFieldsRef.ngOnDestroy();
Same reason as above

2023-03-29 05:46 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +    this.expenseForm?.controls.project.valueChanges
Resolved the commenrts in child pr

2023-03-29 05:52 UTC, rvab approved these changes

2023-03-29 05:59 UTC, Julias0 approved these changes

2023-03-30 06:08 UTC, merged