feat: Dependent Fields: Refactoring
fylein/fyle-mobile-app pull request #1816
Opened 2023-03-21 13:59 UTC by yksolanki9

2023-03-21 15:20 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                <ng-container *ngIf="selectedProject$|async as selectedProject">
`selectedProject$` is a BehaviourSubject - added more details below

2023-03-23 03:03 UTC, rvab approved these changes
Minor comments. Apart from selectedProject$, rest lgtm

2023-03-23 03:03 UTC, rvab commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  selectedProject$: BehaviorSubject<ExtendedProject>;
I'm not sure if this is a good approach. Right now we can go ahead with it.

2023-03-23 03:03 UTC, rvab commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +    this.onPageExit$?.complete();
When will `this.onPageExit$` be undefined?

2023-03-23 05:48 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +      this.onPageExit$ = new Subject();
why is this initialized inside ngOnChanges? Why not do it inside ngOnInit?

2023-03-23 05:48 UTC, Julias0 requested changes
1 comment - rest lgtm

2023-03-23 06:39 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +      this.onPageExit$ = new Subject();
ngOnChanges is called before ngOnInit. And the method inside ngOnChanges uses this subject, which is undefined when ngOnChanges is executed for the first time, so have initialized it in ngOnChanges as well

2023-03-23 06:41 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +    this.onPageExit$?.complete();
Not sure how it happened, but saw an error where this was undefined, so added optional chaining

2023-03-24 06:41 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-fields.component.ts
> +      this.onPageExit$ = new Subject();
Have removed the initialization from `ngOnInit()` and triggering initializing it in ngOnChanges only once using firstChange

2023-03-24 07:43 UTC, Julias0 approved these changes

2023-03-24 12:35 UTC, merged