feat: Optimization for setupFormInit
fylein/fyle-mobile-app pull request #1833
Opened 2023-03-24 11:04 UTC by suyashpatil78

method added to category service for fetching id specific category

Clickup Link - https://app.clickup.com/t/85zrtz58p

2023-03-24 12:11 UTC, yksolanki9 commented on src/app/core/services/categories.service.ts
> +  getCategoryById(id: number): Observable<OrgCategory> {
Add unit tests to this method. Check how tests are written for other methods, I can help if needed

2023-03-24 12:14 UTC, yksolanki9 requested changes
Add unit test for the new method and resolve Dhar's comments, rest lgtm

2023-03-28 06:48 UTC, yksolanki9 requested changes
Add ss for code coverage to confirm if all branches are covered

2023-03-28 06:48 UTC, yksolanki9 commented on src/app/core/mock-data/platform-api-category.data.ts
> +    {
Add 2 more categories with different id

2023-03-28 06:48 UTC, yksolanki9 commented on src/app/core/services/categories.service.spec.ts
> +      expect(res).toEqual(expectedOrgCategoryById[0]);
use object instead of accessing first value of array

2023-03-28 09:42 UTC, suyashpatil78 commented
Code Coverage - 
![image](https://user-images.githubusercontent.com/127177049/228196606-d3d0fd05-7e17-400a-b7ff-90f2879d0219.png)

2023-03-29 10:29 UTC, yksolanki9 approved these changes

2023-03-29 11:18 UTC, Julias0 approved these changes

2023-03-29 11:28 UTC, merged