test: Code Coverage 100% Footer component
fylein/fyle-mobile-app pull request #1842
Opened 2023-03-28 07:26 UTC by CODEX108

clickUp: https://app.clickup.com/t/85zru69dy

![image](https://user-images.githubusercontent.com/82377810/228160392-20b63283-8948-4ba4-8fac-c4d616a3d267.png)

2023-03-28 12:02 UTC, jayfyle approved these changes
looks good to me

2023-03-28 15:11 UTC, Dimple16 requested changes

2023-03-28 15:11 UTC, Dimple16 commented on src/app/shared/components/footer/footer.component.spec.ts
> +      spyOn(footerComponent.homeClicked, 'emit');
```
const homeClickedSpy = spyOn(footerComponent.homeClicked, 'emit');
expect(homeClickedSpy).toHaveBeenCalledTimes(1);
```

2023-03-28 15:11 UTC, Dimple16 commented on src/app/shared/components/footer/footer.component.spec.ts
> +      footerComponent.activeState = FooterState.TASKS;
shouldn't we add this `fixture.detectChanges();` when assigning `footerComponent.activeState`

2023-03-28 15:11 UTC, Dimple16 commented on src/app/shared/components/footer/footer.component.spec.ts
> +    spyOn(footerComponent.cameraClicked, 'emit');
same comment, assign it to a variable and reuse

2023-03-28 15:11 UTC, Dimple16 commented on src/app/shared/components/footer/footer.component.spec.ts
> +    it('should display the task count in the pill when there are tasks', fakeAsync(() => {
why use `fakeAsync` here?

2023-03-29 06:42 UTC, Dimple16 approved these changes

2023-03-29 06:49 UTC, merged