fix: Sign In Page Google Button Loader
fylein/fyle-mobile-app pull request #1843
Opened 2023-03-28 07:45 UTC by jayfyle

# Sign in with Google Button Loader fixed

2023-03-28 09:34 UTC, yksolanki9 requested changes
https://caniuse.com/css-display-contents
`display: contents` is not fully supported by all browsers. Can we try a different approach?

2023-03-30 04:20 UTC, Julias0 requested changes
Will review after Yash Solankis approval

2023-05-26 09:21 UTC, yksolanki9 approved these changes

2023-05-26 12:45 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.scss
>        align-items: center;
are align-items, justify-content and gap needed?

2023-05-29 04:38 UTC, Julias0 approved these changes

2023-05-29 05:27 UTC, yksolanki9 approved these changes

2023-05-29 05:29 UTC, merged