feat: Optimizations for checkPolicyViolation
fylein/fyle-mobile-app pull request #1869
Opened 2023-03-31 09:20 UTC by suyashpatil78

Clickup - https://app.clickup.com/t/85zruru5j

2023-03-31 09:26 UTC, suyashpatil78 commented
Coverage
![Screenshot 2023-03-31 at 2 55 26 PM](https://user-images.githubusercontent.com/127177049/229081821-6412aa7e-0f91-4324-8d9c-49bd8d60aa19.png)

2023-03-31 09:46 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          console.log(category);
Remove console log

2023-03-31 09:49 UTC, suyashpatil78 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          console.log(category);
@yksolanki9 done

2023-03-31 09:53 UTC, yksolanki9 requested changes

2023-03-31 09:53 UTC, yksolanki9 commented on src/app/core/services/categories.service.ts
> +      map((responses) => responses.find((response) => response.name === name))
why do we need to find by name again?

2023-03-31 09:53 UTC, yksolanki9 commented on src/app/core/services/categories.service.ts
> +        name: 'eq.' + name,
Confirm with backend team if the first name should be in upper or lower case?

2023-03-31 09:53 UTC, yksolanki9 commented on src/app/core/services/categories.service.ts
> +        name: 'eq.' + name,
Will it be better to use `ilike` to make it case insensitive?

2023-03-31 09:53 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          const unspecifiedCategory = category;
Another variable is not needed here

2023-03-31 09:58 UTC, suyashpatil78 commented on src/app/core/services/categories.service.ts
> +      map((responses) => responses.find((response) => response.name === name))
@yksolanki9 The data is coming in the form of array, therefore we need to get single response from it.
We have done same thing in getCategoryById - https://github.com/fylein/fyle-mobile-app/pull/1833/files#diff-00ea7bf26983400bc3a2227bb4c1695132c71429b10ebea74274d01ddf41e6eaR180

2023-03-31 10:07 UTC, suyashpatil78 commented on src/app/core/services/categories.service.ts
> +        name: 'eq.' + name,
The data could be in uppercase and lowercase, both. So it is better to use `ilike`

2023-03-31 11:57 UTC, Julias0 commented on src/app/core/services/categories.service.ts
> +        name: 'ilike.%' + name + '%',
if we are searching by the whole name, lets avoid using `%` for wild card characters, since in certain cases it might lead to wrong results.

Example - 
You have `Lunch` and `Team Lunch`. If you search with the above, you run the risk of getting team lunch when searching for lunch

2023-03-31 12:04 UTC, suyashpatil78 commented on src/app/core/services/categories.service.ts
> +        name: 'ilike.%' + name + '%',
Got it!

2023-03-31 12:11 UTC, yksolanki9 commented on src/app/core/services/categories.service.ts
> +        name: 'ilike.%' + name + '%',
Yeah I meant ilike without the matching operator

2023-03-31 12:12 UTC, yksolanki9 commented on src/app/core/services/categories.service.ts
> +      map((responses) => responses.find((response) => response.name === name))
Do you need to find an element inside an array which has only one element?

2023-04-03 05:43 UTC, yksolanki9 commented on src/app/core/services/categories.service.ts
> +      map((responses) => responses.find((response) => response.name === name))
Yes, this was what I was hinting towards

2023-04-03 07:31 UTC, yksolanki9 approved these changes

2023-04-03 10:13 UTC, Julias0 approved these changes

2023-04-03 10:14 UTC, merged