test: Code coverage dateRangeModal component
fylein/fyle-mobile-app pull request #1872
Opened 2023-03-31 14:59 UTC by CODEX108

clickUp: https://app.clickup.com/t/85zrum1n2

![image](https://user-images.githubusercontent.com/82377810/229156468-a5617134-d0d2-423c-beed-3b8fee0f8f8a.png)

2023-04-03 05:14 UTC, Julias0 commented on src/app/fyle/personal-cards/date-range-modal/date-range-modal.component.spec.ts
> +    const endDate = (component.dateRangeEnd.nativeElement.value = '2022-01-15');
Please dont do assignment to two different variables in the same statement

2023-04-03 05:14 UTC, Julias0 requested changes
minor comment - fix and merge

2023-04-03 06:47 UTC, Dimple16 approved these changes

2023-04-04 04:26 UTC, Julias0 commented on src/app/fyle/personal-cards/date-range-modal/date-range-modal.component.spec.ts
> +  beforeEach(waitForAsync(() => {
why is this added to beforeEach?

2023-04-04 04:26 UTC, Julias0 approved these changes

2023-04-04 04:58 UTC, CODEX108 commented on src/app/fyle/personal-cards/date-range-modal/date-range-modal.component.spec.ts
> +  beforeEach(waitForAsync(() => {
The `async()` method is deprecated and `waitForAsync()` is used instead, therefore the waitForAsync is used in beforeEach.

2023-04-04 05:03 UTC, merged