test: Code coverage :  ExpenseCardLite Component
fylein/fyle-mobile-app pull request #1894
Opened 2023-04-04 11:06 UTC by CODEX108

clickup: https://app.clickup.com/t/85zrv3vu6
![image](https://user-images.githubusercontent.com/82377810/229772950-8af1bb7d-965a-4983-bd7f-9efb89319c46.png)

2023-04-05 05:16 UTC, Julias0 commented on src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
> +      expect(fileService.downloadThumbnailUrl).toHaveBeenCalledTimes(2);
Why is the call going out to `fileService.downloadThumbnailUrl` and `fileService.getFilesWithThumbnail` twice? This seems to be a bug no

2023-04-05 05:16 UTC, Julias0 commented on src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
> +      expect(fileService.getFilesWithThumbnail).toHaveBeenCalledTimes(2);
Same as above

2023-04-05 05:16 UTC, Julias0 requested changes
Added comments

2023-04-10 09:38 UTC, CODEX108 commented on src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
> +      expect(fileService.getFilesWithThumbnail).toHaveBeenCalledTimes(2);
to cover the else block in the test case, I have called `getReceipt()` explicitly after setting the return value of fileService.getFilesWithThumbnail() to an empty array.

2023-04-10 11:27 UTC, Julias0 commented on src/app/shared/components/expense-card-lite/expense-card-lite.component.spec.ts
> +      expect(fileService.getFilesWithThumbnail).toHaveBeenCalledTimes(2);
lets remove this

2023-04-10 11:27 UTC, Julias0 approved these changes
1 minor comment - fix and merge

2023-04-10 12:06 UTC, jayfyle approved these changes

2023-04-10 12:52 UTC, merged