test: Code coverage SuggestedDuplicates Component
fylein/fyle-mobile-app pull request #1901
Opened 2023-04-05 15:36 UTC by CODEX108

clickUp: https://app.clickup.com/t/85zrv74xv
![image](https://user-images.githubusercontent.com/82377810/230130645-cc68ba33-f25f-49f2-9c39-2df5f671ab72.png)

2023-04-06 05:01 UTC, jayfyle approved these changes
Looks good to me

2023-04-10 04:47 UTC, Julias0 commented on src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.spec.ts
> +    expect(getTextContent(headerEl)).toContain('3 expenses for');
what are we testing for here?

2023-04-10 04:49 UTC, Julias0 commented on src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.spec.ts
> +    expect(getTextContent(headerEl)).toContain('3 expenses for');
we should check for the whole content right? 
Since the template it 
`{{ duplicateExpenses.length }} expenses for
        {{ duplicateExpenses[0].tx_amount | currency: duplicateExpenses[0].tx_currency:'symbol-narrow' }}`

2023-04-10 04:50 UTC, Julias0 commented on src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.spec.ts
> +    expect(getTextContent(headerEl)).toContain('3 expenses for');
We are not checking for `{{ duplicateExpenses[0].tx_amount | currency: duplicateExpenses[0].tx_currency:'symbol-narrow' }}`

2023-04-10 04:55 UTC, Julias0 requested changes
Added comments

2023-04-10 11:31 UTC, Julias0 approved these changes

2023-04-10 12:07 UTC, jayfyle approved these changes

2023-04-10 12:10 UTC, merged