test: Code Coverage: Receipt Preview Component
fylein/fyle-mobile-app pull request #1953
Opened 2023-04-24 09:07 UTC by jayfyle

### Clickup: https://app.clickup.com/t/85zrxn9rc

# Coverage at 95%

<img width="1440" alt="receipt_preview_95" src="https://user-images.githubusercontent.com/115472256/233951367-540ed839-ab59-4ef9-9880-d2fca3b883b3.png">

2023-04-24 13:54 UTC, Julias0 commented on src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
> +        of({
same as [this](https://github.com/fylein/fyle-mobile-app/pull/1953/files#r1175321691)

2023-04-24 13:54 UTC, Julias0 commented on src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
> +        new Promise((resolve) => {
remove nesting using promise.resolve

2023-04-24 13:55 UTC, Julias0 commented on src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
> +        new Promise((resolve) => {
remove nesting with promise.resolve

2023-04-24 13:55 UTC, Julias0 commented on src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
> +        new Promise((resolve) => {
remove nesting with promise.resolve

2023-04-24 13:55 UTC, Julias0 commented on src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
> +        new Promise((resolve) => {
remove nesting with promise.resolve

2023-04-24 13:55 UTC, Julias0 commented on src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
> +      new Promise((resolve) => {
remove nesting with promise.resolve

2023-04-24 13:55 UTC, Julias0 requested changes
added few comments

2023-04-24 15:23 UTC, jayfyle commented on src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
> +        of({
This returns a reference to material component ref, and the afterDismissed property returns an observable

2023-04-24 15:24 UTC, jayfyle commented on src/app/shared/components/capture-receipt/receipt-preview/receipt-preview.component.spec.ts
> +      new Promise((resolve) => {
Refactoring the outer promise fails the spec and does not recognise the spy objects, so I am restructuring the inner promises

2023-04-25 07:01 UTC, Julias0 approved these changes

2023-04-25 08:47 UTC, merged