test: Add tests for dependent-field component
fylein/fyle-mobile-app pull request #1960
Opened 2023-04-25 20:10 UTC by yksolanki9

Clickup: https://app.clickup.com/t/85zry9tdr

2023-04-27 12:34 UTC, jayfyle commented on src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.spec.ts
> +  it('registerOnTouched', () => {
Why does this test case not have fakeAsync?

2023-04-27 12:40 UTC, jayfyle approved these changes
Looks good to me, overall all specs seem fine. Although, there are no DOM tests. Maybe further specs can be included that check whether interacting with elements trigger the intended methods.

2023-04-28 09:16 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.spec.ts
> +  it('registerOnTouched', () => {
This is a sync event, so we don't need it

2023-05-02 06:40 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.spec.ts
> +    expect(component.onTouchedCallback).toEqual(callbackFn);
This assertion compares functions. We should test against the blur event and see if the spy got triggered or not

2023-05-02 06:41 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.spec.ts
> +    expect(component.onChangeCallback).toEqual(callbackFn);
Same as below, we should trigger an input event (value coming from modal) and see if the change callback spy got triggered or not

2023-05-02 06:43 UTC, Julias0 requested changes
Added comments

2023-05-03 12:54 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.spec.ts
> +    expect(component.onChangeCallback).toEqual(callbackFn);
Resolved

2023-05-03 12:54 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.spec.ts
> +    expect(component.onTouchedCallback).toEqual(callbackFn);
Resolved

2023-05-05 08:35 UTC, Julias0 approved these changes

2023-05-26 10:13 UTC, merged