test: 100% coverage of fy-filters
fylein/fyle-mobile-app pull request #1970
Opened 2023-04-26 17:58 UTC by suyashpatil78

Clickup - https://app.clickup.com/t/85zrxnabp

Coverage - 
![Screenshot 2023-04-26 at 11 27 40 PM](https://user-images.githubusercontent.com/127177049/234662871-69849ee1-3e08-4f9a-b300-6bc4d6aad491.png)

2023-04-27 12:14 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +    expect(component.activeFilter).toEqual({
you should set the value in the component and then check for an assertion. BeforeEach shouldn't be used to set up assertions except for default values, otherwise the tests cases would become difficult to read

2023-04-27 12:14 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +    expect(component.currentFilterValueMap).toEqual({
same as above

2023-04-27 12:15 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +  it('should set not custom date filter map correctly', () => {
you mean that if custom date option is not selected, the values will come as undefined?

2023-04-27 12:16 UTC, Julias0 requested changes
some comments

2023-04-27 12:21 UTC, suyashpatil78 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +  it('should set not custom date filter map correctly', () => {
Yes, changing the name of the test

2023-04-28 04:36 UTC, Julias0 commented on src/app/core/mock-data/filter.data.ts
> +export const filterOptions1 = [
This set of data for filter options look weird - we cant ever have a mix of expenses, reports and advances filters. Use some examples from ones which exist

2023-05-02 02:33 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +        optionType: FilterOptionType.multiselect,
shouldnt the type here be date?

2023-05-02 02:33 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +        optionType: FilterOptionType.multiselect,
same as above

2023-05-02 02:35 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +  it('should set filterOptions option', () => {
didnt understand what we are checking for in this test case

2023-05-02 02:37 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +      options: [
date type filter cannot have options like this

2023-05-02 02:44 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +    component.clearAll();
add assertions before clearAll is called to check if they were set properly before we called clearAll

2023-05-02 02:45 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +    expect(component.customDateMap['Expense Type']).toEqual({
How can Expense Type have date properties? This is not a date type filter

2023-05-02 02:45 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +          label: 'Sent Back',
date type filter created on cannot have options like this

2023-05-02 02:47 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +  it("switchSingleSelectFilter(): should update currentFilterValueMap if filter doesn't exist", () => {
in what case will filter not exist? Is the condition valid?

2023-05-02 02:47 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +    component.currentFilterValueMap = {
only filter1 is defined inside filterOptions, where did filter2 come from?

2023-05-02 02:47 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +      filter2: ['filter1', 'filter2'],
only filter1 is defined inside filterOptions, where did filter2 come from?

2023-05-02 02:48 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +      filter2: ['filter1', 'filter2'],
Why does filter1 have values not defined inside its options?

2023-05-02 02:48 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
PLease clean up the data passed into the test cases into things which can actually happen

2023-05-02 02:49 UTC, Julias0 requested changes
Added a bunch of comments

2023-05-02 07:11 UTC, suyashpatil78 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +  it("switchSingleSelectFilter(): should update currentFilterValueMap if filter doesn't exist", () => {
Yes, 
In `switchFilter()` method, we are using the `filter` variable to pass in `switchSingleSelectFilter()`. If filter is `undefined`, then `switchSingleSelectFilter()` will not have a `filter` parameter.

2023-05-03 04:59 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +      filter1: ['filter1', 'filter2'],
These values are not present in the options list right? So these values cant be selected no

2023-05-03 05:00 UTC, Julias0 commented on src/app/shared/components/fy-filters/fy-filters.component.spec.ts
> +      filter1: ['filter1', 'filter2'],
I see similar issues in the other test cases as well, please to fix them up

2023-05-03 05:03 UTC, Julias0 requested changes
Added comments

2023-05-04 10:10 UTC, Julias0 approved these changes

2023-05-04 10:47 UTC, merged