test:  Code Coverage FyNumber Component
fylein/fyle-mobile-app pull request #1977
Opened 2023-04-27 13:55 UTC by CODEX108

clickUp: https://app.clickup.com/t/85zrxnaed

2023-05-02 06:02 UTC, yksolanki9 requested changes

2023-05-02 06:02 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    component.handleChange({ target: { value: '12,' }, code: 'Comma' } as any);
Add a test case for when user enters `12,5`, `32,4533` and `0`

2023-05-02 06:02 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    launchDarklyService.checkIfKeyboardPluginIsEnabled.and.returnValue(of(true));
Add test cases for when this is false

2023-05-02 06:02 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    expect(component.commaClicked).toBeTrue();
Also, add checks to verify that there should be no value inside `inputWithoutPlugin` component when keyboard plugin is enabled

2023-05-03 05:35 UTC, Julias0 requested changes
Will review after @yksolanki9's review

2023-05-04 08:26 UTC, CODEX108 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    expect(component.commaClicked).toBeTrue();
Should I  create a wrapper component and then test this?

2023-05-04 08:44 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    expect(component.commaClicked).toBeTrue();
You can check the css element and confirm that there's no value inside input field

2023-05-04 08:44 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    const platformSpy = jasmine.createSpyObj('Platform', ['is']);
This is not resolved?

2023-05-04 09:02 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +      expect(component.fc.value).toBe(12.5);
You are setting the value in 128 and checking it in 129. This is not needed

2023-05-04 09:10 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +      expect(component.fc.value).toBe(12.5);
We're patching the value to the formControl. You should spy and directly check if the value is as expected.

2023-05-04 09:15 UTC, yksolanki9 requested changes

2023-05-04 09:15 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +      expect(component.isKeyboardPluginEnabled).toBeFalse();
Also, add a check to see that only the input which satisfies this condition should be shown in the UI

2023-05-04 12:53 UTC, CODEX108 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    const platformSpy = jasmine.createSpyObj('Platform', ['is']);
sorry it is resolved updated the title

2023-05-05 08:11 UTC, yksolanki9 requested changes
Discussed changes over call

2023-05-05 12:27 UTC, yksolanki9 requested changes
@suyash-patil  is working on removing ngControl from the components, check with him once to see if anything changed in fy-number component

2023-05-05 12:27 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    expect(component.onTouchedCallback).toEqual(mockCallback);
Instead of checking this assignment, a better test case would be check if the callback is being called when you're calling `onBlur()`

2023-05-05 12:27 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    expect(component.onChangeCallback).toEqual(mockCallback);
Same as above. You can check if the callback is being called when setting value

2023-05-05 12:27 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    component.onBlur();
You should be triggering the blur event on the input instead

2023-05-05 12:27 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    it('should patch value with period as decimal separator if the last input was a comma or else keep it as it is', () => {
Add a assertion to check if patchValue is being called or not whenever calling handleChange and separate each call to handleChange into a sepaate spec.

2023-05-05 12:27 UTC, yksolanki9 commented on src/app/shared/components/fy-number/fy-number.component.spec.ts
> +    it('should replace comma with period as decimal separator when input is comma-separated', () => {
Same comment as above, separate them out into different specs

2023-05-08 07:29 UTC, yksolanki9 approved these changes

2023-05-09 08:33 UTC, Julias0 approved these changes

2023-05-10 04:32 UTC, merged