test: Code coverage ExpensesCard Component initial setup
fylein/fyle-mobile-app pull request #1978
Opened 2023-04-28 06:05 UTC by CODEX108

clickUp: clickup.com

2023-05-09 07:45 UTC, CODEX108 commented on src/app/shared/components/expenses-card/expenses-card.component.spec.ts
> +    xit('should call onFileUploadChange method on iOS when file input is clicked', fakeAsync(() => {
The case which throws an error
`TypeError: Failed to set the 'files' property on 'HTMLInputElement': Failed to convert value to 'FileList'.`
While testing 

> if (this.isIos) {
        const nativeElement = this.fileUpload.nativeElement as HTMLInputElement;
        nativeElement.onchange = async () => {
          await this.onFileUploadChange(nativeElement);
        };
        nativeElement.click();
      }
I have disabled the test for now

https://stackoverflow.com/questions/52078853/is-it-possible-to-update-filelist

2023-05-11 05:33 UTC, yksolanki9 requested changes
Added comments

2023-05-11 05:33 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.ts
> +  async onFileUploadChange(nativeElement: HTMLInputElement) {
Rename to onFileUpload

2023-05-11 05:33 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.spec.ts
> +    const mockNativeElement = {
Can we use the element from UI and attach files to it instead of doing this?

2023-05-11 05:33 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.spec.ts
> +      const dummyNativeElement = document.createElement('input');
Query on debugElement to access the input

2023-05-11 05:33 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.spec.ts
> +      const dummyNativeElement = document.createElement('input');
Talk to @suyash-patil if you need any help

2023-05-11 05:33 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.spec.ts
> +      expect(nativeElement1.click).toHaveBeenCalledTimes(1);
You're dispatching evene on 783 and checking if it is called on 784? Assign the input to component.fileUpload and we wont need to dispatch the event. Talk to @suyash-patil on how to handle this

2023-05-11 05:33 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.spec.ts
> +      expect(component.attachReceipt).toHaveBeenCalledTimes(1);
With receiptDetails

2023-05-11 05:33 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.spec.ts
> +      expect(component.attachReceipt).toHaveBeenCalledTimes(1);
Remove this, duplicate from line 867

2023-05-11 05:33 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.spec.ts
> +      expect(component.canAddAttachment).toHaveBeenCalledTimes(1);
Try to organize you assertions as they happen in the code, else it becomes difficult to understand. This is the first statement in the method, but is being checked somewhere in the middle

2023-05-11 05:33 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.spec.ts
> +  describe('onInit', () => {
Add assertions to set homeCurrency and call canShowPaymentModeIcon, canShowPaymentModeIcon, getReceipt, handleScanStatus, setOtherData and set isIos

2023-05-11 05:33 UTC, yksolanki9 requested changes
Added comments

2023-05-12 04:36 UTC, CODEX108 commented on src/app/shared/components/expenses-card/expenses-card.component.spec.ts
> +        tx_extracted_data: {
Yes it wilI pass, wanted to cover the branches therefore added this

2023-05-15 17:19 UTC, yksolanki9 requested changes
Discussed over slack

2023-05-18 07:51 UTC, yksolanki9 approved these changes

2023-05-18 13:53 UTC, merged