test: Initial test setup
fylein/fyle-mobile-app pull request #1983
Opened 2023-04-28 11:28 UTC by yksolanki9

Clickup - https://app.clickup.com/t/85zry9tj2

2023-05-08 04:49 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-fields.component.spec.ts
> +        expect(component.addDependentField).not.toHaveBeenCalled();
subscribes neeed to have the done callback called inside them or we need to use fakeAsync otherwise the subscribe block is not executed and the assertions not triggered

2023-05-08 04:49 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-fields.component.spec.ts
> +        expect(component.addDependentField).not.toHaveBeenCalled();
Same in the rest of the cases

2023-05-08 05:18 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-fields.component.spec.ts
> +    const onPageExitSpy = jasmine.createSpyObj('onPageExit$', ['next', 'complete']);
use SpyOn to do this instead of creating a spy here and not passing it in. SpyOn component.onPageExit$ and then set it to null. Call component.ngOnDestroy() and check if the next and complete got called

2023-05-08 05:19 UTC, Julias0 commented on src/app/shared/components/dependent-fields/dependent-fields.component.spec.ts
> +      expect(component.onPageExit$).toEqual(new Subject());
Didnt you set this to null in the beforeEach? Why compare this to new Subject here?

2023-05-08 05:23 UTC, Julias0 requested changes
Added few comments

2023-05-17 14:33 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-fields.component.spec.ts
> +    const onPageExitSpy = jasmine.createSpyObj('onPageExit$', ['next', 'complete']);
Still getting this error - ` TypeError: Cannot read properties of null (reading 'next')` 
We can discuss this once you're back

2023-05-24 07:23 UTC, yksolanki9 commented on src/app/shared/components/dependent-fields/dependent-fields.component.spec.ts
> +    const onPageExitSpy = jasmine.createSpyObj('onPageExit$', ['next', 'complete']);
This is resolved now, I used the return value of spy instead

2023-05-26 10:01 UTC, Julias0 approved these changes

2023-05-26 10:13 UTC, merged