feat: Camera Service
fylein/fyle-mobile-app pull request #1991
Opened 2023-05-04 08:23 UTC by jayfyle

### Clickup: https://app.clickup.com/t/85zt02x46

## Changes made:
1. Removed all imports for `@capacitor/camera` from components CaptureReceipt, CameraPreview
2.  Added the function `requestCameraPermission` which the only function used from the plugin

2023-05-05 09:11 UTC, Julias0 commented on src/app/core/services/camera.service.ts
> +  requestCameraPermissions(permissionsType?: CameraPermissionType[]) {
we can remove the nullable here

2023-05-05 09:11 UTC, Julias0 commented on src/app/core/services/camera.service.spec.ts
> +describe('CameraService', () => {
can we add unit tests for this

2023-05-05 09:11 UTC, Julias0 requested changes
Added comments

2023-05-08 11:33 UTC, jayfyle commented on src/app/core/services/camera.service.ts
> +  requestCameraPermissions(permissionsType?: CameraPermissionType[]) {
It has to be optional as it defined as an optional in the plugin itself.  We are using this method twice, once with params and once without them.

2023-05-08 11:53 UTC, Julias0 approved these changes

2023-05-08 15:25 UTC, merged