test: Code Coverage: Fy-Select-Project Component
fylein/fyle-mobile-app pull request #1998
Opened 2023-05-05 08:48 UTC by jayfyle

### Clickup: https://app.clickup.com/t/85zrxnafv

<img width="1440" alt="fy_select_project_94" src="https://user-images.githubusercontent.com/115472256/236414965-0560dcdb-8360-406b-b88c-a8a37e488c93.png">

2023-05-05 12:45 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +      component.writeValue(undefined);
innerValue can be undefined. Calling writeValue with undefined should not happen.

2023-05-05 12:48 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-project.component.ts
> +  @Input() touchedInParent;
Add types

2023-05-05 12:48 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-project.component.ts
> +  ngOnInit() {}
Remove if unused

2023-05-08 05:33 UTC, Julias0 requested changes
Will review after Yash's review

2023-05-08 06:27 UTC, jayfyle commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +    await component.openModal();
I have a separate test case for checking if clicking on the DOM opens the modal. This is a test case specifically for checking if the method is working correctly

2023-05-08 11:56 UTC, yksolanki9 requested changes
@jayfyle I don't see my comments being resolved

2023-05-09 09:10 UTC, Julias0 approved these changes

2023-05-09 09:30 UTC, yksolanki9 requested changes

2023-05-09 09:30 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +      expect(component.displayValue).toEqual(undefined);
This should be empty string. How did this test even pass?

2023-05-09 11:22 UTC, jayfyle commented on src/app/shared/components/fy-select-project/fy-select-project.component.spec.ts
> +      expect(component.displayValue).toEqual(undefined);
I have checked this test case and it does not return an empty string. The result is undefined.

2023-05-10 08:04 UTC, yksolanki9 approved these changes

2023-05-10 09:47 UTC, merged