test: 98.3% coverage of fy-select-modal component
fylein/fyle-mobile-app pull request #2000
Opened 2023-05-05 14:59 UTC by suyashpatil78

Clickup - https://app.clickup.com/t/85zrxnafj

Coverage -

![Screenshot 2023-05-05 at 8 27 39 PM](https://user-images.githubusercontent.com/127177049/236494291-4e74d176-e002-4ae3-b0ea-811b02392165.png)

lines not covered
Line 134 - `map((event: any) => event.srcElement.value),`

2023-05-08 05:45 UTC, Julias0 requested changes
Will review after @yksolanki9 's review

2023-05-08 11:45 UTC, yksolanki9 requested changes
Initialize data inside beforeEach instead of defining values for every spec

2023-05-08 11:45 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +        { label: 'ECONOMY', value: { travel_class: 'ECONOMY', vendor: 'asdf' }, selected: true },
Can value be an object?

2023-05-08 11:45 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +        { label: 'ECONOMY', value: { travel_class: 'ECONOMY', vendor: 'asdf' }, selected: true },
While we're at it, please add types for all inputs in this file

2023-05-08 11:45 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +    const dummyHtmlInputElement = document.createElement('input');
Use debugElement

2023-05-08 11:45 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +    tick(1000);
This is synchronous, we don't need tick

2023-05-08 11:45 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +    tick(1000);
not needed

2023-05-08 11:45 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +    const searchBarRefSpy = {
use debugElement

2023-05-08 11:45 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +    component.options = [
We're setting options in every test case, can we set it once in beforeEach and update the specs to use it?

2023-05-08 11:45 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +    const recentlyUsed = [
Similar for this, if a spec doesn't need it we can overwrite it to be `[]` or undefined for that spec, but initialize data inside beforeEach

2023-05-08 11:45 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +    tick(1000);
not needed

2023-05-08 11:45 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +      expect(getSpy).toHaveBeenCalledWith(component.cacheName);
toHaveBeenCalledOnceWith

2023-05-08 11:47 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +    dummyHtmlInputElement.dispatchEvent(new Event('keyup'));
Call dispatchEvent twice for 100% coverage

2023-05-08 16:52 UTC, suyashpatil78 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +    const dummyHtmlInputElement = document.createElement('input');
@yksolanki9 I faced error as `Cannot read property of undefined (reading nativeElement)`.
@Julias0 and I reached upon a solution as in this commit
https://github.com/fylein/fyle-mobile-app/pull/1988/commits/a17d242d2b03e27bcb2d604e3befa1364a5398bf

2023-05-08 17:22 UTC, suyashpatil78 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +    dummyHtmlInputElement.dispatchEvent(new Event('keyup'));
I have added this on line 128 to get 100% coverage

2023-05-09 10:13 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +    const dummyHtmlInputElement = document.createElement('input');
https://github.com/fylein/fyle-mobile-app/blob/5659b78707451a89bf6c26b7d164b34ad02f8faa/src/app/shared/components/dependent-fields/dependent-field/dependent-field.component.spec.ts#L103

Check this^. We can discuss it over call if needed

2023-05-09 10:15 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +  value: string | object = '';
Write the contract of object, also add types to cacheName, enableSearch, label, and every other variable above

2023-05-09 10:19 UTC, yksolanki9 requested changes
Added comments

2023-05-09 10:19 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
>        expect(res).toEqual([{ label: 'business', value: 'BUSINESS' }]);
Expect getRecentlyUsedItems to be called once
expect this.utilityService.searchArrayStream to be called once with searchTExt

2023-05-09 10:19 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.spec.ts
> +        expect(result).toEqual(recentlyUsed);
expect recentLocalStorageItemsService.get to not have been called

2023-05-10 10:21 UTC, yksolanki9 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.interface.ts
> +export interface Value {
Rename to ModalOption or some relevant name.

2023-05-10 10:21 UTC, yksolanki9 approved these changes

2023-05-10 13:32 UTC, Julias0 approved these changes

2023-05-10 13:34 UTC, merged