test: Code Coverage: Fy-Select-Project Modal Component
fylein/fyle-mobile-app pull request #2004
Opened 2023-05-08 14:17 UTC by jayfyle

### Clickup: https://app.clickup.com/t/85zrxnag7

# Coverage at 98%: 

<img width="1434" alt="fy-select-project-modal-98" src="https://user-images.githubusercontent.com/115472256/236848042-5278a436-273e-4f16-ad9d-126c4a988d7a.png">

2023-05-09 09:59 UTC, yksolanki9 requested changes

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +      of({
Move objects inside the data file

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +      orgUserSettingsService.get.and.returnValue(of(orgUserSettingsData));
Some of these are already initialized in beforeEach, so are not needed here

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +        expect(projectService.getByParamsUnformatted).toHaveBeenCalledWith({
`toHaveBeenCalled` -> `toHaveBeenCalledOnce`

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +      projectService.getByParamsUnformatted.and.returnValue(of(projects));
Some initializations are already present in beforeEach

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +        expect(orgUserSettingsService.get).toHaveBeenCalled();
Same comments as above

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +      projectService.getbyId.and.returnValue(of(expectedProjects[0].value));
same comments for this too

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +    const dummyHtmlInputElement = document.createElement('input');
Why create a new component? Use the searchBar we already have

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +    dummyHtmlInputElement.dispatchEvent(new Event('keyup'));
This should be an assetion

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +      component.recentlyUsed = [
What if recentlyUsed is an empty array? Check the behaviour is web app once and make changes in code if necessary

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +      component.getRecentlyUsedItems().subscribe((res) => {
Add assertion  recentLocalStorageItemsService.get should not have been called

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +  it('onDoneClick', async () => {
async/await is not needed here

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +    it('should dismiss the modal with selected option', async () => {
same as above

2023-05-09 09:59 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +    component.currentSelection = {
Put large objects in data file

2023-05-10 06:39 UTC, jayfyle commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +    expect(component.getProjects).toHaveBeenCalledWith('projects');
I am facing the date issue that keeps coming up once in a while, where the dates don't match and time conversion happens on karma but fails on github workflow.

2023-05-10 06:41 UTC, jayfyle commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +        expect(projectService.getByParamsUnformatted).toHaveBeenCalledWith({
`ngAfterViewInit` is being called multiple times, as this function is called in the method, these methods are called more than once.

2023-05-10 06:42 UTC, jayfyle commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +        expect(orgUserSettingsService.get).toHaveBeenCalled();
Same, multiple calls to `ngAfterViewinit` is causing this.

2023-05-10 07:47 UTC, yksolanki9 requested changes

2023-05-10 07:47 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +        expect(projectService.getByParamsUnformatted).toHaveBeenCalledWith({
This should not happen, it should be executed only once. Possibly some issue with the setup

2023-05-10 07:47 UTC, yksolanki9 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +    const dummyHtmlInputElement = document.createElement('input');
This is not resolved

2023-05-12 06:48 UTC, yksolanki9 approved these changes

2023-05-12 07:36 UTC, merged