feat: #sms_to_submit_receipts - Profile page UI changes
fylein/fyle-mobile-app pull request #2006
Opened 2023-05-09 07:27 UTC by yksolanki9

Clickup - https://app.clickup.com/t/85zt045kv

2023-05-10 16:53 UTC, yksolanki9 commented on src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
> +//TODO: Fix unit tests
This component is now a presentational component, and most of logic has been moved to the parent component. So this test won't be needed.

2023-05-10 16:55 UTC, yksolanki9 commented on src/app/fyle/my-profile/employee-details-card/employee-details-card.component.ts
> -  async updateMobileNumber() {
Moved this logic to parent and made this a presentational component

2023-05-11 05:25 UTC, Julias0 commented on src/app/fyle/my-profile/my-profile.page.ts
> +          complete: () => this.showToastMessage('Profile saved successfully', 'success'),
Shouldnt we do this on next instead of complete since complete also triggers on error

2023-05-11 05:26 UTC, Julias0 commented on src/app/fyle/my-profile/my-profile.page.ts
> +          catchError((err) => throwError(() => err))
Is this required since the error path will get enacted anyway

2023-05-11 05:27 UTC, Julias0 commented on src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
> -  it('updateMobileNumber(): should update user mobile number', async () => {
can we move the test case for this to the page file

2023-05-11 05:27 UTC, Julias0 requested changes
Added a few comments

2023-05-11 05:47 UTC, yksolanki9 commented on src/app/fyle/my-profile/my-profile.page.ts
> +          complete: () => this.showToastMessage('Profile saved successfully', 'success'),
https://blog.angular-university.io/rxjs-error-handling/#:~:text=Notice%20that%20completion,occur%2C%20not%20both.

Observable can either complete or error out. Both are not possible. Also, checked the UI, only error message is shown

2023-05-11 05:48 UTC, yksolanki9 commented on src/app/fyle/my-profile/my-profile.page.ts
> +          catchError((err) => throwError(() => err))
My bad, this is not needed

2023-05-11 05:49 UTC, yksolanki9 commented on src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
> -  it('updateMobileNumber(): should update user mobile number', async () => {
@Julias0 this will need the page spec to be setup, so I thought of adding it when writing tests for the page component

2023-05-11 07:51 UTC, yksolanki9 commented on src/app/fyle/my-profile/employee-details-card/employee-details-card.component.spec.ts
> -  it('updateMobileNumber(): should update user mobile number', async () => {
Added setup and unit tests for the two newly added methods

2023-05-16 06:09 UTC, yksolanki9 commented
Failing test is due to some timezone mismatch in `team-adv-card.component.spec.ts` will check this

2023-05-23 03:51 UTC, Julias0 commented on src/app/core/services/clipboard.service.ts
> +      // eslint-disable-next-line id-blacklist
when disabling lint add a comment on why this is required

2023-05-23 05:02 UTC, Julias0 approved these changes

2023-05-23 05:02 UTC, Julias0 approved these changes

2023-05-30 06:21 UTC, merged