test: Code coverage setupAccountPage
fylein/fyle-mobile-app pull request #2012
Opened 2023-05-11 11:24 UTC by CODEX108

clickUp: https://app.clickup.com/t/85zt051zw

2023-05-12 12:33 UTC, CODEX108 commented on src/app/post-verification/setup-account/setup-account.page.spec.ts
> +  xit('should emit the correct length validation display value when the password value changes', fakeAsync(() => {
The spec passes without expectations(when I try checking single input at a time / throws error stating `expected false to be true` when I try looping around the assertion.

2023-05-15 12:07 UTC, yksolanki9 requested changes
Draft pr with commented code. Please check pr once before assigning

2023-05-17 12:19 UTC, yksolanki9 requested changes
Minor comments

2023-05-17 12:19 UTC, yksolanki9 commented on src/app/post-verification/setup-account/setup-account.page.spec.ts
> +    tick(500);
The test should work without the tick as well

2023-05-17 12:19 UTC, yksolanki9 commented on src/app/post-verification/setup-account/setup-account.page.spec.ts
> +        fixture.detectChanges();
Should not be needed

2023-05-17 12:19 UTC, yksolanki9 commented on src/app/post-verification/setup-account/setup-account.page.spec.ts
> +      tick(500);
same as above

2023-05-17 12:19 UTC, yksolanki9 commented on src/app/post-verification/setup-account/setup-account.page.spec.ts
> +      expect(orgService.setCurrencyBasedOnIp).toHaveBeenCalledTimes(2);
Should be called only once

2023-05-17 12:19 UTC, yksolanki9 commented on src/app/post-verification/setup-account/setup-account.page.spec.ts
> +      expect(orgService.getCurrentOrg).toHaveBeenCalledTimes(2);
Same as above

2023-05-17 12:19 UTC, yksolanki9 commented on src/app/post-verification/setup-account/setup-account.page.spec.ts
> +      expect(orgService.getCurrentOrg).toHaveBeenCalledTimes(2);
Removing the explicit call to `component.ngOnInit()` should fix this

2023-05-17 12:19 UTC, yksolanki9 commented on src/app/post-verification/setup-account/setup-account.page.spec.ts
> +      expect(component.setupNetworkWatcher).toHaveBeenCalledTimes(1);
Add assertions to check if eou$ and fullname$ are set

2023-05-17 12:19 UTC, yksolanki9 commented on src/app/post-verification/setup-account/setup-account.page.spec.ts
> +    it('should emit the correct value to check for number vadility', () => {
validity

2023-05-17 12:19 UTC, yksolanki9 commented on src/app/post-verification/setup-account/setup-account.page.spec.ts
> +    it('should emit the correct value to check for lowerCase vadility', () => {
Fix the spelling of validity in every test case

2023-05-17 12:19 UTC, yksolanki9 commented on src/app/post-verification/setup-account/setup-account.page.spec.ts
> +    it('should emit the correct value to check for lowerCase vadility', () => {
Fix the spec name

2023-05-18 07:16 UTC, yksolanki9 approved these changes

2023-05-18 13:54 UTC, merged