feat: Add mobile number verification modal
fylein/fyle-mobile-app pull request #2013
Opened 2023-05-11 13:55 UTC by yksolanki9

Clickup - https://app.clickup.com/t/85zt045q1

2023-05-11 14:00 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
> +        loadingText=" "
Empty string will show only the loader. `Verifying ` will causes issues with small and medium screen sizes as the title is big enought.
See the recording attached to description

2023-05-11 14:02 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
> +import { ComponentFixture, TestBed, waitForAsync } from '@angular/core/testing';
This component is incomplete, validation messages and logic is yet to be added. Will add unit tests after that

2023-05-11 14:34 UTC, yksolanki9 commented on src/app/fyle/my-profile/my-profile.page.spec.ts
> +xdescribe('MyProfilePage', () => {
Disabling this test as some methods will again change in the upcoming PRs. Will add tests again once the approach is reviewed

2023-05-15 03:55 UTC, rvab requested changes

2023-05-15 03:55 UTC, rvab commented on src/app/fyle/my-profile/my-profile.page.ts
> +  async verifyMobileNumber(eou: ExtendedOrgUser) {
Shouldn't this be defined before calling it? I know doesn't make a difference. What convention are we following in the mobile app?

2023-05-15 03:55 UTC, rvab commented on src/app/fyle/my-profile/my-profile.page.ts
> +    if (data) {
When and why this will be undefined/null?

2023-05-15 03:55 UTC, rvab commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
> +        loadingText=" "
Have you discussed this with the design team?

2023-05-15 03:55 UTC, rvab commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
> +  <ng-container *ngIf="infoBoxText?.length">
Why do you need `?` here? You're setting the value inside ngOnInit

2023-05-15 03:55 UTC, rvab commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
> +    //TODO: Restrict this to 5 times a day
* Will this be handled by the client or the server?
* Shouldn't we disable the resend OTP for sometime before requesting for a new OTP?

2023-05-15 03:55 UTC, rvab commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
> +      <span class="verify-number-popover--input-container__mandatory"> * </span>
Shouldn't this be in red color?

2023-05-15 03:55 UTC, rvab commented on src/app/fyle/my-profile/my-profile.page.ts
> +          concatMap(() => this.authService.refreshEou()),
Why use `concatMap`? Should be `switchMap` no?

2023-05-15 03:55 UTC, rvab commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
> +    #input
Please check this once https://web.dev/sms-otp-form/#checklist. IMO, We should use autocomplete="one-time-code"

2023-05-15 03:55 UTC, rvab commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.scss
> +      font-size: 14px;
isn't 14px the default font size?

2023-05-15 03:55 UTC, rvab commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
> +      .post('/orgusers/verify_mobile')
Shouldn't there be a new service `mobile-number-verification.service.ts`?

2023-05-15 05:22 UTC, yksolanki9 commented on src/app/fyle/my-profile/my-profile.page.ts
> +    if (data) {
When user dismisses the modal bu clicking on `x`

2023-05-15 05:23 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
> +    //TODO: Restrict this to 5 times a day
Will this be handled by the client or the server?
> Server

Shouldn't we disable the resend OTP for sometime before requesting for a new OTP?
> This was discusses, but Dhar suggested we go with backend validation only as twilio already has a limit of max 2 messages in 1 minute

2023-05-15 05:24 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
> +    #input
Checking

2023-05-15 10:32 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
> +  <ng-container *ngIf="infoBoxText?.length">
Removed the check

2023-05-15 10:35 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
> +      <span class="verify-number-popover--input-container__mandatory"> * </span>
Fixed it

2023-05-15 10:36 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.scss
> +      font-size: 14px;
Removed it

2023-05-15 10:45 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
> +    #input
Added

2023-05-15 11:24 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
> +      .post('/orgusers/verify_mobile')
Created a service

2023-05-15 11:29 UTC, yksolanki9 commented on src/app/fyle/my-profile/my-profile.page.ts
> +  async verifyMobileNumber(eou: ExtendedOrgUser) {
I had actually made them private and so eslint asks us to put them at the bottom of file. But, we faced some difficulty when setting up unit tests for private methods, so we don't mark methods as private.

Your suggestions makes sense, moved it above the calling method.

2023-05-15 11:37 UTC, yksolanki9 commented on src/app/fyle/my-profile/my-profile.page.ts
> +          concatMap(() => this.authService.refreshEou()),
It wont matter as it is an http call and the observable will complete after emitting a value

2023-05-16 05:37 UTC, merged