test: Code Coverage: Sign In Component
fylein/fyle-mobile-app pull request #2016
Opened 2023-05-12 13:06 UTC by jayfyle

### Clickup: https://app.clickup.com/t/85zt04z9t

## Issues faced:
1. The `handleSamlSignIn` does not get full coverage. The code after the `try catch` does not execute, maybe because it is in a `setInterval`
2. There is a disabled test `checking email set`, here the `emailSet` property is responsible for making certain elements on the template visible. However, after the property is set to true via method call. The `fixture` does not update and the query for the elements return null, which should be present, after the `emailSet` is true.

2023-05-17 06:58 UTC, yksolanki9 reviewed
Branches do not have 100% coverage, please mention which branches were not covered and why

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +    expect(inAppBrowserService.create).toHaveBeenCalledOnceWith('url' + '&RelayState=MOBILE', '_blank', 'location=yes');
checkSAMLResponseAndSignInUser to have been called once with ...

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +      expect(component.trackLoginInfo).toHaveBeenCalledTimes(1);
Duplicate assertion

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +      expect(routerAuthService.handleSignInResponse).toHaveBeenCalledOnceWith({});
Arrange assertions in the same sequence as they happen in code for readability

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +      expect(component.handleSamlSignIn).toHaveBeenCalledOnceWith({ saml: true });
Missing assertions: 
routerAuthService.checkEmailExists 
emailLoading

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +      expect(component.handleSamlSignIn).toHaveBeenCalledOnceWith({ saml: true });
Emailset false

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +      component.checkIfEmailExists();
handleSamlSignIn not called

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +      expect(component.handleError).toHaveBeenCalledTimes(2);
If it is being called twice, there's some issue in the logic. Fix it

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +      expect(component.fg.controls.email.markAsTouched).toHaveBeenCalledTimes(1);
Optional - Check if invalid email message is shown in UI

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +      expect(router.navigate).toHaveBeenCalledTimes(1);
args

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +      expect(component.fg.controls.password.markAsTouched).toHaveBeenCalledTimes(1);
Optional - add UI check to see if error is displayed

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +      expect(loaderService.hideLoader).toHaveBeenCalledTimes(2);
It shouldn't be called twice

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +    expect(loaderService.showLoader).toHaveBeenCalledTimes(2);
ONce

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +    expect(loaderService.hideLoader).toHaveBeenCalledTimes(2);
once

2023-05-17 06:58 UTC, yksolanki9 commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +    expect(routerAuthService.isLoggedIn).toHaveBeenCalledTimes(2);
If it is being called twice, there's something wrong in the code or test setup

2023-05-17 06:58 UTC, yksolanki9 requested changes
Branches do not have 100% coverage, please mention which branches were not covered and why

2023-05-17 15:45 UTC, jayfyle commented on src/app/auth/sign-in/sign-in.page.spec.ts
> +      expect(component.handleError).toHaveBeenCalledTimes(2);
I guess here since the same observable is used to check whether `saml` is present in the response, if the source observable errors both the other observables have their error callback triggered

2023-05-23 03:53 UTC, yksolanki9 approved these changes

2023-05-23 05:06 UTC, merged