feat: Add task for adding/verifying mobile number
fylein/fyle-mobile-app pull request #2022
Opened 2023-05-16 07:13 UTC by yksolanki9

Clickups (Combining two tasks as they're overlapping):
- https://app.clickup.com/t/85zt045g1
- https://app.clickup.com/t/85zt045fc

UI Preview:
https://github.com/fylein/fyle-mobile-app/assets/39493102/6d1a1c5d-7155-41b3-92f7-f8bc1d1d87f4

Things changed in this PR:
- Added task for add/verify mobile number based on the user's verification status
- The task will be shown only for RTF users

Code coverage:
<img width="773" alt="Screenshot 2023-05-16 at 8 24 53 PM" src="https://github.com/fylein/fyle-mobile-app/assets/39493102/de82fc18-cbe8-4539-b86b-b589cb84136a">
<img width="773" alt="Screenshot 2023-05-16 at 8 08 21 PM" src="https://github.com/fylein/fyle-mobile-app/assets/39493102/32f7c2a9-8dd6-40c9-9240-940cbcb28ab4">

2023-05-16 16:00 UTC, yksolanki9 commented on src/app/core/models/task.model.ts
> +  count?: number;
It is not being used, so marked as optional

2023-05-17 04:12 UTC, rvab requested changes
minor doubts.

2023-05-17 04:12 UTC, rvab commented on src/app/core/services/tasks.service.spec.ts
> +        expect(res).toEqual([]);
we should write expect for `corporateCreditCardExpenseService.getCorporateCards` and `authService.getEou` toHaveVeenCalledOnce

2023-05-17 04:12 UTC, rvab commented on src/app/core/services/tasks.service.spec.ts
> +      tasksService.getMobileNumberVerificationTasks().subscribe((res) => {
same as above

2023-05-17 04:12 UTC, rvab commented on src/app/core/services/tasks.service.spec.ts
> +      const eou = cloneDeep(extendedOrgUserResponse);
Why do you need cloneDeep here? Each test case should be running independently, no?

2023-05-17 04:12 UTC, rvab commented on src/app/core/services/tasks.service.spec.ts
> +      const eou = cloneDeep(extendedOrgUserResponse);
same as above

2023-05-17 04:12 UTC, rvab commented on src/app/core/services/tasks.service.spec.ts
> +      tasksService.getMobileNumberVerificationTasks().subscribe(() => {
check for toHaveBeenCalledOnce.

2023-05-17 04:12 UTC, rvab commented on src/app/core/services/tasks.service.spec.ts
> +        expect(mapMobileNumberVerificationTaskSpy).toHaveBeenCalledOnceWith('Verify');
same as above

2023-05-17 08:03 UTC, yksolanki9 commented on src/app/core/services/tasks.service.spec.ts
> +        expect(res).toEqual([]);
Sorry missed it, added now

2023-05-17 08:05 UTC, yksolanki9 commented on src/app/core/services/tasks.service.spec.ts
> +      tasksService.getMobileNumberVerificationTasks().subscribe(() => {
Added

2023-05-17 08:06 UTC, yksolanki9 commented on src/app/core/services/tasks.service.spec.ts
> +        expect(mapMobileNumberVerificationTaskSpy).toHaveBeenCalledOnceWith('Verify');
Added

2023-05-17 08:11 UTC, yksolanki9 commented on src/app/core/services/tasks.service.spec.ts
> +      const eou = cloneDeep(extendedOrgUserResponse);
Object are passed by reference. Since we're using a shared object here, it'll be updated in memory and all subsequent tests will fail. Verified this by removing cloneDeep

2023-05-17 10:49 UTC, rvab approved these changes

2023-05-18 05:32 UTC, merged