test: Code Coverage: Switch Org Component
fylein/fyle-mobile-app pull request #2024
Opened 2023-05-16 10:35 UTC by jayfyle

### Clickup: https://app.clickup.com/t/85zt04zpk

# Coverage at 95%

<img width="1440" alt="switch_org_100" src="https://github.com/fylein/fyle-mobile-app/assets/115472256/d740c9f6-4453-47f4-b75c-0bcef6bf1571">

2023-05-17 07:57 UTC, yksolanki9 requested changes
Are we planning to achieve 100% in a separate PR? Please mention what is covered and what is left in the PR description

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +    expect(orgService.getCurrentOrg).toHaveBeenCalledTimes(1);
same for getPrimaryOrg

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +    component.filteredOrgs$.subscribe((res) => {
No testcase for choose true/false and single org users

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +    expect(popoverController.create).toHaveBeenCalledOnceWith({
handleDismissPopup

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +    await component
await is not needed here.

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +        finalize(() => {
These assertions should go inside subscribe

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +      await component.switchOrg(orgData1[0]).then(async () => {
await and then both are not needed

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +      await component.switchOrg(orgData1[0]).then(async () => {
remove then

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +        await Promise.resolve();
Why is this needed?

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +      expect(userEventService.logout).toHaveBeenCalledTimes(1);
Spy and check globalCacheBusterNotifier

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +      expect(orgService.switchOrg).toHaveBeenCalledOnceWith(orgData1[0].id);
globalCacheBusterNotifier

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +      expect(userEventService.logout).toHaveBeenCalledTimes(1);
globalCacheBusterNotifier

2023-05-17 07:57 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +      expect(storageService.clearAll).toHaveBeenCalledTimes(1);
globalCacheBusterNotifier

2023-05-17 09:06 UTC, jayfyle commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +      await component.switchOrg(orgData1[0]).then(async () => {
The method returns a Promise, and multiple nested async blocks hence removing anything will cause the test to fail.

2023-05-17 12:59 UTC, yksolanki9 requested changes
Discussed on slack

2023-05-17 12:59 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.spec.ts
> +      await component.ionViewWillEnter();
Why async?

2023-06-07 06:32 UTC, yksolanki9 approved these changes

2023-06-07 07:00 UTC, merged