feat: More UI changes/fixes for #sms_to_submit_receipts
fylein/fyle-mobile-app pull request #2025
Opened 2023-05-17 10:45 UTC by yksolanki9

Clickup - https://app.clickup.com/t/85zt2ngzr

Changes:
- Show toast message whenever text is copied by user
- Show verify mobile number modal when user clicks on verify cta
- Moved add/edit mobile number into a new component. 
  - Earlier, we were using a share component for editing mobile number, and it used to dismiss the modal and then make api call to save the mobile number and then open the verification modal.
  - The problem with this flow is that if the user is on a slow internet connection, he won't see the verify otp modal for a few seconds.
   - The first approach was to edit the shared component, but since it is a shared component, it's better to keep it presentational instead of importing other services and making api calls from it. So, created a local component for this page to handle this flow
   
Items not covered in this PR:
- Unit tests for the new component
   
UI Preview:
https://github.com/fylein/fyle-mobile-app/assets/39493102/26444b84-27e0-48bf-b026-8a35a4c9d36d
- The issue with Not verified in the recording is known, but I've not been able to figure out a fix for it yet. Will talk to shishira today/tmrw

2023-05-17 14:12 UTC, yksolanki9 commented on src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.html
> +<ion-header mode="md">
Created a new component for the update mobile number popover for the reasons mentioned in the PR description

2023-05-18 04:14 UTC, rvab requested changes
minor comments

2023-05-18 04:14 UTC, rvab commented on src/app/core/services/snackbar-properties.service.spec.ts
> +    expect(properties.data.icon).toEqual(undefined);
There's a method for it. `toBeUndefined`. Please check once

2023-05-18 04:14 UTC, rvab commented on src/app/fyle/my-profile/info-card/info-card.component.ts
> +    if (this.title.includes('Message')) {
Can't we use a different variable instead of comparing string?

2023-05-18 04:14 UTC, rvab commented on src/app/fyle/my-profile/info-card/info-card.component.ts
> +  @Output() textCopied = new EventEmitter<string>();
`copiedText` or `textCopied`?. IMO, the first words sounds better. I'll leave it to you.

2023-05-18 04:14 UTC, rvab commented on src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.html
> +    [placeholder]="placeholder?.length ? placeholder : 'Enter ' + inputLabel"
placeholder || 'Enter ' + inputLabel"

2023-05-18 05:07 UTC, yksolanki9 commented on src/app/core/services/snackbar-properties.service.spec.ts
> +    expect(properties.data.icon).toEqual(undefined);
Done

2023-05-18 05:08 UTC, yksolanki9 commented on src/app/fyle/my-profile/info-card/info-card.component.ts
> +  @Output() textCopied = new EventEmitter<string>();
Renamed

2023-05-18 05:28 UTC, yksolanki9 commented on src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.html
> +    [placeholder]="placeholder?.length ? placeholder : 'Enter ' + inputLabel"
Done

2023-05-18 05:28 UTC, yksolanki9 commented on src/app/fyle/my-profile/info-card/info-card.component.ts
> +    if (this.title.includes('Message')) {
Done

2023-05-18 05:31 UTC, rvab approved these changes

2023-05-18 05:31 UTC, merged