test: Code coverage 100% InvitedUserPage
fylein/fyle-mobile-app pull request #2029
Opened 2023-05-18 11:59 UTC by CODEX108

clickUp: https://app.clickup.com/t/85zt051xp

2023-05-19 05:13 UTC, rvab requested changes
* `done` is wherever subscribe is used.
* Why tick of 500 is required?

2023-05-19 05:13 UTC, rvab commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +      tick(500);
use tick of 500 here?

2023-05-19 05:13 UTC, rvab commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +        expect(connectionStatus).toEqual(true);
`done`?

2023-05-19 05:13 UTC, rvab commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +      const testCases = [
There should test case for each input, no? Aren't we showing any error if the length validation fails? Shouldn't we check for error messages as well?

2023-05-19 05:13 UTC, rvab commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +      const testCases = [
same as above
`done` is missing in most of the test case. Please check once

2023-05-19 05:13 UTC, rvab commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +      component.eou$ = of(cloneDeep(currentEouRes));
why cloneDeep is required? Each test case should be running independently.

2023-05-19 05:13 UTC, rvab commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +      tick(500);
why tick of 500?

2023-05-19 05:13 UTC, rvab commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +      tick(500);
why tick of 500?

2023-05-19 05:13 UTC, rvab commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +  describe('onInit()', () => {
* `onInit` or `ngOnInit`
* Aren't we testing HTML?

2023-05-19 14:41 UTC, CODEX108 commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +        expect(connectionStatus).toEqual(true);
Since I have used `fakeAsync` and `tick` here, thought the done callback is not necessary because fakeAsync and tick provide a synchronous way to handle asynchronous operations.

2023-05-19 14:46 UTC, CODEX108 commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +      tick(500);
Since it threw error `1 timer(s) still pending in queue` and adding tick here fixed the issue

2023-05-19 14:51 UTC, CODEX108 commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +      tick(500);
Provided some time space of 500 ms so that it completes the async tasks because tick() alone behaves differently

2023-05-19 14:56 UTC, CODEX108 commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +      component.eou$ = of(cloneDeep(currentEouRes));
since I am testing the change in the name and password with the help of the `currentEouRes` data, I have used `cloneDeep` to avoid the alteration of the actual `currentEouRes` since this might affect other test cases .

Faced similar issue before therefore added it here.

2023-05-19 14:56 UTC, CODEX108 commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +  describe('onInit()', () => {
Its `ngOnInit`

2023-05-19 15:00 UTC, CODEX108 commented on src/app/post-verification/invited-user/invited-user.page.spec.ts
> +      const testCases = [
As in checking a single keystroke at a time?

2023-05-22 07:50 UTC, rvab approved these changes

2023-05-22 18:45 UTC, merged