test: Add tests for update mobile number popover
fylein/fyle-mobile-app pull request #2038
Opened 2023-05-23 13:30 UTC by yksolanki9

Clickup - https://app.clickup.com/t/85zt2xar4

Code coverage:
<img width="914" alt="Screenshot 2023-05-23 at 6 52 49 PM" src="https://github.com/fylein/fyle-mobile-app/assets/39493102/6865d514-9d03-4b0f-9faf-2abbff8b603f">

2023-05-25 05:37 UTC, Dimple16 requested changes
added comments

2023-05-25 05:37 UTC, Dimple16 commented on src/app/fyle/my-profile/my-profile.page.spec.ts
> +      allInfoCardsData = [
does `allInfoCardsData` have a model? haven't checked the previous PRs if any for context, 
if yes, let us add the model and move this data to mock data file

2023-05-25 05:37 UTC, Dimple16 commented on src/app/fyle/my-profile/update-mobile-number/update-mobile-number.component.spec.ts
> +    const valueErrorMapping = [
move this to mock data and add a model

2023-05-25 14:39 UTC, yksolanki9 commented on src/app/fyle/my-profile/my-profile.page.spec.ts
> +      allInfoCardsData = [
Created a model and moved data to a data file

2023-05-25 14:43 UTC, yksolanki9 commented on src/app/core/mock-data/value-error-mapping-for-update-mobile-number-popover.data.ts
> +interface ValueErrorMapping {
This array just contains the expected input/output for tests and is not being used anywhere in ts code, so I've created the model inside the data file itself

2023-05-29 06:42 UTC, Dimple16 approved these changes

2023-05-29 06:45 UTC, merged