feat: Add error messages in ui
fylein/fyle-mobile-app pull request #2041
Opened 2023-05-24 08:11 UTC by yksolanki9

Clickup - https://app.clickup.com/t/85zt3yxe6

2023-05-24 13:49 UTC, yksolanki9 commented on src/app/shared/directive/form-button-validation.directive.ts
> +    if (this.disabled) {
The directive was overwriting the disabled state of the cta, so added a check here to make sure the cta is always disabled

2023-05-25 03:38 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.html
> -  <ion-toolbar mode="md" class="fy-modal-toolbar verify-number-popover--toolbar">
Fixed class names to be as per BEM

2023-05-25 10:38 UTC, Dimple16 requested changes
added comments

2023-05-25 10:38 UTC, Dimple16 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
> +    const errorMapping = {
let's move the error mapping to enum?

2023-05-25 10:38 UTC, Dimple16 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
> +    const errorMappings = [
add this to mock data file and create a model

2023-05-25 13:38 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.ts
> +            const errorMessage = err.error.message.toLowerCase();
Done

2023-05-25 14:28 UTC, yksolanki9 commented on src/app/fyle/my-profile/verify-number-popover/verify-number-popover.component.spec.ts
> +    const errorMappings = [
This array just contains the expected input/output for tests and is not being used anywhere in ts code, so I've created the model inside the data file itself

2023-05-25 14:30 UTC, yksolanki9 commented on src/app/core/mock-data/error-mapping-for-verify-number-popover.data.ts
> +type ErrorMapping = {
This array just contains the expected input/output for tests and is not being used anywhere in ts code, so I've created the model inside the data file itself

2023-05-26 06:31 UTC, Dimple16 approved these changes

2023-05-29 06:45 UTC, merged