test: Code Coverage: View-Team Reports Component #2
fylein/fyle-mobile-app pull request #2043
Opened 2023-05-24 12:32 UTC by jayfyle

### Clickup: https://app.clickup.com/t/85zt05531

## Coverage at 99%:

<img width="1440" alt="view_team_report_99" src="https://github.com/fylein/fyle-mobile-app/assets/115472256/9b9ec924-357d-4180-8d47-0644525b9e68">

2023-05-25 13:16 UTC, yksolanki9 requested changes
Organize the assertions inside ionViewWillEnter as they are executed in the code.

2023-05-26 07:01 UTC, yksolanki9 requested changes

2023-05-26 10:43 UTC, jayfyle commented on src/app/fyle/view-team-report/view-team-report.page.spec.ts
> +
This is the final subscribe for the block, can't access the intermediate assignment for `this.erpts$`, the previous matcher was incorrect. Have fixed it now.

2023-05-29 05:47 UTC, yksolanki9 commented on src/app/fyle/view-team-report/view-team-report.page.spec.ts
> +      expect(component.systemComments).toEqual(userCommentsData);
Add comments other than policy and system for this test case

2023-05-29 05:47 UTC, yksolanki9 commented on src/app/fyle/view-team-report/view-team-report.page.spec.ts
> +      expect(component.userComments).toEqual(userCommentsData);
This is not correct. System comments and user comments cannot be the same. Please don't modify the api response to suit the tests.

2023-05-29 05:47 UTC, yksolanki9 commented on src/app/fyle/view-team-report/view-team-report.page.spec.ts
> +      expect(reportService.getApproversByReportId).toHaveBeenCalledOnceWith(activatedRoute.snapshot.params.id);
Missing assertion for sharedWith

2023-05-30 06:50 UTC, yksolanki9 approved these changes

2023-05-30 07:35 UTC, merged