test: Code Coverage: My View Report Component #2
fylein/fyle-mobile-app pull request #2052
Opened 2023-05-29 14:55 UTC by jayfyle

### Clickup: https://app.clickup.com/t/85zt055va

# Coverage at 99%

<img width="1440" alt="my_view_report_99" src="https://github.com/fylein/fyle-mobile-app/assets/115472256/c838bba0-b157-476a-aea5-bdc083778922">

2023-05-29 18:36 UTC, Dimple16 requested changes
added comments

2023-05-29 18:36 UTC, Dimple16 commented on src/app/fyle/my-view-report/my-view-report.page.spec.ts
> +      const erpt = cloneDeep({ ...expectedAllReports[0], rp_state: 'APPROVER_INQUIRY' });
are we not mocking `cloneDeep()`?

2023-05-29 18:36 UTC, Dimple16 commented on src/app/fyle/my-view-report/my-view-report.page.spec.ts
> +    it('shoudl edit report name', fakeAsync(() => {
`should`

2023-05-29 18:36 UTC, Dimple16 commented on src/app/fyle/my-view-report/my-view-report.page.spec.ts
> +      tick(5000);
do we need`5000`?

2023-05-29 18:36 UTC, Dimple16 commented on src/app/fyle/my-view-report/my-view-report.page.spec.ts
> +      const properties = {
move this to mock model properties file

2023-05-30 05:39 UTC, jayfyle commented on src/app/fyle/my-view-report/my-view-report.page.spec.ts
> +      const erpt = cloneDeep({ ...expectedAllReports[0], rp_state: 'APPROVER_INQUIRY' });
No, no this is to ensure the properties don't get modified and fail some other test

2023-05-30 10:56 UTC, Dimple16 approved these changes

2023-06-01 07:09 UTC, yksolanki9 approved these changes

2023-06-01 08:01 UTC, merged