test: 100% Coverage of SelectCurrency page inside setup account
fylein/fyle-mobile-app pull request #2053
Opened 2023-05-30 05:56 UTC by suyashpatil78

https://app.clickup.com/t/85zt052f3

![Screenshot 2023-05-30 at 11 12 25 AM](https://github.com/fylein/fyle-mobile-app/assets/127177049/146baea6-7a91-42a7-aabf-a0ffa2830bcb)

2023-05-30 06:57 UTC, yksolanki9 requested changes
Minor comments

2023-05-30 06:57 UTC, yksolanki9 commented on src/app/post-verification/setup-account/select-currency/select-currency.component.html
> +      <ion-button data-testid="doneBtn" (click)="onDoneClick()"> Done </ion-button>
We can directly get the ion-button from css. No need to add test id

2023-05-30 06:57 UTC, yksolanki9 commented on src/app/post-verification/setup-account/select-currency/select-currency.component.spec.ts
> +    expect(component.currencies$).toBeDefined();
Compare with expected value

2023-05-30 06:57 UTC, yksolanki9 commented on src/app/post-verification/setup-account/select-currency/select-currency.component.spec.ts
> +    expect(component.currencies$).toBeDefined();
same as above

2023-05-30 06:57 UTC, yksolanki9 commented on src/app/post-verification/setup-account/select-currency/select-currency.component.spec.ts
> +  it('should load currencies on initialization even if value is empty', fakeAsync(() => {
What's the difference between this and previous test case?

2023-05-30 08:33 UTC, suyashpatil78 commented on src/app/post-verification/setup-account/select-currency/select-currency.component.spec.ts
> +  it('should load currencies on initialization even if value is empty', fakeAsync(() => {
This test is to cover the branch `|| shortCode`, if there is not value corresponding to the shortcode, then the `longName` takes the value of `shortcode`

2023-05-30 09:25 UTC, suyashpatil78 commented on src/app/post-verification/setup-account/select-currency/select-currency.component.spec.ts
> +  it('should load currencies on initialization even if value is empty', fakeAsync(() => {
I have combined the two tests into a single test to check both the branches

2023-05-30 13:18 UTC, Dimple16 approved these changes
minor comments

2023-05-30 13:18 UTC, Dimple16 commented on src/app/post-verification/setup-account/select-currency/select-currency.component.spec.ts
> +      expect(currencies).toEqual([
move this to mock data file

2023-06-02 11:42 UTC, yksolanki9 approved these changes

2023-06-05 04:17 UTC, merged