test: 100% Coverage of AppVersionPage
fylein/fyle-mobile-app pull request #2057
Opened 2023-05-30 08:39 UTC by suyashpatil78

https://app.clickup.com/t/85zt04yyy

2023-05-30 09:08 UTC, suyashpatil78 commented
![Screenshot 2023-05-30 at 2 36 21 PM](https://github.com/fylein/fyle-mobile-app/assets/127177049/7ef23aa6-f369-403a-8c28-2c1cc7060803)
![Screenshot 2023-05-30 at 2 37 09 PM](https://github.com/fylein/fyle-mobile-app/assets/127177049/2e09329b-972c-4e39-a9fb-3c2b9d70f148)

2023-05-31 06:38 UTC, yksolanki9 requested changes

2023-05-31 06:38 UTC, yksolanki9 commented on src/app/auth/app-version/app-version.page.spec.ts
> +    expect(deviceService.getDeviceInfo).toHaveBeenCalledTimes(2);
Use shareReplay so that it will be called only once

2023-06-01 06:25 UTC, yksolanki9 approved these changes
Missing types. Please raise another PR with types

2023-06-01 06:31 UTC, merged