fix: Back Button Service
fylein/fyle-mobile-app pull request #2067
Opened 2023-05-31 12:44 UTC by jayfyle

### Clickup: https://app.clickup.com/t/85zt699cp

# Fixed types

2023-06-01 06:31 UTC, yksolanki9 requested changes

2023-06-01 06:31 UTC, yksolanki9 commented on src/app/core/services/back-button.service.ts
> +            if (popoverDetails?.data?.action === 'close') {
Every modal/popover in ionic returns data object. We can create a generic type for this.
So, the type here would look like `OverlayResponse<{action?: string}>`
Let me know if you need any help with this

2023-06-01 15:47 UTC, Dimple16 approved these changes

2023-06-02 05:06 UTC, yksolanki9 approved these changes

2023-06-02 05:19 UTC, merged