test: Code coverage View Mileage
fylein/fyle-mobile-app pull request #2072
Opened 2023-06-01 09:42 UTC by CODEX108

clickUp: app.clickup.com

2023-06-02 05:37 UTC, yksolanki9 approved these changes
Minor comments

2023-06-02 05:37 UTC, yksolanki9 commented on src/app/fyle/view-mileage/view-mileage.page.spec.ts
> +import { etxncData, expenseData1, expenseData2 } from 'src/app/core/mock-data/expense.data';
Rename to etxnData?

2023-06-02 05:37 UTC, yksolanki9 commented on src/app/fyle/view-mileage/view-mileage.page.spec.ts
> +    it('should get all the org setting and return true if new reports Flow Enabled ', () => {
Write one test case for when projectFieldName is present, project is not mandatory and tx_project_name is set to some value.

2023-06-02 05:37 UTC, yksolanki9 commented on src/app/fyle/view-mileage/view-mileage.page.spec.ts
> +    });
Set view = Individual and check that canFlagorUnflag and canDelete should be false

2023-06-02 05:37 UTC, yksolanki9 commented on src/app/fyle/view-mileage/view-mileage.page.spec.ts
> +      expect(component.activeEtxnIndex).toEqual(20);
Logicslly incorrect -  If there are 3 txns in report then the activeIndex cannot be 20. Change it to 2

2023-06-05 05:56 UTC, yksolanki9 requested changes

2023-06-05 05:56 UTC, yksolanki9 commented on src/app/fyle/view-mileage/view-mileage.page.spec.ts
> +      expect(component.activeEtxnIndex).toEqual(20);
The ask was to change the activeIndex, not the number of txns in report

2023-06-06 04:13 UTC, Dimple16 reviewed
resolve existing comments

2023-06-08 12:22 UTC, yksolanki9 approved these changes

2023-06-08 13:05 UTC, merged