Fyle-1vef81-1: Recently used items service
fylein/fyle-mobile-app pull request #239
Opened 2021-02-11 12:13 UTC by Dimple16

2021-02-11 12:17 UTC, Julias0 approved these changes

2021-02-26 16:00 UTC, iamtarun1993 commented on src/app/core/models/recently_used.model.ts
> +    recent_project_ids?: number[];
2 space tabs

2021-02-27 14:20 UTC, iamtarun1993 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentlyUsedV2():Observable<RecentlyUsed> {
why this is named as ...v2()
we are not using any v2 api,

2021-02-27 14:21 UTC, iamtarun1993 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentlyUsedV2():Observable<RecentlyUsed> {
getRecentlyUsedV2():<space>Observable<RecentlyUsed> {

2021-03-01 04:58 UTC, abhishek1234321 approved these changes

2021-03-01 07:32 UTC, Dimple16 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentlyUsedV2():Observable<RecentlyUsed> {
named it v2 here as in the app/shared-js we are using getRecentlyRsedItems (one from localStorage and other from API) API one is named as v2 - for consistency named the same way here too cc @iamtarun1993

2021-03-01 10:26 UTC, iamtarun1993 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentlyUsedV2():Observable<RecentlyUsed> {
Ok, but still will suggest use `getRecentlyUsed` because we are not using any SharedJS here.
@abhishek1234321 @Julias0  need your help.

2021-03-01 10:28 UTC, abhishek1234321 requested changes

2021-03-01 10:28 UTC, abhishek1234321 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentlyUsedV2():Observable<RecentlyUsed> {
we don't need to name it as v2 here, since sharedjs will not be present here and this is the new angular world so can have the same name in two different cases

2021-03-05 06:56 UTC, Dimple16 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentlyUsedV2():Observable<RecentlyUsed> {
^this is resolved cc @iamtarun1993 @abhishek

2021-03-08 09:13 UTC, abhishek1234321 approved these changes

2021-03-08 09:13 UTC, abhishek1234321 commented on src/app/core/models/recently_used.model.ts
> +}
add a new line at the end @Dimple16

2021-03-08 09:13 UTC, abhishek1234321 commented on src/app/core/services/recently-used-items.service.ts
> +}
same as above

2022-08-02 07:00 UTC, closed without merging