Fyle-25cy8j-1: Start location autofill in mileage page
fylein/fyle-mobile-app pull request #262
Opened 2021-02-18 16:19 UTC by Dimple16

2021-02-25 13:26 UTC, Dimple16 commented
https://user-images.githubusercontent.com/31147415/109159867-1f146a80-779b-11eb-90e7-dcaf75a79675.mov

2021-02-26 14:01 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +            eou: eou,
`eou: eou` is not needed, only eou is enough...for typescript

2021-02-26 14:02 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +            eou: eou,
if key and value is same no need to do
value: value

2021-02-26 14:04 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      concatMap(( isPredictedLocation) => {
concatMap((isPredictedLocation) => {

2021-02-26 14:06 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +        if (recentStartLocation && eou && currentLocation) {
use iif() of rxJs

2021-02-26 14:09 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +        if (isRecentLocationPresent) {
what will happen if isRecentLocationPresent is false??

2021-02-26 15:05 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +        if (isRecentLocationPresent) {
this is fixed

2021-03-09 15:09 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      concatMap((autocompleteLocationInfo: any) => {
no `any` please.. replace it with model

2021-03-10 09:04 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      currentLocation: from(Geolocation.getCurrentPosition({
please pull the Latest master and merge it to branch. Use `getCurrentLocation` from location service.

2021-03-14 12:56 UTC, iamtarun1993 approved these changes

2021-03-15 04:57 UTC, abhishek1234321 requested changes

2021-03-15 04:57 UTC, abhishek1234321 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +import {LocationService} from 'src/app/core/services/location.service';
`{ LocationService }` @tarunkumarfyle let us please fix this everywhere

2021-03-15 04:57 UTC, abhishek1234321 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +    type locationInfo = {recentStartLocation: string, eou: ExtendedOrgUser, currentLocation: GeolocationPosition};
when do we use `type`? why do we need it here? why not use an `interface`? @tarunkumarfyle @Julias0 @Dimple16 ?

2021-03-15 04:57 UTC, abhishek1234321 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      concatMap(isPredictedLocation => {
why do we need to use `concatMap` everywhere?

2021-03-15 04:57 UTC, abhishek1234321 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +          return this.locationService.getGeocode(isPredictedLocation[0].place_id, isPredictedLocation[0].description).pipe(
what if `isPredictedLocation[0]` is undefined or null?

2021-03-15 04:57 UTC, abhishek1234321 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +              if (location) {
is `location` an observable? if not in one case you are returning an observable and the other you aren't

2021-03-15 05:35 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +    type locationInfo = {recentStartLocation: string, eou: ExtendedOrgUser, currentLocation: GeolocationPosition};
as this is used only one place here, used `type` instead of `interface` - https://fylein.slack.com/archives/C017C400V37/p1615304487035500 @abhishek1234321

2021-03-15 05:54 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      concatMap(isPredictedLocation => {
using `concateMap` here as the previous it should subscribe to next observable only after previous one completes
the values are used as params for API call

2021-03-15 06:05 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +              if (location) {
returning `of(null)`

2021-03-15 06:38 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +          return this.locationService.getGeocode(isPredictedLocation[0].place_id, isPredictedLocation[0].description).pipe(
this is fixed

2021-03-15 07:03 UTC, abhishek1234321 approved these changes

2021-03-15 07:06 UTC, abhishek1234321 approved these changes

2022-08-02 07:00 UTC, closed without merging