Fyle-27cvgk: Category auto-fills in expense page
fylein/fyle-mobile-app pull request #283
Opened 2021-02-26 07:58 UTC by Dimple16

2021-02-26 08:06 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    this.recentlyUsedValues$.subscribe(recentValue => {
const isAutofillsEnabled$ = orgUserSettings$.pipe(
  map(orgUserSettins => orgUserSettings.expense_form_autofills && 
      orgUserSettings.expense_form_autofills.allowed &&
      orgUserSettings.expense_form_autofills.enabled)
)

2021-02-26 14:41 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  doRecentOrgCategoryIdsExist: any;
Why `: any;`??
it should be `: boolean` na??

2021-02-26 14:42 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  }
};

2021-02-26 14:43 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  getRecentlyUsedCategories() {
Please define the output model here
ex: 

getRecentlyUsedCategories(): Observables<Categories[]> {

2021-02-26 14:45 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  recentCategories$: any;
this should be Observable<any>

2021-02-26 14:46 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  autoFilledCategory: any;
boolean

2021-02-26 14:49 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        this.recentCategories$ = recentCategories;
use $ if the variable is Observable.

2021-02-26 15:21 UTC, Dimple16 commented
https://user-images.githubusercontent.com/31147415/109318896-4ee37100-7874-11eb-8b36-f388c9fc9999.mov

2021-03-05 07:49 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      filteredCategories: this.filteredCategories$.pipe(
put this in one line.. easy to read.
`filteredCategories: this.filteredCategories$.pipe(take(1))`

2021-03-05 07:50 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const isAutofillsEnabled = orgUserSettings && orgUserSettings.expense_form_autofills && orgUserSettings.expense_form_autofills.allowed && orgUserSettings.expense_form_autofills.enabled;
do we still need to check ``orgUserSettings && ` . IIRC in another PR you already added this in model

2021-03-05 07:50 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const doRecentOrgCategoryIdsExist = isAutofillsEnabled && recentValue && recentValue.recent_org_category_ids && recentValue.recent_org_category_ids.length > 0;
same here for recentValue

2021-03-08 09:05 UTC, abhishek1234321 requested changes

2021-03-08 09:05 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const isCategoryExtracted = etxn.tx && etxn.tx.extracted_data && etxn.tx.extracted_data.category && etxn.tx.fyle_category && etxn.tx.fyle_category !== 'Unspecified';
do we need this extra check `etxn.tx.fyle_category`? 4th condition isn't really needed no?

2021-03-08 09:05 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        const autoFillCategory = recentCategories && recentCategories[0];
we aren't checking for length no?

2021-03-08 09:05 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>        console.log({ report });
will console logs appear in production build @madhavmansuriya40 @Julias0 @tarunkumarfyle ?

2021-03-08 09:05 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      if ((!this.fg.controls.category.value || (this.autoFilledCategory)) && extractedData.category) {
please explain in code comments on what is happening here?

2021-03-08 09:05 UTC, abhishek1234321 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
>    recentrecentlyUsedItems$: Observable<any[]>;
why is this `any`?

2021-03-08 09:05 UTC, abhishek1234321 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +      this.recentrecentlyUsedItems$ = of(this.recentlyUsed);
what `recentrecentlyUsedItems` mean? `recentRecently`?

2021-03-08 09:05 UTC, abhishek1234321 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +      this.recentrecentlyUsedItems$ = from(this.recentLocalStorageItemsService.get(this.cacheName)).pipe(
explain in code comments, on what is happening here?

2021-03-08 09:07 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  recentCategories$: any;
also shouldn't `doRecentOrgCategoryIdsExist` be a type `boolean`?

2021-03-08 09:34 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  recentCategories: any;
Added recentCategories as it can be null or list of category ids

2021-03-08 11:48 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>        console.log({ report });
no... on prod build console log got removed automatically.

2021-03-08 12:48 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      filteredCategories: this.filteredCategories$.pipe(take(1)),
has multiple observables, but here we need the first one cc @Julias0 @abhishek1234321

2021-03-08 12:49 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          recentCategories: this.getRecentlyUsedCategories()
this is used only in one place so haven't added as an observable

2021-03-08 12:50 UTC, Dimple16 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +      this.recentrecentlyUsedItems$ = of(this.recentlyUsed);
yes, this is existing naming, haven't changed

2021-03-08 12:51 UTC, Dimple16 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +      this.recentrecentlyUsedItems$ = from(this.recentLocalStorageItemsService.get(this.cacheName)).pipe(
this is existing `recentlyUsedItems` using `localstorage` , no change in codebase here except for the if/else block

2021-03-10 05:14 UTC, Julias0 commented on src/app/shared/components/fy-select/fy-select.component.ts
> +  @Input() recentlyUsed: any[];
Dont we have a model for recently used?

2021-03-10 05:19 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          recentCategories: this.getRecentlyUsedCategories()
So inside forkjoin we avoid putting the $ in the key name otherwise the return value will also come with a $, which is not a observable.
Ex - if we put `recentCategories$` here, it will come up as `recentCategories$` in line 1126

2021-03-10 05:23 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      filteredCategories: this.filteredCategories$.pipe(take(1)),
so filteredCategories$ is a stream that changes value(i.e. what categories are available) depending on what project we have selected etc.

For `getRecentlyUsedCategories` we need the first value of that stream because autofill happens when the form is initially loaded.

2021-03-10 05:23 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  recentCategories: any[];
:knife:

2021-03-11 08:40 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                      formControlName="category">
please check all linting issues

2021-03-11 08:40 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  recentCategories: any;
can we rename this to `recentCategorieIds` ?

2021-03-11 08:40 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    const orgUserSettings$ = this.orgUserSettings$;
can we not use `this.orgUserSettings$` where `orgUserSettings$` is used?

2021-03-11 08:40 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    const orgUserSettings$ = this.orgUserSettings$;
i think we are not using this `const orgUserSettings$`, if not please remove

2021-03-11 08:40 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
>    recentrecentlyUsedItems$: Observable<any[]>;
this is not taken care yet @Dimple16

2021-03-11 08:40 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +      this.recentrecentlyUsedItems$ = of(this.recentlyUsed);
can we rename the observable name here?

2021-03-11 08:40 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +      this.recentrecentlyUsedItems$ = from(this.recentLocalStorageItemsService.get(this.cacheName)).pipe(
please add code comments

2021-03-11 08:40 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +        map((options: any) => {
`any` ?

2021-03-11 08:43 UTC, Dimple16 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +        map((options: any) => {
haven't changed any existing code @madhavmansuriya40

2021-03-11 08:43 UTC, Dimple16 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +      this.recentrecentlyUsedItems$ = from(this.recentLocalStorageItemsService.get(this.cacheName)).pipe(
just added the if block, else block remains the same as existing with no change of auto-fills

2021-03-11 08:45 UTC, Dimple16 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +      this.recentrecentlyUsedItems$ = of(this.recentlyUsed);
not changing existing code

2021-03-11 08:47 UTC, Dimple16 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
>    recentrecentlyUsedItems$: Observable<any[]>;
not changing existing code, this is taken care in auto-fills recentlyused

2021-03-11 08:49 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    const orgUserSettings$ = this.orgUserSettings$;
this is used in line 812 @madhavmansuriya40

2021-03-11 09:00 UTC, madhavmansuriya40 approved these changes

2021-03-14 13:01 UTC, iamtarun1993 commented on src/app/core/models/org-category.model.ts
> +  displayName: string;
`displayName` is optional. IIRC it is not coming from API response. We are calculating this variable in the app.

2021-03-14 13:04 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  recentCategories: { label: string, value: OrgCategory, selected?: boolean }[];
can we convert this `selected` variable to `is_selected`?
will this change affect other areas also?
If this change needs to do a major change in the app, you can leave now. just put a //todo over here.

2021-03-14 13:08 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          recentCategories: this.getRecentlyUsedCategories()
yes, in some places we followed this `test$` inside forkJoin(), we need to fix those later.

2021-03-14 13:08 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>        console.log({ report });
remove it @Dimple16

2021-03-14 13:11 UTC, iamtarun1993 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +  @Input() recentlyUsed: { label: string, value: OrgCategory | CostCenter, selected?: boolean }[];
hey no no.. this is a common component. we can't use 2 models something like this.
I don't think this is a good idea to do.
A component should be dull as much as possible.

2021-03-14 13:13 UTC, iamtarun1993 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +  @Input() recentlyUsed: { label: string, value: OrgCategory | CostCenter, selected?: boolean }[];
@abhishek1234321 @Julias0 please help here.

2021-03-14 13:14 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        if (filteredCategories && filteredCategories.length > 0 && recentValue.recent_org_category_ids && recentValue.recent_org_category_ids.length > 0) {
Lets move the contents of this method into a service

2021-03-14 13:17 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    return forkJoin({
what will happen in offline mode??

2021-03-14 13:19 UTC, iamtarun1993 commented on src/app/shared/components/fy-select/fy-select.component.ts
> +  @Input() recentlyUsed: { label: string, value: OrgCategory | CostCenter, selected?: boolean }[];
same here

2021-03-14 13:20 UTC, Julias0 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +  @Input() recentlyUsed: { label: string, value: OrgCategory | CostCenter, selected?: boolean }[];
The right way to do this is here - 
https://stackoverflow.com/questions/46893991/declare-a-component-with-generic-type

It is a bit verbose - and imho should be done as a separate step since this needs to be fixed in multi select too

2021-03-14 13:23 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const isAutofillsEnabled = orgUserSettings.expense_form_autofills && orgUserSettings.expense_form_autofills.allowed && orgUserSettings.expense_form_autofills.enabled;
can you make this a helper method inside some service? 
orgUserSettingsService.isAutofillsEnables(orgUserSettings: OrgUserSettings)

2021-03-14 13:23 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const doRecentOrgCategoryIdsExist = isAutofillsEnabled && recentValue.recent_org_category_ids && recentValue.recent_org_category_ids.length > 0;
same as above
orgUserSettingsService. doRecentOrgCategoryIdsExist(orgUserSettings: OrgUserSettings, recentValue: RecentValues)

2021-03-14 13:24 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const isCategoryExtracted = etxn.tx && etxn.tx.extracted_data && etxn.tx.extracted_data.category && etxn.tx.fyle_category !== 'Unspecified';
same as above, lets move this inside a service

2021-03-14 13:26 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      if (doRecentOrgCategoryIdsExist && !etxn.tx.id ||
instead of variables inside the `if` condition, use methods - 
`if (TransactionService.isExpenseInDraftState(etxn) && !DataExtractionService.isCategoryExtracted(etxn.tx.extracted_data))`

2021-03-15 06:54 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  recentCategories: { label: string, value: OrgCategory, selected?: boolean }[];
In all the modals we are using as `selected` will need to change there too, adding a //todo over here @tarunkumarfyle

2021-03-15 09:05 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const isAutofillsEnabled = orgUserSettings.expense_form_autofills && orgUserSettings.expense_form_autofills.allowed && orgUserSettings.expense_form_autofills.enabled;
will need to change this in all other prs, will create a separate clean up pr for this cc @iamtarun1993

2021-03-15 09:06 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const doRecentOrgCategoryIdsExist = isAutofillsEnabled && recentValue.recent_org_category_ids && recentValue.recent_org_category_ids.length > 0;
will add this in clean up pr too cc @iamtarun1993

2021-03-15 09:37 UTC, iamtarun1993 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentCategories(filteredCategories, recentValues): Observable<{ label: string, value: OrgCategory, selected?: boolean }[]> {
define the dataType of these two input params also.

2021-03-15 09:39 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const isAutofillsEnabled = orgUserSettings.expense_form_autofills && orgUserSettings.expense_form_autofills.allowed && orgUserSettings.expense_form_autofills.enabled;
OK.

2021-03-15 09:41 UTC, iamtarun1993 approved these changes

2021-03-15 10:56 UTC, iamtarun1993 approved these changes

2021-03-15 16:41 UTC, abhishek1234321 approved these changes

2022-08-19 10:17 UTC, closed without merging