Fyle-27cvh7: Cost center auto-fills in all expense forms
fylein/fyle-mobile-app pull request #284
Opened 2021-02-26 19:14 UTC by Dimple16

https://user-images.githubusercontent.com/31147415/109344550-e1940800-7894-11eb-9183-e2f74c3e3208.mov

2021-02-27 16:00 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    )
`;` after every .pipe end

2021-02-27 16:03 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          this.autoFilledCostCenter = autoFillCostCenter.value.id;
In this PR I can only see this value assigned, but never used.

Is it used in any other PR.. If yes ignore this comment, else remove this variable

2021-03-01 04:25 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const doRecentCostCenterIdsExist = isAutofillsEnabled && recentValue && recentValue.recent_cost_center_ids && recentValue.recent_cost_center_ids.length > 0;
do you still need `recentValue && recentValue.recent_cost_center_ids`

2021-03-01 04:26 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const doRecentCostCenterIdsExist = isAutofillsEnabled && recentValue && recentValue.recent_cost_center_ids && recentValue.recent_cost_center_ids.length > 0;
Will not Ts model will take care of this thing ?

2021-03-01 04:27 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      const doRecentCostCenterIdsExist = isAutofillsEnabled && recentValue && recentValue.recent_cost_center_ids && recentValue.recent_cost_center_ids.length > 0;
same as above

2021-03-01 05:07 UTC, iamtarun1993 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +      const doRecentCostCenterIdsExist = isAutofillsEnabled && recentValue && recentValue.recent_cost_center_ids && recentValue.recent_cost_center_ids.length > 0;
same as above

2021-03-01 05:07 UTC, iamtarun1993 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +        const autoFillCostCenter = recentCostCenters && recentCostCenters[0];
same as above

2021-03-01 10:11 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          this.autoFilledCostCenter = autoFillCostCenter.value.id;
This will be used in tracking events pr - will assign tracking pr separately for all fields

2021-03-01 10:15 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const doRecentCostCenterIdsExist = isAutofillsEnabled && recentValue && recentValue.recent_cost_center_ids && recentValue.recent_cost_center_ids.length > 0;
will need `recentValue.recent_cost_center_ids` as it can be null

2021-03-01 10:17 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      const doRecentCostCenterIdsExist = isAutofillsEnabled && recentValue && recentValue.recent_cost_center_ids && recentValue.recent_cost_center_ids.length > 0;
will need recentValue.recent_cost_center_ids as it can be null

2021-03-01 10:17 UTC, Dimple16 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +      const doRecentCostCenterIdsExist = isAutofillsEnabled && recentValue && recentValue.recent_cost_center_ids && recentValue.recent_cost_center_ids.length > 0;
will need recentValue.recent_cost_center_ids as it can be null

2021-03-01 10:18 UTC, Dimple16 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +        const autoFillCostCenter = recentCostCenters && recentCostCenters[0];
This will be used in tracking events pr - will assign tracking pr separately for all fields

2021-03-01 15:16 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          this.autoFilledCostCenter = autoFillCostCenter.value.id;
ok.

2021-03-03 08:51 UTC, iamtarun1993 approved these changes

2021-03-04 12:33 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        const autoFillCostCenter = recentCostCenters && recentCostCenters[0];
if the model for recent value is there
we can remove the existence check
`recentCostCenters[0]` instead of `recentCostCenters && recentCostCenters[0]`

please check this

2021-03-04 12:33 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>        console.log({ report });
can we remove this?

2021-03-04 12:33 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  recentlyUsedCostCenters$: Observable<any>;
can we use
`recentlyUsedCostCenters$: Observable< RecentlyUsed >;`

if the model for RecentlyUsed and RecentlyUsedCostCenters will be the same

2021-03-04 12:33 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  recentCostCenters: any;
this might be an array of ids
if yes, can we user `recentCostCenters: [];`

2021-03-04 12:33 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      const isAutofillsEnabled = orgUserSettings.expense_form_autofills.allowed && orgUserSettings.expense_form_autofills.enabled;
same as `add-edit-expense.page.ts`

2021-03-04 12:33 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      const doRecentCostCenterIdsExist = isAutofillsEnabled && recentValue.recent_cost_center_ids && recentValue.recent_cost_center_ids.length > 0;
same as `add-edit-expense.page.ts`

2021-03-04 12:33 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +        const autoFillCostCenter = recentCostCenters && recentCostCenters[0];
same as `add-edit-expense.page.ts`

2021-03-04 12:33 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +  recentCostCenters: any;
`[]` instead of any

2021-03-04 12:33 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +      recentValue: this.recentlyUsedValues$
if `this.recentlyUsedValues$` is not used at multiple places can directly make an api call here

2021-03-04 12:33 UTC, madhavmansuriya40 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +  @Input() recentlyUsed;
it will be good if we define the type everywhere

2021-03-05 07:24 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const doRecentCostCenterIdsExist = isAutofillsEnabled && recentValue.recent_cost_center_ids && recentValue.recent_cost_center_ids.length > 0;
tried this, but recent_cost_center_ids can be null too - will throw length of undefined error cc @madhavmansuriya40

2021-03-05 07:25 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        const autoFillCostCenter = recentCostCenters && recentCostCenters[0];
this not from the model, it is from filtered cost center list cc @madhavmansuriya40

2021-03-05 07:28 UTC, Dimple16 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +      recentValue: this.recentlyUsedValues$
will be used for project auto-fill too cc @madhavmansuriya40

2021-03-05 07:34 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +       * 4. When there exists recently used cost center ids to auto-fill
This is work even on edit case cc @madhavmansuriya40

2021-03-05 07:35 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      const isAutofillsEnabled = orgUserSettings.expense_form_autofills.allowed && orgUserSettings.expense_form_autofills.enabled;
recent_cost_center_ids can be null too - will throw length of undefined error @madhavmansuriya40

2021-03-05 07:35 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      const doRecentCostCenterIdsExist = isAutofillsEnabled && recentValue.recent_cost_center_ids && recentValue.recent_cost_center_ids.length > 0;
same as above

2021-03-08 07:45 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      const doRecentCostCenterIdsExist = isAutofillsEnabled && recentValue.recent_cost_center_ids && recentValue.recent_cost_center_ids.length > 0;
api will return null in few cases, resolved offline

2021-03-08 07:47 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  recentlyUsedCostCenters$: Observable<any>;
Recently used cost centers is inside recently used, no model for this

2021-03-08 07:53 UTC, Dimple16 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.ts
> +  @Input() recentlyUsed;
It can be null in a few cases

2021-03-09 05:45 UTC, madhavmansuriya40 approved these changes

2021-03-09 07:07 UTC, abhishek1234321 requested changes

2021-03-09 07:07 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            costCentersList.filter(res => {
the usage of filter is wrong, filter generates a new array anyway so why push to another array? @tarunkumarfyle @Dimple16

2021-03-09 07:07 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          recentValue.recent_cost_center_ids.forEach(costCenterId => {
not understanding what is happening here, why do you need a filter inside a forEach?

2021-03-09 07:07 UTC, abhishek1234321 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      map(({costCenters, recentValue}) => {
isn't this repeated in multiple places? shouldn't this be common?

2021-03-09 07:14 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          recentValue.recent_cost_center_ids.forEach(costCenterId => {
filtering in `594` does not retain the order od recent items, it filters in the order of the categoryList, so added a `foreach` to filter it from the recent sorted list

2021-03-09 07:27 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      map(({costCenters, recentValue}) => {
I think we can move this to a service, but make sure the previous two observables are not linked to form-Group..

2021-03-09 07:29 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  recentCostCenters: any;
we don't have any models for cost-center now. You can create a model for cost-center but then you need to update this in many places.

2021-03-09 13:46 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      map(({costCenters, recentValue}) => {
moved the computation to service now cc @abhishek1234321 @iamtarun1993

2021-03-09 17:59 UTC, abhishek1234321 approved these changes

2021-03-09 17:59 UTC, abhishek1234321 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentCostCenters(costCenters, recentValue):Observable<any> {
`Observable<any>` or will this be `Observable<int[]>`?

2021-03-09 17:59 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  recentlyUsedCostCenters$: Observable<any>;
why is this `any`?

2021-03-09 18:03 UTC, Dimple16 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentCostCenters(costCenters, recentValue):Observable<any> {
This is a list of cost center objects cc @abhishek1234321

2022-08-19 10:17 UTC, closed without merging