FYLE-27cvh0: Project auto-fills in expense forms
fylein/fyle-mobile-app pull request #287
Opened 2021-03-01 14:57 UTC by Dimple16

2021-03-03 08:55 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        concatMap((projectIds) => {
what will happen if the above condition becomes false ???

2021-03-03 09:05 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            switchMap((eou) => {
this look. little bit complex.
try to avoid nested switchmap

2021-03-03 09:39 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        concatMap((projectIds) => {
this is fixed

2021-03-03 09:41 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            switchMap((eou) => {
doing the same way used in `fy-select-modal-component`

2021-03-03 11:40 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            switchMap((eou) => {
@Julias0 can you check this place.. I'm guessing we can solve this in a better way??
too much-nested thing is happening here...

2021-03-03 11:41 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            return(null);
return null you can skip. It will return undefined which would behave the same

2021-03-03 11:42 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            return(null);
return null;

2021-03-03 11:42 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            return(null);
why () is needed here?

2021-03-03 11:42 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        concatMap((projectIds) => {
use switchMap here. The data will flow through this pipe only once, so concatMap is not necessary

2021-03-03 11:44 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            switchMap((eou) => {
You can use this to avoid nesting @Dimple16 
https://www.learnrxjs.io/learn-rxjs/operators/combination/withlatestfrom

2021-03-03 11:45 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  getRecentlyUsedProjects() {
I think this whole method can be moved into a service

2021-03-03 11:47 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                this.recentProjects = recentProjects;
Do not set values inside map. Do assignments only inside subscribe

2021-03-03 11:47 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                this.autoFillProject =  orgUserSettings.preferences.default_project_id;
same as above

2021-03-03 11:59 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            return(null);
if returning [] but else returning null not a good idea.
check #engineering channel.

2021-03-05 17:22 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              projectIds: projectIds,
only `projectIds`. In TypeScript if key and value is same no need to do `key: key` only `key` is enough

2021-03-05 17:28 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                this.recentProjects = recentProjects;
yes please... can you take care of this in Category PR also??

2021-03-08 05:42 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +              mileageCategoryIds: mileageCategoryIds,
only mileageCategoryIds

2021-03-08 05:44 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +                this.recentProjects = recentProjects;
Set value inside subscribe.. not inside map.

2021-03-09 03:16 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +    }).pipe(
reference for the above comment, you can apply this same snippet above

2021-03-10 05:25 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  recentlyUsedProjects$: Observable<any>;
same as above

2021-03-10 05:25 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +  recentlyUsedProjects$: Observable<any>;
same as above, also check if at other places(in your changes) `any` can be replaced?

2021-03-11 04:11 UTC, madhavmansuriya40 approved these changes

2021-03-11 04:11 UTC, madhavmansuriya40 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentlyUsedProjects(orgUserSettings, recentValue, eou, categoryIds):Observable<ExtendedProject[]> {
`: `

2021-03-11 04:11 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              if (orgSettings.projects.enabled && orgUserSettings.preferences && orgUserSettings.preferences.default_project_id) {
please remove

2021-03-11 09:11 UTC, iamtarun1993 commented on src/app/core/models/extendedProject.model.ts
> +  ap1_email?: string;
why these things are non-mandatory... these keys will always come in an API response. value can be null.

you should only put "?" when you are calculating any key value in the frontend in some places.
ex: assume we are calculating project_display_name like this to show this in some places
project_display_name: project_code + project_name + project_description


project_display_name?: string;

2021-03-11 09:17 UTC, iamtarun1993 commented on src/app/core/models/extendedProject.model.ts
> +  ap1_email?: string;
you can check the reference from the fyle-api model reference.
please talk to @lakshmisuhas1996 if you need to understand why we are doing this.

2021-03-11 09:20 UTC, Dimple16 commented on src/app/core/models/extendedProject.model.ts
> +  ap1_email?: string;
had referred @lakshmisuhas1996 's pr and added the same here - https://github.com/fylein/fyle-mobile-app2/pull/296/files @iamtarun1993

2021-03-11 09:21 UTC, iamtarun1993 commented on src/app/core/models/extendedProject.model.ts
> +export interface ExtendedProject {
filename `extended-project.model.ts`

2021-03-11 09:31 UTC, lakshmisuhas1996 commented on src/app/core/models/extendedProject.model.ts
> +  ap1_email?: string;
@Dimple16 the pr is wip; all the properties that are included in API response should not be optional in ts model. It is olay if the values are null for some props

2021-03-11 09:39 UTC, iamtarun1993 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentlyUsedProjects(orgUserSettings, recentValue, eou, categoryIds): Observable<ExtendedProject[]> {
use `getRecentlyUsedProjects (config: {orgUserSettings: dataType, recentValue: dataType, eou: dataType, categoryIds: dataType})`

make some required changes in page.ts also.

2021-03-11 09:40 UTC, iamtarun1993 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentlyUsedProjects(orgUserSettings, recentValue, eou, categoryIds): Observable<ExtendedProject[]> {
Lemme know why we are doing this.
you can check `getv2CardTransactions` method.

2021-03-11 09:42 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  presetProject: number;
what is `presentProject` ?
it should be `currentProject` or something else.

2021-03-11 09:43 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  presetProject: number;
pre-filled project id

2021-03-11 09:45 UTC, iamtarun1993 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  presetProject: number;
and why dataType is number?

2021-03-11 09:45 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  presetProject: number;
same as above

2021-03-11 09:46 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  presetProject: number;
project id is of type number

2021-03-11 09:48 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  presetProject: number;
as the project is prefilled, kept the naming as `preset` following the same in webapp too @iamtarun1993

2021-03-11 15:37 UTC, iamtarun1993 approved these changes

2021-03-12 05:00 UTC, abhishek1234321 requested changes

2021-03-12 05:05 UTC, Dimple16 commented on src/app/core/services/recently-used-items.service.ts
> +  getRecentlyUsedProjects(config: {orgUserSettings: OrgUserSettings, recentValue: RecentlyUsed, eou: ExtendedOrgUser, categoryIds: string[]}): Observable<ExtendedProject[]> {
when this method is called will need to check for data type and pass params, passing this way will not have to check in service again cc @iamtarun1993 @abhishek1234321  - https://github.com/fylein/fyle-mobile-app2/pull/287#discussion_r592205345

2021-03-12 13:36 UTC, abhishek1234321 approved these changes

2022-08-19 10:17 UTC, closed without merging