feat: Add eject expenses from platform
fylein/fyle-mobile-app pull request #2875
Opened 2024-04-19 04:52 UTC by bistaastha

Tests will be fixed in follow up PR

2024-04-19 04:53 UTC, bistaastha commented on src/app/core/services/platform/v1/approver/reports.service.ts
> +    return this.approverPlatformApiService.post<void>('/reports/eject_expenses', payload);
returning a void observable following the existing pattern for remove transaction API

2024-04-19 06:23 UTC, Chethan-Fyle commented on src/app/core/services/platform/v1/approver/reports.service.spec.ts
> +  let reportsService: ApproverReportsService;
`reportsService` --> `approverReportsService`.

2024-04-19 06:25 UTC, Chethan-Fyle commented on src/app/core/services/platform/v1/spender/reports.service.spec.ts
> +  let reportsService: SpenderReportsService;
`reportsService` --> `spenderReportsService`.

2024-04-19 06:29 UTC, Chethan-Fyle commented on src/app/fyle/view-expense/view-expense.page.ts
> +    private reportsService: ApproverReportsService
`reportsService` --> `approverReportsService`

2024-04-19 06:31 UTC, Chethan-Fyle requested changes
Minor comments.

2024-04-23 06:48 UTC, mvaishnavi commented on src/app/core/services/platform/v1/approver/reports.service.ts
> +  ejectExpenses(rptId: string, txnId: string, comment?: string[]): Observable<void> {
`expenseId`
let's fix this terminology for the add Expense to report service method too.

2024-04-23 06:51 UTC, mvaishnavi approved these changes

2024-04-25 06:09 UTC, Chethan-Fyle approved these changes

2024-04-26 07:09 UTC, merged