feat: Migrate getbyId -> spenderPlatformV1ApiService
fylein/fyle-mobile-app pull request #2946
Opened 2024-05-03 12:06 UTC by SahilK-027

### Description
Successfully migrated `getbyId` -> `spenderPlatformV1ApiService`
Tested working for ✅:
```js
add-edit-advance.page
add-edit-expense.page
add-edit-mileage.page
add-edit-per-diem.page
fy-select-project-modal.component
```

<img width="1440" alt="Screenshot 2024-05-03 at 5 30 42 PM" src="https://github.com/fylein/fyle-mobile-app/assets/104154041/2ba13455-135f-4c37-92be-c2ff7090df6c">

## Clickup
[Please add link here](https://app.clickup.com/t/86cv9xc5e)

2024-05-06 09:23 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +      expect(apiV2ResponseSingle.data[0]).toEqual(jasmine.objectContaining(res));
is it the right way to test mocked objects?

2024-05-06 09:25 UTC, devendrafyle approved these changes
Minor comment

2024-05-06 09:30 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +      expect(apiV2ResponseSingle.data[0]).toEqual(jasmine.objectContaining(res));
Mock data has some fields that are not there in the `PlatformAPI` response so I am testing it against `objectContaining`. I think this is the correct way to test otherwise we will have to change the entire APIV2 mock data.

2024-05-06 09:36 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +      expect(apiV2ResponseSingle.data[0]).toEqual(jasmine.objectContaining(res));
create new mock data, sir, that depicts the real scenario after the update, why apiV2Data if we are hitting platform API

2024-05-06 10:05 UTC, suyashpatil78 commented on src/app/core/services/projects.service.spec.ts
> +      expect(apiV2ResponseSingle.data[0]).toEqual(jasmine.objectContaining(res));
+1

2024-05-06 10:16 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +      expect(apiV2ResponseSingle.data[0]).toEqual(jasmine.objectContaining(res));
Sure @devendrafyle 👍

2024-05-06 10:51 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +    expect(spenderPlatformV1ApiService.get).toHaveBeenCalledWith('/projects', {
Done sir

2024-05-06 10:53 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +          id: 'eq.257528',
why the `transform` method is not mocked? please test that function as well if it's being called or used.

2024-05-06 11:21 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +          id: 'eq.257528',
Done!

2024-05-06 11:35 UTC, Dimple16 requested changes
added comments

2024-05-06 11:35 UTC, Dimple16 commented on src/app/core/test-data/projects.spec.data.ts
> +import { PlatformProject } from '../models/platform/platform-project.model';
we shouldn't be adding the mock data here
there should be a mock data file for platformProject in the mock data folder 
`/mock-data/platform-project.data.ts` 
All the mock data related to `PlatformProject` model should be added there

2024-05-06 11:35 UTC, Dimple16 commented on src/app/core/test-data/projects.spec.data.ts
> +export const platformProjectSingleRes: PlatformApiResponse<PlatformProject[]> = deepFreeze({
this should be in a separate file

2024-05-06 11:48 UTC, SahilK-027 commented on src/app/core/test-data/projects.spec.data.ts
> +import { PlatformProject } from '../models/platform/platform-project.model';
Ok

2024-05-06 11:48 UTC, SahilK-027 commented on src/app/core/test-data/projects.spec.data.ts
> +export const platformProjectSingleRes: PlatformApiResponse<PlatformProject[]> = deepFreeze({
Ok

2024-05-07 05:42 UTC, Dimple16 requested changes
one question
we shouldn't be using `deepFreeze` 
Why is it needed?

2024-05-07 05:42 UTC, Dimple16 commented on src/app/core/test-data/platformProjects.spec.data.ts
> +import deepFreeze from 'deep-freeze-strict';
why is this needed?

2024-05-07 05:48 UTC, SahilK-027 commented on src/app/core/test-data/platformProjects.spec.data.ts
> +import deepFreeze from 'deep-freeze-strict';
@suyashpatil78 can you please explain?

2024-05-07 06:06 UTC, SahilK-027 commented on src/app/core/test-data/platformProjects.spec.data.ts
> +import deepFreeze from 'deep-freeze-strict';
- If there is a common global mock data that we are using in two different places, then if the data gets modified in one place it affects the other test cases in different files.
- So we need to create a deep copy of data but it's not feasible to make a deep copy in every place we are using and modifying the mock data, hence we are using a new dependency `deep-freeze`.

2024-05-07 10:20 UTC, Dimple16 approved these changes

2024-05-07 10:26 UTC, merged