fix:  null behavior of category_ids Platform Projects Migration
fylein/fyle-mobile-app pull request #3003
Opened 2024-05-17 10:41 UTC by SahilK-027

### Description
fix:  `null` behavior of category_ids Platform Projects Migration

## Clickup
[Please add link here](https://app.clickup.com/t/86cvduwju)

2024-05-17 12:11 UTC, suyashpatil78 commented on src/app/core/services/projects.service.ts
> +        map((projectV2Array: ProjectV2[]) => projectV2Array)
Why is map required here?

2024-05-17 12:16 UTC, SahilK-027 commented on src/app/core/services/projects.service.ts
> +        map((projectV2Array: ProjectV2[]) => projectV2Array)
`transformToV2Response` now  returns an `Observable<ProjectV2[]>`  so map to extract the first ProjectV2 object from the array emitted by `transformToV2Response` by the previous observable.

2024-05-20 12:34 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +    const params = ProjectPlatformParams;
why this ?

2024-05-20 12:35 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +    const params = ProjectPlatformParams;
you directly use the mock data, no need of additional variables

2024-05-20 12:35 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +      expect(projectsService.transformToV2Response).toHaveBeenCalled();
`toHaveBeenCalledWith`

2024-05-20 12:37 UTC, devendrafyle commented on src/app/core/services/projects.service.ts
> -    }>
dont we have data type for this ?

2024-05-20 12:53 UTC, devendrafyle approved these changes
Minor comments

2024-05-20 12:57 UTC, devendrafyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      projects: activeCategories$.pipe(switchMap((categories) => this.projectsService.getAllActive(categories))),
where are you passing the `activeCategories` ?

2024-05-20 12:57 UTC, devendrafyle requested changes
Minor comments

2024-05-23 05:56 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +    });
not the right way, why you are calling the service in test file, we create mock object and test them here not use their functions, if you want to mock this service method then create the mock data for `active` categories and use it here

2024-05-23 05:56 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +      expect(projectsService.transformToV1Response).toHaveBeenCalled();
use `toHaveBeenCalledOnceWith`

2024-05-23 05:59 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +  });
why the transform method is not covered here,

2024-05-23 06:01 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +      expect(projectsService.transformToV2Response).toHaveBeenCalled();
why this is conversation is marked resolved if nothing is updated

2024-05-23 06:01 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +    const params = ProjectPlatformParams;
nothing is updated

2024-05-23 06:02 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +    });
mentioned above

2024-05-23 06:04 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +    });
why new variables have been used when they can avoided

2024-05-23 06:04 UTC, devendrafyle commented on src/app/core/services/projects.service.ts
> -    }>
why this is not updated

2024-05-23 06:06 UTC, SahilK-027 commented
I will work on suggested changes @devendrafyle 👍

2024-05-23 06:09 UTC, devendrafyle commented on src/app/core/services/recently-used-items.service.spec.ts
> +      });
mentioned aboved

2024-05-23 06:16 UTC, devendrafyle requested changes
Please resolve all the comments

2024-05-23 07:19 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +      expect(projectsService.transformToV1Response).toHaveBeenCalled();
Done 👍

2024-05-23 07:19 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +    const params = ProjectPlatformParams;
Done 👍

2024-05-23 07:20 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +      expect(projectsService.transformToV2Response).toHaveBeenCalled();
Done 👍

2024-05-23 07:26 UTC, SahilK-027 commented on src/app/core/services/projects.service.ts
> -    }>
No we don't have it!

2024-05-23 07:29 UTC, SahilK-027 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      projects: activeCategories$.pipe(switchMap((categories) => this.projectsService.getAllActive(categories))),
Done 👍

2024-05-23 07:29 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +    });
Created mock data 👍

2024-05-23 07:30 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +  });
Covered in every place 👍

2024-05-23 07:30 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +    });
Done 👍

2024-05-23 07:30 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +      expect(projectsService.transformToV1Response).toHaveBeenCalled();
Done 👍

2024-05-23 07:30 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +    });
Done 👍

2024-05-23 07:31 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +    });
OK done 👍

2024-05-23 07:31 UTC, SahilK-027 commented on src/app/core/services/recently-used-items.service.spec.ts
> +      });
Done 👍

2024-05-23 07:32 UTC, SahilK-027 commented on src/app/core/services/projects.service.ts
> -    }>
Should I create it? I don't think a need, it's used in only one place.

2024-05-23 09:42 UTC, SahilK-027 commented
Will work on code coverage after getting ✅

2024-05-23 12:36 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +      expect(res).toEqual(expectedReponseActiveOnly);
we always expect `res` in the end of the method before `done()`

2024-05-23 12:37 UTC, devendrafyle approved these changes
Minor comment, Please fix the test cases and test thoroughly

2024-05-23 12:37 UTC, devendrafyle commented on src/app/core/services/projects.service.spec.ts
> +      expect(res).toEqual(expectedReponseActiveOnly);
Please try to implement everywhere you have used this.

2024-05-27 10:11 UTC, Dimple16 requested changes
added comments

2024-05-27 10:11 UTC, Dimple16 commented on src/app/core/services/projects.service.spec.ts
> +    expect(projectsService.getAllActive).toHaveBeenCalledWith(undefined);
why undefined?

2024-05-27 10:11 UTC, Dimple16 commented on src/app/core/services/projects.service.ts
>    // TODO: We should remove this from being used and replace with transform
this comment is not required anymore

2024-05-27 10:11 UTC, Dimple16 commented on src/app/core/services/projects.service.ts
> -    }>
let's add one

2024-05-27 10:11 UTC, Dimple16 commented on src/app/core/services/recently-used-items.service.spec.ts
> +          {
once you add the new model
move this entire thing to the new mock data file

2024-05-27 10:11 UTC, Dimple16 commented on src/app/core/services/recently-used-items.service.spec.ts
> +      categoriesService.getAll().subscribe((categories) => {
why are we making another API call here?

2024-05-27 10:11 UTC, Dimple16 commented on src/app/core/services/recently-used-items.service.spec.ts
> +      categoriesService.getAll().subscribe((categories) => {
why is this required?

2024-05-27 10:11 UTC, Dimple16 commented on src/app/core/test-data/projects.spec.data.ts
> +export const testActiveCategoryList: OrgCategory[] = deepFreeze([
`activeCategoryList` should do

2024-05-27 10:11 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      projectsCount: this.projectsService.getProjectCount({ categoryIds: [] }, this.allActiveCategories),
in which case will the first argument be passed?

2024-05-27 10:11 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    activeCategories$.subscribe((activeCategories) => {
have we tested this well if there is any race condition here?

2024-05-27 10:11 UTC, Dimple16 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +  it('onDoneClick(): should dimiss the modal on clicking the done CTA', async () => {
can we use the convention followed across for async unit tests by using faskeasync?

2024-05-27 10:11 UTC, Dimple16 commented
please fix the unit tests

2024-05-28 05:55 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +      expect(res).toEqual(expectedReponseActiveOnly);
Ok fixed all the occurrences 👍

2024-05-28 05:56 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +  it('should be able to fetch project by id with activeCategoryList', (done) => {
Ok

2024-05-28 05:58 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +    expect(projectsService.getAllActive).toHaveBeenCalledWith(undefined);
The caller can provide three things:
- `null`
- `All categories array`
- `nothing` (undefined)

2024-05-28 05:59 UTC, SahilK-027 commented on src/app/core/services/projects.service.ts
>    // TODO: We should remove this from being used and replace with transform
Done 👍

2024-05-28 06:00 UTC, SahilK-027 commented on src/app/core/services/recently-used-items.service.spec.ts
> +      categoriesService.getAll().subscribe((categories) => {
Yes this should be removed

2024-05-28 06:03 UTC, SahilK-027 commented on src/app/core/services/recently-used-items.service.spec.ts
> +      categoriesService.getAll().subscribe((categories) => {
This is Done 👍

2024-05-28 06:05 UTC, SahilK-027 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      projectsCount: this.projectsService.getProjectCount({ categoryIds: [] }, this.allActiveCategories),
If we want to get the count of projects which are mapped with the particular categories.
`const categoryIds = params.categoryIds?.map((categoryId) => parseInt(categoryId, 10));`

2024-05-28 06:15 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +  it('should be able to fetch project by id with activeCategoryList', (done) => {
Done 👍

2024-05-28 06:15 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +  it('should be able to fetch data when no params provided and activeCategoryList is null', (done) => {
Done 👍

2024-05-28 06:33 UTC, SahilK-027 commented on src/app/core/services/recently-used-items.service.spec.ts
> +          {
Done 👍

2024-05-28 06:33 UTC, SahilK-027 commented on src/app/core/services/recently-used-items.service.spec.ts
> +      categoriesService.getAll().subscribe((categories) => {
Done 👍

2024-05-28 06:34 UTC, SahilK-027 commented on src/app/core/test-data/projects.spec.data.ts
> +export const testActiveCategoryList: OrgCategory[] = deepFreeze([
I think we should keep the consistency
<img width="1440" alt="Screenshot 2024-05-28 at 12 02 36 PM" src="https://github.com/fylein/fyle-mobile-app/assets/104154041/90e84c0f-8538-4010-9b0d-58ab9682865a">

2024-05-28 06:38 UTC, SahilK-027 commented on src/app/shared/components/fy-select-project/fy-select-modal/fy-select-project-modal.component.spec.ts
> +  it('onDoneClick(): should dimiss the modal on clicking the done CTA', async () => {
This is Done 👍

2024-05-30 10:10 UTC, SahilK-027 commented on src/app/core/services/projects.service.ts
> -    }>
Done 👍

2024-05-30 10:19 UTC, SahilK-027 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    activeCategories$.subscribe((activeCategories) => {
Adding test cases

2024-05-31 08:38 UTC, SahilK-027 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    activeCategories$.subscribe((activeCategories) => {
Everything is working fine, as expected, how can we add Jasmine test cases to test this particular thing?

2024-05-31 11:26 UTC, devendrafyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    activeCategories$.subscribe((activeCategories) => {
arry sir, why don't create mock data for active categories and can use that as active categories

2024-05-31 11:29 UTC, devendrafyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    activeCategories$.subscribe((activeCategories) => {
> Everything is working fine, as expected, how can we add Jasmine test cases to test this particular thing?

you can check do it by `it('describe the test case')` or `describe` followed by `it` if it is a method that can have more than one case where it can return different values.

2024-05-31 11:44 UTC, SahilK-027 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    activeCategories$.subscribe((activeCategories) => {
This is done...
Thread: https://fylein.slack.com/archives/C017C400V37/p1717144800588849

2024-05-31 12:39 UTC, devendrafyle commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +        )
instead of nested `switchMap`, can do this in a better way, look for `combineLatest`

2024-06-01 05:48 UTC, suyashpatil78 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      projects: this.activeCategories$.pipe(
extract this to a separate variable like this
```ts
const projects$ = this.activeCategories$.pipe(
    switchMap((activeCategories) => this.projectsService.getAllActive(activeCategories))
);
```
and then use it here, easier to read

2024-06-01 07:18 UTC, SahilK-027 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            switchMap((allActiveCategories) =>
Done 👍

2024-06-01 07:19 UTC, SahilK-027 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +        )
Done 👍

2024-06-01 07:25 UTC, SahilK-027 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +      projects: this.activeCategories$.pipe(
Done 👍

2024-06-03 09:09 UTC, suyashpatil78 approved these changes

2024-06-03 09:19 UTC, suyashpatil78 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        return this.activeCategories$.pipe(
I think there is a better way to do this
```ts
getRecentProjects(): Observable<ProjectV2[]> {
  return forkJoin({
    recentValues: this.recentlyUsedValues$,
    eou: this.authService.getEou(),
    activeCategories: this.activeCategories$
  }).pipe(
    switchMap(({ recentValues, eou, activeCategories }) => {
      const formControl = this.getFormControl('category') as { value: OrgCategory };
      const categoryId = formControl.value && (formControl.value.id as unknown as string[]);
      return this.recentlyUsedItemsService.getRecentlyUsedProjects({
        recentValues,
        eou,
        categoryIds: categoryId,
        activeCategoryList: activeCategories,
      });
    })
  );
}
```

Can you check if we can do the same things at other places. Nested switchMap are very difficult to understand

2024-06-03 10:09 UTC, SahilK-027 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        return this.activeCategories$.pipe(
Yes will try to reduce nested `switchMap`s

2024-06-03 12:07 UTC, SahilK-027 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        return this.activeCategories$.pipe(
Done 👍

2024-06-03 13:25 UTC, SahilK-027 commented on src/app/core/services/projects.service.spec.ts
> +  describe('geByParamsUnformatted():', () => {
Done 👍

2024-06-04 11:30 UTC, Chethan-Fyle approved these changes

2024-06-04 13:44 UTC, merged