feat: Changing edit expense form & card design on dashboard
fylein/fyle-mobile-app pull request #3074
Opened 2024-06-13 08:02 UTC by neohacker18

### Description
Changing edit expense form by adding card nickname optionally & card design on dashboard by adding bank name and moving card logo to bottom right. Nickname is added optionally here as well.

## Clickup
Please add link here
https://app.clickup.com/t/86cvp13h0

## UI Preview
1. Without nickname
![image](https://github.com/fylein/fyle-mobile-app/assets/46134586/8a1da102-176a-4fa4-9040-b9a067f20e60)
2. With nickname
![image](https://github.com/fylein/fyle-mobile-app/assets/46134586/7d846c30-973d-4046-a6e1-9e6cab5b868b)
3. Edit expense form with nickname
![image](https://github.com/fylein/fyle-mobile-app/assets/46134586/3294b7cd-62d9-4787-a898-507206b6b6ad)

2024-06-18 10:37 UTC, Chethan-Fyle approved these changes

2024-06-19 05:05 UTC, bistaastha commented on src/app/shared/components/card-number/card-number.component.html
> +<div>
Please update it as per mobile app designs

2024-06-19 05:06 UTC, bistaastha requested changes
Update the designs

2024-06-20 05:11 UTC, bistaastha approved these changes

2024-06-20 05:52 UTC, neohacker18 commented
## Some div and alignment changes
![image](https://github.com/fylein/fyle-mobile-app/assets/46134586/bd7574e2-c495-4f23-afcb-0e721aed4e13)
![image](https://github.com/fylein/fyle-mobile-app/assets/46134586/ac9332d1-cc02-4817-8ab6-f3033c5b8f6f)

2024-06-20 05:56 UTC, merged