complete method typeerror fix
fylein/fyle-mobile-app pull request #3171
Opened 2024-08-14 13:39 UTC by Madhusudan092001

## Clickup
Please add link here

## Code Coverage
TypeError
s.complete is not a function. (In 's.complete()', 's.complete' is undefined)

The error `s.complete() is not a function` occurs when the `complete` method is either undefined or not a function on the target object. I confirmed through console logs that `event.target` is a valid `ion-infinite-scroll` element, and the `complete` method exists as a function. However, if the method doesn't exist for a specific user, it might be missing or incorrectly bound to the target element. As a fallback, I implemented a check to ensure that if `event.target` or `complete` isn't a function, the `complete` method won't be called, preventing the error.

## UI Preview
Please add screenshots for UI changes

2024-08-14 14:22 UTC, suyashpatil78 requested changes

2024-08-14 14:22 UTC, suyashpatil78 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      if (typeof event?.target?.complete === 'function') {
can we use JavaScript optional chaining here?

2024-08-16 05:21 UTC, Madhusudan092001 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      if (typeof event?.target?.complete === 'function') {
Yes sir we can also use optional chaining here as it will simplifies the code as compared to the typeof check
I guess we can do it like this :

if (!event?.target?.complete) { 
  console.error('complete() method is not available on the target element');
} else {
  event.target.complete();
}

Sir here using the optional chaining ?.  the if block (!event?.target?.complete) will execute when either of the following happens :
event is null or undefined
event.target is null or undefined
event.target.complete is null, undefined, or false

So we are not directly calling the complete method when it can became undefined or not available which leads to the typeerror

And when complete is a function then we can directly access it in the else using event.target.complete();

2024-08-16 05:54 UTC, suyashpatil78 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      if (typeof event?.target?.complete === 'function') {
We don't push console logs/errors to production

2024-08-16 05:55 UTC, suyashpatil78 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      if (typeof event?.target?.complete === 'function') {
Can we use optional chaining to check if `complete` method exist or not on `target` object?

2024-08-16 06:13 UTC, Madhusudan092001 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      if (typeof event?.target?.complete === 'function') {
Yes sir i guess then we can try like this without consoling:

Sir the optional chaining will work in a similar manner as above for checking in event?.target?.complete(); 

const completed = event?.target?.complete(); //Here we can assign the result of optional chaining into a variable

//And now if it gives a true value then only we are accessing it or calling, and if undefined then it will 
                               be falsy and not called
if (completed) { 
  completed();
}

2024-08-16 06:19 UTC, suyashpatil78 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      if (typeof event?.target?.complete === 'function') {
Can you think of another approach? We can use optional chaining for the complete method also.

2024-08-16 06:31 UTC, Madhusudan092001 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      if (typeof event?.target?.complete === 'function') {
Yes sir then we can directly check using the optional chaining without the different if else or variable declarations

Like  event?.target?.complete?.();
It will check complete method exist on target or not and if not it will evaluate to undefined without throwing an error

2024-08-16 06:33 UTC, suyashpatil78 commented on src/app/fyle/team-reports/team-reports.page.ts
> +      if (typeof event?.target?.complete === 'function') {
Nice! This will be cleaner and works well.

2024-08-16 11:33 UTC, suyashpatil78 approved these changes

2024-08-16 11:47 UTC, merged