feat: Dismiss Dialog for duplicate expenses
fylein/fyle-mobile-app pull request #3175
Opened 2024-08-19 18:17 UTC by devendrafyle

## Clickup
https://app.clickup.com/t/86cw6epah

2024-08-20 03:23 UTC, Dimple16 commented on src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.scss
> +    line-height: 20.48px;
Does `20px` work?

2024-08-20 03:24 UTC, Dimple16 commented on src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.scss
> +    color: #fff;
Use the color variable

2024-08-20 03:27 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +// eslint-disable-next-line
?

2024-08-20 03:29 UTC, Dimple16 commented on src/global.scss
> +  --width: 298px;
check this in different resolutions

2024-08-20 03:30 UTC, Dimple16 commented on src/theme/colors.scss
> +$brand-gradient: linear-gradient(162deg, #f36 3.01%, #fe5196 111.5%);
this is not required, we already have `$pink-gradient`

2024-08-20 03:31 UTC, Dimple16 commented on src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.scss
> +    font-weight: 400;
This should be there by default, check if it's not required

2024-08-20 05:32 UTC, devendrafyle commented on src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.ts
> +  // eslint-disable-next-line
eslint error

2024-08-20 05:33 UTC, devendrafyle commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +// eslint-disable-next-line
eslint throwing error here, else need to create new modal for it

2024-08-20 05:33 UTC, devendrafyle commented on src/global.scss
> +  --width: 298px;
i have checked this, seems to working fine

2024-08-20 05:35 UTC, devendrafyle commented on src/theme/colors.scss
> +$brand-gradient: linear-gradient(162deg, #f36 3.01%, #fe5196 111.5%);
ahh right, will fix this

2024-08-20 05:36 UTC, devendrafyle commented on src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.scss
> +    color: #fff;
ok

2024-08-20 05:36 UTC, devendrafyle commented on src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.scss
> +    line-height: 20.48px;
yep

2024-08-20 05:41 UTC, devendrafyle commented on src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.scss
> +    font-weight: 400;
no actually for different dialogue, for this dismiss dialogue we need to add this class styling since the `color` is different by default and we also want `margin-top`

2024-08-20 05:55 UTC, devendrafyle commented on src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.ts
> +  // eslint-disable-next-line
fixed this by adding the observable type

2024-08-20 05:55 UTC, devendrafyle commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +// eslint-disable-next-line
fixed this by creating new type in model file

2024-08-22 08:29 UTC, Dimple16 approved these changes
one question

2024-08-22 08:29 UTC, Dimple16 commented on src/app/core/models/platform/v1/expenses.model.ts
> +export type Expenses = Expense[];
don't we have this already?

2024-08-22 08:32 UTC, Dimple16 requested changes
I don't think the new model `expenses` is required

2024-08-22 09:02 UTC, devendrafyle commented on src/app/core/models/platform/v1/expenses.model.ts
> +export type Expenses = Expense[];
we do not have the exact model already, but we can skip this

2024-08-22 09:05 UTC, devendrafyle commented on src/app/core/models/platform/v1/expenses.model.ts
> +export type Expenses = Expense[];
Updated this

2024-08-22 09:09 UTC, Dimple16 approved these changes

2024-08-22 09:24 UTC, Dimple16 approved these changes

2024-08-25 15:21 UTC, Chethan-Fyle approved these changes

2024-08-26 10:52 UTC, suyashpatil78 approved these changes

2024-08-27 09:46 UTC, merged