test: Added unit test cases for dismiss dialog
fylein/fyle-mobile-app pull request #3176
Opened 2024-08-20 03:18 UTC by devendrafyle

## Clickup
https://app.clickup.com/t/86cw6epbu

2024-08-20 03:44 UTC, Dimple16 requested changes
added comments

2024-08-20 03:44 UTC, Dimple16 commented on src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.spec.ts
> +    it('should dismiss item', (done) => {
`should dismiss expense?`

2024-08-20 03:44 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
> +      if (popoverResponse.data?.status === 'success') {
shouldn't we test the else case too?

2024-08-20 08:37 UTC, devendrafyle commented on src/app/fyle/dashboard/tasks/dismiss-dialog/dismiss-dialog.component.spec.ts
> +    it('should dismiss item', (done) => {
yep updated

2024-08-20 08:47 UTC, devendrafyle commented on src/app/fyle/potential-duplicates/potential-duplicates.page.spec.ts
> +      if (popoverResponse.data?.status === 'success') {
added these cases too

2024-08-22 08:30 UTC, Dimple16 approved these changes

2024-08-26 07:06 UTC, merged