AccountService model changes
fylein/fyle-mobile-app pull request #320
Opened 2021-03-17 13:20 UTC by lakshmisuhas1996

2021-03-17 13:23 UTC, lakshmisuhas1996 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          return !!accounts.find((account) => account.acc.type === 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT');
Getting TS compilation error of cannot use length on typeExtendedAccount. Also  .find will return an object of ExtendedAccount Model and getting length > 0 will always return false.... so thus converting this to boolean here

2021-03-18 06:08 UTC, madhavmansuriya40 approved these changes

2021-03-18 09:05 UTC, madhavmansuriya40 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          return !!accounts.find((account) => account.acc.type === 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT');
the same will be in mileage and per diem, please check and update

2021-03-18 09:20 UTC, lakshmisuhas1996 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          return !!accounts.find((account) => account.acc.type === 'PERSONAL_CORPORATE_CREDIT_CARD_ACCOUNT');
We are using filter there... here also changing .find to .filter

2021-03-21 06:03 UTC, iamtarun1993 commented on src/app/core/models/extended-account.model.ts
> +export interface ExtendedAccount {
within `V1` directory

2021-03-21 06:04 UTC, iamtarun1993 commented on src/app/core/services/accounts.service.ts
> +  filterAccountsWithSufficientBalance(accounts: ExtendedAccount[], isAdvanceEnabled, accountId?) {
data type of `isAdvanceEnabled, accountId?`

2021-03-21 06:04 UTC, iamtarun1993 commented on src/app/core/services/accounts.service.ts
> +  getEMyAccounts(filters?): Observable<ExtendedAccount[]> {
datatype of `filters`

2021-03-21 06:05 UTC, iamtarun1993 commented on src/app/core/services/accounts.service.ts
> +  constructPaymentModes(accounts: ExtendedAccount[], isMultipleAdvanceEnabled, isNotOwner?) {
datatype of `isMultipleAdvanceEnabled, isNotOwner?` and datatype of output

2021-03-21 06:05 UTC, iamtarun1993 requested changes
datatype of some input and output missing

2021-03-22 07:23 UTC, lakshmisuhas1996 commented on src/app/core/services/accounts.service.ts
>      const data = {
as of now, we are not passing any filters to this method and got these params from api def; and making these optional because at times we may query by only one query param...

2021-03-22 12:53 UTC, iamtarun1993 commented on src/app/core/services/accounts.service.ts
> +  filterAccountsWithSufficientBalance(accounts: ExtendedAccount[], isAdvanceEnabled: boolean, accountId?: string) {
return datatype of this methos

2021-03-22 12:54 UTC, iamtarun1993 commented on src/app/core/services/accounts.service.ts
> +  constructPaymentModes(accounts: ExtendedAccount[], isMultipleAdvanceEnabled: boolean, isNotOwner?: boolean) {
same here

2021-03-22 13:00 UTC, lakshmisuhas1996 commented on src/app/core/services/accounts.service.ts
> +  filterAccountsWithSufficientBalance(accounts: ExtendedAccount[], isAdvanceEnabled: boolean, accountId?: string) {
return type will be implicitly inferred by ts since we are passing accounts as ExtendedAccount[] type?

2021-03-22 13:01 UTC, lakshmisuhas1996 commented on src/app/core/services/accounts.service.ts
> +  constructPaymentModes(accounts: ExtendedAccount[], isMultipleAdvanceEnabled: boolean, isNotOwner?: boolean) {
Added below by typecasting with **as**...adding in function def only for now

2021-03-22 14:55 UTC, iamtarun1993 commented on src/app/core/models/v1/extended-account.model.ts
> +    advance: {
indentation

2021-03-22 14:56 UTC, iamtarun1993 approved these changes

2021-03-23 10:56 UTC, Julias0 approved these changes

2022-08-19 10:18 UTC, closed without merging