fix: Replace the scanning receipt loader
fylein/fyle-mobile-app pull request #3203
Opened 2024-09-11 08:51 UTC by Z3RO-O

## Clickup
https://app.clickup.com/t/86cw9uytw

## Code Coverage
Please add code coverage here

## UI Preview
![image](https://github.com/user-attachments/assets/4387f202-6442-47ec-a4a8-0c4f8a208ae1)

2024-09-11 09:33 UTC, Chethan-Fyle approved these changes

2024-09-11 11:28 UTC, Dimple16 commented
@Z3RO-O, can you check why the lint and unit tests workflow is failing?

2024-09-11 11:28 UTC, Dimple16 requested changes
will review after the workflows are resolved

2024-09-12 06:49 UTC, Z3RO-O commented
> will review after the workflows are resolved

fixed

2024-09-16 12:03 UTC, suyashpatil78 approved these changes

2024-09-17 05:57 UTC, Dimple16 approved these changes

2024-09-17 09:24 UTC, merged