Fyle filter pipe try1 - Trying to implement filter pipe
fylein/fyle-mobile-app pull request #343
Opened 2021-03-26 10:04 UTC by shishirams222

2021-03-26 10:18 UTC, abhishek1234321 requested changes

2021-03-26 10:18 UTC, abhishek1234321 commented on src/app/shared/pipes/filter.pipe.ts
> +  transform(items: any[], searchText: string): any[] {
would it be `any[]` always or can we be more specific? like `string[]` etc?

2021-03-26 10:18 UTC, abhishek1234321 commented on src/app/shared/pipes/filter.pipe.ts
> +		if (!items) {
indentation 2 spaces please

2021-03-26 10:18 UTC, abhishek1234321 commented on src/app/shared/pipes/filter.pipe.ts
> +		if (!items) {
what if `items` is an `[]`?

2021-03-26 10:18 UTC, abhishek1234321 commented on src/app/shared/pipes/filter.pipe.ts
> +		if (!searchText) {
do we have any convention wherein some parameters can be optional in a filter?

2021-03-26 10:18 UTC, abhishek1234321 commented on src/app/shared/pipes/filter.pipe.ts
> +		searchText = searchText.toLowerCase();
searchTextLowerCase

2021-03-26 10:18 UTC, abhishek1234321 commented on src/app/shared/pipes/filter.pipe.ts
> +      return item.toLowerCase().includes(searchText);
indentation is off

2021-03-29 06:50 UTC, shishirams222 commented on src/app/shared/pipes/filter.pipe.ts
> +  transform(items: any[], searchText: string): any[] {
It should be `any[]`, list might not be just list of strings. So kept it as `any[]`. There are more checks inside

2021-03-29 06:50 UTC, shishirams222 commented on src/app/shared/pipes/filter.pipe.ts
> +		if (!items) {
Updated

2021-03-29 06:50 UTC, shishirams222 commented on src/app/shared/pipes/filter.pipe.ts
> +		if (!items) {
updated

2021-03-29 07:33 UTC, Julias0 commented on src/app/shared/pipes/filter.pipe.ts
> +
no empty line please

2022-08-19 10:18 UTC, closed without merging