Loader fix in loader-master branch
fylein/fyle-mobile-app pull request #348
Opened 2021-03-29 12:15 UTC by iamtarun1993

2021-03-29 12:20 UTC, iamtarun1993 commented on src/app/core/services/loader.service.ts
>    async showLoader(message = 'Please wait...', duration = 1000 ) {
for now `duration = 1000` is present in the method declaration, will remove this at last PR. Removing this now actually giving too much issue in ts compilation.

Though we defined this variable but never used it. check line no 20.

2021-03-31 16:37 UTC, Julias0 commented on src/app/app.component.ts
> +        // this.menuController.swipeGesture(false);
ei why is this commented

2021-04-05 15:22 UTC, Julias0 commented on src/app/app.component.ts
> +        // this.menuController.swipeGesture(false);
dei why is this in PR

2021-04-05 18:29 UTC, iamtarun1993 commented on src/app/app.component.ts
> +        // this.menuController.swipeGesture(false);
will remove this when merging to master.

2021-04-07 08:58 UTC, abhishek1234321 requested changes

2021-04-08 06:07 UTC, Julias0 approved these changes

2021-04-09 02:53 UTC, abhishek1234321 approved these changes

2022-08-19 10:18 UTC, closed without merging