camera and photos permission in instaFyle
fylein/fyle-mobile-app pull request #352
Opened 2021-03-30 14:22 UTC by iamtarun1993

2021-03-30 16:05 UTC, Julias0 approved these changes

2021-03-30 16:11 UTC, Julias0 approved these changes

2021-03-31 03:39 UTC, abhishek1234321 commented
screenshots please?

2021-03-31 04:13 UTC, abhishek1234321 requested changes

2021-03-31 04:13 UTC, abhishek1234321 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +  async requestCameraAndPhotosPermission(actions?: string) {
why is `actions` optional? also shouldn't it be `action`? since it is a string?

2021-03-31 04:13 UTC, abhishek1234321 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +        header = 'Allow Fyle to access your camera';
`Allow Fyle to access your Camera`

2021-03-31 04:13 UTC, abhishek1234321 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +        header = 'Allow Fyle to access your Photos';
can you put current screenshots, easier to identify the content in the popup than here

2021-03-31 04:13 UTC, abhishek1234321 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +      header = 'Allow Fyle to access camera, Files and media';
`Allow Fyle to access Camera, Files and Media`

2021-03-31 04:13 UTC, abhishek1234321 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +      header = 'Allow Fyle to access camera, Files and media';
the casing is off here and in description for Camera, Files etc, can we please stick to one convention?

2021-03-31 04:13 UTC, abhishek1234321 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +      message = 'To capture photos, allow Fyle access to your camera and your device\'s photos, media, and files.\n Tap Settings > Permissions, and turn Camera and "Files and Media" on.'
`Tap Settings > Permissions` I couldn't find any menu called `Permissions` in my phone it shows `App Permissions`

Also they need to click on the Fyle app and then grant permissions no?

2021-03-31 04:13 UTC, abhishek1234321 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +        text: 'Not Now'
why do this? why not just show a cancel button? `Not now` indicates this being optional and they can do it later

2021-03-31 04:13 UTC, abhishek1234321 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +    if (permissionPopup === 'primary') {
what is this used for?

2021-03-31 05:13 UTC, iamtarun1993 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +      message = 'To capture photos, allow Fyle access to your camera and your device\'s photos, media, and files.\n Tap Settings > Permissions, and turn Camera and "Files and Media" on.'
No no. This app will open Fyle app's settings directly. No need to click Fyle app.

On my phone, this is called "Permission", not "App permissions"

2021-03-31 05:16 UTC, iamtarun1993 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +        text: 'Not Now'
the content is given by Sai, and most apps showing "Not Now" not "Cancel".

2021-03-31 05:24 UTC, iamtarun1993 commented
For iOS camera permission
<img width="395" alt="Screenshot 2021-03-31 at 10 51 31 AM" src="https://user-images.githubusercontent.com/23378996/113094396-38cc2600-920f-11eb-9ff0-5e805dfe0d4d.png">

for iOS photos permission
<img width="382" alt="Screenshot 2021-03-31 at 10 53 49 AM" src="https://user-images.githubusercontent.com/23378996/113094536-79c43a80-920f-11eb-9cc8-4cd5de62d768.png">

for Android photos and media permission
<img width="400" alt="Screenshot 2021-03-31 at 10 54 08 AM" src="https://user-images.githubusercontent.com/23378996/113094556-847ecf80-920f-11eb-910c-3b9a2e74df32.png">

2021-03-31 05:25 UTC, iamtarun1993 commented on src/app/fyle/camera-overlay/camera-overlay.page.ts
> +        header = 'Allow Fyle to access your Photos';
https://github.com/fylein/fyle-mobile-app2/pull/352#issuecomment-810772514

2022-08-19 10:18 UTC, closed without merging