Changes for to support all vehicle types
fylein/fyle-mobile-app pull request #353
Opened 2021-03-31 05:31 UTC by lakshmisuhas1996

2021-04-05 11:12 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +          const allVehicleTypes = ['two_wheeler', 'four_wheeler', 'four_wheeler1', 'four_wheeler3', 'four_wheeler4', 'bicycle', 'electric_car'];
you need to push all those new vehicle types inside array for new expense case.
check `constructMileageOptions` method()

2021-04-05 11:15 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.scss
> +    color: #f36;
declare color as variable. We skipped this when developing the app for first time.
we can't skip this now.

2021-04-05 18:41 UTC, iamtarun1993 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  vehiclesList = [
get this from transactionServcie.

2021-04-05 18:44 UTC, iamtarun1993 commented on src/app/shared/components/fy-select/fy-select.component.html
> +  <span class="fy-select--input-icon" *ngIf="value?.icon">
make sure this is not braking any style for other case.

2021-04-05 18:45 UTC, iamtarun1993 commented on src/app/shared/components/fy-select/fy-select.component.scss
> +    color: #f36;
variable

2021-04-08 07:12 UTC, lakshmisuhas1996 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +          const allVehicleTypes = ['two_wheeler', 'four_wheeler', 'four_wheeler1', 'four_wheeler3', 'four_wheeler4', 'bicycle', 'electric_car'];
added

2021-04-08 07:43 UTC, lakshmisuhas1996 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +            mileage_calculated_amount: res.mileageConfig[formValue.mileage_vehicle_type.type] * calculatedDistance,
here **etxn.tx.mileage_rate** value wille be default vehicle rate (for new expense case) and mileage_rate (from api response). In Edit / new mileage expense when we change the vehicle type -   **etxn.tx.mileage_rate** value is not updated according to the vehicle we set and hence sending **mileage_calculated_amount** value wrong in some cases.

2021-04-08 14:03 UTC, iamtarun1993 commented on src/app/core/services/transaction.service.ts
> +  getAllSupportedVehicles() {
declare return type

2021-04-08 14:06 UTC, iamtarun1993 approved these changes

2021-04-13 13:09 UTC, Julias0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +        type vehicleOption = {type: string; value: { type: string; icon: string }; label: string; icon: string};
move type definitions to parent level

2021-04-13 13:10 UTC, Julias0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  getVehicleOptions() {
this can be moved to a service i think

2021-04-14 04:57 UTC, lakshmisuhas1996 commented on src/app/core/services/transaction.service.ts
> +  getAllSupportedVehicles() {
return type will be inferred by TS automatically, explicitly mentioning not required here...

2021-04-15 16:13 UTC, Julias0 commented on src/app/core/services/transaction.service.ts
> +        type vehicleOption = {type: string; value: { type: string; icon: string }; label: string; icon: string};
move this to parent object level

2021-04-15 16:13 UTC, Julias0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  vehicleOptions$: Observable<{ label: string, value: { type: string; icon: string }, selected?: boolean }[]>;
type vehicleOption = { label: string, value: { type: string; icon: string }, selected?: boolean }

2021-04-16 05:20 UTC, lakshmisuhas1996 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  vehicleOptions$: Observable<{ label: string, value: { type: string; icon: string }, selected?: boolean }[]>;
couldn't able to declare type aliases inside class... we have to do like [this](https://github.com/microsoft/TypeScript/issues/7061) to define types inside a class.. also for every observable we are doing like this.. else we have to put this inside a model?

2021-04-19 11:29 UTC, Julias0 approved these changes

2021-04-21 05:38 UTC, Julias0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +            mileage_calculated_amount: res.mileageConfig[formValue.mileage_vehicle_type.type] * calculatedDistance,
afaik this was there because if a milage is there with older milage rate - this would update that mileage if opened.
Ex - I have a mileage rate of 4 INR/km on 3rd July
This mileage rate gets updated by admin on 5th July
Now if I try to edit my expense, the new mileage rate will be used

2021-04-21 05:39 UTC, Julias0 approved these changes

2021-04-21 05:40 UTC, Julias0 requested changes
The mileage rate wala thing needs to be looked at

2022-08-19 10:18 UTC, closed without merging