FYLE-2va69r: Expense fields service and model changes
fylein/fyle-mobile-app pull request #379
Opened 2021-04-21 16:17 UTC by Dimple16

2021-04-22 13:15 UTC, Dimple16 commented on src/app/core/models/V1/expense-field.model.ts
> +  code?: string;
no, not all fields will have the code value

2021-04-22 13:16 UTC, Dimple16 commented on src/app/core/models/V1/expense-field.model.ts
> +  id?: number;
no, in v1 we don't have the id of expense fields yet, this will be implemented only after migration

2021-04-22 13:16 UTC, Dimple16 commented on src/app/core/models/V1/field-created-by.model.ts
> +  allowed_CIDRs?: string[];
not all fields will have these values

2021-04-23 05:16 UTC, madhavmansuriya40 commented on src/app/core/models/V1/expense-fields-map.model.ts
> +  boolean_column1: ExpenseField;
all types are `ExpenseField` <- is this valid?

2021-04-23 05:21 UTC, Dimple16 commented on src/app/core/models/V1/expense-fields-map.model.ts
> +  boolean_column1: ExpenseField;
This will be a map of `key` as `column_name` and `value` as the `Expense field object`

2021-04-23 05:32 UTC, madhavmansuriya40 approved these changes

2021-04-23 06:20 UTC, iamtarun1993 commented on src/app/core/models/V1/expense-field.model.ts
> +  options: any[];
why options dataType is any[] ??
can you put a sample object here?

2021-04-23 06:22 UTC, iamtarun1993 commented on src/app/core/models/V1/expense-field.model.ts
> +  updated_by: Date;
updated_by: Date; 
are you sure? 
is not not org_user_id ?

2021-04-23 06:24 UTC, iamtarun1993 commented on src/app/core/models/V1/expense-field.model.ts
> +import { FieldCreatedBy } from "./field-created-by.model";
`src/app/core/models/v1/expense-field.model.ts`
small `v` not `V`.. There is one PR to fix these but don't think these got merged yet.

2021-04-23 06:25 UTC, iamtarun1993 commented on src/app/core/services/expense-fields.service.ts
> +  getAllMap() {
return datatype

2021-04-24 15:27 UTC, Dimple16 commented on src/app/core/services/expense-fields.service.ts
> +  getAllMap() {
this is a map of `{ column_name: ExpenseField, .... }` ex: 
```
{
 text_column1: ExpenseField,
 purpose: ExpenseField,
 txn_dt: ExpenseField,
}
```
@iamtarun1993 can we use the above as a model? all the values will be of type `ExpenseField`

2021-04-27 04:54 UTC, iamtarun1993 commented on src/app/core/services/expense-fields.service.ts
> +  getAllMap() {
yes define this as a return object type
getAllMap(): <{text_column1: ExpenseFiled, purpose: ExpenseFiled, ....}>

2021-04-27 04:55 UTC, iamtarun1993 commented on src/app/core/services/offline.service.ts
> +  getExpenseFieldsMap() {
please mention return type also here

2021-05-03 09:44 UTC, abhishek1234321 requested changes

2021-05-03 09:44 UTC, abhishek1234321 commented on src/app/core/services/expense-fields.service.ts
> +  getAllMap(): Observable<ExpenseFieldsMap> {
could you explain in code comments and example on what happens in this method?

2021-05-04 06:36 UTC, Dimple16 commented on src/app/core/services/expense-fields.service.ts
> +  getAllMap(): Observable<ExpenseFieldsMap> {
added comments

2021-05-05 04:55 UTC, abhishek1234321 approved these changes

2021-05-07 07:22 UTC, Julias0 commented on src/app/core/models/v1/expense-fields-map.model.ts
> +export interface ExpenseFieldsMap {
Ok dont declare everything as optional but use this in combination with Partial generic class

2021-05-07 09:56 UTC, Dimple16 commented on src/app/core/models/v1/expense-fields-map.model.ts
> +export interface ExpenseFieldsMap {
this is done

2021-05-10 05:20 UTC, Julias0 approved these changes

2022-08-19 10:18 UTC, closed without merging