FYLE-2va69r: Tfc revamp - Custom inputs changes
fylein/fyle-mobile-app pull request #382
Opened 2021-04-24 15:15 UTC by Dimple16

2021-04-26 11:07 UTC, madhavmansuriya40 approved these changes

2021-04-26 11:07 UTC, madhavmansuriya40 commented on src/app/core/services/custom-fields.service.ts
> +      name: customInput[prefix + 'field_name'],
at some places, custom fields are with prefix and at someplace they are direct
please test it in all cases

2021-04-27 05:21 UTC, iamtarun1993 commented on src/app/core/services/custom-inputs.service.ts
>    getAll(active: boolean) {
return type

2021-04-28 08:06 UTC, Dimple16 commented on src/app/core/services/custom-fields.service.ts
> +      name: customInput[prefix + 'field_name'],
yes, this is done

2021-05-03 14:16 UTC, abhishek1234321 requested changes

2021-05-04 06:43 UTC, Dimple16 commented on src/app/core/services/custom-inputs.service.ts
> +  getAll(active: boolean): Observable<ExpenseField[]> {
passing active parameter

2021-05-04 06:50 UTC, Dimple16 commented on src/app/core/services/custom-fields.service.ts
> +      name: customInput[prefix + 'field_name'],
`setProperty` is called only from `standardizeCustomFields`, `standardizeCustomFields` this method is used in expense forms and view trip/team trip pages

2021-05-05 04:53 UTC, abhishek1234321 approved these changes

2021-05-06 05:45 UTC, abhishek1234321 approved these changes

2021-05-07 07:20 UTC, Julias0 commented on src/app/core/services/custom-inputs.service.ts
> +  getAll(active: boolean): Observable<ExpenseField[]> {
`getAll({ active: boolean } = { active: false })`

2022-08-19 10:18 UTC, closed without merging