FYLE-2vgfnd: Tfc revamp - Expense page and service method changes
fylein/fyle-mobile-app pull request #383
Opened 2021-04-26 17:38 UTC by Dimple16

2021-04-28 11:39 UTC, Dimple16 commented on src/app/core/services/expense-fields.service.ts
> +  findCommonRoles(roles) {
existing method moved from `transaction_field_configurations` service

2021-04-28 11:41 UTC, Dimple16 commented on src/app/core/services/expense-fields.service.ts
> +
All below methods are moved from `transaction_field_configurations` service. No changes done.

2021-04-28 11:42 UTC, Dimple16 commented on src/app/core/services/expense-fields.service.ts
> +      switchMap(fields => {
existing method moved from transaction_field_configurations service - not changing existing ones

2021-04-28 11:48 UTC, madhavmansuriya40 approved these changes

2021-05-03 14:21 UTC, abhishek1234321 requested changes

2021-05-03 14:21 UTC, abhishek1234321 commented on src/app/core/models/v1/default-txn-field-values.model.ts
> +  bus_travel_class?: string;
any reason on why all of these should be optional?

2021-05-03 14:21 UTC, abhishek1234321 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>          if (tfcMap) {
let us change the variable from tfcMap to something else?

2021-05-04 06:54 UTC, Dimple16 commented on src/app/core/models/v1/default-txn-field-values.model.ts
> +  bus_travel_class?: string;
while computing the default txn field values, we return only the fields which have a default value, these keys will not be present always

2021-05-05 05:04 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>          if (tfcMap) {
updated to `expenseFieldsMap`

2021-05-06 05:54 UTC, abhishek1234321 requested changes

2021-05-07 09:10 UTC, Dimple16 commented on src/app/core/services/expense-fields.service.ts
> +            is_custom: false
for expense fields we call the mapping method, custom fields do not have the mapping

2021-05-10 11:07 UTC, abhishek1234321 approved these changes

2021-05-12 10:28 UTC, Julias0 approved these changes

2022-08-19 10:18 UTC, closed without merging