Changed duplicate detection test call URL
fylein/fyle-mobile-app pull request #411
Opened 2021-05-28 07:15 UTC by kartikeyrajvaidya

2021-06-18 09:09 UTC, Julias0 commented on src/app/core/services/duplicate-detection.service.ts
>    post(url, data, config?) {
Add data type in following format - 
post(url: string, data: { param1: string, param2: number }, config: { wth_is_this: is_this_required }): Observable<ComplianceResponse> {

2021-06-18 09:09 UTC, Julias0 commented on src/app/core/services/duplicate-detection.service.ts
> +        return this.post('/l1_test', transactionCopy);
same as above?

2021-06-18 09:10 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              if (!isEqual(currentDate, originalDate)) {
`return !isEqual(currentDate, originalDate) ` no need for if condition

2021-06-18 09:10 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              if (!isEqual(currentExpenseObject.tx[fieldName], originalExpenseObject.tx[fieldName])) {
same as above

2021-06-18 09:11 UTC, Julias0 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      switchMap((test) => {
test -> isPossibleDuplicate

2021-06-18 09:13 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>    getPossibleDuplicates() {
I see duplication in expense, mileage and per diem - can you look into reducing it?

2021-06-18 09:13 UTC, Julias0 requested changes
Lets take care of duplication too

2021-06-27 15:43 UTC, abhishek1234321 requested changes

2022-08-19 10:18 UTC, closed without merging