FYLE-49ewrt Vehicle type to be converted to a field
fylein/fyle-mobile-app pull request #484
Opened 2021-07-16 02:33 UTC by iravisankar

![localhost_8100_enterprise_add_edit_mileage;navigate_back=true(iPhone X)](https://user-images.githubusercontent.com/86199056/125882674-9a6e025f-d666-464e-81dd-3c99d422a8e9.png)

![localhost_8100_enterprise_add_edit_mileage;navigate_back=true(iPhone X) (1)](https://user-images.githubusercontent.com/86199056/125882685-dd0f87aa-9456-4d4a-bc86-0a50fffd5696.png)

2021-07-16 04:47 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
> +                <app-fy-select [enableSearch]="false" [label]="'Vehicle Type'" [mandatory]="true" [nullOption]="false"
`app-fy-select` uses modal controller, for vehicle type we will need to use `mat-bottom-sheet-container' - `matBottomSheet`, can refer to - `AddTxnToReportDialogComponent`

2021-07-16 04:50 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.html
> +                <app-fy-select [enableSearch]="false" [label]="'Vehicle Type'" [mandatory]="true" [nullOption]="false"
this is because we have fixed length of vehicle options, it won't vary more than 4-6, there will be white spacing if we use modalController

2021-12-22 06:23 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +  vehicleTypeOptions$: Observable<any>;
this would be a list of strings?  we can add a model if required

2021-12-22 06:24 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +            if (i > -1) {
can use the condition directly here or rename `i`?

2021-12-22 08:08 UTC, Dimple16 commented on src/app/fyle/my-view-mileage/my-view-mileage.page.html
> +<ion-header mode="md">
does this branch have the latest master? or is this an intentional change?

2021-12-22 08:18 UTC, Dimple16 commented on src/app/shared/components/fy-select/fy-select-modal/fy-select-modal.component.scss
> +  &--bottom-up {
`bottom-sheet`?

2021-12-22 08:19 UTC, Dimple16 requested changes
few comments

2022-01-19 05:34 UTC, iravisankar commented on src/app/fyle/my-view-mileage/my-view-mileage.page.html
> +<ion-header mode="md">
its from master

2022-01-19 07:43 UTC, Dimple16 requested changes

2022-01-19 07:43 UTC, Dimple16 commented on src/app/fyle/my-view-mileage/my-view-mileage.page.html
> +<ion-header mode="md">
I feel something is off, these files shouldn't be here no?

2022-01-20 06:01 UTC, Dimple16 approved these changes

2022-01-24 06:53 UTC, shishirams222 approved these changes

2022-02-01 12:12 UTC, pradeep8093 commented on src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.ts
>      });
remove ,

2022-02-01 12:12 UTC, pradeep8093 commented on src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.ts
> +        policyViolations: this.policyViolations,
remove ,

2022-02-01 12:13 UTC, pradeep8093 commented on src/app/fyle/capture-receipt/capture-receipt.page.ts
> +              canExtractData: this.isInstafyleEnabled,
remove ,

2022-02-01 12:14 UTC, pradeep8093 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +        }
extract this if block logic out to a different function

2022-02-01 12:20 UTC, pradeep8093 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +        }
extract this logic out too

2022-03-22 11:40 UTC, iravisankar commented on src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.ts
>      });
it was added by husky

2022-03-30 05:18 UTC, pradeep8093 approved these changes

2022-11-05 16:07 UTC, closed without merging