CU-1tkvpjy: Filters in advances
fylein/fyle-mobile-app pull request #738
Opened 2021-11-09 17:29 UTC by MasterYushi

https://user-images.githubusercontent.com/24858182/140974367-008ff61f-0782-4f4b-bb31-9b073b9e8d39.mp4

2021-11-10 06:09 UTC, Dimple16 commented on src/app/fyle/my-advances/my-advances.page.scss
> +  &--filter-pills {
this is used in multiple pages, we can add this to global.scss

2021-11-10 06:32 UTC, MasterYushi commented on src/app/fyle/my-advances/my-advances.page.scss
> +  &--filter-pills {
resolved

2021-11-10 09:27 UTC, Dimple16 requested changes
few comments

2021-11-10 09:27 UTC, Dimple16 commented on src/app/fyle/my-advances/my-advances.page.ts
> +                //filtering
the filtering and sorting logic can be added in separate methods and make the call here

2021-11-10 09:27 UTC, Dimple16 commented on src/app/fyle/my-advances/my-advances.page.ts
> +  private generateFilterPills() {
`private` intentional?

2021-11-10 10:54 UTC, MasterYushi commented on src/app/fyle/my-advances/my-advances.page.scss
> +  &--filter-pills-container {
was resolved in the same commit, please check

2021-11-10 11:16 UTC, pradeep8093 commented on src/app/fyle/my-advances/my-advances.page.ts
> +    return generatedFilters;
this whole block of if-else can be extracted out to pure function and instead of if else you can use a dictionary

2021-11-10 12:22 UTC, MasterYushi commented on src/app/fyle/my-advances/my-advances.page.ts
> +    return generatedFilters;
will look into it

2021-11-10 17:18 UTC, MasterYushi commented on src/app/fyle/my-advances/my-advances.page.ts
> +                //filtering
resolved

2021-11-10 17:18 UTC, MasterYushi commented on src/app/fyle/my-advances/my-advances.page.ts
> +  private generateFilterPills() {
resolved

2021-11-10 17:18 UTC, MasterYushi commented on src/app/fyle/my-advances/my-advances.page.ts
> +    return generatedFilters;
resolved

2021-11-11 15:13 UTC, MasterYushi commented on src/app/core/services/filters-helper.service.ts
> +      const capitalizedStates = filters.state.map(
Converts SENT_BACK to Sent Back

2021-11-16 10:27 UTC, pradeep8093 commented on src/app/fyle/my-advances/my-advances.page.ts
> +  async onFilterClick(filterType: string) {
var stateDIct = {
  state: 'State',
  sort: 'Sort By'
}

await this.openFilters(stateDIct[filterType]);

2021-11-16 10:27 UTC, pradeep8093 commented on src/app/core/services/filters-helper.service.ts
> +    if (filters && filters.state) {
use dict

2021-11-16 10:27 UTC, pradeep8093 commented on src/app/core/services/filters-helper.service.ts
> +      if (sortBy.value.includes('NewToOld')) {
extract it out to a pure function

2021-11-17 09:50 UTC, pradeep8093 approved these changes

2021-11-17 10:28 UTC, Dimple16 commented on package-lock.json
> +      "name": "fyle-mobile-app2",
what is this change? can you verify if this was by mistake?

2021-11-17 10:30 UTC, Dimple16 commented on src/app/core/services/utility.service.ts
> +  sortMixedAdvances(filters: Filters, advancesArray: any[]): any[] {
`MixedAdvances?` can we rename?

2021-11-17 10:30 UTC, Dimple16 commented on src/app/core/services/utility.service.ts
> +    let newArr = advancesArray;
`newArr` - rename

2021-11-17 10:32 UTC, Dimple16 approved these changes

2021-11-17 10:37 UTC, MasterYushi commented on package-lock.json
> +      "name": "fyle-mobile-app2",
it happened when I merged master into this branch

2021-11-17 10:38 UTC, MasterYushi commented on src/app/core/services/utility.service.ts
> +  sortMixedAdvances(filters: Filters, advancesArray: any[]): any[] {
`sortCombinedAdvances()` ?

2021-11-18 16:21 UTC, Julias0 commented on src/app/core/services/filters-helper.service.ts
> +            .replace(/\b\w/g, (l) => l.toUpperCase()) //capitalizing first letter of each word
you can use the capitalize filter to do this

2021-11-18 16:22 UTC, Julias0 commented on src/app/core/services/filters-helper.service.ts
> +    for (const key in filters) {
avoid using for in loops. Use Object.keys with for of loop or forEach

2021-11-18 16:24 UTC, Julias0 commented on src/app/fyle/my-advances/my-advances.page.ts
> +            options: [
what about other states?

2021-11-18 16:25 UTC, Julias0 commented on src/app/fyle/my-advances/my-advances.page.ts
> +                value: 'crDateNewToOld',
lets use enums instead of strings to prevent chance of spelling mistakes

2021-11-18 16:28 UTC, Julias0 commented on src/app/fyle/my-advances/my-advances.page.ts
> +                let newArr = [...advArray];
use cloneDeep

2021-11-18 16:29 UTC, Julias0 commented on src/app/core/services/utility.service.ts
> +  sortAllAdvances(filters: Filters, advancesArray: any[]): any[] {
explicity pass sort property and sort direction

2021-11-18 16:30 UTC, Julias0 commented on src/app/core/services/utility.service.ts
> +          const adv1Date = adv1.areq_created_at
use moment for comparing date time objects instead of doing it like this

2021-11-18 16:31 UTC, Julias0 commented on src/app/core/services/utility.service.ts
> +      if (filters.sortParam.includes('crDate')) {
make filters.sortParam a enum and compare it directly against the enums instead of checking for substring.

2021-11-18 16:31 UTC, Julias0 commented on src/app/core/services/utility.service.ts
> +      } else if (filters.sortParam.includes('appDate')) {
same as above for both this and the bottom one

2021-11-18 16:32 UTC, Julias0 commented on src/app/core/services/utility.service.ts
> +      } else if (filters.sortParam.includes('appDate')) {
There is duplication in the structure of the three parts of the if else ladder. See how you can remove that

2021-11-18 16:32 UTC, Julias0 commented on src/app/fyle/my-advances/my-advances.page.ts
> +        filterOptions: [
extract this out to a method into a service

2021-11-19 17:18 UTC, MasterYushi commented on src/app/core/services/filters-helper.service.ts
> +      }
could extract this into a function too

2021-11-19 17:24 UTC, MasterYushi commented on src/app/core/services/filters-helper.service.ts
> +      }
extracted

2021-11-24 04:18 UTC, Julias0 commented on src/app/core/services/filters-helper.service.ts
> +  private getSortString(sortParam: SortingParam, sortDir: SortingDirection) {
this.getSortString(filters[key], filters.sortDir)
This generates a enum by doing string manipulation which has more chances to make mistakes. Do this with a if else construct

2021-11-24 04:19 UTC, Julias0 commented on src/app/core/services/filters-helper.service.ts
> +    if (sortValue.includes('NewToOld') || sortValue.includes('ZToA')) {
You shouldnt check enums wrt substrings. Explicitly check for mateches or decouple the direction and the property

2021-11-24 04:21 UTC, Julias0 commented on src/app/core/services/utility.service.ts
> +      sortedAdvancesArray = sortedAdvancesArray.sort((adv1, adv2) => {
whenever you are sorting in js sort after making a copy otherwise the original object will get modified

2021-11-24 04:23 UTC, Julias0 commented on src/app/core/services/utility.service.ts
> +        const adv1Date = adv1.areq_created_at ? moment(adv1.areq_created_at) : moment(adv1.adv_created_at);
```typescript
const sortingValue1 = getSortingValue(adv1);
const sortingValue2 = getSortingValue(adv2);

return compareSortingValues(sortingValue1, sortingValue2, sortDir);
```

In the current format this function is not readable. Lets break it down into smaller chunks

2021-11-24 04:24 UTC, Julias0 commented on src/app/core/services/utility.service.ts
> +        const adv1Date = adv1.areq_approved_at ? moment(adv1.areq_approved_at) : moment(19700101);
`19700101` is a magic number - we should enclose them at least in variables or constants which are injected.

2021-11-24 04:24 UTC, Julias0 commented on src/app/core/services/utility.service.ts
> +    if (sortParam === SortingParam.creationDate) {
each part of the condition extract out into a separate function

2021-11-30 11:31 UTC, Julias0 approved these changes

2022-04-05 07:18 UTC, closed without merging