Update active card, org card and add default org tag
fylein/fyle-mobile-app pull request #748
Opened 2021-11-15 13:10 UTC by yksolanki9

https://www.loom.com/share/7a5924581fdf4fcda2e4779cfc05ecc0

2021-11-15 13:12 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.html
>  </ion-header>
Ignore header

2021-11-15 13:12 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.html
> +      </ion-grid>
Ignore. Will be updated as per new card design

2021-11-15 13:13 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.scss
>  $header-background: #f5f5f5;
Ignore. Shimmers will be updated

2021-11-15 13:13 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.scss
>      --background: #f5f5f5;
Ignore below this

2021-11-15 13:16 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.ts
> +    ]).pipe(switchMap(([orgs, activeOrg]) => of(orgs.filter((org) => org.id !== activeOrg.id))));
Can ignore the entire file for now. 
We used to include `active org` while searching. Have updated the code to ignore it but it is failing in some cases.

2021-11-15 13:17 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.html
>  </ion-header>
Ignore header - yet to be updated

2021-11-15 13:19 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.ts
> +import { combineLatest, forkJoin, from, fromEvent, noop, Observable, of } from 'rxjs';
Can ignore the entire file for now.
We used to include `active org` while searching. Have updated the code to ignore it but it is failing in some cases.

2021-11-15 16:09 UTC, abhishek1234321 requested changes

2021-11-15 16:09 UTC, abhishek1234321 commented on src/app/auth/switch-org/active-org-card/active-org-card.component.scss
> +  background: $pink-gradient-2;
consider using `background-color`?

2021-11-15 16:09 UTC, abhishek1234321 commented on src/app/auth/switch-org/active-org-card/active-org-card.component.scss
> +  line-height: 1.3;
is this needed?

2021-11-15 16:09 UTC, abhishek1234321 commented on src/app/auth/switch-org/active-org-card/active-org-card.component.scss
> +  &__grid {
why do we do this? can we not use a common class to override this? I see this is repeated in a lot of places

2021-11-15 16:09 UTC, abhishek1234321 commented on src/app/auth/switch-org/active-org-card/active-org-card.component.scss
> +      height: calc(100% - 10px);
why do we want to fix width and height?

2021-11-18 09:59 UTC, yksolanki9 commented on src/app/auth/switch-org/active-org-card/active-org-card.component.scss
> +  background: $pink-gradient-2;
`linear-gradient()` does not work with `background-color`

2021-11-18 10:00 UTC, yksolanki9 commented on src/app/auth/switch-org/active-org-card/active-org-card.component.scss
> +  line-height: 1.3;
Else `line-height` defaults to 20px

2021-11-18 10:19 UTC, yksolanki9 commented on src/app/auth/switch-org/active-org-card/active-org-card.component.scss
> +  &__grid {
Created a global class `ion-grid-no-padding` for this

2021-11-18 10:22 UTC, yksolanki9 commented on src/app/core/services/org.service.ts
> +    return this.apiService.get('/orgs', {
We never showed the primary org in mobile before this

2021-11-18 10:28 UTC, yksolanki9 commented on src/app/auth/switch-org/active-org-card/active-org-card.component.scss
> +      height: calc(100% - 10px);
![Screenshot from 2021-11-18 15-54-05](https://user-images.githubusercontent.com/39493102/142397862-7783e5cc-0986-41e4-a713-c145671ce265.png)

Using it to create another div inside this^ icon so that we can center the currency properly

2021-11-19 09:08 UTC, abhishek1234321 approved these changes

2021-11-19 10:10 UTC, Dimple16 commented on src/app/auth/switch-org/org-card/org-card.component.html
> +<ion-grid class="ion-grid-no-padding org-card__container" matRipple (click)="onClick()">
is the method name `onClick()`? can we rename with context?

2021-11-19 10:11 UTC, Dimple16 commented on src/app/auth/switch-org/org-card/org-card.component.html
> +      <div class="org-card__pill-container__pill">Default Org</div>
this doesn't follow bem

2021-11-19 10:14 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.ts
> +import { combineLatest, forkJoin, from, fromEvent, noop, Observable, of } from 'rxjs';
still failing?

2021-11-19 10:16 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.html
> +    <div class="switch-org--org-element" *ngFor="let dummy of [1,2,3,4,5,6]">
do this - [1,2,3,4,5,6] in ts file

2021-11-19 10:17 UTC, Dimple16 requested changes
few comments

2021-11-22 08:19 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.html
> +    <div class="switch-org--org-element" *ngFor="let dummy of [1,2,3,4,5,6]">
This will be done in the pr of shimmers

2021-11-22 08:50 UTC, yksolanki9 commented on src/app/auth/switch-org/org-card/org-card.component.html
> +<ion-grid class="ion-grid-no-padding org-card__container" matRipple (click)="onClick()">
Done

2021-11-22 14:05 UTC, yksolanki9 commented on src/app/auth/switch-org/org-card/org-card.component.html
> +      <div class="org-card__pill-container__pill">Default Org</div>
Ignoring this comment as discussed

2022-01-21 07:36 UTC, Dimple16 approved these changes

2022-01-21 07:36 UTC, Dimple16 commented on src/app/auth/switch-org/active-org-card/active-org-card.component.scss
> +    width: calc(100% - 164px);
need to test this across resolutions

2022-01-21 07:36 UTC, Dimple16 commented on src/app/auth/switch-org/switch-org.page.scss
> +      padding-top: 8px;
`padding: 8px 0 0 12px`

2022-01-27 06:30 UTC, yksolanki9 commented on src/app/auth/switch-org/switch-org.page.scss
> +      padding-top: 8px;
Done

2022-01-27 06:33 UTC, merged