Suggested merge trails
fylein/fyle-mobile-app pull request #752
Opened 2021-11-16 11:00 UTC by Code0987

2021-11-17 04:29 UTC, gokulk16 requested changes

2021-11-17 04:29 UTC, gokulk16 commented on src/app/core/services/status.service.ts
> +        const matched = lowerCaseComment.match(/merged (\d+) expenses/);
same as webapp.
matched variable shoud be changed to something more contextual

2021-11-20 12:17 UTC, gokulk16 commented
please add screenshots/loom video for any user-visible changes made.

2021-11-20 12:24 UTC, gokulk16 approved these changes

2021-11-22 08:38 UTC, Julias0 approved these changes

2022-03-11 07:51 UTC, merged