Fyle 1x0eqtg : Approve Report Popup design
fylein/fyle-mobile-app pull request #800
Opened 2021-12-23 13:44 UTC by siddharth0-0

![image (2)](https://user-images.githubusercontent.com/66034160/147248814-e388c2e5-1f91-4cd4-bbf7-484bb541bb5f.png)

![image](https://user-images.githubusercontent.com/66034160/147248622-5fb4f88f-dc54-49fc-b376-17366378d2a2.png)

![image](https://user-images.githubusercontent.com/66034160/147248781-3dbe8204-dadb-4bbd-9087-f9a9e896fc5a.png)

2021-12-23 13:52 UTC, Dimple16 commented
fix lint issues and change the policy violation info icon to the yellow triangle one, this icon is information, let us change it to a warning

2021-12-23 13:54 UTC, Dimple16 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.html
> +  <div class="popup-alert--info-container" *ngIf="numIssues">
we can use the `fy-alert-info` component with `type="'warning'"` here

2021-12-23 13:54 UTC, Dimple16 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.scss
> +    margin-bottom: 25px;
24 / 26 works?

2021-12-23 13:54 UTC, Dimple16 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.scss
> +    margin-top: 25px;
same as above

2021-12-23 13:54 UTC, Dimple16 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +  @Input() etxns;
is this a list?

2021-12-23 13:55 UTC, Dimple16 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +    for (let i = 0; i < etxns.length; i++) {
use forEach

2021-12-23 13:55 UTC, Dimple16 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +    for (let i = 0; i < etxns.length; i++) {
same as above

2021-12-23 13:55 UTC, Dimple16 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +      if (etxn.tx_manual_flag) {
can we combine these conditions and use only 1 for loop?

2021-12-23 13:56 UTC, Dimple16 requested changes
added comments

2021-12-24 06:05 UTC, Dimple16 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +  @Input() etxns: [];
check if this is a list of type Expense -> `@Input() etxns: Expense[];`

2021-12-24 06:06 UTC, Dimple16 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +  getNumIssues(etxns) {
`getNumIssues(etxns: Expense)` ?

2021-12-24 06:06 UTC, Dimple16 approved these changes

2022-01-03 16:19 UTC, Julias0 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +    etxns.forEach((etxn) => {
use reduce

2022-01-03 16:19 UTC, Julias0 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +      if (etxn.tx_policy_flag || etxn.tx_manual_flag) {
dont we check the policy amount along with policy flag?

2022-01-04 07:50 UTC, siddharth0-0 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +      if (etxn.tx_policy_flag || etxn.tx_manual_flag) {
So policy amount check is not required here. The check is required in case of `critical policy violation`.
If the expense would have a critical policy violation, user would not have been able to add it to report and expense would not have been seen in team-reports.

2022-01-04 08:36 UTC, Dimple16 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +    if (this.etxns) {
`this.etxns && this.etxns.length > 0`

2022-01-04 08:37 UTC, Dimple16 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +  numIssues: number = 0;
remove `: number`

2022-01-04 08:40 UTC, Dimple16 commented on src/app/fyle/view-team-report/view-team-report.page.ts
> +      this.refinerService.startSurvey({ actionName: 'Approve Report' });
can you check if this is working properly? I feel the survey won't get triggered

2022-01-04 10:15 UTC, Dimple16 approved these changes

2022-01-04 12:49 UTC, abhishek1234321 approved these changes

2022-01-04 12:49 UTC, abhishek1234321 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +  numIssues = 0;
`numIssues: number = 0`

2022-01-05 06:28 UTC, siddharth0-0 commented on src/app/shared/components/popup-alert-component/popup-alert-component.component.ts
> +  numIssues = 0;
will be handled by default.

2022-01-05 06:28 UTC, merged