fixed : Send Report Id From View Report on click of add expense
fylein/fyle-mobile-app pull request #802
Opened 2021-12-26 07:28 UTC by siddharth0-0

No Visual Changes

2021-12-27 13:32 UTC, Dimple16 approved these changes

2021-12-28 12:23 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          () => this.activatedRoute.snapshot.params.rp_id,
wait - the reportOption which was selected at the above level, that is not getting considered at all. That will have some implications no? What if the report id has not been passed in the URL? This looks incorrect to me

2021-12-29 10:18 UTC, Dimple16 requested changes
check the cases discussed

2022-01-04 04:39 UTC, Dimple16 requested changes
verify the conditions mentioned

2022-01-04 04:39 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            report: this.activatedRoute.snapshot.params.rp_id ? paramReport$ : selectedReport$,
can you check if there is any case where the `params.rp_id` is set when this page opens? because according to the condition priority is given to the param report and not the selected report. Ideally, this check should happen in `selectedreport$` 
Few things to check:
- If it is a new expense if there is no existing selected report if the report param is present -> set the report field
- Once the page is open, it'll have the report field filled, now on edit, it should be added to any other report if I make a change - because there might be many reports in the list
- Check cases of adding expense and edit expense - if the correct report is filled/modified correctly when edited
- While opening an expense (edit expense page) -> the correct report should be selected

2022-01-04 09:45 UTC, siddharth0-0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            report: this.activatedRoute.snapshot.params.rp_id ? paramReport$ : selectedReport$,
Tested all the test cases

2022-01-04 10:13 UTC, Dimple16 approved these changes

2022-01-04 14:19 UTC, abhishek1234321 approved these changes

2022-01-06 07:07 UTC, merged