Fyle 1x64m5r : Adding shimmers to my-advances page
fylein/fyle-mobile-app pull request #803
Opened 2021-12-27 09:15 UTC by siddharth0-0

https://user-images.githubusercontent.com/66034160/147456140-10e77182-1196-4dc8-b668-f89b300dd68f.mp4

https://user-images.githubusercontent.com/66034160/147456145-d824aa41-5b8f-4514-90d7-21e9cb304b0e.mp4

2021-12-27 13:30 UTC, Dimple16 commented on src/app/fyle/my-advances/my-advances.page.html
> +    class="my-expenses--shimmers"
check if this class is required, this isn't added in CSS file, can be removed

2021-12-27 13:30 UTC, Dimple16 commented on src/app/fyle/my-advances/my-advances.page.ts
> +  refreshAdvances$ = new BehaviorSubject<void>(null);
intentional change?

2021-12-27 13:31 UTC, Dimple16 requested changes
we should make similar changes in Team advances page too

2022-01-05 10:57 UTC, Dimple16 commented on src/app/fyle/my-advances/my-advances.page.html
> +      <ng-container *ngIf="(advances$ | async)?.length===0">
add spacing

2022-01-05 11:01 UTC, Dimple16 requested changes
this has team advances page changes too, can you add a loom?

2022-01-05 12:15 UTC, Dimple16 approved these changes

2022-01-05 15:01 UTC, abhishek1234321 requested changes

2022-01-05 15:01 UTC, abhishek1234321 commented on src/app/fyle/team-advance/team-advance.page.html
> +    <div *ngIf="!isLoading">
same comments as above

2022-01-05 15:01 UTC, abhishek1234321 commented on src/app/fyle/team-advance/team-advance.page.ts
> +    setTimeout(() => {
same comments as above

2022-01-05 15:28 UTC, Dimple16 commented on src/app/fyle/my-advances/my-advances.page.ts
> +  isLoading = false;
we can skip this for boolean, number - https://palantir.github.io/tslint/rules/no-inferrable-types/ 
inferred directly, there is lint added too - `Type boolean trivially inferred from a boolean literal, remove type annotation` cc @abhishek1234321

2022-01-06 06:42 UTC, siddharth0-0 commented on src/app/fyle/my-advances/my-advances.page.ts
> +    setTimeout(() => {
500ms is just been added to load the shimmers.

2022-01-07 04:53 UTC, abhishek1234321 commented on src/app/fyle/my-advances/my-advances.page.ts
> +    setTimeout(() => {
@Dimple16 could you check this? ideally we should hide shimmers only after the data is loaded

2022-01-10 04:38 UTC, iravisankar approved these changes

2022-01-10 04:47 UTC, iravisankar commented
@siddharth0-0  please confirm shimmers on infinite scroll

2022-01-13 05:04 UTC, abhishek1234321 approved these changes

2022-01-13 06:08 UTC, merged