Fyle 1xqe5y1 : Report zero state on search/added Approve date in View Report
fylein/fyle-mobile-app pull request #808
Opened 2022-01-05 13:39 UTC by siddharth0-0

![zem](https://user-images.githubusercontent.com/66034160/148226654-70dc5d93-db1e-4a09-9a5c-e4e17744e172.png)
![zero](https://user-images.githubusercontent.com/66034160/148226652-86b9a4d7-f0dd-4488-8cd6-b8d10af398e3.png)

`date besides approve state`
![app_d](https://user-images.githubusercontent.com/66034160/148226663-588be32b-18ee-4656-b513-376f7f28192a.png)
![app_date](https://user-images.githubusercontent.com/66034160/148226660-c1ee7e06-ab2a-4350-998f-7d8c1c5a6c09.png)

2022-01-05 14:58 UTC, Dimple16 approved these changes

2022-01-05 15:02 UTC, Dimple16 commented
remove the `package-lock.json` file change

2022-01-05 15:03 UTC, abhishek1234321 requested changes

2022-01-05 15:03 UTC, abhishek1234321 commented on src/app/fyle/my-view-report/my-view-report.page.ts
> +    const erpt = await this.erpt$.toPromise();
why do we need to convert to promise? should we not stick to observables?

2022-01-12 05:10 UTC, iravisankar approved these changes

2022-01-13 05:05 UTC, abhishek1234321 approved these changes

2022-01-14 07:27 UTC, merged