added Expense removed with delete icon in history tab
fylein/fyle-mobile-app pull request #820
Opened 2022-01-13 12:36 UTC by siddharth0-0

2022-01-17 06:02 UTC, Dimple16 requested changes

2022-01-17 06:02 UTC, Dimple16 commented on src/app/app.component.ts
> +    console.log('da', data);
remove

2022-01-17 06:02 UTC, Dimple16 commented on src/app/fyle/my-view-report/my-view-report.page.scss
> +      opacity: 0.8;
do we need this?

2022-01-17 06:02 UTC, Dimple16 commented on src/app/fyle/my-view-report/my-view-report.page.scss
> +    padding: 0 5px;
6?

2022-01-20 05:09 UTC, siddharth0-0 commented on src/app/fyle/my-view-report/my-view-report.page.scss
> +      opacity: 0.8;
Yes opacity was added  to make text look similar to figma design

2022-01-21 09:55 UTC, iravisankar approved these changes

2022-01-21 14:06 UTC, Dimple16 approved these changes

2022-01-24 05:18 UTC, merged