Fix for Policy violation design issue (1ytrn4u)
fylein/fyle-mobile-app pull request #824
Opened 2022-01-18 11:00 UTC by saitejasFyle

Sharing you with the before and after screenshots below

Fixes: I have removed the unwanted bullet point and maintained uniformity in the contents of Policy violations and Claimed amount

Before Fix: 

![1ytrn4u - Before Fix](https://user-images.githubusercontent.com/97864484/149924402-b7484847-98b0-4ef3-919a-a09160daa0ac.png)

After Fix:

![1ytrn4u - After Fix](https://user-images.githubusercontent.com/97864484/149924619-b14cbaa9-2b19-432d-99a9-23fec1bae926.png)

2022-01-18 15:56 UTC, Dimple16 requested changes

2022-01-18 15:56 UTC, Dimple16 commented on src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.scss
> +    list-style-type: none;
this will remove the bullet for the entire list, we need to remove the bullet point only if one item is there in the list

2022-01-18 15:56 UTC, Dimple16 commented on src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.scss
> +    padding-left: 7px;
6 or 8 works?

2022-01-18 15:56 UTC, Dimple16 commented on src/global.scss
> +    margin: 5.3px;
can we use 6px?

2022-01-18 15:56 UTC, Dimple16 commented on src/global.scss
> +    font-size: 0.86em;
14px should do

2022-01-19 08:40 UTC, Dimple16 approved these changes

2022-01-19 08:45 UTC, Julias0 commented on src/app/shared/components/fy-policy-violation-info/fy-policy-violation-info.component.html
> +      <ul class="policy-violation-info--list" [ngClass]="{ 'list-type-none': !criticalPolicyViolated }">
list-type-none -> policy-violation-info--list__no-bullet
his will persist the heirarchy in the class name

2022-01-19 08:59 UTC, Julias0 commented
Also Add a screenshot on how it looks when a critical policy violation is present

2022-01-20 11:43 UTC, Julias0 approved these changes

2022-01-21 15:13 UTC, merged