Resolve sidemenu comments
fylein/fyle-mobile-app pull request #825
Opened 2022-01-18 11:12 UTC by yksolanki9

2022-01-18 15:52 UTC, Dimple16 requested changes

2022-01-18 15:52 UTC, Dimple16 commented on src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.scss
> +        padding-left: 9px;
10?

2022-01-18 15:52 UTC, Dimple16 commented on src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.ts
> +  @Input() numPrimaryOptions: number;
`primaryOptionsCount`?

2022-01-18 16:13 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content-item/sidemenu-content-item.component.scss
> +        padding-left: 9px;
The design uses a 3px red margin for active tabs. 4px/2px dont look good. So if I make this 10px, I'll have to make the others 13px

2022-01-19 09:58 UTC, Dimple16 approved these changes

2022-01-20 11:52 UTC, Julias0 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +      primaryOptions.splice(
Extract this and the below part into a pure function. @Dimple16 can help with this

2022-01-20 11:53 UTC, Julias0 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +    ].filter((sidemenuItem) => sidemenuItem.isVisible);
why move this here?

2022-01-21 05:51 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +    ].filter((sidemenuItem) => sidemenuItem.isVisible);
This was done to get count of primary options that would be visible and display the divider accordingly. For secondary options it wont matter if we filter in this method or after combining with primary.

2022-01-21 07:08 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu.component.ts
> +      primaryOptions.splice(
Done

2022-01-25 14:12 UTC, Julias0 commented on src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.html
> +        [showDivider]="i === primaryOptionsCount ? true : false"
`[showDivider]="i === primaryOptionsCount"` should behave the same

2022-01-25 14:12 UTC, Julias0 approved these changes

2022-01-27 06:34 UTC, yksolanki9 commented on src/app/shared/components/sidemenu/sidemenu-content/sidemenu-content.component.html
> +        [showDivider]="i === primaryOptionsCount ? true : false"
Done

2022-01-27 07:07 UTC, merged