FYLE-1z55me7: Prompt report submission mobile app changes
fylein/fyle-mobile-app pull request #829
Opened 2022-01-20 14:53 UTC by Dimple16

### List of changes

**- Making `Add to report` mandatory during add expense
- Adding a different background to `Add to report`
- On Save and new, redirect to expense form with report name filled**

![Screenshot 2022-01-20 at 7 50 15 PM](https://user-images.githubusercontent.com/31147415/150362271-15973937-d2d1-4b54-95ef-d6e6ae5473bc.png)

![Screenshot 2022-01-20 at 7 53 28 PM](https://user-images.githubusercontent.com/31147415/150362285-4e0605ad-48fd-49a7-9754-547b5fcd6955.png)

2022-01-25 13:54 UTC, Julias0 approved these changes

2022-01-25 13:56 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                <div class="add-edit-expense--internal-block add-edit-expense--report-section">
What happens if an expense 
hits critical policy violation during adding of a new expense
No reports are present
No internet is present
Wont it lead to the case that this field is a required field but it is not visible?

2022-01-25 13:57 UTC, Julias0 requested changes
Put out a note in #mobile_app for some questions

2022-02-08 13:20 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                <div class="add-edit-expense--internal-block add-edit-expense--report-section">
The cases are handled:
- When no reports are present
   - User can create a new report
-  No internet is present
   - Add to Report field is made mandatory only when online
-  When an expense is critical policy violated
   -  If a report is added to expense, on click of the save button, the critical policy violation pop up is shown
   -  On continuing to save with the critical policy violation, expense is saved and not added to report

2022-02-08 17:40 UTC, Julias0 approved these changes

2022-02-09 05:37 UTC, merged