FYLE-1zaxwp4
fylein/fyle-mobile-app pull request #835
Opened 2022-01-25 08:26 UTC by saitejasFyle

Changes for FYLE-1zaxwp4

Change: 

https://www.loom.com/share/7a74cbb08f2b46acbaed32b737b2741b

The suggestion in the video has been accepted and pushed here

2022-01-25 09:10 UTC, Dimple16 requested changes

2022-01-25 09:10 UTC, Dimple16 commented on src/app/fyle/my-profile/employee-details-card/employee-details-card.component.ts
> +  // @ViewChild('mobileNumberRef', { read: ElementRef }) mobileNumberRef: ElementRef;
why is this commented out?

2022-01-25 09:10 UTC, Dimple16 commented on src/app/fyle/my-profile/employee-details-card/employee-details-card.component.ts
> +    // const mobileNumberEl = this.mobileNumberRef?.nativeElement;
can remove if we aren't using this anymore

2022-01-27 05:37 UTC, saitejasFyle commented on src/app/fyle/my-profile/employee-details-card/employee-details-card.component.ts
> +  // @ViewChild('mobileNumberRef', { read: ElementRef }) mobileNumberRef: ElementRef;
Yup it's not necessary, let me remove those

2022-01-27 06:29 UTC, Dimple16 approved these changes

2022-01-27 16:46 UTC, Julias0 approved these changes

2022-01-28 06:07 UTC, merged