update project name in my expenses list
fylein/fyle-mobile-app pull request #843
Opened 2022-01-28 11:39 UTC by Ajinkya2000

![Screenshot from 2022-01-28 17-09-09](https://user-images.githubusercontent.com/55014143/151540724-3aa15e09-6f8f-447e-bfb4-b8816e51e0a5.png)

2022-02-01 12:30 UTC, pradeep8093 approved these changes

2022-02-07 06:33 UTC, shishirams222 approved these changes

2022-02-16 08:24 UTC, Dimple16 requested changes

2022-02-16 08:24 UTC, Dimple16 commented on src/app/shared/components/expenses-card/expenses-card.component.html
> +              <span class="text-capitalize"> {{ expenseFields?.project_id[0].field_name }}: </span>
`expenseFields?.project_id[0]?.field_name`

2022-03-02 10:31 UTC, Dimple16 approved these changes

2022-03-20 06:14 UTC, closed without merging