Update Project Name in Split Expense
fylein/fyle-mobile-app pull request #853
Opened 2022-01-31 06:31 UTC by Ajinkya2000

![localhost_8100_enterprise_add_edit_expense;id=tx96JLRvfXqC;persist_filters=true(iPhone SE)](https://user-images.githubusercontent.com/55014143/151748803-0c247e95-ae9b-4036-b7dd-7635cb547dad.png)
![localhost_8100_enterprise_add_edit_expense;id=tx96JLRvfXqC;persist_filters=true(iPhone SE) (1)](https://user-images.githubusercontent.com/55014143/151748855-e24a68cf-6a93-425b-86ee-4c7fc2f67f13.png)

2022-02-01 14:22 UTC, pradeep8093 approved these changes

2022-02-09 10:46 UTC, shishirams222 commented on src/app/fyle/split-expense/split-expense.page.ts
> +  selectProjectMessage = 'a Project';
This can be renamed as something like: `selectProjectMessage` -> `warningTextLabel`

2022-02-16 07:45 UTC, Ajinkya2000 commented on src/app/fyle/split-expense/split-expense.page.ts
> +  selectProjectMessage = 'a Project';
Okay will change this.

2022-02-16 11:52 UTC, Dimple16 requested changes

2022-02-16 11:52 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.ts
> +    // if the project field name is not project, this will remove "a" from the required text
why not have the `a` for both cases? is removing required here?

2022-02-16 11:52 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.html
> +              Please select {{ selectProjectMessage }}.
is this required here? can we not directly use it here? you can add it conditionally it

2022-02-16 11:52 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.html
> +              [placeholder]="txnFields?.project_id?.placeholder"
`placeholder` is not required here, only `label` should do, the component handles what has to be shown as the placeholder

2022-02-16 11:52 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.html
> +              [placeholder]="txnFields?.project_id?.placeholder"
check `fy-select-project.component.html`

2022-02-16 11:52 UTC, Dimple16 commented on src/app/fyle/split-expense/split-expense.page.html
> +          Split by {{ splitType === 'projects' ? txnFields.project_id.field_name : splitType}}
`txnFields?.project_id?.field_name`

2022-03-01 18:18 UTC, Ajinkya2000 commented on src/app/fyle/split-expense/split-expense.page.ts
> +    // if the project field name is not project, this will remove "a" from the required text
Yes, because if a user renamed `project` to say `event`, then ideally we must be showing **an event** not **a event**. So we decided to just remove the `a`.

2022-03-01 18:30 UTC, Ajinkya2000 commented on src/app/fyle/split-expense/split-expense.page.html
> +              Please select {{ selectProjectMessage }}.
Yes added conditionally. It made more sense.

2022-03-01 18:31 UTC, Ajinkya2000 commented on src/app/fyle/split-expense/split-expense.page.html
> +              [placeholder]="txnFields?.project_id?.placeholder"
So placeholder is required here because the admin also sets the placeholder text. So we need to show that.

2022-03-02 10:32 UTC, Dimple16 approved these changes

2022-03-20 06:13 UTC, closed without merging