Implemented notify me only under delegatee notification settings
fylein/fyle-mobile-app pull request #860
Opened 2022-01-31 12:09 UTC by saitejasFyle

While implementing, found an existing issue which is, the selected mode of notification under delegatee notification dropdown was not getting populated once we revisit the notifications page after saving the changes.

This has also been taken care in this change.

2022-02-01 05:52 UTC, Dimple16 approved these changes

2022-02-01 05:52 UTC, Dimple16 commented on src/app/core/models/org_user_settings.model.ts
> +  notify_delegatee: boolean;
are these present every time?

2022-02-02 06:34 UTC, saitejasFyle commented on src/app/core/models/org_user_settings.model.ts
> +  notify_delegatee: boolean;
Yeah

2022-02-02 07:32 UTC, Julias0 requested changes

2022-02-02 07:38 UTC, saitejasFyle commented on src/app/fyle/notifications/notifications.page.ts
> +      if (this.notificationForm) {
Yeah whenever we subscribe to updateDelegateSubscription(), if a form group instance (notificationForm) is already present, we have to populate the current notifyOption by setting the value to that form control. So to check if the formGroup is undefined or not, I have added the if condition.

2022-02-02 07:39 UTC, saitejasFyle commented on src/app/fyle/my-profile/my-profile.page.ts
> +    const orgUserSettings$ = await this.offlineService
It's done. And I've raised the PR

2022-02-05 08:10 UTC, Julias0 commented on src/app/fyle/notifications/notifications.page.ts
> +      if (this.notificationForm) {
Lets talk about this on monday

2022-02-08 06:20 UTC, Julias0 approved these changes

2022-02-09 05:09 UTC, merged