Pontential duplicates from task page
fylein/fyle-mobile-app pull request #866
Opened 2022-02-02 02:26 UTC by iravisankar

2022-02-02 08:06 UTC, Dimple16 requested changes

2022-02-02 08:06 UTC, Dimple16 commented on src/app/core/services/tasks.service.ts
> +              icon: TaskIcon.REPORT,
are we using the same icon for duplicates?

2022-02-02 08:06 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.scss
> +    padding-top: 20px;
`padding: 20px 0;`

2022-02-02 08:06 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.scss
> +      text-align: center;
use global class for `text-center`

2022-02-02 08:06 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +  duplicatesSetData;
is this of a specific type?

2022-02-02 08:06 UTC, Dimple16 commented on src/app/shared/components/expenses-card/expenses-card.component.scss
> +    margin-top: -10px;
`margin: -10px 0 0 12px;`

2022-02-15 09:00 UTC, iravisankar commented on src/app/core/services/tasks.service.ts
> +              icon: TaskIcon.REPORT,
same icon used in design

2022-02-15 16:04 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.scss
> +    padding-bottom: 20px;
remove either of the padding

2022-02-15 16:05 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.scss
> +    border-radius: 15px;
does 14 or 16px work?

2022-02-15 16:05 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.scss
> +    text-align: center;
use `text-center`

2022-02-15 16:05 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.scss
> +    text-align: center;
global class

2022-02-21 06:02 UTC, iravisankar commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +          tap((duplicatesSets) => {
Storing in duplicatesSetData on every trigger to use in other places.

2022-02-21 11:20 UTC, Dimple16 requested changes

2022-02-21 11:20 UTC, Dimple16 commented on src/app/core/models/v2/duplicate-sets.model.ts
> +  fields: any[];
any?

2022-02-21 11:20 UTC, Dimple16 commented on www/.gitignore
> -# Ignore everything in this directory
any reason this is removed?

2022-02-22 17:17 UTC, iravisankar commented on www/.gitignore
> -# Ignore everything in this directory
got an error on Appflow to add `www` folder. so added it, but found the real issue...,  so removed it now...

2022-02-23 14:19 UTC, Dimple16 requested changes

2022-02-23 14:19 UTC, Dimple16 commented on src/app/core/services/handle-duplicates.service.ts
> +  getDuplicatesSet() {
should we add a return type?

2022-02-23 23:16 UTC, iravisankar commented on src/app/core/services/handle-duplicates.service.ts
> +  dismissAll(duplicateSetTransactionIds: string[], transactionIds: string[]) {
it does not return any value

2022-02-28 09:30 UTC, Dimple16 approved these changes

2022-11-05 16:08 UTC, closed without merging