update project name in view advances
fylein/fyle-mobile-app pull request #869
Opened 2022-02-02 08:09 UTC by Ajinkya2000

![Screenshot from 2022-02-02 13-38-57](https://user-images.githubusercontent.com/55014143/152116370-860d9ee0-9083-4029-a24a-260a27828633.png)

2022-02-16 06:25 UTC, pradeep8093 approved these changes

2022-02-16 11:41 UTC, Dimple16 requested changes

2022-02-16 11:41 UTC, Dimple16 commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
> +    this.offlineService.getAllEnabledExpenseFields().subscribe((expenseFields) => {
we don't use the `expense_fields` project in advances, is this intentional? did we make any change in the backend?

2022-03-02 10:33 UTC, Dimple16 approved these changes

2022-03-20 06:13 UTC, closed without merging