Update Project Name in View Expense Page in team reports
fylein/fyle-mobile-app pull request #871
Opened 2022-02-02 08:39 UTC by Ajinkya2000

![Screenshot from 2022-02-02 14-09-15](https://user-images.githubusercontent.com/55014143/152120349-41d39c16-5d3d-4b65-a249-520681fc9753.png)

2022-02-09 15:27 UTC, pradeep8093 approved these changes

2022-02-16 09:50 UTC, shishirams222 approved these changes

2022-02-16 10:23 UTC, Dimple16 requested changes

2022-02-16 10:23 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.ts
> +          this.projectFieldName = expenseFieldsMap?.project_id[0].field_name;
`expenseFieldsMap?.project_id[0]?.field_name`

2022-02-16 10:23 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.html
> +          {{projectFieldName | titlecase}}: {{ etxn.tx_project_name ? etxn.tx_project_name : 'Unspecified' }}
`{{ projectFieldName | titlecase }} : {{ etxn.tx_project_name ? etxn.tx_project_name : 'Unspecified' }}`

2022-03-02 07:26 UTC, Julias0 approved these changes

2022-03-20 06:13 UTC, closed without merging