Fyle 1rwz3mg : Sent Back Task for Individual Advances
fylein/fyle-mobile-app pull request #884
Opened 2022-02-09 07:40 UTC by siddharth0-0

2022-02-11 06:19 UTC, Dimple16 commented
fix lint issues

2022-02-14 05:30 UTC, Dimple16 requested changes
add trackers wherever required

2022-02-14 05:30 UTC, Dimple16 commented on src/app/core/services/tasks.service.ts
> +      }
else? will this have any default?

2022-02-14 05:30 UTC, Dimple16 commented on src/app/core/services/tasks.service.ts
> +  mapSentBackAdvacnesToTasks(
`mapSentBackAdvancesToTasks` typo

2022-02-15 09:24 UTC, Dimple16 commented
trackers aren't added yet, please check

2022-02-15 09:31 UTC, Dimple16 approved these changes

2022-02-15 11:57 UTC, Julias0 commented on src/app/core/services/tasks.service.ts
> +  getSelectedFilter(selectedFilters, filterName, value) {
define datatype of the arguments passed

also rename this method - I dont understand what this function does by reading its name

2022-02-15 11:57 UTC, Julias0 commented on src/app/core/services/tasks.service.ts
> +  getSelectedFilter(selectedFilters, filterName, value) {
Also make this a proper pure function - @Dimple16 can help here

2022-02-22 09:09 UTC, siddharth0-0 commented on src/app/core/services/tasks.service.ts
> +  getSelectedFilter(selectedFilters, filterName, value) {
Have removed the function itself as it was no longer needed

2022-02-22 11:39 UTC, Julias0 commented on src/app/core/services/advance.service.ts
> +  getAdvancesStats(params) {
getAdvancesStats -> getMyAdvanceRequestStats

2022-02-22 11:41 UTC, Julias0 commented on src/app/core/services/advance.service.ts
> +  getAdvancesStats(params) {
params should have a datatype

2022-02-22 11:43 UTC, Julias0 commented on src/app/core/services/advance.service.ts
> +  getAdvancesStats(params) {
add a return type

2022-02-22 11:45 UTC, Julias0 commented on src/app/core/services/advance.service.ts
> +        this.apiv2Service.get('/advance_requests/stats', {
extract out into a separate function

2022-02-22 11:51 UTC, Julias0 commented on src/app/core/services/tasks.service.ts
> +          header: `Advance${aggregate.totalCount === 1 ? '' : 's'} sent back!`,
do these in separate variables and use the variables here - it is hard to read like this
Example - 
```typescript
header: `Advance${aggregate.totalCount === 1 ? '' : 's'} sent back!`, -> 

const header = `Advance${aggregate.totalCount === 1 ? '' : 's'} sent back!`;

{
...
header,
...
}
```

2022-02-22 11:53 UTC, Julias0 commented on src/app/fyle/dashboard/tasks/tasks.component.ts
> +      from(this.loaderService.showLoader('Opening your advance...'))
Opening your advance.. -> Opening your advance request

Note: Advance and advance requests are separate things, make sure you dont mix them up

2022-02-25 05:30 UTC, siddharth0-0 commented on src/app/core/services/advance.service.ts
> +  getAdvancesStats(params) {
moved function in `advance-request.service.ts`

2022-02-26 19:01 UTC, Julias0 approved these changes

2022-02-28 07:21 UTC, merged