Fix alignment of Please enter amount text
fylein/fyle-mobile-app pull request #903
Opened 2022-02-15 10:31 UTC by yksolanki9

Before:
![localhost_8100_enterprise_add_edit_advance_request(Pixel 5)](https://user-images.githubusercontent.com/39493102/154043624-a5b65cb9-7d95-40eb-9617-dea86e6fed0f.png)

After:
![localhost_8100_enterprise_add_edit_mileage;navigate_back=true(Pixel 5)](https://user-images.githubusercontent.com/39493102/154043392-b98efae7-f0eb-4748-a52f-32f59249f8e1.png)

2022-02-15 14:07 UTC, Dimple16 requested changes

2022-02-15 14:07 UTC, Dimple16 commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.scss
> +    margin: -8px 0 0 52%;
need to verify this on different resolutions, might break in smaller width phones

2022-02-18 14:11 UTC, Dimple16 approved these changes

2022-02-21 06:07 UTC, yksolanki9 commented on src/app/fyle/add-edit-advance-request/add-edit-advance-request.page.scss
> +    margin: -8px 0 0 52%;
Discussed

2022-02-21 06:08 UTC, merged