Add fyle camera in my-expenses page
fylein/fyle-mobile-app pull request #910
Opened 2022-02-17 15:11 UTC by yksolanki9

2022-02-21 07:48 UTC, Dimple16 requested changes

2022-02-21 07:48 UTC, Dimple16 commented on .gitignore
> +.angular
is this an intentional change?

2022-02-21 07:48 UTC, Dimple16 commented on src/app/shared/components/expenses-card/expenses-card.component.ts
> +    public platform: Platform
use this as private and add a variable to use in the HTML

2022-02-21 07:48 UTC, Dimple16 commented on src/app/shared/components/expenses-card/expenses-card.component.html
> +            *ngIf="platform.is('ios')"
this will change according to the below comment

2022-02-21 07:59 UTC, yksolanki9 commented on .gitignore
> +.angular
Yes

2022-02-21 08:06 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.ts
> +    public platform: Platform
Done

2022-02-21 14:00 UTC, Dimple16 approved these changes

2022-02-23 12:29 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                <input *ngIf="isIos" type="file" #fileUpload accept="application/pdf,image/*" style="display: none" />
dei no inline styling. Please remove this

2022-02-23 12:30 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +                <input *ngIf="isIos" type="file" #fileUpload accept="application/pdf,image/*" style="display: none" />
please remove the inline styling from everywhere

2022-02-23 12:31 UTC, Julias0 commented on src/app/shared/components/expenses-card/expenses-card.component.ts
> +          this.expense.tx_file_ids = [];
extract out this part into a separate function

2022-02-23 12:31 UTC, Julias0 commented on src/app/shared/components/expenses-card/expenses-card.component.ts
> +          this.expense.tx_file_ids.push(fileObj.id);
any way we can avoid doing this here and do this inside the subscribe?

2022-02-25 07:53 UTC, yksolanki9 commented on src/app/shared/components/expenses-card/expenses-card.component.ts
> +          this.expense.tx_file_ids = [];
Made a separate function `setThumnail()` for this

2022-03-01 13:03 UTC, Julias0 approved these changes

2022-03-01 13:06 UTC, merged