Fyle 22c3ghr - view advance/advance request pages UI revamp
fylein/fyle-mobile-app pull request #915
Opened 2022-02-21 06:39 UTC by saitejasFyle

2022-02-21 09:21 UTC, Dimple16 commented
Comments on the screenshots:
- Approved on and Issued on icons are different
- Payment mode icon is incorrect
- Check the spacing between the card section and receipt preview, currently it is more
- When the project is not added, we should show a `-`, also due to this the icon looks flattened
- `Paid` pill color is different
- In the approver's section, if the state is approved and beyond, we need to show the approved on `date` as well
- Check the margin spacing of the dividers, we need to increase it by 1/2px

2022-02-21 11:00 UTC, Dimple16 commented on src/app/shared/components/fy-statistic/fy-statistic.component.ts
> +  @Input() icon: any;
is this a string?

2022-02-21 11:00 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.html
> +    <!-- <div> -->
why is this?

2022-02-21 11:00 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.html
> +        <!-- <ion-icon
remove

2022-02-21 11:00 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.html
> +      <!-- <div class="summary-tile--card-container__exchange-rate" *ngIf="foreignCurrencySymbol">
remove

2022-02-21 11:00 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.html
> +    <!-- </div> -->
check if this is redundant

2022-02-21 11:01 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.html
> +  <div class="summary-tile--approval-state-block">
`summary-tile`? typo? or is this intentionally named?

2022-02-21 11:02 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.scss
> +    font-size: 14px;
this is by default, check if required, else remove

2022-02-21 11:02 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.scss
> +    font-weight: 400;
same as above

2022-02-21 11:03 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.scss
> +    margin-top: -40px;
need to verify this in different devices

2022-02-21 11:03 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.scss
> +    padding: 35px 6px 17px 6px;
`36px 6px 16px 6px`? works?

2022-02-21 11:04 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.ts
> +  @Input() currency: any;
avoid using `any`, you an add the type of currency as string

2022-02-21 11:04 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.ts
> +  @Input() amount: any;
any?

2022-02-21 11:04 UTC, Dimple16 commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.ts
> +  @Input() foreignCurrencySymbol: any;
same as above

2022-02-21 11:05 UTC, Dimple16 commented on src/assets/svg/calendar-grey.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
In svgs, you can remove the height and width, can add CSS to use it accordingly

2022-02-21 11:05 UTC, Dimple16 commented on src/assets/svg/card-grey.svg
> +<svg width="20" height="18" viewBox="0 0 20 18" fill="none" xmlns="http://www.w3.org/2000/svg">
same for all the svgs

2022-02-21 11:06 UTC, Dimple16 commented
In the video, when the edit option is present, it looks like the 3 actions icons have different colors, verify this in Figma and change accordingly

2022-02-23 10:11 UTC, saitejasFyle commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +          <div *ngIf="attachedFiles.length === 0" class="view-advance-request--element">
I have taken care of this using optional chaining

2022-02-23 10:11 UTC, saitejasFyle commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +          <div *ngIf="attachedFiles.length > 0">
I have taken care of this using optional chaining

2022-02-23 10:12 UTC, saitejasFyle commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +        <ion-grid class="view-advance-request--padding-0">
Yup, it's done

2022-02-23 10:13 UTC, saitejasFyle commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.ts
> +  @Input() currency: any;
done

2022-02-24 07:14 UTC, Dimple16 commented
> can you please add screenshots of how the screens look when edit mode is present?

please add this?

2022-02-24 10:32 UTC, saitejasFyle commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +                  [icon]="'../../../../assets/svg/calendar-grey.svg'"
Tried it, but adding a CSS layer over the image does not suit. It spoils the experience and richness of an original image

2022-02-24 10:39 UTC, saitejasFyle commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +              <div class="view-advance-request--element" *ngIf="advanceRequest.areq_approved_at">
Yup, sorry for that

2022-02-24 10:40 UTC, saitejasFyle commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +      <div *ngIf="advanceRequest.areq_advance_id" class="view-advance-request--view-advance">
Done

2022-02-24 10:45 UTC, saitejasFyle commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.scss
> +  &--element {
This was the notation that we were using. Depicts the actual element that's been rendered.

2022-02-24 10:47 UTC, saitejasFyle commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.scss
>      border-bottom: 1px solid #e0e0e0;
Done

2022-02-24 11:37 UTC, saitejasFyle commented on src/app/shared/components/fy-statistic/fy-statistic.component.scss
> +    font-size: 14px;
Yup that's not needed

2022-02-24 11:38 UTC, saitejasFyle commented on src/app/shared/components/fy-statistic/fy-statistic.component.ts
> +  @Input() type: any;
The other 3 variables are string. But a value could be anything right?

2022-02-24 11:43 UTC, saitejasFyle commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.html
> +  <div class="summary-tile--approval-state-block">
Intentionally named after the component itself

2022-02-24 11:46 UTC, saitejasFyle commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.scss
> +    font-weight: 400;
actually I think we want that

2022-02-24 11:48 UTC, saitejasFyle commented on src/app/shared/components/fy-summary-tile/fy-summary-tile.component.scss
> +    margin-top: -40px;
I have checked it in the different devices under responsiveness in the browser

2022-02-28 10:02 UTC, Dimple16 requested changes

2022-02-28 10:02 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.scss
> +$advance_draft_color: #464d57;
I guess a few of these colors are added in `colors.scss`, verify and reuse / add accordingly

2022-02-28 10:02 UTC, Dimple16 commented on src/app/shared/components/summary-tile/summary-tile.component.scss
> +      // background-color: $highlight-black;
remove if not required

2022-02-28 10:13 UTC, saitejasFyle commented on src/app/shared/components/summary-tile/summary-tile.component.scss
> +      // background-color: $highlight-black;
It's not required, so removing it

2022-02-28 12:05 UTC, saitejasFyle commented on src/app/shared/components/summary-tile/summary-tile.component.scss
> +$advance_draft_color: #464d57;
It's done

2022-02-28 12:08 UTC, Dimple16 approved these changes

2022-03-01 12:46 UTC, Julias0 commented on src/app/core/models/approver.model.ts
> +export interface AdvanceApprover {
we should restrict 1 interface to 1 file

2022-03-01 12:47 UTC, Julias0 commented on src/app/core/models/approver.model.ts
> +export interface AdvanceApprover {
Otherwise this is a violation of the single responsibility principle

2022-03-01 12:48 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() approvals: AdvanceApprover[];
set this to empty array be default.

2022-03-01 12:50 UTC, Julias0 commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +              [type]="'string'"
ok dont pass constants like this since there is a chance of making spelling mistakes. Create a enum and from the component of this file, expose the enum through a getter. That way if you make a mistake the compiler can detect it

2022-03-01 12:51 UTC, Julias0 commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +                  [type]="'date'"
same comment as above for all type properties

2022-03-01 12:52 UTC, Julias0 commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +            [value]="advanceRequest.project_name || '-' | ellipsis: 15"
`[value]="(advanceRequest.project_name || '-') | ellipsis: 15"`

2022-03-01 12:53 UTC, Julias0 commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +        <div *ngIf="(advanceRequestCustomFields$|async)?.length > 0">
dont combine this

first resolve with a ng-container and then check for length

```html
<ng-container *ngIf="advanceRequestCustomFields$|async as advanceRequestCustomFields">
  <div *ngIf="advanceRequestCustomFields.length > 0">
   ...
  </div>
</ng-container>
```

2022-03-01 12:53 UTC, Julias0 commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +            *ngFor="let advanceRequestCustomField of advanceRequestCustomFields$ | async; index as i"
same as above - dont combine async with other stuff, it becomes difficult to debug.

2022-03-01 12:55 UTC, Julias0 commented on src/app/shared/components/fy-statistic/fy-statistic.component.ts
> +  @Input() value: any;
You can use union types if you are unsure of what type will be passed in @saitejasFyle

2022-03-01 12:58 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() categoryDisplayName: string;
`categoryDisplayName` -> category

2022-03-01 12:58 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() merchantName: string;
`merchantName` -> `merchant`

2022-03-01 12:59 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() projectName: string;
`projectName` -> `project`

2022-03-01 12:59 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() projectName: string;
I mean I dont see a value add in suffixing the Name. Feel free to push back if you have strong ground for this

2022-03-01 13:01 UTC, Julias0 commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() foreignCurrencySymbol: string;
ok use the proper property name as returned from the api. I am unable to understand what this maps to

2022-03-02 06:04 UTC, saitejasFyle commented on src/app/core/models/approver.model.ts
> +export interface AdvanceApprover {
Got it..Done

2022-03-02 06:37 UTC, saitejasFyle commented on src/app/shared/components/summary-tile/summary-tile.component.ts
> +  @Input() foreignCurrencySymbol: string;
Ok, that is tx_orig_currency..I've updated this.

2022-03-02 06:50 UTC, saitejasFyle commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +              [type]="'string'"
I've introduced a class variable called statisticType with the config as below:

statisticType = {
    string: 'string',
    number: 'number',
    date: 'date',
    boolean: 'boolean'
  }

And for an instance,  instead of referring constants directly I'm calling them as statisticType.string

2022-03-03 05:24 UTC, Julias0 commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +              <div *ngIf="advanceRequestCustomField.type === 'DATE' && advanceRequestCustomField.value">
you missed using the enums here

2022-03-03 05:25 UTC, Julias0 commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
> +    string: 'string',
use keys like 'text', 'numerical' and 'bool' to avoid these errors

2022-03-03 05:26 UTC, Julias0 commented on src/app/fyle/my-view-advance/my-view-advance.page.ts
> +  statisticType = {
ok create a proper enum not a dictionary. 

typescript has a type called enum and lets have it in a separate file to avoid duplication

2022-03-03 06:27 UTC, saitejasFyle commented on src/app/fyle/my-view-advance/my-view-advance.page.ts
> +  statisticType = {
Done

2022-03-03 06:32 UTC, saitejasFyle commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.html
> +              <div *ngIf="advanceRequestCustomField.type === 'DATE' && advanceRequestCustomField.value">
Done

2022-03-03 07:34 UTC, saitejasFyle commented on src/app/fyle/my-view-advance-request/my-view-advance-request.page.ts
> +    string: 'string',
I've added all keys of the enum file in all caps

2022-03-04 06:51 UTC, Julias0 commented on src/app/shared/components/fy-statistic/datatypes-statistic.enum.ts
> +export enum StatisticTypes {
rename file to statistic-type.enum.ts

file naming convention should match the entity inside - its just that we convert it to dashcase

2022-03-04 06:52 UTC, Julias0 approved these changes

2022-03-04 08:05 UTC, merged