Make `Add to Report` mandatory based on user settings
fylein/fyle-mobile-app pull request #918
Opened 2022-02-22 11:39 UTC by yksolanki9

2022-02-22 12:59 UTC, Dimple16 requested changes

2022-02-22 12:59 UTC, Dimple16 commented on src/app/core/models/v1/user-property.model.ts
> +export interface Setting {
this is very general, can you check `org_user_settings.model.ts`
check if we can do something similar here

2022-02-22 12:59 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            this.isReportMandatory = true;
don't assign inside map, do this inside the subscribe

2022-02-22 12:59 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        .pipe(
we should add a map here and add variables, check forkJoin used elsewhere

2022-02-22 12:59 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +              res.isConnected &&
this will change accordingly

2022-02-22 12:59 UTC, Dimple16 commented on src/app/fyle/add-edit-mileage/add-edit-mileage.page.ts
> +      forkJoin({
same comments as expense form

2022-02-22 12:59 UTC, Dimple16 commented on src/app/fyle/add-edit-per-diem/add-edit-per-diem.page.ts
> +      forkJoin({
same comments as expense form

2022-02-23 06:55 UTC, yksolanki9 commented on src/app/core/models/v1/user-property.model.ts
> +export interface Setting {
Yes, I had checked there but there is no shared model defined. We have used setting specific models there

2022-02-23 09:57 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +        .pipe(
Discussed

2022-02-23 10:03 UTC, yksolanki9 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            this.isReportMandatory = true;
Done

2022-02-23 14:13 UTC, Dimple16 approved these changes

2022-02-23 14:13 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
>      if (this.mode === 'add') {
this might change based on the latest conversion, confirm and make changes

2022-03-22 12:28 UTC, closed without merging