Fyle 22qkzgn
fylein/fyle-mobile-app pull request #936
Opened 2022-03-04 08:07 UTC by saitejasFyle

2022-03-07 12:00 UTC, Dimple16 commented on src/app/fyle/dashboard/dashboard.service.ts
> +  getCCCDetails(): Observable<{ totalTxns: string; totalAmount: string; cardDetails: any }> {
can we have a type for cardDetails?

2022-03-07 12:03 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.html
> +  <div class="stats--ccc-bank-name1">
why is this `name1`? can we rename?

2022-03-07 12:03 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.html
> +  <!-- <div class="stats--ccc-sync-detail" *ngIf="cardDetail.ba_last_synced_at">
control the view based on unify ccce settings

2022-03-07 12:04 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +$ccc-bank-name: #c4cae8;
add this to `colors.scss`

2022-03-07 12:04 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +  }
add a line

2022-03-07 12:05 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    text-align: right;
use global class - `text-right`

2022-03-07 12:06 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +      padding-left: 0;
use `padding: 0 4px 0 0`

2022-03-07 12:06 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +      padding-left: 4px;
same as above

2022-03-07 12:06 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    padding-bottom: 18px;
same as above

2022-03-07 12:07 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    background-size: 100% 100%;
does 100% work for all resolutions? please verify

2022-03-07 12:08 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    letter-spacing: -0.005em;
is this required?
can we not make it `letter-spacing: 0 !important` ?

2022-03-07 12:08 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
> +  @Input() cardDetail: any;
add types for all the inputs

2022-03-07 12:11 UTC, Dimple16 commented on src/app/shared/components/spent-cards/spent-cards.component.ts
> +  @Input() spentCards: any;
add input types

2022-03-07 12:12 UTC, Dimple16 commented on src/app/shared/pipes/mask-number.pipe.ts
> +@Pipe({
oops, I added this pipe too, let us remove and replace once its on task master

2022-03-07 12:13 UTC, Dimple16 commented on src/global.scss
> +  margin-left: 40%;
does this work well for all resolutions? I guess it might break on iOS

2022-03-16 09:11 UTC, saitejasFyle commented on src/app/core/models/approver.model.ts
> +export interface AdvanceApprover {
That's here because I accidentally worked on the current change in another branch and moved it here. This change is related to advance and advance request revamp. It got merged

2022-03-16 09:17 UTC, saitejasFyle commented on src/app/core/services/corporate-credit-card-expense.service.ts
> +  constructInQueryParamStringForV2(params) {
string[] -> Done

2022-03-16 09:20 UTC, saitejasFyle commented on src/app/fyle/dashboard/stats/stats.component.ts
> +  getCardDetail(statsResponse) {
Done

2022-03-16 09:21 UTC, saitejasFyle commented on src/app/fyle/dashboard/stats/stats.component.ts
> +      map((res) => res),
Done

2022-03-16 09:27 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.html
> +  <div class="stats--ccc-bank-name1">
Changed name1 -> detail

2022-03-16 09:29 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +$ccc-bank-name: #c4cae8;
Done

2022-03-16 09:31 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    text-align: right;
It's an unwanted class, removed it

2022-03-16 09:36 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +      padding-left: 0;
Unwanted class -> removed it

2022-03-16 09:36 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +      padding-left: 4px;
Unwanted class -> removed it

2022-03-16 09:36 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    padding-bottom: 18px;
Unwanted class -> removed it

2022-03-16 17:18 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.ts
> +  @Input() cardDetail: any;
Done

2022-03-16 17:18 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/spent-cards.component.ts
> +  @Input() spentCards: any;
Done

2022-03-16 17:18 UTC, saitejasFyle commented on src/app/fyle/dashboard/stats/stats.component.ts
> +  cardTransactionsAndDetails: { totalTxns: string; totalAmount: string; cardDetails: any };
Done

2022-03-16 17:20 UTC, saitejasFyle commented on src/global.scss
> +  margin-left: 40%;
Checked it.. It doesn't break on IOS resolutions

2022-03-17 05:39 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +  }
Done

2022-03-17 05:55 UTC, saitejasFyle commented on src/app/fyle/dashboard/dashboard.service.ts
> +  getExpenseDetailsInCards = function (uniqueCards, statsResponse) {
Done

2022-03-17 06:20 UTC, saitejasFyle commented on src/app/fyle/dashboard/dashboard.service.ts
> +  getExpenseDetailsInCards = function (uniqueCards, statsResponse) {
Done

2022-03-17 06:22 UTC, saitejasFyle commented on src/app/fyle/dashboard/dashboard.service.ts
> +  getCCCDetails(): Observable<{ totalTxns: string; totalAmount: string; cardDetails: any }> {
Done

2022-03-17 06:22 UTC, saitejasFyle commented on src/app/fyle/dashboard/stats/stats.component.ts
> +  cardTransactionsAndDetails$: Observable<{ totalTxns: string; totalAmount: string; cardDetails: any }>;
Done

2022-03-17 07:54 UTC, saitejasFyle commented on src/app/shared/pipes/mask-number.pipe.ts
> +@Pipe({
Resolved

2022-03-22 14:12 UTC, saitejasFyle commented on src/app/core/services/corporate-credit-card-expense.service.ts
> +    // return from(this.authService.getEou()).pipe(
Done... Separated the logic based on the unifyCCCSettingsEnabled condition

2022-03-22 14:12 UTC, saitejasFyle commented on src/app/fyle/dashboard/stats/stats.component.html
> +        </div> -->
Done... Separated the logic based on the unifyCCCSettingsEnabled condition

2022-03-22 14:12 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.html
> +  <!-- <div class="stats--ccc-sync-detail" *ngIf="cardDetail.ba_last_synced_at">
Done... Separated the logic based on the unifyCCCSettingsEnabled condition

2022-03-29 06:32 UTC, Dimple16 requested changes

2022-03-29 06:32 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +  isUnifyCCCEnabled$: Observable<{ enabled: boolean }>;
aren't we considering allowed && enabled?

2022-03-29 06:32 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +        this.cardNumbers = [];
why are we reassigning it to an empty list here? this is added by default while declaring?

2022-03-29 06:32 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    if (filter.cardNumbers && filter.cardNumbers.length) {
replace this condition this way - `filter.cardNumbers?.length`

2022-03-29 06:32 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    const filterMaster = [
filterMaster? this name is confusing

2022-03-29 06:32 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    if (this.filters.cardNumbers && this.filters.cardNumbers.length > 0) {
replace with `this.filters.cardNumbers?.length > 0`

2022-03-29 06:32 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.html
> +  <!-- <div class="stats--ccc-sync-detail" *ngIf="cardDetail.ba_last_synced_at">
this needs to be checked

2022-03-29 06:32 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    transform-origin: center;
check if these css properties supports all browsers - https://caniuse.com/

2022-03-29 06:32 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    margin: 0px;
`margin: 0;`

2022-03-29 07:14 UTC, saitejasFyle commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +  isUnifyCCCEnabled$: Observable<{ enabled: boolean }>;
No, this is something I'm defining. It's just a stream returning value for enabled key based on the parameters (allowed and enabled )

2022-03-29 07:23 UTC, saitejasFyle commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +        this.cardNumbers = [];
It's not necessary. Just for fool proof

2022-03-29 07:27 UTC, saitejasFyle commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    if (filter.cardNumbers && filter.cardNumbers.length) {
It's already been taken care, It's weird that it's being repeated here. But it's fixed now

2022-03-29 07:27 UTC, saitejasFyle commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    if (this.filters.cardNumbers && this.filters.cardNumbers.length > 0) {
Done

2022-03-29 07:28 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    margin: 0px;
Done

2022-03-29 07:32 UTC, saitejasFyle commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    const filterMaster = [
Yeah, this naming is to signify that this member holds all the filter configurations

2022-03-29 07:35 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    transform-origin: center;
Yes it is widely used.

<img width="1318" alt="Screenshot 2022-03-29 at 1 04 55 PM" src="https://user-images.githubusercontent.com/97864484/160558439-ef0626ec-0ef7-4480-b426-d68633ca7b42.png">

2022-03-29 08:03 UTC, Dimple16 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +    const filterMaster = [
can we rename it?filterMain? allFilters?

2022-03-29 08:04 UTC, Dimple16 commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    transform-origin: center;
what about the other 2 transform properties?

2022-03-29 08:27 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    transform-origin: center;
<img width="1323" alt="Screenshot 2022-03-29 at 1 55 57 PM" src="https://user-images.githubusercontent.com/97864484/160567981-a506e580-ae4a-43a0-b389-9a4aaa886216.png">

<img width="1321" alt="Screenshot 2022-03-29 at 1 56 27 PM" src="https://user-images.githubusercontent.com/97864484/160568008-343d16eb-8f91-4bd8-b230-563a3a83dff6.png">

<img width="1324" alt="Screenshot 2022-03-29 at 1 56 50 PM" src="https://user-images.githubusercontent.com/97864484/160568054-160cd06d-1ab7-4522-bc3d-a2aa3a69f528.png">

2022-03-29 08:27 UTC, saitejasFyle commented on src/app/shared/components/spent-cards/card-detail/card-detail.component.scss
> +    transform-origin: center;
lgtm

2022-03-29 08:47 UTC, Dimple16 approved these changes

2022-11-05 16:08 UTC, closed without merging