Merge expense page
fylein/fyle-mobile-app pull request #949
Opened 2022-03-11 05:37 UTC by iravisankar

2022-03-14 17:00 UTC, Dimple16 commented on src/app/fyle/merge-expense/merge-expense.page.scss
> +      text-align: center;
can use `text-center` global class

2022-03-14 17:00 UTC, Dimple16 commented on src/app/fyle/merge-expense/merge-expense.page.scss
> +      text-align: center;
same as above

2022-03-14 17:02 UTC, Dimple16 commented on src/app/fyle/merge-expense/merge-expense.page.scss
> +    color: #f36;
use color variables

2022-03-14 17:06 UTC, Dimple16 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  disableFormElements: any;
is this boolean?

2022-03-14 17:07 UTC, Dimple16 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  location_1Options: option[];
use camelCase

2022-03-14 17:10 UTC, Dimple16 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    this.projectService.getAllActive().subscribe((reso) => {
rename `reso`

2022-03-14 17:12 UTC, Dimple16 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    const aa = options.map((option) => {
`aa`?

2022-03-14 17:12 UTC, Dimple16 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  formatBillableOptions(options) {
add types everywhere

2022-03-14 17:13 UTC, Dimple16 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +
same as above for this block too

2022-03-15 10:52 UTC, iravisankar commented on src/app/core/services/merge-expenses.service.ts
> +    const ext = this.getReceiptExtension(file.name);
`getReceiptExtension`  for getting receipts extension (jpg or pdf)

2022-03-15 12:00 UTC, Dimple16 approved these changes

2022-03-16 05:10 UTC, Julias0 commented on src/app/core/services/merge-expenses.service.ts
> +  mergeExpenses(sourceTxnIds: string[], targetTxnId: string, targetTxnFields): Observable<string> {
targetTxnFields - this should have a data type associated

2022-03-16 05:10 UTC, Julias0 commented on src/app/core/services/merge-expenses.service.ts
> +  mergeExpenses(sourceTxnIds: string[], targetTxnId: string, targetTxnFields): Observable<string> {
can you paste a log of the response here - I want to see what is being returned

2022-03-16 05:11 UTC, Julias0 commented on src/app/core/services/merge-expenses.service.ts
> +      (expense) => expense.source_account_type && expense.source_account_type === 'PERSONAL_ADVANCE_ACCOUNT'
expense.source_account_type && expense.source_account_type === 'PERSONAL_ADVANCE_ACCOUNT'

to

expense?.source_account_type === 'PERSONAL_ADVANCE_ACCOUNT'

2022-03-16 05:11 UTC, Julias0 commented on src/app/core/services/merge-expenses.service.ts
> +      (expense) => expense.source_account_type && expense.source_account_type === 'PERSONAL_ADVANCE_ACCOUNT'
Make similar changes everywhere

2022-03-16 05:11 UTC, Julias0 commented on src/app/core/services/merge-expenses.service.ts
> +        ['APPROVER_PENDING', 'APPROVED', 'PAYMENT_PENDING', 'PAYMENT_PROCESSING', 'PAID'].indexOf(expense.tx_state) > -1
use includes instead of indexOf - easier to read

2022-03-16 05:11 UTC, Julias0 commented on src/app/core/services/merge-expenses.service.ts
> +      isAdvancePresent: advanceExpenses && advanceExpenses.length > 0,
fix wrt the same syntax on comment above

2022-03-16 05:13 UTC, Julias0 commented on src/app/core/services/merge-expenses.service.ts
> +    if (extension && ['pdf'].indexOf(extension) > -1) {
in what case can extension be empty?

2022-03-16 05:13 UTC, Julias0 commented on src/app/core/services/merge-expenses.service.ts
> +      return ['APPROVED', 'PAYMENT_PENDING', 'PAYMENT_PROCESSING', 'PAID'].indexOf(expense.tx_state) > -1;
use includes

2022-03-16 05:14 UTC, Julias0 commented on src/app/core/services/merge-expenses.service.ts
> +    const reportedExpense = expenses.filter((expense) => expense.tx_state === 'APPROVER_PENDING');
return  expenses.filter((expense) => expense.tx_state === 'APPROVER_PENDING');

2022-03-16 05:14 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  mergedExpenseOptions: any = {};
use proper data types please

2022-03-16 05:15 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  mergedExpense = {};
use proper data types please

2022-03-16 05:15 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  customInputs$: Observable<any>;
dont use any please

2022-03-16 05:15 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  mergedCustomProperties: any = {};
please use data types

2022-03-16 05:15 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  projects;
please use data types

2022-03-16 05:15 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  categories;
please use data types

2022-03-16 05:15 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  selectedExpense;
please use data types

2022-03-16 05:16 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  from: string;
this variable name is too generic. Please make it more specific

2022-03-16 05:17 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    this.expenses = this.router.getCurrentNavigation().extras.state.selectedElements;
why use extras? Why not send via params normally?

2022-03-16 05:17 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +            if (expense[field] !== undefined && expense[field] !== null) {
we shouldnt be making changes to state inside map. Please do this inside subscribe

2022-03-16 05:18 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  generateCustomInputOptions() {
This function is too large. Lets cut it up into smaller pure functions and move that into services

2022-03-16 05:24 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    from(Object.keys(this.expenses[0])).subscribe((field) => {
use first instead of accessing by index

2022-03-16 05:24 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      from(this.expenses)
putting a observable inside a subscribe is an antipattern

2022-03-16 05:25 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +              this.mergedExpenseOptions[field].options.push({
making changes to state inside map is an antipattern

2022-03-16 05:26 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    this.expenseOptions$ = from(this.expenses).pipe(
you can extract this out into a service as a function that takes in an argument of expenses array

2022-03-16 05:26 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      scan((acc, curr) => {
why use scan? Why not use reduce?

2022-03-16 05:27 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      scan((acc, curr) => {
again, why use scan?

2022-03-16 05:27 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    this.receiptOptions$ = from(this.expenses).pipe(
move to service

2022-03-16 05:29 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    // eslint-disable-next-line complexity
we shouldn't be doing this. the cyclomatic complexity is here for a reason

2022-03-16 05:30 UTC, Julias0 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      const isAllCCCMatchedExpenses = expenses.every((expense) => expense.tx_corporate_credit_card_expense_group_id);
isAllCCCMatchedExpenses -> areAllCCCMatchedExpenses

2022-03-16 05:30 UTC, Julias0 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      const isAllExpensesSubmitted = expenses.every(
isAllExpensesSubmitted -> areAllExpensesSubmitted

2022-03-16 05:30 UTC, Julias0 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +          ['APPROVER_PENDING', 'APPROVED', 'PAYMENT_PENDING', 'PAYMENT_PROCESSING', 'PAID'].indexOf(expense.tx_state) >
use includes

2022-03-16 05:32 UTC, Julias0 commented on src/app/fyle/my-expenses/my-expenses.page.ts
> +      const isMileagePerdiem = expenses.some(
isMileagePerdiem -> areSomeMileageOrPerDiemExpenses

2022-03-16 05:34 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      .filter((res) => res.value);
we should filter before we do the map

2022-03-16 05:45 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    this.location1Options = this.expenses
you can extract and move this inside a service

2022-03-16 05:47 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.html
> +        <ng-container *ngFor="let customInput of this.customInputs$ | async as customInputs">
move this portion inside a component. Use the same control value accessor pattern with validators that I have done with route selector

2022-03-16 05:49 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.html
> +      <ng-container *ngIf="['Bus', 'Flight', 'Hotel', 'Train'].includes(getCategoryName(fg.value.category))">
All of the category dependant fields group together and cut out into a subform which interacts with the parent with control value accessor. Corresponding logic of validation etc should also move inside the subform component

2022-03-16 05:50 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.html
> +          *ngIf="formatReceiptOptions(expenseOptions)?.length !== 0"
please dont use functions inside html

2022-03-16 05:50 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.html
> +            [disabled]="formatReceiptOptions(expenseOptions)?.length === 0"
same as above. Please do this change throughout

2022-03-16 05:51 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.html
> +          <div class="merge-expenses--card-header">Card Transaction</div>
extract this out into a presentational component

2022-03-16 05:51 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +          new Date(new Date(field.value).toDateString()).getTime()
please use moment for date time adventures

2022-03-16 05:52 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +          option.label = this.projects[this.projects.map((project) => project.id).indexOf(option.value)].name;
ok I cant make sense of what is happening here

2022-03-16 05:55 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.html
> +                    [disabled]="disableFormElements || mergedExpenseOptions.tx_currency.isSame || ( mergedExpenseOptions.tx_currency.options && mergedExpenseOptions.tx_currency.options?.length ===0 )
why is everything coming from inside `mergedExpenseOptions`?
I dont see a clear benefit in doing something like this?

2022-03-16 05:56 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.html
> +                    [options]="mergedExpenseOptions.tx_currency.options"
why is everything coming from inside `mergedExpenseOptions`?
I dont see a clear benefit in doing something like this?

2022-03-16 05:57 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.html
> +                    [disabled]="disableFormElements || mergedExpenseOptions.tx_currency.isSame || ( mergedExpenseOptions.tx_currency.options && mergedExpenseOptions.tx_currency.options?.length ===0 )
we should avoid putting such long conditionals in html. Please find a better way to do this. Lets decide on the desired approach on slack before we go ahead with this please

2022-03-16 05:58 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      this.mergedExpenseOptions[field].options = [];
What is the use of an object like this? Are you doing this to maintain a dictionary of pre-existing form values? If yes this is the wrong way to do this

2022-03-16 06:00 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    allCategories$
Instead of subscribing to all of items separately, you can forkjoin all of the streams, create an object with all the desired values and use it as patch value on the form. The part where you are doing the forkJoin can move into a service with proper arguments

2022-03-16 06:01 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    if (field === 'source_account_type' && isDuplicate) {
Why do it in this fashion? Why not just prepare an object with all required properties and just patchValue it to the form directly?

2022-03-16 06:01 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    this.attachments$ = this.fg.controls.receipt_ids.valueChanges.pipe(
I think we can cut out this whole section into a service method

2022-03-16 06:02 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    source_txn_ids.splice(index, 1);
Lets avoid using slice. use slice or somrthing if you want to remove indexes

2022-03-16 06:02 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    const source_txn_ids = [];
avoid mixing camelCasing and snakeCasing please

2022-03-16 06:03 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    if (!this.fg.valid) {
Avoid having guard clauses like this
if (this.fg.valid) {
// do something

} else {
this.fg.markAllAsTouched();
}

2022-03-16 06:03 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +        take(1),
we shouldnt have to take 1 when we are using generateFromFg. This means we are getting data from an incomplete stream

2022-03-16 06:04 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      switchMap(async (customProperties) => ({
why use async here? You dont have any async properties here? Why not just use map?

2022-03-16 06:05 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    const customInputs$ = this.getCustomFields();
Please call these things either customInputs or customFields. Dont use both names please

2022-03-16 06:08 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.html
> +        <ng-container *ngFor="let customInput of this.customInputs$ | async as customInputs">
Please dont use this inside html

2022-03-16 06:09 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    this.customInputs$ = this.fg.controls.category.valueChanges.pipe(
Once we move the custom inputs inside a component with control value accessor, this rxjs jugaad will completely go away

2022-03-16 06:12 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      target_txn_id: [, Validators.required],
I think we should separate out `target_txn_id` and the rest as separate forms altogether. The whole of the rest should be a subform since it depends on `target_txn_id` but if on changing `target_txn_id` updates the whole form, we can run into cyclic triggers

2022-03-16 06:12 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +  patchValues(customInputs) {
this will go away once we do the subform

2022-03-16 06:13 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    this.CCCTxn$ = this.fg.controls.paymentMode.valueChanges.pipe(
we can cut out the right hand side of this into a service method

2022-03-16 06:13 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    return options.map((option) => {
move to service

2022-03-16 06:13 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    return options.map((option) => {
move to service

2022-03-16 06:13 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    return options.map((option) => {
move to service

2022-03-16 06:14 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.html
> +          *ngIf="formatReceiptOptions(expenseOptions)?.length !== 0"
check for `expenseOptions` being present at a parent level ng-container with ng if please

2022-03-16 06:14 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    if (!options) {
we should avoid guard clauses

2022-03-16 06:15 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    return options.filter((option, index) => this.expenses[index].tx_file_ids !== null);
is this to remove

2022-03-16 06:15 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    if (!options || !this.categories) {
avoid guard clauses please

2022-03-16 06:15 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +    const label = this.categories[this.categories.map((category) => category.id).indexOf(options)]?.displayName;
ok I cant read this - simplify

2022-03-22 11:47 UTC, rvab requested changes

2022-03-22 11:47 UTC, rvab commented on src/app/core/services/merge-expenses.service.ts
> +  getReceiptDetails(file) {
`file`data type?

2022-03-22 11:47 UTC, rvab commented on src/app/core/services/merge-expenses.service.ts
> +    if (['pdf'].includes(extension)) {
can use `endsWith`.

2022-03-22 11:47 UTC, rvab commented on src/app/core/services/merge-expenses.service.ts
> +        label: expense.tx_org_category_id.toString(),
Why `toString()`?

2022-03-22 11:47 UTC, rvab commented on src/app/core/services/merge-expenses.service.ts
> +        label: expense.tx_purpose.toString(),
`tx_purprose` isn't a string?

2022-03-22 11:47 UTC, rvab commented on src/app/core/services/merge-expenses.service.ts
> +          options = field.options.filter((option) => option !== '');
use `option !== ''` in above code

2022-03-22 11:47 UTC, rvab commented on src/app/core/services/merge-expenses.service.ts
> +  formatCustomInputOptionsByType(combinedCustomProperties) {
`combinedCustomProperties` data type

2022-03-22 11:47 UTC, rvab commented on src/app/core/services/merge-expenses.service.ts
> +      const existing = customProperty.filter((option) => option.name === field.name);
use `customProperty.find` if there are no duplicates

2022-03-22 11:47 UTC, rvab commented on src/app/fyle/merge-expense/category-dependent-fields-form/category-dependent-fields-form.component.scss
> +    margin-top: -12px;
negative required?

2022-03-22 11:47 UTC, rvab commented on src/app/fyle/merge-expense/custom-inputs-fields-form/custom-inputs-fields-form.component.ts
> +  constructor(private formBuilder: FormBuilder) {}
remove `formBuilder` if not used

2022-03-22 11:47 UTC, rvab commented on src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
> +type OptionsData = Partial<{ options: Option[]; areSameValues: boolean }>;
Can we not keep these `types` in the common file?

2022-03-22 11:47 UTC, rvab commented on src/app/fyle/merge-expense/merge-expense.module.ts
> +
extra line?

2022-03-22 11:47 UTC, rvab commented on src/app/fyle/merge-expense/merge-expense.page.html
> +      <div *ngIf="fg.controls.target_txn_id.touched && !fg.controls.target_txn_id.valid" class="merge-expenses--error">
use `fg.controls.target_txn_id.invalid` instead of `!fg.controls.target_txn_id.valid`

2022-03-22 11:47 UTC, rvab commented on src/app/core/services/merge-expenses.service.ts
> +      })
from line no 392 to 402. Create a separate method for this?

2022-03-22 18:23 UTC, iravisankar commented on src/app/core/services/merge-expenses.service.ts
> +        label: expense.tx_purpose.toString(),
here we show these values for users to select.

2022-03-22 18:32 UTC, iravisankar commented on src/app/fyle/merge-expense/category-dependent-fields-form/category-dependent-fields-form.component.scss
> +    margin-top: -12px;
can't avoid here, fixed negative margins on other places.

2022-03-23 05:22 UTC, rvab approved these changes

2022-03-23 05:22 UTC, rvab commented on src/app/core/services/merge-expenses.service.ts
> +          options = field.options.filter((option) => option !== '');
?

2022-03-23 05:22 UTC, rvab commented on src/app/core/services/merge-expenses.service.ts
> +        if (existing?.length) {
`existing` will be an array?

2022-03-23 05:22 UTC, rvab commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      (expense) => expense.tx_id === this.fg.controls.genericFields.get('amount').value
`expense.tx_id === this.fg.controls.genericFields.get('amount').value` is this correct?

2022-03-23 05:22 UTC, rvab commented on src/app/core/models/options-data.type.ts
> +export type OptionsData = Partial<{ options: Option[]; areSameValues: boolean; name?: string; value?: any }>;
`name?: string; value?: any`. I don't think `?` is required here since `Partial` is used. Please confirm

2022-03-23 05:29 UTC, iravisankar commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      (expense) => expense.tx_id === this.fg.controls.genericFields.get('amount').value
yes getting value from the form group

2022-03-23 05:31 UTC, iravisankar commented on src/app/core/services/merge-expenses.service.ts
> +        if (existing?.length) {
yes

2022-03-23 07:03 UTC, Julias0 commented on src/app/core/models/options-data.type.ts
> +export type OptionsData = Partial<{ options: Option[]; areSameValues: boolean; name: string; value: any }>;
dont export type - export an interface

2022-03-23 07:03 UTC, Julias0 commented on src/app/core/models/options-data.type.ts
> +export type OptionsData = Partial<{ options: Option[]; areSameValues: boolean; name: string; value: any }>;
Make this multiline too

2022-03-23 07:04 UTC, Julias0 commented on src/app/core/models/option.type.ts
> +export type Option = Partial<{ label: string; value: any }>;
dont export type - export only interfaces.
Also dont export with generics like Partial. Those should be used in the place of usage

2022-03-23 07:05 UTC, Julias0 commented on src/app/core/models/custom-input.type.ts
> +export type CustomInputs = Partial<{
this should be interface not type. Dont use partial inside defnition - use it at the place of usage

2022-03-23 07:05 UTC, Julias0 commented on src/app/core/models/expense.model.ts
> +  tx_tax_group_id?: string;
This seems out of scope for this initiative

2022-03-23 07:05 UTC, Julias0 commented on src/app/core/models/expense.model.ts
> +  tx_tax_group_id?: string;
why is this change here?

2022-03-25 09:15 UTC, iravisankar commented on src/app/core/models/expense.model.ts
> +  tx_tax_group_id?: string;
`tx_tax_group_id `  is missing in Expense model. now added that...

2022-03-25 09:16 UTC, iravisankar commented on src/app/core/services/merge-expenses.service.ts
> +    return from(expenses).pipe(
there is no case for an empty array here.

2022-03-25 09:16 UTC, iravisankar commented on src/app/core/services/merge-expenses.service.ts
> +    return from(expenses).pipe(
there is no case for an empty array here.

2022-03-25 09:19 UTC, iravisankar commented on src/app/core/services/merge-expenses.service.ts
> +        if (moment(field.value, moment.ISO_8601, true).isValid()) {
here verifying that the value is a valid date.

2022-03-25 10:52 UTC, Julias0 commented on src/app/core/services/merge-expenses.service.ts
> +        if (moment(field.value, moment.ISO_8601, true).isValid()) {
extract this out into a function in dateService

2022-03-25 10:54 UTC, Julias0 commented on src/app/fyle/merge-expense/category-dependent-fields-form/category-dependent-fields-form.component.ts
> +  @Input() location1OptionsData: Observable<OptionsData>;
we should pass in inputs as observables. Please resolve these at the parent and pass in as values

2022-03-25 10:54 UTC, Julias0 commented on src/app/fyle/merge-expense/category-dependent-fields-form/category-dependent-fields-form.component.ts
> +  @Input() location2OptionsData: Observable<OptionsData>;
above comment same for all similar places

2022-03-25 10:57 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +              !location1OptionsData?.areSameValues && !this.touchedCategoryDepedentFields?.includes('location_1')
we should extract this out into a function - this structure has duplication

2022-03-28 04:24 UTC, iravisankar commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +              !location1OptionsData?.areSameValues && !this.touchedCategoryDepedentFields?.includes('location_1')
Below one  is for patch values to form while changing the expense to keep       
```
location_1: !location1OptionsData?.areSameValues && !this.touchedCategoryDepedentFields?.includes('location_1')
                    ? this.expenses[selectedIndex].tx_locations[0]
                    : this.categoryDependentForm.value?.location_1
```
The below one is for patch values to form while onload.   

`                location_1: location1OptionsData?.areSameValues ? location1OptionsData?.options[0]?.value : null,`

2022-03-28 12:17 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +            amount: amountOptionsData?.areSameValues ? amountOptionsData?.options[0]?.value : null,
pattern is repetative, lets extract out to a function

2022-03-28 12:17 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      // eslint-disable-next-line complexity
we shouldnt skipping this :(

2022-03-28 12:18 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +              !amountOptionsData?.areSameValues && !this.touchedGenericFields?.includes('amount')
pattern is same, please to extract out to a function

2022-03-28 12:18 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +      billable: this.fg.controls.genericFields.value.billable,
this.fg.controls.genericFields.value
create a getter for this, that way you dont have to repeat this again and again

2022-03-28 12:19 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +          toArray()
why is there a toArray here?

2022-03-28 12:23 UTC, Julias0 commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +              !location1OptionsData?.areSameValues && !this.touchedCategoryDepedentFields?.includes('location_1')
Didnt understand. 
You can reduce duplication in this format no

getSomething(val, propertyName, expensePropName) {
  return !val?. areSameValues && !this.touchedCategoryDepedentFields?.includes(propertyName)? ? this.expenses[selectedIndex][expensePropName][0]: this.categoryDependentForm.value && this.categoryDependantForm.value[propertyName];
}

Also remove the ternary operators, it makes this very difficult to read

2022-03-28 12:46 UTC, iravisankar commented on src/app/fyle/merge-expense/merge-expense.page.ts
> +          toArray()
observables stream the response. used `toarray` to convert into array
now changed it to 
```
          reduce((acc, curr) => {
            acc.push(curr);
            return acc;
          }, []),
```

2022-03-30 14:16 UTC, Julias0 commented on src/app/core/services/merge-expenses.service.ts
> +        label: expense.tx_purpose.toString(),
Didnt understand this

2022-03-30 14:18 UTC, Julias0 commented on src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
> +  @Input() categoryDependentFormGroup: FormGroup;
If this is not being used please to remove it

2022-03-30 14:18 UTC, Julias0 commented on src/app/fyle/merge-expense/custom-inputs-fields-form/custom-inputs-fields-form.component.ts
> +  private ngControl: NgControl;
If this is not being used please to remove it

2022-03-30 14:19 UTC, Julias0 commented on src/app/fyle/merge-expense/generic-fields-form/generic-fields-form.component.ts
> +  private ngControl: NgControl;
If this is not being used please remove this

2022-03-30 14:19 UTC, Julias0 commented on src/app/fyle/merge-expense/category-dependent-fields-form/category-dependent-fields-form.component.ts
> +  private ngControl: NgControl;
if this is not being used please to remove it

2022-03-30 14:57 UTC, Julias0 approved these changes

2022-04-04 05:11 UTC, Julias0 approved these changes

2022-04-04 11:03 UTC, merged