Potential Duplicates
fylein/fyle-mobile-app pull request #956
Opened 2022-03-16 04:20 UTC by iravisankar

<img width="329" alt="image" src="https://user-images.githubusercontent.com/86199056/158515986-8fd08b9f-27c1-4365-b3d2-5f640b0edc6f.png">
![localhost_8100_enterprise_my_expenses_filters=%7B%7D(iPhone SE) (9)](https://user-images.githubusercontent.com/86199056/158516026-03f6c6b6-2e6d-4cf7-8904-845b23bae6d0.png)
<img width="335" alt="image" src="https://user-images.githubusercontent.com/86199056/158516094-c86b1e0b-0880-45a1-b19c-6f13e4cd40f7.png">
![localhost_8100_enterprise_my_expenses_filters=%7B%7D(iPhone SE) (10)](https://user-images.githubusercontent.com/86199056/158516131-a086b8a0-2218-4bb3-91c6-ff33c90d40ff.png)

2022-03-16 07:31 UTC, Dimple16 requested changes

2022-03-16 07:31 UTC, Dimple16 commented on src/app/core/services/tasks.service.ts
> +    const duplicateIds = [].concat.apply(
why not use the `spread` operator or `reduce` here?

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.html
> +        <div *ngIf="duplicateExpenses?.length > 0" class="add-edit-expense--alert-offline">
we have an existing duplicates section too, please do verify if both aren't overlapping in this case

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  duplicatesSet$: Observable<any>;
avoid `any`, can add type wherever required

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          const duplicateIds = [].concat.apply(
same comment for .apply

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.ts
> +  mergeExpense() {
`mergeExpenses`? I guess it should be plural here

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.html
> +              [isDismissable]="duplicatesSet.length > 2"
wherever we use length, add `?.length` just in case the list doesn't load due to network issues etc

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +  duplicatesSet$: Observable<any>;
add type

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +  loadData$: BehaviorSubject<any>;
add type

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +  duplicateExpenses;
add type

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +      .pipe(map((sets: any) => sets.length))
is `sets` a list here?

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +      console.log(this.duplicatesSetData[this.selectedSet].transaction_ids);
remove console

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +      const indexInExpensesSet = this.duplicatesSetData[this.selectedSet].transaction_ids.indexOf(expense.tx_id);
`this.duplicatesSetData[this.selectedSet]?.transaction_ids?.` ..so on.

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +      const indexInExpensesSet = this.duplicatesSetData[this.selectedSet].transaction_ids.indexOf(expense.tx_id);
use includes

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +      if (indexInExpensesSet > -1) {
can avoid this by using includes

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +    const txnIds = this.duplicatesSetData[this.selectedSet].transaction_ids;
add fail-safes wherever required

2022-03-16 07:31 UTC, Dimple16 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +      message: 'Duplicates was successfully dismissed',
the content sounds off - verify with design / product team

2022-03-16 12:26 UTC, iravisankar commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +      message: 'Duplicates was successfully dismissed',
updated with web app content

2022-03-18 05:00 UTC, Julias0 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +      tx_id: `in.(${selectedTxnIds.toString()})`,
Shouldnt you join this with a `,`?

2022-03-18 05:06 UTC, Julias0 commented on src/app/core/models/task.model.ts
> +  isAmountHidden?: boolean;
hideAmount

2022-03-18 05:08 UTC, Julias0 commented on src/app/core/services/tasks.service.ts
>            this.expensesTaskCount$.next(draftExpenses.length + unreportedExpenses.length);
Shouldn't this be added to expensesTaskCount? This is also a expenses specific task right?

2022-03-18 05:24 UTC, Julias0 commented on src/app/core/services/tasks.service.ts
> +          duplicateSets && duplicateSets.length > 0 ? this.mapPotentialDuplicatesTasks(duplicateSets) : of([])
Dont use ternary operators here please - use a proper if condition

2022-03-18 05:24 UTC, Julias0 commented on src/app/core/services/tasks.service.ts
> +          duplicateSets && duplicateSets.length > 0 ? this.mapPotentialDuplicatesTasks(duplicateSets) : of([])
duplicateSets?.length > 0

2022-03-18 05:41 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  duplicatesSet$: Observable<Expense[][]>;
is this being used?

2022-03-18 05:42 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +    if (!this.activatedRoute.snapshot.params.id) {
avoid using guard clauses.

if (this.activatedRoute.snapshot.params.id) {

// do something

}

2022-03-18 05:42 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            tx_id: `in.(${duplicateIds.toString()})`,
shouldnt we join the array with `,` ?

2022-03-18 05:43 UTC, Julias0 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            map((expenses) => {
the portion inside the map block is difficult to read - simplify please

2022-03-20 20:31 UTC, iravisankar commented on src/app/core/services/tasks.service.ts
> +          duplicateSets && duplicateSets.length > 0 ? this.mapPotentialDuplicatesTasks(duplicateSets) : of([])
if else not working inside switchMap if it has an empty array

2022-03-21 13:06 UTC, rvab requested changes

2022-03-21 13:06 UTC, rvab commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +                    const index = expensesArray.findIndex((duplicateTxn: any) => expenseId === duplicateTxn.tx_id);
Add data type if possible `duplicateTxn: any`

2022-03-21 13:17 UTC, iravisankar commented on src/app/core/models/task.model.ts
>    count: number;
amount contains currency too , its optional because some items don't have amount value.

2022-03-21 13:20 UTC, iravisankar commented on src/app/core/services/handle-duplicates.service.ts
> +  dismissAll(duplicateSetTransactionIds: string[], transactionIds: string[]) {
api not returning any avalue

2022-03-21 13:26 UTC, iravisankar commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  getDuplicateExpenses() {
it will not return any value

2022-03-21 13:31 UTC, iravisankar commented on src/app/shared/components/expenses-card/expenses-card.component.ts
> +  @Input() isFromPotentialDuplicates: boolean;
using these in many places around the app, will fix this separately

2022-03-21 13:34 UTC, iravisankar commented on src/app/core/services/tasks.service.ts
> +          value: ['DUPLICATE'],
value type was declared as an array

2022-03-25 12:06 UTC, iravisankar commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +          this.duplicateExpenses = duplicateExpenses[0];
`duplicateExpenses`  have array of expenses , now i renamed it to `duplicateExpensesSet`

2022-03-25 13:46 UTC, iravisankar commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +            return this.transactionService.getETxnc({ offset: 0, limit: 10, params }).pipe(
okay.., here we don't need a limit. now i set limit as 100

2022-03-25 13:53 UTC, iravisankar commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +  duplicateSets$: Observable<Expense[][]>;
here its an array of expenses array, now  fixed

2022-03-27 04:36 UTC, Julias0 commented on src/app/core/services/tasks.service.ts
> +            content: `Review`,
content: 'Review',

2022-03-27 04:37 UTC, Julias0 commented on src/app/fyle/potential-duplicates/potential-duplicates.page.ts
> +        this.duplicateExpenses = duplicateExpenses;
we should do this inside the subsribe. Tap should mostly be used for console.log

2022-03-28 10:32 UTC, Julias0 commented on src/app/core/services/tasks.service.ts
> +        header: `${duplicateIds.length} Potential duplicates`,
check casing once with web app

2022-03-28 10:33 UTC, Julias0 commented on src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.ts
> +      tx_id: `in.(${txnIds.toString()})`,
Shouldnt we join this with `,` instead of calling toString on an array?

2022-03-30 06:32 UTC, Dimple16 approved these changes

2022-03-30 06:32 UTC, Dimple16 commented on src/app/core/services/tasks.service.ts
> +  generatePotentialDuplicatesFilter(selectedFilters) {
`selectedFilters` is this a list?

2022-03-30 06:54 UTC, iravisankar commented on src/app/fyle/add-edit-expense/add-edit-expense.page.ts
> +  duplicatesSet$: Observable<Expense[][]>;
it's removed already...

2022-03-30 14:15 UTC, Julias0 commented on src/app/fyle/add-edit-expense/suggested-duplicates/suggested-duplicates.component.ts
> +    const txnIds = this.duplicateExpenses.map((expense) => expense.tx_id);
```typescript

const txnIds = this.duplicateExpenses.map((expense) => expense.tx_id).join(',');

```

2022-04-04 11:26 UTC, merged