2px Spacing between currency and amount
fylein/fyle-mobile-app pull request #968
Opened 2022-03-23 10:03 UTC by sandy-fyle

2px Spacing between currency and amount

Before :

![before](https://user-images.githubusercontent.com/102028313/159673895-865ff56f-fa33-484b-9545-d2b65c9967c5.png)

After:

![after](https://user-images.githubusercontent.com/102028313/159673936-099463ba-d648-4585-bbec-616011fbcd7d.png)

2022-03-24 09:53 UTC, Dimple16 requested changes

2022-03-24 09:53 UTC, Dimple16 commented on src/app/shared/components/expenses-card/expenses-card.component.scss
> +  ~ &--amount {
remove the extra change

2022-03-24 18:15 UTC, sandy-fyle commented on src/app/shared/components/expenses-card/expenses-card.component.scss
> +  ~ &--amount {
which extra change? I didn't get you actually

2022-03-25 05:15 UTC, sandy-fyle commented on src/app/shared/components/expenses-card/expenses-card.component.scss
> +  ~ &--amount {
added the removed space

2022-03-25 12:51 UTC, Dimple16 approved these changes

2022-03-25 12:55 UTC, merged