added skeleton loader to view expense
fylein/fyle-mobile-app pull request #975
Opened 2022-03-28 05:32 UTC by MasterYushi

https://user-images.githubusercontent.com/24858182/160332437-1b7798a2-7df0-4b20-ac4b-9c95f3c98148.mp4

2022-03-28 08:08 UTC, Dimple16 commented
Comments from the video:
- We need to add a skeleton for amount and pill inside the card section
- The spacing between items below needs to be verified
- The height of each item needs to be checked, it looks smaller in the video

2022-03-28 08:25 UTC, Dimple16 requested changes

2022-03-28 08:25 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.html
> +                [src]="'../../../assets/svg/' + (paymentModeIcon === 'fy-matched' ? 'fy-unmatched' : paymentModeIcon) + '.svg'"
is this change intentional?

2022-03-28 08:25 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.html
> +                    [src]="'../../../assets/svg/fy-' + etxn.tx_fyle_category.toLowerCase() + '.svg'"
`etxn?.tx_fyle_category?.toLowerCase()`

2022-03-28 08:25 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.ts
> +    this.attachments$.subscribe(noop, noop, () => {
why are we doing it this way?

2022-03-28 08:25 UTC, Dimple16 commented on src/app/shared/components/view-expense-skeleton-loader/view-expense-skeleton-loader.component.scss
> +$shimmer-border-radius: 4px;
are we using these in multiple places? if not, we can add them directly?

2022-03-28 08:25 UTC, Dimple16 commented on src/app/shared/components/view-expense-skeleton-loader/view-expense-skeleton-loader.component.scss
> +$shimmer-border-radius: 4px;
adding variables for every value which is used only once might be redundant

2022-03-28 08:25 UTC, Dimple16 commented on src/app/shared/components/view-expense-skeleton-loader/view-expense-skeleton-loader.component.ts
> +  rows = Array(7).fill(0);
add a comment on why we are doing this, might help others who work in the same area in future

2022-03-28 08:54 UTC, MasterYushi commented on src/app/fyle/view-expense/view-expense.page.html
> +                    [src]="'../../../assets/svg/fy-' + etxn.tx_fyle_category.toLowerCase() + '.svg'"
wasn't changed by me, probably a result of a formatter spacing changes. The diff for this file is clean in my editor but it shows a lot of addition and deletions here on github

2022-03-28 08:55 UTC, MasterYushi commented on src/app/shared/components/view-expense-skeleton-loader/view-expense-skeleton-loader.component.scss
> +$shimmer-border-radius: 4px;
I believe this is a better approach and more readable for other people. Let's say you assign someone to change the border radius of the shimmers, he would just have to come to this scss file and change the value of the variable `$border-shimmers` instead of trying to find where this property was defined in the whole file.

2022-03-28 09:00 UTC, MasterYushi commented on src/app/shared/components/view-expense-skeleton-loader/view-expense-skeleton-loader.component.ts
> +  rows = Array(7).fill(0);
done

2022-03-28 09:02 UTC, MasterYushi commented on src/app/fyle/view-expense/view-expense.page.ts
> +    this.attachments$.subscribe(noop, noop, () => {
fetching attachments is the part that takes the most time, so when it completes `isLoading` is set to `false`

2022-03-29 06:19 UTC, MasterYushi commented on src/app/fyle/view-expense/view-expense.page.html
> +                [src]="'../../../assets/svg/' + (paymentModeIcon === 'fy-matched' ? 'fy-unmatched' : paymentModeIcon) + '.svg'"
the diff shown in github is messed up somehow. The diff I see in vs code when looking at the same commit is cleaner and I only changed a few lines, no logic was changed

2022-03-30 08:24 UTC, Dimple16 requested changes

2022-03-30 08:24 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.html
> +      <ng-container *ngIf="etxn.tx_policy_flag">
`etxn?.tx_policy_flag`

2022-03-30 08:24 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.html
> +          <div class="view-expense--card-container__category">{{ etxn.tx_categoryDisplayName || 'Unspecified' }}</div>
`etxn?.tx_categoryDisplayName`

2022-03-30 08:24 UTC, Dimple16 commented on src/app/fyle/view-expense/view-expense.page.html
> +          <div class="view-expense--card-container__category">{{ etxn.tx_categoryDisplayName || 'Unspecified' }}</div>
use fail-safe everywhere

2022-03-30 08:24 UTC, Dimple16 commented on src/app/shared/components/view-expense-skeleton-loader/view-expense-skeleton-loader.component.scss
> +$shimmer-border-radius: 4px;
please update these, I feel we are using extra variables here without multiple use case

2022-03-30 10:20 UTC, ayush-seth commented on src/app/fyle/view-expense/view-expense.page.html
> +          <div class="view-expense--card-container__category">{{ etxn.tx_categoryDisplayName || 'Unspecified' }}</div>
this is not a part of my changes or the work I did in this clickup task. It was like this before I touched it. Should I still make these changes?

2022-04-11 04:56 UTC, Dimple16 approved these changes

2022-04-11 08:56 UTC, merged