added auto-population of report name in create-expense-view
fylein/fyle-mobile-app pull request #992
Opened 2022-03-29 14:28 UTC by ayush-seth

https://user-images.githubusercontent.com/24858182/160634788-96ba21a0-7d88-4e85-8ab2-ac4448bda7d2.mp4

2022-03-29 14:39 UTC, Dimple16 requested changes

2022-03-29 14:39 UTC, Dimple16 commented on src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
> +      const reportTitle = await this.reportService.getReportPurpose({ ids: null }).toPromise();
why are we converting observable to promise here? let us use it as an observable directly

2022-03-29 14:40 UTC, MasterYushi commented on src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
> +      const reportTitle = await this.reportService.getReportPurpose({ ids: null }).toPromise();
because we need to wait for the api call to fetch the report name before displaying the create report modal. This is inside an async function so I am following the async await syntax

2022-03-29 15:36 UTC, Dimple16 requested changes

2022-03-29 15:36 UTC, Dimple16 commented on src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
> +      const reportTitle = await this.reportService.getReportPurpose({ ids: null }).toPromise();
we can have an observable with the value of API response, on subscribe of that you can set the reportTitle, 
The change here is valid, but since we are following the observable pattern everywhere, I guess we can avoid converting it to promises again

2022-03-29 15:48 UTC, ayush-seth commented on src/app/shared/components/fy-add-to-report/fy-add-to-report.component.ts
> +      const reportTitle = await this.reportService.getReportPurpose({ ids: null }).toPromise();
We cannot do that. Subscribing to it and then setting the value of the variable to the returned value will not halt the execution.

If the network is slow, the modal will be called with 'reportTitle' as undefined before the API call is resolved that's why we need to use await here

2022-03-30 08:16 UTC, Dimple16 approved these changes

2022-03-30 14:11 UTC, Julias0 approved these changes

2022-03-30 22:10 UTC, merged