fixed uneven spacing between Date and category
fylein/fyle-mobile-app pull request #995
Opened 2022-03-30 03:33 UTC by sandy-fyle

Before:

![Screenshot (1)](https://user-images.githubusercontent.com/102028313/160746041-218f9f70-dd70-4751-8e39-18a9f8ef5238.png)

After:

![Screenshot (2)](https://user-images.githubusercontent.com/102028313/160746048-fd663838-3b7c-445c-8940-de78a3f250e5.png)

2022-03-30 08:10 UTC, Dimple16 requested changes

2022-03-30 08:10 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    margin-top: -13px;
check if `margin-top: -12px;` works

2022-03-30 08:10 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> +    margin-top: -13px;
also add screenshots with error messages

2022-04-04 07:59 UTC, Dimple16 requested changes

2022-04-04 07:59 UTC, Dimple16 commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> -    margin-top: -12px;
this will have an impact on all fields, please check

2022-04-07 07:40 UTC, sandy-fyle commented on src/app/fyle/add-edit-expense/add-edit-expense.page.scss
> -    margin-top: -12px;
Hey date isn't mandatory now but it was required before so it was giving error and error of date was not aligned but now   I added margin-top: -12px back. Now it looks good to me.
![1](https://user-images.githubusercontent.com/102028313/162145961-eb18ad5f-8c5c-4b8c-8eb3-68b70862829e.png)
e

2022-04-11 04:58 UTC, Dimple16 approved these changes

2022-04-19 03:20 UTC, merged